### ISSUE TITLE
[BUG]: Parsers/annotators does not work

### ISSUE THREAD

**Issue by christopherli2026** [NLP-Suite/NLP-Suite#1008]
Parsers/annotators tool does not work. It opens a little tab and closes and comes out with an error message of "python quit unexpectedly" on a Macbook Air M1 chip. 
<img width="1330" alt="Screenshot 2023-02-05 at 1 06 43 PM" src="https://user-images.githubusercontent.com/123025287/216836985-716a1c44-1df0-4ef1-8d5a-1ec196a7914e.png">

**Comment by Emory-NLP** [comment]
Please, upload a screenshot of the content of the NLP_setup_external_software_config.csv file found under the config subdirectory of the NLP installation directory.

**Comment by christopherli2026** [comment]
<img width="743" alt="Screenshot 2023-02-05 at 1 11 23 PM" src="https://user-images.githubusercontent.com/123025287/216837181-d76ff045-28f8-43a2-97f6-1a282d95db0a.png">

**Comment by Emory-NLP** [comment]
Everything looks good here. Will upload a new release later today that may solve several problems.

**Comment by christopherli2026** [comment]
Great, thanks so much!
