### ISSUE TITLE
[BUG]: Compute N-grams function does not work 

### ISSUE THREAD

**Issue by christopherli2026** [NLP-Suite/NLP-Suite#1009]
Whenever I press compute n-grams, the program refuses to load. No error messages popped up. 
<img width="1332" alt="Screenshot 2023-02-05 at 1 56 38 PM" src="https://user-images.githubusercontent.com/123025287/216839127-84696783-27be-4826-b72a-4b7f63dd9263.png">

**Comment by Emory-NLP** [comment]
Good lord Christopher. You could continue to try until you are blue in the face. You MUST wait for the new release.

**Comment by christopherli2026** [comment]
Got it, thanks!
