### ISSUE TITLE
WordNet Not Working

### ISSUE THREAD

**Issue by HelenBai2002Tong** [NLP-Suite/NLP-Suite#1018]
When trying to run WordNet with the setting as follows:
<img width="1333" alt="image" src="https://user-images.githubusercontent.com/38171691/217676740-07c9729a-7e3f-449b-9b93-5d5367559cb6.png">

The following error occurred with the error message in the terminal as follows:
<img width="1333" alt="image" src="https://user-images.githubusercontent.com/38171691/217676940-f1759b23-e79a-4a34-8f87-90843597aaa8.png">

I am using a MAC, and my NLP-Suite is on the newest version (3.4.9).

**Comment by Emory-NLP** [comment]
Could you copy/paste the error message you get in terminal with the line number of the error?

**Comment by HelenBai2002Tong** [comment]
Exception in Tkinter callback

Traceback (most recent call last):

  File
"/Users/tongbai/anaconda/envs/NLP/lib/python3.8/site-packages/nltk/corpus/util.py",
line 84, in __load

    root = nltk.data.find(f"{self.subdir}/{zip_name}")

  File
"/Users/tongbai/anaconda/envs/NLP/lib/python3.8/site-packages/nltk/data.py",
line 583, in find

    raise LookupError(resource_not_found)

LookupError:

**********************************************************************

  Resource wordnet not found.

  Please use the NLTK Downloader to obtain the resource:


  >>> import nltk

  >>> nltk.download('wordnet')



  For more information see: https://www.nltk.org/data.html


  Attempted to load corpora/wordnet.zip/wordnet/


  Searched in:

    - '/Users/tongbai/nltk_data'

    - '/Users/tongbai/anaconda/envs/NLP/nltk_data'

    - '/Users/tongbai/anaconda/envs/NLP/share/nltk_data'

    - '/Users/tongbai/anaconda/envs/NLP/lib/nltk_data'

    - '/usr/share/nltk_data'

    - '/usr/local/share/nltk_data'

    - '/usr/lib/nltk_data'

    - '/usr/local/lib/nltk_data'

**********************************************************************



During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File
"/Users/tongbai/anaconda/envs/NLP/lib/python3.8/tkinter/__init__.py", line
1892, in __call__

    return self.func(*args)

  File "knowledge_graphs_WordNet_main.py", line 193, in <lambda>

    run_script_command=lambda: run(GUI_util.inputFilename.get(),

  File "knowledge_graphs_WordNet_main.py", line 76, in run

    filesToOpen=
knowledge_graphs_WordNet_util.disaggregate_GoingDOWN(WordNetDir,outputDir,
wordNet_keyword_list, noun_verb)

  File
"/Users/tongbai/Desktop/NLP-Suite-current-stable/src/knowledge_graphs_WordNet_util.py",
line 57, in disaggregate_GoingDOWN

    process_keyword(wordNet_keyword_list, noun_verb)

  File
"/Users/tongbai/Desktop/NLP-Suite-current-stable/src/knowledge_graphs_WordNet_util.py",
line 39, in process_keyword

    synset = wn.synsets(keyword, pos = wn.NOUN)

  File
"/Users/tongbai/anaconda/envs/NLP/lib/python3.8/site-packages/nltk/corpus/util.py",
line 121, in __getattr__

    self.__load()

  File
"/Users/tongbai/anaconda/envs/NLP/lib/python3.8/site-packages/nltk/corpus/util.py",
line 86, in __load

    raise e

  File
"/Users/tongbai/anaconda/envs/NLP/lib/python3.8/site-packages/nltk/corpus/util.py",
line 81, in __load

    root = nltk.data.find(f"{self.subdir}/{self.__name}")

  File
"/Users/tongbai/anaconda/envs/NLP/lib/python3.8/site-packages/nltk/data.py",
line 583, in find

    raise LookupError(resource_not_found)

LookupError:

**********************************************************************

  Resource wordnet not found.

  Please use the NLTK Downloader to obtain the resource:


  >>> import nltk

  >>> nltk.download('wordnet')



  For more information see: https://www.nltk.org/data.html


  Attempted to load corpora/wordnet


  Searched in:

    - '/Users/tongbai/nltk_data'

    - '/Users/tongbai/anaconda/envs/NLP/nltk_data'

    - '/Users/tongbai/anaconda/envs/NLP/share/nltk_data'

    - '/Users/tongbai/anaconda/envs/NLP/lib/nltk_data'

    - '/usr/share/nltk_data'

    - '/usr/local/share/nltk_data'

    - '/usr/lib/nltk_data'

    - '/usr/local/lib/nltk_data'

**********************************************************************




Thank you for helping with this.


Best,

Tong

Roberto ***@***.***> 于2023年2月8日周三 19:26写道：
