### ISSUE TITLE
Cannot install google earth pro into my machine

### ISSUE THREAD

**Issue by Thegoat098** [NLP-Suite/NLP-Suite#1033]
Hello,

I am having a lot of trouble installing google earth pro into my nlp suite machine (in the install external software part). The instructions say to double click on the .exe file to extract all software files, but I do not see the opportunity to do this, and this could be why I cannot find the directory for google earth pro. If you guys could give me the help for it that would be great. Thank you!

**Comment by Emory-NLP** [comment]
You must upload a screenshot of the NLP_setup__external_software GUI and of the download directory too see what your Google Earth Pro download file looks like.
