### ISSUE TITLE
[BUG]: NER annotator tool Error message (likely issue with tensorflow and Mac M1 chip)

### ISSUE THREAD

**Issue by christopherli2026** [NLP-Suite/NLP-Suite#1037]
<img width="1339" alt="Screenshot 2023-02-19 at 10 06 34 PM" src="https://user-images.githubusercontent.com/123025287/220000398-a67555a7-ae5a-46d8-a882-408eecd1a840.png">

**Comment by Emory-NLP** [comment]
Follow the instructions given. They clearly tell you what to do. But... since tensorflow is installed in STEP2, it seems that you have not run STEP2 after fixing the problems with your machine.
