### ISSUE TITLE
[BUG]: Narrative Analysis GUI unable to set I/O and run

### ISSUE THREAD

**Issue by Max-Cao-1011** [NLP-Suite/NLP-Suite#1038]
**Add a screenshot of the GUI you are running with the widget selections**
![image](https://user-images.githubusercontent.com/110353222/220741503-1ec8a431-d8a7-41f8-b98b-82bb1c8a61da.png)

**Describe the bug**
Cannot enter I/O information, and there is no button for "RUN" no matter what option is chosen.

**To Reproduce**
1. Go to 'GUI for a suite of tools of NLP...'
2. Click on the drop down menu for 'CORPUS/DOCUMENT Analysis Tools'
3. Scroll down to 'Narrative analysis (ALL options GUI)' and click
4. Click 'RUN'

**Screenshots**
![image](https://user-images.githubusercontent.com/110353222/220742282-7e5249c5-fdf5-4d23-ad5b-ef2d54d577f7.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Release Version: NLP Suite -- 3.5.8

**Comment by Emory-NLP** [comment]
The GUI is just a place holder for a number of other GUIs. The RUN button has now been enabled, though.
