### ISSUE TITLE
[BUG]: WordNet GUI, keywords not showing up

### ISSUE THREAD

**Issue by Max-Cao-1011** [NLP-Suite/NLP-Suite#1043]
**Add a screenshot of the GUI you are running with the widget selections**
![image](https://user-images.githubusercontent.com/110353222/221435825-f1003a9f-3d21-4fe7-9b99-16f14da19be7.png)

**Describe the bug**
Keywords not showing up after adding multiple synsets.

**To Reproduce**
1. Go to 'Narrative analysis (all options GUI)'
2. Click on 'Via WordNet' and RUN
3. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/110353222/221435918-97af4d47-6f2d-40b9-908c-6b8c8bfbe7e5.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Release Version 3.6.1

**Comment by Emory-NLP** [comment]
Not an error. It just tells you the synsets you have selected. If you press Show you can see those same values.. You should read the HELP? for that line of widgets. I have added more hover-over info... Will push with next round of edits.
