### ISSUE TITLE
[BUG]: WordNet GUI not reading from input directory

### ISSUE THREAD

**Issue by Max-Cao-1011** [NLP-Suite/NLP-Suite#1044]
**Add a screenshot of the GUI you are running with the widget selections**
![image](https://user-images.githubusercontent.com/110353222/221437392-b565c3ba-97dd-4e5d-a630-e2dad933dbf0.png)

**Describe the bug**
When I checked Zoom in/down to find related words, selected synset and run, it returned a random csv file that is not related to my corpus.

**To Reproduce**
1. Select "WordNet" in CORPUS/DOCUMENT Analysis Tools
2. Click on 'RUN'
3. Set I/O
4. Check "Zoom in/down to find related words"
5. Select synsets
6. Click 'RUN'

**Screenshots**
![image](https://user-images.githubusercontent.com/110353222/221437556-b9a4db1f-1e87-4e7f-bd60-3d066fc142d0.png)
The output result is not generated from my input directory, which contains completely different data.

**Desktop (please complete the following information):**
 - OS: windows 10
 - Release Version 3.6.1

**Comment by Emory-NLP** [comment]
Not an error. Added hover-over info. That algorithms only takes as input the WordNet lexical database and not the I/O configuration document(s).
