### ISSUE TITLE
[BUG]: Error while trying to run WordNet Zoom in/down and find related words for synset "person"

### ISSUE THREAD

**Issue by lengseongche** [NLP-Suite/NLP-Suite#1048]
**Add a screenshot of the GUI you are running with the widget selections**
<img width="1345" alt="Screen Shot 2023-02-27 at 5 07 53 PM" src="https://user-images.githubusercontent.com/122478647/221696881-521e6ec5-6b51-4952-9da1-f490cac58801.png">

**Screenshots**
<img width="566" alt="Screen Shot 2023-02-27 at 5 09 45 PM" src="https://user-images.githubusercontent.com/122478647/221697164-03a11f95-de47-437c-8698-8672f4879bfc.png">

**Desktop (please complete the following information):**
 - MAC OS 12.6.3
 - Release Version 3.6.3

**Comment by Emory-NLP** [comment]
Wrong version of WordNet downloaded.
