### ISSUE TITLE
[BUG]: N-grams Viewer error 

### ISSUE THREAD

**Issue by mstout4721** [NLP-Suite/NLP-Suite#105]
**Describe the bug**
When I tried to run the N-grams and Word Co-occurrences Viewer GUI, I encountered an error stating that the "Searched_N-Grams.csv" file did not exist in my output directory. This is causing the code to fail. I looked throughout my files to fine this csv file and it does not exist on my computer. Is this a file that the GUI itself is supposed to create? Or do I need to download it from somewhere?

I am using the Inaugural Addresses corpus. I renamed all the files as follows : "In_mm-dd-yyyy" format. (Initially I just had it as mm-dd-yyyy, but the GUI did not like that. I had to put the some word before the date so I just did "In" as in "inaugural".) 

**To Reproduce**
1. Go to the N-Grams and Word Co-occurrences Viewer GUI
2. Click on 'N-grams VIEWER' and input any search word. I put 'God.' 
3. click date options, aggregate by year, format mm-dd-yyyy, Character separator as _  , and position 2
4. Run. The error should be found in the command line. 

**Screenshots**
<img width="571" alt="Screen Shot 2021-03-03 at 5 49 14 PM" src="https://user-images.githubusercontent.com/60442497/109891107-19f96480-7c4e-11eb-9787-030ae753477d.png">
<img width="635" alt="Screen Shot 2021-03-03 at 5 49 31 PM" src="https://user-images.githubusercontent.com/60442497/109891113-1d8ceb80-7c4e-11eb-8813-2176d71e08fa.png">

**Desktop :**
 - OS: Mac OS 
 - Release Version: NLP 2021_02_04 version with recent auto_update package from GitHub added

**Comment by DDVD233** [comment]
It looks like Yingying is also having the same issue. 
![Xnip2021-03-04_21-02-58](https://user-images.githubusercontent.com/16710181/109969354-c27ef580-7d2e-11eb-9db7-7a06a756b41d.jpg)

However, I am not able to reproduce that issue on my machine. So I am not sure what caused it. 
By the way, the Chinese in the screenshot is just the Java usage manual. It seems like we are calling java in a incorrect way.

**Comment by RafaelPiloto10** [comment]
Looks like you get the same error towards the end "No such file or directory: ......", but the root cause is the incorrect usage of java. I am getting the same error on my machine as well (OS X). However, my corpus is formatted "mm-dd-yyyy" and my separator value is " ".  When this is passed in the java command, it produces an extra space. This may be a bug for future reference

**Comment by Emory-NLP** [comment]
Moved away from Java version to a Python version
