### ISSUE TITLE
CLOSE button

### ISSUE THREAD

**Issue by Emory-NLP** [NLP-Suite/NLP-Suite#1050]
Most users do not use the CLOSE button available in all GUIs to CLOSE the GUI. They tend to use the red button on Mac or X on Windows. This habit, unfortunately, does not allow to run functions run when clicking CLOSE. The worse consequence of this habit is that the NLP Suite is never updated. We must trap the use of red button or X and pass it to CLOSE.

**Comment by vkameswaran** [comment]
This does not appear to stop the NLP Suite from updating. No matter how I close the window, it appears to automatically pull new updates. The only place I saw this issue was when I tried to update settings in the NLP_setup GUIs. This can be fixed by adding a line near the end of the file, right before going into the main loop, as in this example.

```python
GUI_util.window.protocol("WM_DELETE_WINDOW", close_GUI) # new line
GUI_util.window.mainloop() # existing line
```

In `NLP_setup_external_software_main` and `NLP_setup_package_language_main` we can add this line:
```python
GUI_util.window.protocol("WM_DELETE_WINDOW", close_GUI)
```

Since `NLP_setup_IO_main` is structured slightly differently, the required line is instead:
```python
GUI_util.window.protocol("WM_DELETE_WINDOW", lambda: close_GUI(IO_configuration_upon_entry))
```

**Comment by Emory-NLP** [comment]
Added the lines to NLP__setup GUIs and will push. Do the added lines also allow the functions to perform the checks for value changes (and save) that the CLOSE performs?

**Comment by vkameswaran** [comment]
Ah, I wasn't clear. These updates mainly ensure that the config changes are checked and saved, no matter how the setup windows are closed. The git pull already happens correctly from all the GUIs.

**Comment by Emory-NLP** [comment]
Ehm. In the NLP_setup GUIs, upon hitting CLOSE, the code behind it also checks whether any changes have been made and asks the user to save. Roberto

From: Vaishant Kameswaran ***@***.***>
Sent: Monday, March 13, 2023 9:35 AM
To: NLP-Suite/NLP-Suite ***@***.***>
Cc: Franzosi, Roberto ***@***.***>; Author ***@***.***>
Subject: [External] Re: [NLP-Suite/NLP-Suite] CLOSE button (Issue #1050)


Ah, I wasn't clear. These updates mainly ensure that the config changes are checked and saved, no matter how the setup windows are closed. The git pull already happens correctly from all the GUIs.

-

**Comment by vkameswaran** [comment]
Right. Before this change, those checks would only happen if the user clicked the CLOSE button. These lines make sure that happens even if they [x] out of the GUI.

**Comment by Emory-NLP** [comment]
Great. Thank you Vaishant. Will wait to see if you can solve the freezing OK or Yes/No timed buttons then I'll push.

From: Vaishant Kameswaran ***@***.***>
Sent: Monday, March 13, 2023 9:44 AM
To: NLP-Suite/NLP-Suite ***@***.***>
Cc: Franzosi, Roberto ***@***.***>; Author ***@***.***>
Subject: [External] Re: [NLP-Suite/NLP-Suite] CLOSE button (Issue #1050)


Right. Before this change, those checks would only happen if the user clicked the CLOSE button. These lines make sure that happens even if they [x] out of the GUI.

-
