### ISSUE TITLE
[BUG]: Trying to convert output to JSON.. Could not convert output to JSON! Stanford CoreNLP

### ISSUE THREAD

**Issue by atn25** [NLP-Suite/NLP-Suite#1051]
**Add a screenshot of the GUI you are running with the widget selections**

**Describe the bug**
Every chapter of the book is met with the error that Stanford CoreNLP cannot process the file. It says that the output cannot be converted to JSON. 
**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/100001530/222628573-b634513e-af14-4590-9bd0-a0ca5c2c4fd6.png)**Desktop (please complete the following information):**
![image](https://user-images.githubusercontent.com/100001530/222875046-524a85ba-0b1d-4235-bb8b-242710acc968.png) - OS X 

**Additional context**

**Comment by Emory-NLP** [comment]
You should always add the screenshot of the GUI you are running or we have no clue... The GUI would also tells us if you are running Mac or Windows and which release of the NLP Suite :-)

**Comment by atn25** [comment]
> 

Just added the GUI screenshot
