### ISSUE TITLE
[BUG]: Opened gexf file with Gephi but no SVO network graphs shown

### ISSUE THREAD

**Issue by lengseongche** [NLP-Suite/NLP-Suite#1052]
**Add a screenshot of the GUI you are running with the widget selections**
<img width="1351" alt="Screen Shot 2023-03-05 at 10 05 18 AM" src="https://user-images.githubusercontent.com/122478647/222968664-413af0e0-b66a-4a69-9eb6-a7cb2356a5da.png">

**Describe the bug**
I am using the HIV corpus. I tried to open the output gexf files from SVO Extraction & Visualization Pipeline but no network graphs are shown in Gephi. 

**Screenshots**
<img width="1295" alt="Screen Shot 2023-03-05 at 10 01 39 AM" src="https://user-images.githubusercontent.com/122478647/222968808-ec2de988-b2ee-4bf3-adbc-765298724f7e.png">

**Desktop (please complete the following information):**
 - OS: macOS 12.6.3
 - Release Version NLP 3.6.4 version

**Comment by Emory-NLP** [comment]
ehm. I see that you are using Gephi 10. Have you tried to click on data laboratory or preview? Is there anything there? Can you try the Gephi option under data_visualiztion GUI with the SVO csv file and see if that works?

**Comment by lengseongche** [comment]
> ehm. I see that you are using Gephi 10. Have you tried to click on data laboratory or preview? Is there anything there? Can you try the Gephi option under data_visualiztion GUI with the SVO csv file and see if that works?

I tried clicking on data laboratory and preview, and they seem empty too. Then I tried the Gephi option under data visualization GUI. The output HTML worked but still, no graphs were shown in Gephi.

**Comment by Emory-NLP** [comment]
Maybe we can Zoom in half an hour or so if you are available?

**Comment by lengseongche** [comment]
> Maybe we can Zoom in half an hour or so if you are available?

Yes I am available after 12:30. Thank you Professor Franzosi!
