### ISSUE TITLE
[BUG]: Sentiment Analysis GUI has shape of stories checkbox disabled

### ISSUE THREAD

**Issue by vkameswaran** [NLP-Suite/NLP-Suite#1054]
**Add a screenshot of the GUI you are running with the widget selections**

<img width="1462" alt="Screenshot 2023-03-17 at 1 06 57 PM" src="https://user-images.githubusercontent.com/20121935/225971815-8988a5f8-ce14-47aa-b964-536035ae2994.png">

**Describe the bug**

The help button and code comments say that the "Open Shape of Stories GUI" checkbox should be enabled when CoreNLP is selected as the algorithm.

> The 'Shape of stories' GUI is only available when computing sentiment scores via Stanford CoreNLP on a corpus of txt files in an input directory.

However, this is not happening (see screenshot). It is only enabled when "*" is selected.

**To Reproduce**
1. Open Sentiment Analysis GUI
2. Select Stanford CoreNLP as the algorithm
3. Note that checkbox is not enabled

**Solution**
This is happening because the [code](https://github.com/NLP-Suite/NLP-Suite/blob/current-stable/src/sentiment_analysis_main.py#L433) is checking for "Stanford CoreNLP" while the actual string is "&nbsp;&nbsp;&nbsp;Stanford CoreNLP" (with leading spaces). This can be fixed by changing `SA_algorithm_var.get()!='Stanford CoreNLP'` to `SA_algorithm_var.get().strip()!='Stanford CoreNLP'`, to automatically remove any leading spaces.

**Comment by Emory-NLP** [comment]
A bit complicated issue that had been left undone; fixed along with opening the shape_of_stories GUI with the correct csv file.
