### ISSUE TITLE
[BUG]: Sentiment Analysis stopped at "done loading processor"

### ISSUE THREAD

**Issue by Max-Cao-1011** [NLP-Suite/NLP-Suite#1056]
**Add a screenshot of the GUI you are running with the widget selections**
![image](https://user-images.githubusercontent.com/110353222/226124369-3266a2aa-2b05-4821-956f-4cb89e0d290b.png)

**Describe the bug**
After hitting run, the terminal stucked at "Done loading processors!" for more than 12 hours with no output generated.

**To Reproduce**
1. Select 'Sentiment Analysis' in Corpus/Document analysis tools
2. Tick the boxes for calculate sentence mean and median, and select *(all) sentiment analysis algorithm
3. Click 'RUN'

**Screenshots**
<img width="684" alt="d69cf50a92b44b6741e56db4a2512a5" src="https://user-images.githubusercontent.com/110353222/226124502-32a77a75-e827-4a2b-8eac-6fca06afa3e2.png">

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Release Version 3.6.5

**Additional context**
Also had the same problem on Mac

**Comment by Emory-NLP** [comment]
Could you try the same options with "The three little pigs" document under lib?

**Comment by Max-Cao-1011** [comment]
Yes, it can generate output for "The three little pigs", and a error message pops up. I'll try Harry Potter again after pip install.
![image](https://user-images.githubusercontent.com/110353222/226125847-53cb22eb-bb0b-4d5d-8fb5-681826c88659.png)

**Comment by Max-Cao-1011** [comment]
It still not works for Harry Potter, the command line stucks at "Done loading processors" again. But I was able to generate output from the three little pigs.
![image](https://user-images.githubusercontent.com/110353222/226126209-128d27dc-3d0d-435d-b2cf-318f49e91ca1.png)
