### ISSUE TITLE
BUG: Not sure if this is a bug but we get this message for our corpus (German folktales)

### ISSUE THREAD

**Issue by christopherli2026** [NLP-Suite/NLP-Suite#1060]
<img width="1347" alt="Screenshot 2023-03-20 at 9 37 04 PM" src="https://user-images.githubusercontent.com/123025287/226500011-3c989157-aae3-4650-985e-57d8acd73225.png">

**Comment by Emory-NLP** [comment]
It seems that there are no locations? Does the NER subfolder contain any csv file with locations? Very possible that a fairytale may have no geocodable locations.

**Comment by christopherli2026** [comment]
According to NER, there are a few locations recognized, as well as a few countries and other places. I think this might be a bug but I'm not completely sure.

Christopher Li
Biology BS and Chemistry BA '26
Emory University
732-526-5631
***@***.***
________________________________
From: Roberto ***@***.***>
Sent: Monday, March 20, 2023 10:51 PM
To: NLP-Suite/NLP-Suite ***@***.***>
Cc: Li, Christopher ***@***.***>; Author ***@***.***>
Subject: [External] Re: [NLP-Suite/NLP-Suite] BUG: Not sure if this is a bug but we get this message for our corpus (German folktales) (Issue #1060)


It seems that there are no locations? Does the NER subfolder contain any csv file with locations? Very possible that a fairytale may have no geocodable locations.
