### ISSUE TITLE
Appending time of creation to avoid overriding an output folder

### ISSUE THREAD

**Issue by bianshuyang** [NLP-Suite/NLP-Suite#1065]
<img width="1284" alt="image" src="https://user-images.githubusercontent.com/52821055/227633890-1ebe189e-332e-4124-920f-d216748dcb6d.png">
This shouldn't be limited to computer version, but it's an M2 chip.
When rerun using same corpus but with different input on N-gram, if one re-runs it and did not rename the results folder, it will be emptied immediately and past results will lost.
Solution: Just easily append time.time or python datetime package of current date and time to rename the outputed folder. For instance, 
nGrams-VIEWER_Final_corpus 
could be renamed to:
nGrams-VIEWER_Final_corpus-20230324164100, meaning 2023/Mar/24, 16:41:00 starting running

Example today:
<img width="506" alt="image" src="https://user-images.githubusercontent.com/52821055/227634793-13296f63-1279-4f66-9506-9fccd09dd88e.png">
Only the results of the second one were there, the first one was lost (but recoverable by rerunning the entire algorithm again)

**Comment by Emory-NLP** [comment]
We do have that option in the file creation option but we disconnected it as it typically creates filenames too long for Windows and different scripts then crash.
