### ISSUE TITLE
Potential non-updated "getFileList" code in SVO_main.py

### ISSUE THREAD

**Issue by bianshuyang** [NLP-Suite/NLP-Suite#1068]
We need to import the function "getFileList" in the SVO_main.py as well.
<img width="479" alt="image" src="https://user-images.githubusercontent.com/52821055/231002368-fce560f6-920d-4662-80c8-15f4fbe9a19f.png">

**Comment by Emory-NLP** [comment]
The getFileList for SVO is processed in _util (CoreNLP, Stanza, spaCy). It is never processed in _main for any GUI. Works perfectly well with the newspaper articles in lib\sampleData.
