### ISSUE TITLE
[BUG]: Install requires Microsoft Visual Studio C++ 14.0 or greater to build requirements

### ISSUE THREAD

**Issue by RafaelPiloto10** [NLP-Suite/NLP-Suite#107]
**Describe the bug**
To pip install some of the requirements, Microsoft Visual Studio C++ is required to build the modules.

**To Reproduce**
1. Create a new conda environment
2. Install the requirements via `python -m pip install -r requirements.txt`

**Expected behavior**
All requirements should be installed without any error.

**Screenshots**
![image](https://user-images.githubusercontent.com/31188361/109914216-817ad880-7c7d-11eb-9d43-def652f1eb8e.png)

**Desktop (please complete the following information):**
 - OS: Windows

**Additional context**
Solution: Install the [windows build tools package](https://visualstudio.microsoft.com/visual-cpp-build-tools/) and install C++.
![image](https://user-images.githubusercontent.com/31188361/109914296-a53e1e80-7c7d-11eb-85ae-6eabeb0ed7a6.png)

**Comment by RafaelPiloto10** [comment]
This bug has a manual solution that does not require much tech-savvy labor - investigating to see if there is a way to auto install this dependency in case the user needs it.

**Comment by DDVD233** [comment]
This is interesting. I tested it on a freshly installed Windows virtual machine and never got that error. Could that be related to the Python version or Windows version?

**Comment by RafaelPiloto10** [comment]
The specs to my machine can be found here.

![image](https://user-images.githubusercontent.com/31188361/109977752-2374e200-7ccb-11eb-9e4d-7499c373142f.png)
![image](https://user-images.githubusercontent.com/31188361/109977922-561eda80-7ccb-11eb-9778-ffefb9f74ee5.png)

Could be related to my Windows install.

**Comment by Emory-NLP** [comment]
Added the error and solution to the GitHub wiki troubleshoooting page for Microsoft C++
