### ISSUE TITLE
Issue with topic modeling in mallet

### ISSUE THREAD

**Issue by Ronoodle7** [NLP-Suite/NLP-Suite#1070]
<img width="953" alt="image" src="https://user-images.githubusercontent.com/124203158/231317968-631b3ea8-cb6e-4d69-9140-0720eec06e49.png">
On windows
Whenever I try to run topic modeling with Mallet, I get this error. But there is no space in the directory.

**Comment by Emory-NLP** [comment]
Can you read???? What does the message say? You will get points deducted for this.
