### ISSUE TITLE
[BUG]: Word2Vec Unicode Encode Error and Runtime Error

### ISSUE THREAD

**Issue by Max-Cao-1011** [NLP-Suite/NLP-Suite#1074]
**Add a screenshot of the GUI you are running with the widget selections**
BERT:
![image](https://user-images.githubusercontent.com/110353222/232104636-8d075880-88c2-480b-b187-3de470192bf0.png)
Gensim:
![image](https://user-images.githubusercontent.com/110353222/232104672-0eabfe8c-8372-458b-b727-3b4c2b2d0e3c.png)

**Describe the bug**
BERT produced RuntimeError: you must first build vocabulary before training the model.
Gensim produced UnicodeEncodeError: 'charmap' codec can't encode character '\u25c4' in position 276398: character maps to 'undefined'

**To Reproduce**
1. Go to 'Word embeddings (Word2Vec) (via BERT & Gensim)'
2. Select visualization option to  'Plot word vectors' and '2D'
3. Select either 'Word embeddings (via BERT)' or 'Word2Vec (via Gensim)'
4. Click RUN

**Screenshots**
BERT Error:
![image](https://user-images.githubusercontent.com/110353222/232105436-515d6a31-9202-4fcc-8f03-a532fa8ea964.png)
Gensim Error:
![image](https://user-images.githubusercontent.com/110353222/232105574-4d2a96ac-abb1-4d33-aa80-e90b3f667025.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Release Version 3.7.2

**Comment by Emory-NLP** [comment]
Misleading message. In reality, the Three Little Pigs file is simply too small for training. Will test for file length. For now, if you are using the file for a video, use Murphy - Miracles thicker than fog and it will work.

**Comment by Max-Cao-1011** [comment]
Dr. Franzosi,
I ran the Harry Potter corpus using the same widget selection (for BERT) as above, and it returned the following error after runing for 3 hours, and the only HTML output is empty:
![image](https://user-images.githubusercontent.com/110353222/232251478-063e7965-f774-40b4-b4ec-ce3bb38f927c.png)

**Comment by Emory-NLP** [comment]
Not a clue Max. And unfortunately, I am swamped to look into it :-
