### ISSUE TITLE
[BUG]: word embedding wordvec GUI error 

### ISSUE THREAD

**Issue by DaekyungGo** [NLP-Suite/NLP-Suite#1080]
**Add a screenshot of the GUI you are running with the widget selections**
<img width="709" alt="image" src="https://user-images.githubusercontent.com/123411357/232933746-dfdce615-70c2-42b7-912d-e337642f8acb.png">
**Describe the bug**
When running GUI for Word2vec (via Gensim), such error in terminal occurs. (AttributeError: 'list' object has no attribute 'shape')

A clear and concise description of what the bug is. Please indicate what corpus you are using.

**To Reproduce**

**Screenshots**
Add screenshots to help explain your problem and indicate the error.

**Desktop (please complete the following information):**
 - OS: [e.g. OS X/Windows]
 - Release Version (type `NLP --version` e.g. 22) 

**Additional context**

**Comment by Emory-NLP** [comment]
Can you open terminal and type pip show gensim and post the screenshot of the result?

**Comment by DaekyungGo** [comment]
<img width="707" alt="image" src="https://user-images.githubusercontent.com/123411357/232949379-4be59f47-b29d-4a81-bf2f-f2974fc71bfe.png">

Here it is. Thank you.
