### ISSUE TITLE
STEP1 STEP2 STEP3 NLP Suite Installation

### ISSUE THREAD

**Issue by Emory-NLP** [NLP-Suite/NLP-Suite#1108]
After the implementation of Tensorflow/BERT in the NLP Suite and the M1 and M2 Apple chips, users have serious problems with STEP1, STEP2 and STEP3.

**Comment by bianshuyang** [comment]
[requirements_m1.txt](https://github.com/NLP-Suite/NLP-Suite/files/12500757/requirements_m1.txt)
Recent classroom experience suggests that simply updating M2's requirement to the above file, and coupled with brew install numpy, brew install scipy will most likely resolve the issue.
User should also attempt to follow the brew installation instructions written at: https://github.com/bianshuyang/M2installNLP
