### ISSUE TITLE
[BUG]: AttributeError: module 'PIL.Image' has no attribute 'Resampling

### ISSUE THREAD

**Issue by kaavyamuthuganesan** [NLP-Suite/NLP-Suite#1112]
![error](https://github.com/NLP-Suite/NLP-Suite/assets/142953438/2c5491b7-20a6-4257-b1a9-bbca09a71e17)
**Describe the bug**
When I attempt to run the NLP Suite I receive the above error message. I also had an issue with Step 1, where when I tried to verify the installation of anaconda following the instructions in wiki, I received an error when using conda but not anaconda.
![issue with step 1 verification](https://github.com/NLP-Suite/NLP-Suite/assets/142953438/6d8c09f7-1c9d-48b6-93eb-7c7a0bceba5b)

**Desktop (please complete the following information):**
 - OS: Windows
 - Release Version  `NLP version 3.9.0`

**Comment by Emory-NLP** [comment]
The problem is NOT with PIL but with the fact that Anaconda (conda) is not installed. Please, contact Simon at simon.bian@emory.edu to help you re-run STEP1 etc.

**Comment by kaavyamuthuganesan** [comment]
Hi, I asked Simon in class and he helped me check my STEP 1 and he said anaconda has been installed. When doing step 2 he told me to change all the condas to anaconda instead. The anaconda version which has been installed is version 1.7.2.
