### ISSUE TITLE
NLP GUI has dark background [MAC]

### ISSUE THREAD

**Issue by ajuare5** [NLP-Suite/NLP-Suite#1117]
**Screenshot**
<img width="1507" alt="image" src="https://github.com/NLP-Suite/NLP-Suite/assets/109641563/445861ae-0cf3-485a-9f3c-d89feaea482f">
**macOS Ventura 13.5**
**NLP Release 3.8.9/3.9.2**
***
**Description**
An issue was brought up in class on August 30, 2023, in which the NLP GUI had a black background which made some texts, widgets, buttons, etc. hard to see, read, and distinguish. 
***
**Solution**
To change the visual appearance on macOS:
1. Click on the Apple menu in the top-left corner of your screen.
2. Select "System Preferences" from the drop-down menu.
3. In the System Preferences window, click on "General."
4. In the "Appearance" section, you'll see three options: "Light," "Dark," and "Auto." Click on "Light" to switch to Light mode.
*Switching to Auto may also work if you want to keep the dark appearance on for other *
5. The NLP GUI should change to a light background

**Comment by bianshuyang** [comment]
Thanks for finding out the solution!
