### ISSUE TITLE
Bug when clicking on Setup default NLP parsers... in the NLP Main Menu

### ISSUE THREAD

**Issue by kaavyamuthuganesan** [NLP-Suite/NLP-Suite#1118]
![nlp main menu button error](https://github.com/NLP-Suite/NLP-Suite/assets/142953438/37fd9479-384f-4b76-b219-921762a3aedc)

When I click on the button to set up the NLP default parsers I get the following errors:
![error](https://github.com/NLP-Suite/NLP-Suite/assets/142953438/bf13c9cd-0165-4f4d-8ec9-83fe40a5379a)

**Comment by bianshuyang** [comment]
Unsure how you run the NLP Suite... If you are not using virtual environment, try conda activate to enter a virtual environment, install all dependencies if prompted so, and use python3 NLP_menu_main.py again to see if the issue gets resolved.

**Comment by kaavyamuthuganesan** [comment]
Issue resolved when I run NLP suite through the terminal with command python "C:\Program Files\NLP-Suite-current-stable\src\NLP_menu_main.py"
