### ISSUE TITLE
[BUG]: NLP Suite cannot create charts

### ISSUE THREAD

**Issue by coralynnkc** [NLP-Suite/NLP-Suite#1121]
0. SCREENSHOTS.
![error 1](https://github.com/NLP-Suite/NLP-Suite/assets/142829954/2ba8e776-f6b1-4ee4-8634-f1eaa541281f)
![error 2](https://github.com/NLP-Suite/NLP-Suite/assets/142829954/8ff1a496-ac61-4c42-add9-2b0befe88eb3)
![error 3](https://github.com/NLP-Suite/NLP-Suite/assets/142829954/868097f6-6e03-4620-9cc7-7cfbc3a932d6)
![error 4](https://github.com/NLP-Suite/NLP-Suite/assets/142829954/321239ab-9ff1-4f1a-8cae-b782691c62d2)
![error 5](https://github.com/NLP-Suite/NLP-Suite/assets/142829954/b084e16a-8278-420e-9cee-49e493588771)

1. DESCRIPTION.
For the corpus The Three Little Pigs.txt,  'compute document(s) statistics' with 'create chart(s)' is only producing .csv files, then failing to produce charts because the produced .csv files are being read as empty. 

2. STEPS.
1. NLP Suite Main Menu GUI
2. General Utility Tools -> Statistical Tools -> Statistics (txt files) -> Run
3. Compute Document Statistics -> Run

3. INFORMATION.
Windows OS
NLP Suite Release 3.9.2

**Comment by bianshuyang** [comment]
Try these:
1) Update NLP Suite. If it doesn't work, delete the "config" folder as well.
2) Try to place output directly in C:\Users and no other sub folders. 
These might not work as it is machine dependent.

**Comment by kaavyamuthuganesan** [comment]
Hi I am facing a similar error, was not sure if you were able to get it to work for you.
