### ISSUE TITLE
[BUG]: Fail to run the World Cloud

### ISSUE THREAD

**Issue by ZichenHuang000** [NLP-Suite/NLP-Suite#1124]
![屏幕截图 2023-09-04 143613](https://github.com/NLP-Suite/NLP-Suite/assets/143022231/fd17b366-504c-4c94-81cf-a90a553f7f51)
![屏幕截图 2023-09-04 143449](https://github.com/NLP-Suite/NLP-Suite/assets/143022231/853c803c-b3be-46d4-8b94-51b812ed111f)

DESCRIPTION
When I click the "RUN", it does not generate anything, and the command line stops at "AttributeError: 'ImageDraw' object has no attribute 'textsize'".

STEPS
1. main menu
2. visualization tools: Wordclouds (all options GUI)
3. "RUN"

Windows OS
NLP Suite Release 3.9.2

Additional context: 
The external software WORDNET is missing after an updates, I downloaded it from the website and the Win self extractor installed it on desktop, but there is no file named WORDNET and thereby NLP Suite cannot find its directory to. I am not sure if this is what has caused the failure to run Wordclouds
![屏幕截图 2023-09-04 145452](https://github.com/NLP-Suite/NLP-Suite/assets/143022231/30007bdf-0884-4584-b4a3-ab1b234652bc)

**Comment by Emory-NLP** [comment]
Which Windows version are you running?

**Comment by ZichenHuang000** [comment]
It is the Windows 11.

**Comment by bianshuyang** [comment]
https://stackoverflow.com/questions/76189891/imagedraw-object-has-no-attribute-textbbox
Based on info, In outside conda, regular conda, conda's NLP env, could you make sure you install by the following line?
pip3 install Pillow==9.5.0

**Comment by ZichenHuang000** [comment]
I kinda forget but where could I type this line in, or where could I find the outside conda, regular conda, conda's NLP env?
![屏幕截图 2023-09-04 161812](https://github.com/NLP-Suite/NLP-Suite/assets/143022231/7ae5f372-dbe4-46a8-be92-dbd7ae43568d)

**Comment by bianshuyang** [comment]
pip is in terminal ... Helpful link: https://www.youtube.com/watch?v=9z7gGUbAj5U
It is advisable to google how to pip install and use anaconda in command line...
Otherwise, try booking an appointment with me: https://calendly.com/simonbian/nlpinstall

**Comment by bianshuyang** [comment]
Open terminal, then type pip install Pillow==9.5.0. If you don't know how to open the terminal, simply in the folder, then type "Powershell", and it will pop up a terminal for you to do command-line prompts.

**Comment by ZichenHuang000** [comment]
Pillow 9.5.0. is installed and question is solved, thank you so much!
