### ISSUE TITLE
[BUG]: NLP Suite, cannot run GUI for Data Visualization

### ISSUE THREAD

**Issue by SahithiGangaram434** [NLP-Suite/NLP-Suite#1125]
0. SCREENSHOTS
<img width="899" alt="image" src="https://github.com/NLP-Suite/NLP-Suite/assets/78706301/42ac8c88-bc6f-46b6-86ff-536612450133">

1. DESCRIPTION
I am experiencing an issue when attempting to run the NLP Suite data visualization GUI. Instead of launching, I encounter an error message in the command prompt. My corpus is Indian Folktales. The error message is as follows:
<img width="1112" alt="image" src="https://github.com/NLP-Suite/NLP-Suite/assets/78706301/51d09ff8-dadb-441c-95ad-43e000dde8bf">

It appears that the error is occurring in the 'file_spell_checker_util.py' file when attempting to import various Python packages. The specific error message relates to an 'AttributeError' in the 'read_text' method of a 'WindowsPath' object. Please advise on how to resolve this issue. Thank you!

2. STEPS
1. download the NLP Suite from the GitHub repository.
2. Navigate to the root directory of the NLP Suite project.
3. Run the NLP Suite data visualization GUI with Visualization tools dropdown menu (Wordclouds) and CORPUS/DOCUMENT Analysis Tools (Style Analysis) 
4. Observe that nothing happens, and the above error message appears in the command prompt

This error prevents the NLP Suite data visualization GUI from launching.

3. DESKTOP information
Microsoft Windows 11 Home 
NLP Suite Release 3.9.3/3.9.3

**Comment by bianshuyang** [comment]
Issue identified in: https://github.com/explosion/spaCy/issues/5301
Not completely replicable.
My advice: 1) Uninstall spacy. Typically it is pip uninstall spacy
2) Then immediately use conda to install spacy again: conda install -c conda-forge spacy
or conda install spacy.
3) If not, try pip install spacy again.
Also, remember to download the required component called "en_core_web_sm":
pip install -U pip setuptools wheel
pip install -U spacy
python -m spacy download en_core_web_sm
Please, for all installation instructions, follow: https://spacy.io/usage

If non works, visit my calendly and let's debug more. https://calendly.com/simonbian/

**Comment by bianshuyang** [comment]
The issue was resolved by completely removing the buggy and reinstalling a newest version of anaconda, and reinstalling all dependencies based on the requirements.txt. Possible suggestion: buggy anaconda version + Windows 11 environment path results in the incompatability. 
Note: Likely suggests the need to upgrade drastically the current installation scripts given the surprisingly new features of Windows 11.
