### ISSUE TITLE
[BUG]: Importing CORPUS text folder

### ISSUE THREAD

**Issue by Deesha12345** [NLP-Suite/NLP-Suite#1129]
**Add a screenshot of the GUI you are running with the widget selections**

**Describe the bug**
The assignment says to upload the whole corpus for mass text analysis, however it wont allow me to upload more than one document in the input section. 

**Desktop (please complete the following information):**
 - Mac M2
 - Release Version
<img width="1130" alt="Screenshot 2023-09-07 at 9 10 25 AM" src="https://github.com/NLP-Suite/NLP-Suite/assets/143028806/2c94e30b-6a4c-49ee-9e66-a83779d882dd">

**Comment by bianshuyang** [comment]
You must select "directory" (2nd option) not "file" . Read readme and help files.
