### ISSUE TITLE
[BUG]:Taking forever to run when input is directory.

### ISSUE THREAD

**Issue by ZichenHuang000** [NLP-Suite/NLP-Suite#1131]
![屏幕截图 2023-09-07 133301](https://github.com/NLP-Suite/NLP-Suite/assets/143022231/d35e51b4-cf9b-4fb7-9399-15d803b0b0ab)
![屏幕截图 2023-09-07 133321](https://github.com/NLP-Suite/NLP-Suite/assets/143022231/42bf4476-65cc-4501-a6e9-90d9cd49c66e)

DESCRIPTION
N-grams computation functions well when the input is one single text file, and when the input is newspaperarticles directory. But it takes forever to run when the input directory is a file containing more than 500 files and the command line stops at "Processing file 504/504 xxx.txt". I am not sure if this is normal or there's something wrong.

STEPS
1. go to "Style analysis(all options GUI)
2. Compute n-grams

Desktop
Windows 11
 NLP Suite 3.9.2

**Comment by bianshuyang** [comment]
Did a more limited data set appear to be working? (such as, 4 documents, 14 documents, etc.) Thanks. In computing, the NLP will parse the data and display nearly every word in some of the programs, rendering extremely large documents, eating up a lot of your memory...

**Comment by ZichenHuang000** [comment]
Yes a more limited data set does work. Thank you!
