### ISSUE TITLE
[BUG]: Folder created, no data being put in

### ISSUE THREAD

**Issue by aamaya5** [NLP-Suite/NLP-Suite#1133]
**Add a screenshot of the GUI you are running with the widget selections**
<img width="571" alt="Screenshot 2023-09-08 at 12 28 47 AM" src="https://github.com/NLP-Suite/NLP-Suite/assets/144411465/f6c64e59-2b9f-47bc-85c1-2a992a747b09">
<img width="977" alt="Screenshot 2023-09-08 at 12 28 33 AM" src="https://github.com/NLP-Suite/NLP-Suite/assets/144411465/8019fb1f-fa49-4035-91e9-8b1325aa3983">
<img width="1345" alt="Screenshot 2023-09-08 at 12 29 16 AM" src="https://github.com/NLP-Suite/NLP-Suite/assets/144411465/ed1b71bf-9755-4c7c-93f4-730712e2c83d">

**Describe the bug**
Input and output files are being read correctly and the folder with all the output is being created, however this is no data being put into the file, and the folder is empty. I am using the novels English corpus.

**To Reproduce**
1. Go to NLP and open the N-Gram GUI
2. Using the novels English corpus, run the N-Gram.
3. Go to the output folder and see no data.
4. Terminal says " language_list ['English'] "

**Desktop (please complete the following information):**
 - Macbook Air M2 Chip
 - Release Version  NLP Suite Version 3.9.4

**Comment by bianshuyang** [comment]
Read readme, tips and [help?] button. You must select >=1 of the "VIEWER".


I copied the [?help] below:
```

Please, tick the Ngram VIEWER checkbox if you wish to run the Ngram Viewer script.

Tick the Co-Occurrence VIEWER checkbox if you wish to run the Co-Occurrene Viewer script.

You can run both Viewers at the same time.

The NGrams part of the algorithm requires date metadata, i.e., a date embedded in the filename (e.g., The New York Time_2-18-1872). YOU CAN SETUP DATES EMBEDDED IN FILENAMES BY CLICKING THE "Setup INPUT/OUTPUT configuration" WIDGET AT THE TOP OF THIS GUI AND THEN TICKING THE CHECKBOXES "Filename embeds multiple items" AND "Filename embeds date" WHEN THE NLP_setup_IO_main GUI OPENS.

For both viewers, results will be visualized in Excel line plots.

For n-grams the routine will display the FREQUENCY OF NGRAMS (WORDS), NOT the frequency of documents where searched word(s) appear. For Word Co-Occurrences the routine will display the FREQUENCY OF DOCUMENTS where searched word(s) appear.
```

**Comment by Emory-NLP** [comment]
Several comments.
1. Change your Mac settings not too have a black background
2. The I/O text box does not show any values selected
3. Have you clicked the RUN button; nothing happens otherwise; and when you click RUN it will warn you of what you are missing.

**Comment by aamaya5** [comment]
Hello,

Thank you guys for your help. However, none of the English folktales files
contain any date. Are we supposed to date each of the individual files?

Best,
Aiden Amaya

**Comment by bianshuyang** [comment]
If there is no date, that means an approach to analyze your corpus via date-based method is invalid. You will need to do alternative analysis on different metrics.
