### ISSUE TITLE
Error when running GUI for Excel Charts

### ISSUE THREAD

**Issue by kaavyamuthuganesan** [NLP-Suite/NLP-Suite#1137]
From the visualization main GUI I opened the special visualization options with the excel charts GUI option. I tried running the program but got a TypeError: read_csv() got an unexpected keyword argument 'on_bad_lines'
![excel gui](https://github.com/NLP-Suite/NLP-Suite/assets/142953438/72a9a86e-c8d7-4522-8fe9-97aec660b10a)
![excel error](https://github.com/NLP-Suite/NLP-Suite/assets/142953438/26a33a94-0875-429c-b61e-8c21c394063a)

**Comment by Emory-NLP** [comment]
Which version of pandas are you using? To find out...

Open command line/terminal
Type activate NLP
pip show pandas

**Comment by kaavyamuthuganesan** [comment]
version 2.0.3

**Comment by Emory-NLP** [comment]
That should not create problems. Same newer version I am using. I see though that you are using a GUI we have not used in a long time. I suspect there may be problems with the GUI.

**Comment by kaavyamuthuganesan** [comment]
I am trying to create visuals for the homework 3 using the csv files that were generated. i noticed another person had raised an issue where I am having a similar error in which when i run the n grams options when computing n grams it generates csv files but says the csv files are empty so it cannot create charts.

**Comment by Emory-NLP** [comment]
As I said, I would not use the charts_Excel_main GUI. Not tested in a long time :-(

**Comment by kaavyamuthuganesan** [comment]
ok, what should I do if none of the visualization options work for me and my partner?

**Comment by Emory-NLP** [comment]
Let's zoom

**Comment by bianshuyang** [comment]
I am referring this issue from the one you recently raised and found working
`https://github.com/NLP-Suite/NLP-Suite/issues/1138`
I am closing it as the error message appears duplicated and with the prior one resolved I am closing this as well. Please reopen both if anything doesn't work as expected.
