### ISSUE TITLE
error running ngrams viewer

### ISSUE THREAD

**Issue by kaavyamuthuganesan** [NLP-Suite/NLP-Suite#1138]
After opening N-grams and co-occurences viewer, I try to run the N-grams viewer, but I am getting an error.

![n grams gui](https://github.com/NLP-Suite/NLP-Suite/assets/142953438/55c39696-be6c-41e0-ac64-bd52eb7e92e6)
![n grams error line](https://github.com/NLP-Suite/NLP-Suite/assets/142953438/8b7b2cd7-3c3a-437f-be73-1cdcded9eeee)

**Comment by bianshuyang** [comment]
If you open a python environment in your terminal (simply type python in terminal), and enter these codes:
```
import pandas as pd
print(pd.__version__)
```

What do you get?
This issue is mentioned: https://stackoverflow.com/questions/72210768/read-csv-got-an-unexpected-keyword-argument-on-bad-lines
It looks like an incorrect (either too updated to too non-updated version) of pandas is installed incorrectly on your machine and rollback / update is needed.

Simon

**Comment by adrianvalencia1** [comment]
Hi, I was able to run this on my computer after downgrading my version of Pandas.

In the console, type:
`"C:\Users\<your windows username>\anaconda3\envs\NLP\Scripts\activate.bat"`
`pip install pandas==1.4.0`

Please let me know if this fixes the problem or causes other errors.

**Comment by bianshuyang** [comment]
That's great to hear. If you are able to run the program and has spotted no other issues you may close this issue. No more zoom is needed.

**Comment by kaavyamuthuganesan** [comment]
I downgraded pandas to vers 1.4.0 but I still am getting an error:

![view error](https://github.com/NLP-Suite/NLP-Suite/assets/142953438/85db8f4a-c8b1-469d-a73d-fc69531786ae)

**Comment by bianshuyang** [comment]
Hi! Did you make sure you install the lower version of pandas in the NLP environment and the regular conda? You must make sure that you use the lower version across environment. 
To see if you have a version, you can use `conda env list `to  see an enivronment. And also `conda activate _Xenvironment_` (Xenvironment to be replaced by the `absolute` path of the environment in list). Then `pip freeze` to see the packages, or use the above python import method to see the version of packages. Then close completely all widgets in NLP Suite, and restart cmopletely again.

**Comment by kaavyamuthuganesan** [comment]
yes it is installed in the NLP environment and the regular conda

**Comment by kaavyamuthuganesan** [comment]
it appears to be working for me now. thank you

**Comment by bianshuyang** [comment]
If it doesn't work again feel free to reopen it.
