### ISSUE TITLE
[BUG]: Updating Issues 

### ISSUE THREAD

**Issue by RemyFinkelstein** [NLP-Suite/NLP-Suite#1140]
**Add a screenshot of the GUI you are running with the widget selections**

![Screenshot 2023-09-10 133431](https://github.com/NLP-Suite/NLP-Suite/assets/143026730/a9baffdb-b317-4e46-b07f-fec2e269afdd)

**Describe the bug**
A clear and concise description of what the bug is. Please indicate what corpus you are using.

I'm on a Windows 11 Surface and each time I try to run NLP I am sent to an older version and it will not update even if I close it and restart. I get the same message saying I am running an older version. This measn when I try to run Style Analysis in the Linguistcis Analysis tools, I don't have the ability to chose WordCloud and cannot run the homework I need to. It says it's running version 3.9.2 instead of 3.9.5.

![Screenshot 2023-09-10 132545](https://github.com/NLP-Suite/NLP-Suite/assets/143026730/190d3880-dfa8-4e82-9bb7-a1920fb3d32f)

**To Reproduce**
1. Go to 'files'
2. Click on 'NLP suite' 'src' 
3. type powershell
4. type NLP_menu_main.py
6. See erroroneous GUI

**Comment by bianshuyang** [comment]
1. You can redownload the NLP Suite.
2. Follow the line by line method. Give admin privleges to the terminal low (run in administrator). Then execute the "git"... steps. I copy below. You must execute these steps right where the folder `"setup_Windows"` is. Steps:
`git init ..`
`git remote add -m current-stable -f origin https://github.com/NLP-Suite/NLP-Suite.git`
`git checkout -f current-stable`
`git add -A .`
`git stash`
`git pull -f origin current-stable`
3. The terminal screenshot is limited. Please attempt to output to a pdf and let me see the verbose output from the terminal. LIkely, not all dependencies are installed correctly. Alternatively, some dependencies need roll back. Alternatively, some dependencies need propagated to a new install.
4. It is highly recommend you book an appointment as early as possible. https://calendly.com/simonbian/nlpinstall?month=2023-09&date=2023-09-11

**Comment by RemyFinkelstein** [comment]
I've redownloaded and now I'm running the newest version but I'm now unable to set up default output file. No matter what I chose I am directed to this but its not true. I'm not sure what to do.
 [cid:c93737fa-49c4-499a-82cd-8be057cc329d]
________________________________
From: Shuyang Bian ***@***.***>
Sent: Sunday, September 10, 2023 2:24 PM
To: NLP-Suite/NLP-Suite ***@***.***>
Cc: Finkelstein, Remy ***@***.***>; Author ***@***.***>
Subject: [External] Re: [NLP-Suite/NLP-Suite] [BUG]: Updating Issues (Issue #1140)


  1.  You can redownload the NLP Suite.
  2.  Follow the line by line method. Give admin privleges to the terminal low (run in administrator). Then execute the "git"... steps. I copy below. You must execute these steps right where the folder "setup_Windows". Steps:
git init .. git remote add -m current-stable -f origin https://github.com/NLP-Suite/NLP-Suite.git git checkout -f current-stable git add -A . git stash git pull -f origin current-stable
  3.  The terminal screenshot is limited. Please attempt to output to a pdf and let me see the verbose output from the terminal. LIkely, not all dependencies are installed correctly. Alternatively, some dependencies need roll back. Alternatively, some dependencies need propagated to a new install.
  4.  It is highly recommend you book an appointment as early as possible. https://calendly.com/simonbian/nlpinstall?month=2023-09&date=2023-09-11

**Comment by bianshuyang** [comment]
You must show or attach a screenshot to let me understand the concrete issue. As always, terminal logs are strongly encouraged. Alternatively, you may consider uploading a video with a voice telling me what the issue is.  Always, clarity is strongly encouraged.

**Comment by RemyFinkelstein** [comment]
I ended up having to reboot my entire computer because my computer was crashing and everything was bugging so I'm in the process of redownloading NLP Suite and the line of code below does not function.

foreach ($k in type src/requirements.txt | select-string -Pattern "#" -notMatch) {
      pip install $k
}

[https://res.cdn.office.net/assets/mail/file-icon/png/photo_16x16.png]Screenshot 2023-09-12 154628.png<https://emory-my.sharepoint.com/:i:/g/personal/rfinke3_emory_edu/ERIh3DAIeTVClhEw3Ctk-GwBSoeoacoMHp_0QEG70bh_Pg>[https://res.cdn.office.net/assets/mail/file-icon/png/photo_16x16.png]Screenshot 2023-09-12 154749.png<https://emory-my.sharepoint.com/:i:/g/personal/rfinke3_emory_edu/EQlrhqcESUJNspOub73NyqoB6P82L8kaDEy_KTR4cLclFg>

I already scheduled an appointment for 4:30 today so I'm just sending something before as I am not having the same issues as when I schedueld the meeting.

Thank you,
Remy Finkelstein
________________________________
From: Shuyang Bian ***@***.***>
Sent: Sunday, September 10, 2023 5:37 PM
To: NLP-Suite/NLP-Suite ***@***.***>
Cc: Finkelstein, Remy ***@***.***>; Author ***@***.***>
Subject: [External] Re: [NLP-Suite/NLP-Suite] [BUG]: Updating Issues (Issue #1140)


You must show or attach a screenshot to let me understand the concrete issue. As always, terminal logs are strongly encouraged.

**Comment by bianshuyang** [comment]
Remy, You must change the src/requirements.txt to the actual directory, e.g. C:/remi/Desktop/requirements.txt, etc.. Alternatively, you must **open the terminal from the src** folder and then run: `pip install -r requirements.txt `.
Finally, I cannot see the screenshots. How did you upload the image? The best way is to save the image locally, copy and paste in the dialogue here, or simply just drag to the github page.

**Comment by RemyFinkelstein** [comment]
I tried both and it hasn't worked. The requirements.txt doc is in my src folder.
________________________________
From: Shuyang Bian ***@***.***>
Sent: Tuesday, September 12, 2023 2:54 PM
To: NLP-Suite/NLP-Suite ***@***.***>
Cc: Finkelstein, Remy ***@***.***>; Author ***@***.***>
Subject: [External] Re: [NLP-Suite/NLP-Suite] [BUG]: Updating Issues (Issue #1140)


Remy, You must change the src/requirements.txt to the actual directory, e.g. C:/remi/Desktop/requirements.txt, etc.. Alternatively, you must open the terminal from the src folder and then run: pip install -r requirements.txt .
Finally, I cannot see the screenshots. How did you upload the image? The best way is to save the image locally, copy and paste in the dialogue here, or simply just drag to the github page.

**Comment by RemyFinkelstein** [comment]
Hi,
Are we still meeting today? No pressure.
Remy Finkelstein.
________________________________

**Comment by bianshuyang** [comment]
[A screenshot of a computer  Description automatically generated]

From: RemyFinkelstein ***@***.***>
Date: Tuesday, September 12, 2023 at 16:39
To: NLP-Suite/NLP-Suite ***@***.***>
Cc: Bian, Simon ***@***.***>, Comment ***@***.***>
Subject: [External] Re: [NLP-Suite/NLP-Suite] [BUG]: Updating Issues (Issue #1140)
Hi,
Are we still meeting today? No pressure.
Remy Finkelstein.
________________________________

**Comment by bianshuyang** [comment]
Please resend a screenshot of the issue if it is still not resolved. You must have the **absolute** path. **EXAMPLE ONLY: YOU MUST CHANGE BASED ON WHERE IT ACTUALLY IS.** Let's say your file is C:/remi/Desktop/requirements.txt
`foreach ($k in type C:/remi/Desktop/requirements.txt | select-string -Pattern "#" -notMatch) {`
`      pip install $k`
`}`
Does that work? Also, for the method of `pip install -r requirements.txt ` you must make sure that you are installing correctly in the respective directory. If in doubt, you must send a screenshot **through github by copying and pasting** instead of replying to email. There is configuration issues with the reply.
