### ISSUE TITLE
[BUG]: Ngrams Viewer Bug with the Pandas package

### ISSUE THREAD

**Issue by lydianneking** [NLP-Suite/NLP-Suite#1142]
Screenshot of the GUI with the widget selections:

![search words ngrams viewer](https://github.com/NLP-Suite/NLP-Suite/assets/143012998/1407b2ac-a8d5-4a3b-9148-e3a2e14a94f0)

Description of the Bug
When running searching a word on the ngrams viewer, an error pops up that says "DataFrame object has no attribute append". 

To Reproduce
1. Go to Style Analysis GUI
2. Then go to the Ngrams Option
3. Then input a search term and click "run"

Screenshot of the error
![image](https://github.com/NLP-Suite/NLP-Suite/assets/143012998/d0a8c4c9-9e70-4050-b10f-b4223de31f30)

Desktop Type
 - macOS Big Sur, Version 11. 7.6
 - NLP Version 3.9.5

Additional Notes: 
I went in and downloaded an older version of pandas that still had append, but I wanted to know if there was a better option.

**Comment by bianshuyang** [comment]
In the environment you are working in, what is the result of these lines? 
Mine was:
<img width="171" alt="image" src="https://github.com/NLP-Suite/NLP-Suite/assets/52821055/d518f29a-54c3-4eae-a53e-b44137af10b5">
Out[3]: '1.5.2'


You must downgrade to the appropriate version as the code is running on some deprecated syntax.

**Comment by bianshuyang** [comment]
Since you are using conda, you **(must)** be in the appropriate environment of yours:
conda install pandas=1.5.2
