### ISSUE TITLE
Wordcloud Stop Words Issue 

### ISSUE THREAD

**Issue by Deesha12345** [NLP-Suite/NLP-Suite#1143]
<img width="790" alt="Screenshot 2023-09-11 at 3 03 36 PM" src="https://github.com/NLP-Suite/NLP-Suite/assets/143028806/82f8f7ec-ed86-4373-b98c-cab1728e8935">

<img width="790" alt="Screenshot 2023-09-11 at 3 03 36 PM" src="https://github.com/NLP-Suite/NLP-Suite/assets/143028806/6bac378e-f886-4d99-8956-fbac4cb8d901">
<img width="778" alt="Screenshot 2023-09-11 at 3 03 24 PM" src="https://github.com/NLP-Suite/NLP-Suite/assets/143028806/3e64614f-5d21-4233-80f5-23813762c0c0">

Even when I turned of Stop Words in NLP suit and ran it 2 more times, my wordclouds still only included them.

**Comment by Ncdfr** [comment]
I am experiencing the same issue currently.
9/11/2023 3:43
