### ISSUE TITLE
Wordclouds Algorithm Type Error

### ISSUE THREAD

**Issue by coralynnkc** [NLP-Suite/NLP-Suite#1144]
0. SCREENSHOTS.
![wordclouds - 1](https://github.com/NLP-Suite/NLP-Suite/assets/142829954/4fdc2819-86e7-4cc6-8298-a34a98bba314)
![wordclouds - 2](https://github.com/NLP-Suite/NLP-Suite/assets/142829954/ca822ff5-031d-4eef-9189-4c2113b411b2)
![wordclouds - 3](https://github.com/NLP-Suite/NLP-Suite/assets/142829954/7adf8f96-3450-4e55-b53a-495bf831dfe9)

1. DESCRIPTION.
Utilizing the corpus The Three Little Pigs.txt for example, the WordCloud creation algorithm fails due to a TypeError. 

2. STEPS.
- NLP Suite Main Menu GUI
- Visualization Tools -> Wordclouds (ALL options GUI) -> Run

3. INFORMATION.
Windows OS
NLP Suite Release 3.9.6

**Comment by bianshuyang** [comment]
I am copying a response to some of my students here, likely some dependencies are incorrectly or manually updated, resulting in conflict.

“The ImageDraw.textsize() method was deprecated in PIL version 9.2.0 and completely [removed](https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fpillow.readthedocs.io%2Fen%2Fstable%2Fdeprecations.html%23font-size-and-offset-methods&data=05%7C01%7Csimon.bian%40emory.edu%7Ce0936cf24163416e5f5308dbaf450701%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C638296483220514392%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Ri8WT7fn%2FTAgSp2NmZnWi1KnaukGLaAL6g%2F4rwFF7m8%3D&reserved=0) beginning with version 10.0.0 on 2023-07-01.” Quoted: [https://stackoverflow.com/questions/76189891/imagedraw-object-has-no-attribute-textbbox](https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fstackoverflow.com%2Fquestions%2F76189891%2Fimagedraw-object-has-no-attribute-textbbox&data=05%7C01%7Csimon.bian%40emory.edu%7Ce0936cf24163416e5f5308dbaf450701%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C638296483220514392%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=lejHuhgZQsXZKezzqI2oCvIqhJVewNU%2FPYMIADqbks0%3D&reserved=0)
 
The result:
In terminal, you must install an older version of Pillow: pip install Pillow==9.5.0 (if pip doesn’t work, try pip3)
You may have to toggle between conda and non-conda, conda-plain or conda-NLP environment somehow to install this package everywhere. If you are certain which environment you run the NLP Suite, please install the package only in the corresponding environment.
 
If you still have a problem with word cloud, you may try: [https://stackoverflow.com/questions/74178079/wordcloud-installation-on-windows-pil-pillow](https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fstackoverflow.com%2Fquestions%2F74178079%2Fwordcloud-installation-on-windows-pil-pillow&data=05%7C01%7Csimon.bian%40emory.edu%7Ce0936cf24163416e5f5308dbaf450701%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C638296483220514392%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=uDZHfgZwjLOe9lOnrHqB2Mgu1oM8Dl4qqOg47n4qelQ%3D&reserved=0)
 
Helpful tip to debug is to: copy usually the last 2 lines – 3 lines of the error message and type the package that was having an error (in this case, you can apparently see it’s wordcloud). Then, Google search for stackoverflow for an error. It is highly likely an error has been made by someone else, at which point you just follow the highest-rated results.

**Comment by bianshuyang** [comment]
In short:
`pip install freetype-py`
`pip uninstall pillow`
`pip install --no-cache-dir pillow`
`pip install Pillow==9.5.0`
If pip doesn't work you may try pip3. You must also make sure you perform these packages updates / downgrades in the corresponding anaconda environment.
