### ISSUE TITLE
SETUP External Software failed since version 3.9.3+

### ISSUE THREAD

**Issue by Cyebukayire** [NLP-Suite/NLP-Suite#1145]
**Describe the bug**

NLP Suite can't find the **Gephi** and **Google Earth Pro** apps. This failed when I upgraded from version 3.9.2 to version 3.9.3 on 9/1/2023.

<img width="468" alt="Screenshot 2023-09-11 at 3 10 35 PM" src="https://github.com/NLP-Suite/NLP-Suite/assets/55869293/c3076e56-9b99-4959-830a-99610611f3b2">

**My `/NLP-Suite/config/NLP_setup_external_software_config.csv` file has all paths for the setups**
```
Software,Installation_path,Download_link
          Stanford CoreNLP,/Users/peace/Emory_Classes/QTM_190/external_softwares/stanford-corenlp-4.5.4,https://stanfordnlp.github.io/CoreNLP/download.html
          Gephi,/Applications/Gephi.app,https://gephi.org/users/download/
          Google Earth Pro,/Applications/Google Earth Pro.app,https://www.google.com/earth/download/gep/agree.html?hl=en-GB
          Java (JDK),"Java version ""17.0.8"" installed",https://www.oracle.com/java/technologies/downloads/archive/
          MALLET,/Users/peace/Emory_Classes/QTM_190/external_softwares/mallet-2.0.8,http://mallet.cs.umass.edu/download.php
          WordNet,/Users/peace/Emory_Classes/QTM_190/external_softwares/WordNet-3.0,https://wordnet.princeton.edu/download/current-version
```

The problem is that the **Gephi** and **Google Earth Pro** apps still can't be found by the NLP Suite.

**Desktop (please complete the following information):**
 - OS: MAC OS

 - Release Version: MacbookAir M1 2020

**Comment by bianshuyang** [comment]
Hi, thanks for raising. Software,Installation_path,Download_link
          Stanford CoreNLP,/Users/peace/Emory_Classes/QTM_190/external_softwares/stanford-corenlp-4.5.4,https://stanfordnlp.github.io/CoreNLP/download.html
          **Gephi,/Applications/**,https://gephi.org/users/download/
          **Google Earth Pro,/Applications/**,https://www.google.com/earth/download/gep/agree.html?hl=en-GB
          Java (JDK),"Java version ""17.0.8"" installed",https://www.oracle.com/java/technologies/downloads/archive/
          MALLET,/Users/peace/Emory_Classes/QTM_190/external_softwares/mallet-2.0.8,http://mallet.cs.umass.edu/download.php
          WordNet,/Users/peace/Emory_Classes/QTM_190/external_softwares/WordNet-3.0,https://wordnet.princeton.edu/download/current-version


Please replace your csv file with above. It is somewhat incredible as it works on my computer. Possibly, if you have time, delte the config.csv and reset it up , and let me know how it performs. Thanks

**Comment by Cyebukayire** [comment]
@bianshuyang Thank you so much for helping me. I had to edit the paths to be:
```
Gephi,/Applications/
Google Earth Pro,/Applications/
```
Just like you showed me Instead of:
```
Gephi,/Applications/Gephi.app
Google Earth Pro,/Applications/Google Earth Pro.app
```

It's strange cause I used the same file for previous versions. Thank you so much again.
This helped a lot.

**Comment by bianshuyang** [comment]
Hi Peace, if possible could you save a copy of this somewhere else and delete the file, only setting up the config of the two apps you mentioned? After the testing is done you can simply restore the old config. This is for testing purpose and will help enhance the robustness of the software. If you find it hard it's ok to just simply close the issue.

**Comment by Cyebukayire** [comment]
Got it 👍
I deleted the file and created a new one with the content you shared with me. It's working so well.
Thank you very much, @bianshuyang.
