### ISSUE TITLE
Folder Input for Compute document stats bug

### ISSUE THREAD

**Issue by gasparsalcedo** [NLP-Suite/NLP-Suite#1146]
![Screen Shot 2023-09-11 at 3 41 11 PM](https://github.com/NLP-Suite/NLP-Suite/assets/34404834/40ac5bd4-16f5-40c3-b0b7-aad6ff197dc8)

**Describe the bug**
When I try to compute document statistics when the input is a file full of documents it doesn't work and terminal gives me this error code.

There must be at least one file that is incomparable due to split size error. But we skip it and proceed.
 

**Desktop (please complete the following information):**
 - OS:mac os Catalina
 - Release Version (type `NLP --version` 9.6)

**Comment by bianshuyang** [comment]
This error is expected (in fact coded by me). What options do you use to set up IO? We compare the files based off certain characteristics (naming, splitting etc.). If your set up of IO sorting is not valid (such as forcing a string to be a date, or have invalid number positions), these errors would be thrown out  - i.e. all files proceeded through a random order. However, there would be no functionality decrease in terms of output.
