### ISSUE TITLE
Changing "Number Stored as Text" 

### ISSUE THREAD

**Issue by jqian45** [NLP-Suite/NLP-Suite#1148]
**Is your feature request related to a problem? Please describe.**
The numbers for the sentence length export as "text" instead of "number" in Excel. It required an extra step to highlight the column and convert the numbers to a "number" format. The data exports as a number for the other variables, but for some reason, only the x-axis values become "text." 

**Describe the solution you'd like**
I would like for the numbers to be stored as "Numbers" instead of "text." 

**Describe alternatives you've considered**
I manufactured my own tables in Excel by resaving the data values as numbers. This did not take too long, but I did have to look up how to do so because you can't just highlight the entire column -- the option to convert disappears. This solutions requires changing the delimiter settings. 

Screenshot showing the problem. 
<img width="1439" alt="Screen Shot 2023-09-13 at 1 47 03 PM" src="https://github.com/NLP-Suite/NLP-Suite/assets/144945114/52bbf9f1-97d2-429c-8442-c74c8e4dbb32">

**Comment by Emory-NLP** [comment]
OK, first, please, show the GUI you used with the options you selected to generate the output csv file that has the problem you mention. A manufactured file gives no clues where to find a potential problem. The GUI would also provide an indication whether you are using a Mac or Windows machine.

**Comment by jqian45** [comment]
Apologies! It was using this G
<img width="1344" alt="Screen Shot 2023-10-02 at 1 38 50 PM" src="https://github.com/NLP-Suite/NLP-Suite/assets/144945114/bb913fee-a846-461a-9c9a-85fd72fc8ef5">
UI:
