### ISSUE TITLE
[BUG]: Unable to set Stanza's parsers + Terminal Error

### ISSUE THREAD

**Issue by evacap1** [NLP-Suite/NLP-Suite#1149]
<img width="1246" alt="Screen Shot 2023-09-13 at 2 03 29 PM" src="https://github.com/NLP-Suite/NLP-Suite/assets/109560962/efc6d6b3-388a-4e92-af9b-281ff17438c5">

On the "default NLP packages and the language of your corpus" GUI (accessed through the "setup NLP package and corpus language" dropdown in the NLP parsers and annotators GUI, the selection for Stanza doesn't seem to be recognized. Instead, "Available parsers for [NLP package name]" displays the parsers of the previously selected packages (Stanford CoreNLP or spaCy) and not the parsers for Stanza. 

1. Go to 'Parsers and Annotators' option in the "CORPUS/DOCUMENT Analysis Tools" dropdown menu in the NLP & Data Visualization GUI
2. Click on 'setup NLP package and corpus language' under the "Setup" dropdown on the bottom right of the Parsers & Annotators GUI
3. Select "Stanza" as the "NLP Package"
4. See how "Available parsers for [NLP package]" are the parsers for the previously-selected NLP Package (either for Stanford CoreNLP or for spaCy

<img width="804" alt="Screen Shot 2023-09-13 at 2 03 29 PM copy" src="https://github.com/NLP-Suite/NLP-Suite/assets/109560962/bce6b1c2-ede3-4272-9caa-38ab6ab88b65">
Neural Network and PCFG are parsers for Stanford CoreNLP, despite Stanza being the selected NLP package. 

MacOS, NLP version 3.9.7

**Comment by bianshuyang** [comment]
Is there any terminal output? Could you try closing and re-starting the program?

**Comment by evacap1** [comment]
This is the message I get on Terminal:


File "NLP_setup_package_language_main.py", line 191, in get_available_languages

    languages_available = Stanza_util.list_all_languages()

  File "/Users/evacapelsonschool/Downloads/NLP-Suite-current-stable/src/Stanza_util.py", line 42, in list_all_languages

    langs_full = sorted([dict(constants_util.languages)[x] for x in languages])

  File "/Users/evacapelsonschool/Downloads/NLP-Suite-current-stable/src/Stanza_util.py", line 42, in <listcomp>

    langs_full = sorted([dict(constants_util.languages)[x] for x in languages])

KeyError: 'myv'

___________

Eva Capelson

Quantitative Sciences major | History minor
***@***.*** | linkedin.com<https://www.linkedin.com/in/eva-capelson-6744b9221/> | 858-776-3632

________________________________
From: Shuyang Bian ***@***.***>
Sent: Wednesday, September 13, 2023 11:58 AM
To: NLP-Suite/NLP-Suite ***@***.***>
Cc: Capelson, Eva ***@***.***>; Author ***@***.***>
Subject: [External] Re: [NLP-Suite/NLP-Suite] [BUG]: Unable to set Stanza's parsers (Issue #1149)


Is there any terminal output? Could you try closing and re-starting the program?

**Comment by bianshuyang** [comment]
[NLP_default_package_language_config.csv](https://github.com/NLP-Suite/NLP-Suite/files/12601578/NLP_default_package_language_config.csv)
What is your config file? Please send back to debug or replace. Alternatively, delete the config file (of the name of above **only**) and redo the parser set up. I suspect something is wrong with your language (I've never seen "myv")... I also never saw it in the code repo.

**Comment by bianshuyang** [comment]
https://github.com/NLP-Suite/NLP-Suite/issues/1160 
I am merging all of the same bug together.

**Comment by bianshuyang** [comment]
This is marked "closed" but is still in working to organize the threads. Please visit the one I linked (#1160) to get further updates if I make some. If I don't make any comments it means it is still under fix.

**Comment by evacap1** [comment]
This is the error I get on Terminal in regards to setting Stanza as the parser: 
<img width="686" alt="Screen Shot 2023-09-18 at 1 27 46 PM" src="https://github.com/NLP-Suite/NLP-Suite/assets/109560962/3880e626-9486-4989-a6d0-59a345f82ce3">

**Comment by bianshuyang** [comment]
Hi the main thread is updated, You may be interested in taking a look. https://github.com/NLP-Suite/NLP-Suite/issues/1160

**Comment by evacap1** [comment]
Cool, thanks!
