### ISSUE TITLE
[BUG]: Unable to run neural network parser for stanford core nlp

### ISSUE THREAD

**Issue by kaavyamuthuganesan** [NLP-Suite/NLP-Suite#1150]
![parser gui](https://github.com/NLP-Suite/NLP-Suite/assets/142953438/6bc0a3e9-c5e8-4816-943c-b1c80fcb75cc)

**Describe the bug**
When I click run for the neural network parser option for the stanford core nlp, it does not run. no pop ups appear like for when i run the PCFG option. When I checked the command line, it was blank.

![parser terminal](https://github.com/NLP-Suite/NLP-Suite/assets/142953438/1a525ec1-bab9-44f4-84c6-5219d8f49131)

I have a windows 11 and am using ver 3.9.7 of NLP Suite

**Comment by bianshuyang** [comment]
Your options look odd. The "{'" are likely factors.
[NLP_default_package_language_config.csv](https://github.com/NLP-Suite/NLP-Suite/files/12601022/NLP_default_package_language_config.csv)
Could you try replacing the appropriate config file with mine?
Especially, resend your original config file back first as a backup.

**Comment by kaavyamuthuganesan** [comment]
thank you, that fixed the issue

**Comment by kaavyamuthuganesan** [comment]
for some reason I have to keep manually fixing the options in the csv file. whenever I close the NLP suite and then open it again, the options for neural network and pcfg have { } added to them.
