### ISSUE TITLE
[BUG]: Error in Tips dictionary

### ISSUE THREAD

**Issue by ZichenHuang000** [NLP-Suite/NLP-Suite#1152]
![image](https://github.com/NLP-Suite/NLP-Suite/assets/143022231/6d5df8b3-34d3-4f32-b8d4-c9b27120c18a)

DESCRIPTION
This error appears when I tried to open Tips file "DEPREL"

STEPS
1. Go to "parsers & annotators"
2. Click on "Tips File"
3. Scroll down to "DEPREL"

Windows 11
NLP Suite 3.9.4

**Comment by bianshuyang** [comment]
[TIPS_NLP_DEPREL (Dependency Relations) Stanford CoreNLP.pdf](https://github.com/NLP-Suite/NLP-Suite/files/12640923/TIPS_NLP_DEPREL.Dependency.Relations.Stanford.CoreNLP.pdf)
Thank you. If you want to read, it is here. It has been renamed and not all TIPS are updated.
