### ISSUE TITLE
Error when setting up lang and trying to run Stanza

### ISSUE THREAD

**Issue by kaavyamuthuganesan** [NLP-Suite/NLP-Suite#1155]
Whenever I try to setup a parser, for some reason { } get added to the options and I have to replace my file with the file provided by Simon in https://github.com/NLP-Suite/NLP-Suite/issues/1150#issuecomment-1718163585

Also, I get an error when trying to run Stanza.

![set up stanza error line](https://github.com/NLP-Suite/NLP-Suite/assets/142953438/87a28fb4-6980-4894-92b2-d90a919552a9)
![stanza parser](https://github.com/NLP-Suite/NLP-Suite/assets/142953438/39d9e168-e553-4029-a9f1-ce2982f4e68f)
![stanza error line](https://github.com/NLP-Suite/NLP-Suite/assets/142953438/55235797-77c3-4958-9d2e-c4a68f581ba0)

**Comment by bianshuyang** [comment]
Could you try force delete every file in the "src" (those .py") and replace it with appropriate py downloaded from github freshly?

**Comment by kaavyamuthuganesan** [comment]
I tried deleting all the .py files and replacing them with the ones from github, but I still have the { } and am getting the following error in terminal:
![stanza](https://github.com/NLP-Suite/NLP-Suite/assets/142953438/cd8ed6c9-2115-4166-9a59-6af0529d2b76)

**Comment by bianshuyang** [comment]
This is a common issue and I will merge to a main thread.

**Comment by bianshuyang** [comment]
Main thread: https://github.com/NLP-Suite/NLP-Suite/issues/1160

**Comment by bianshuyang** [comment]
This is marked "closed" but is still in working to organize the threads. Please visit the one I linked (#1160) to get further updates if I make some. If I don't make any comments it means it is still under fix.

**Comment by bianshuyang** [comment]
Hi the main thread is updated, You may be interested in taking a look. https://github.com/NLP-Suite/NLP-Suite/issues/1160
