### ISSUE TITLE
Incorrect axes in chart produced by running stanford core nlp neural networks parser in NLP by DEPREL frequency

### ISSUE THREAD

**Issue by kaavyamuthuganesan** [NLP-Suite/NLP-Suite#1156]
I ran stanford coreNLP neural networks parser. It produced charts. For the chart where data is grouped by deprel, the chart produced has frequency on the x axis and the value of mean/mode/skew/kurtosis on the y axis.

![nlp pars gui](https://github.com/NLP-Suite/NLP-Suite/assets/142953438/012394c2-b5a2-47a6-beda-0e9da1725d91)

![mean mode etc graph](https://github.com/NLP-Suite/NLP-Suite/assets/142953438/da84fa9e-44ba-428a-aa7c-2c3bc6d3c8b8)

**Comment by bianshuyang** [comment]
Can you also send the entire output file this graph was origniated from here? Thanks. (I may or may not have been coded this part, and I want to make sure it's not something deprecated)

**Comment by kaavyamuthuganesan** [comment]
[NLP_byDepRel_freq_CoreNLP_Dir_Corpus_nn_CoNLL_no_hyperlinks_DepRel_group_stats_bar_chart.xlsx](https://github.com/NLP-Suite/NLP-Suite/files/12641816/NLP_byDepRel_freq_CoreNLP_Dir_Corpus_nn_CoNLL_no_hyperlinks_DepRel_group_stats_bar_chart.xlsx)
