### ISSUE TITLE
[BUG]: repeated encoding data error for spacy

### ISSUE THREAD

**Issue by ZichenHuang000** [NLP-Suite/NLP-Suite#1157]
![image](https://github.com/NLP-Suite/NLP-Suite/assets/143022231/4402adf0-4179-476a-b2be-d37fa797a87c)
![image](https://github.com/NLP-Suite/NLP-Suite/assets/143022231/d2df438c-272e-41e8-8261-e8f44a65d557)
![image](https://github.com/NLP-Suite/NLP-Suite/assets/143022231/63cc2616-9ffa-49ab-89f1-cec41752182f)
![image](https://github.com/NLP-Suite/NLP-Suite/assets/143022231/7af2250d-5b8f-455c-b5db-9e41a2c89890)
![image](https://github.com/NLP-Suite/NLP-Suite/assets/143022231/fcb24e48-cbc8-4a6c-b0e4-f26b53914dd5)

DESCRIPTION
It seems like this is in a loop of encoding data error. This process was able to continue by clicking "confirm" on error message for Stanford CoreNLP, but it keeps repeating for spacy (after clicking "confirm", the command line runs a few lines and throw the same error again)

STEPS
1. Go to main page
2. select "parsers and annotators"
3. click "setup"
4. select parser to be spacy
5. basic function "spacy" is not available, so choose basic function "stanza"
6. RUN
7. see error, click confirm
8. see error and back to 7

Windows 11
NLP Suite 3.9.4

**Comment by bianshuyang** [comment]
The first error is easy for a rationale: the NLP package is set to be spacy, even if the "basic" one is not spacy.
Also make sure to save the file.


For utf 8: I copy a prior response by email to another student so more can see it. Maybe it's prudent to do a small sample. A 100 bunch is too much.

<img width="612" alt="image" src="https://github.com/NLP-Suite/NLP-Suite/assets/52821055/87868cf6-6cd1-408d-9892-db358c2f94d3">

<br>
It also means...

you must read through the list of NLP menu main to find and see which files are not utf-8 encoded and possibly delete, change, or re-encode it using NLP Suite. Read TIPS, helps, and readme files, etc.
 you should find your own method to get rid of the error, possibly not by running all files together, but by analyzing a bunch of small section of the files and remove the erroneous files.

**Comment by bianshuyang** [comment]
Further, would you be able to send back the errorneous csv file? Thanks.

**Comment by ZichenHuang000** [comment]
I was able to use spacy with one txt file as an input. 

All the files pass the utf-8 compliance test (command lines showing that they are all utf-8 compliant), but the data encoding error loop continues when I replace one txt file with a whole directory.

[Gay men personal stories - 100 samples.zip](https://github.com/NLP-Suite/NLP-Suite/files/12641588/Gay.men.personal.stories.-.100.samples.zip)
 
I attach the directory of files I am using. (I am not sure if they are the erroneous file)
