### ISSUE TITLE
[BUG]: Stanza Parsers and Annotators Error - Unsupported Language 'hbo'

### ISSUE THREAD

**Issue by SahithiGangaram434** [NLP-Suite/NLP-Suite#1158]
<img width="898" alt="image" src="https://github.com/NLP-Suite/NLP-Suite/assets/78706301/2872001c-1b47-4833-8651-2b500a15b59b">

**Describe the bug**
The bug occurs when attempting to run the parsers and annotators for Stanza within the NLP-Suite tool. The specific error message received is as follows:

<img width="971" alt="image" src="https://github.com/NLP-Suite/NLP-Suite/assets/78706301/3e691574-53c9-4ef7-8e71-93a63954b601">

<img width="1117" alt="image" src="https://github.com/NLP-Suite/NLP-Suite/assets/78706301/f075f356-0034-421b-9037-08baf35b1136">

**To Reproduce**
1. Navigate to the directory containing the NLP-Suite tool.
2. Execute the command python NLP_main_menu.py.
3. Using the parser and annotators GUI, run the Stanza
parsers on your corpus.
4. Observe the error message as described above.

**Desktop (please complete the following information):**
 - DESKTOP information
Microsoft Windows 11 Home
- NLP Suite Release 3.9.7/3.9.7

**Additional context**
The bug appears to be related to the use of the Stanza tool for parsing and annotating text. When attempting to run the parsers for Stanza, the tool encounters an issue while checking for available languages. Specifically, it tries to access a language code 'hbo,' which is not recognized or supported by Stanza, leading to a 'KeyError' in the process.

The expected behavior is that the Stanza tool should be able to run without encountering errors related to unsupported languages or missing files.

**Comment by bianshuyang** [comment]
What did you see if you go to this menu? 
![image](https://github.com/NLP-Suite/NLP-Suite/assets/52821055/71165d56-a87e-4314-9967-393744a9344a)
By clicking on something called:
![image](https://github.com/NLP-Suite/NLP-Suite/assets/52821055/258a4c86-9be5-4187-b330-63eae29e8d7a)

**Comment by SahithiGangaram434** [comment]
It still gives that error. 
<img width="1110" alt="image" src="https://github.com/NLP-Suite/NLP-Suite/assets/78706301/78bfb4b5-ee37-4635-9c79-8b15e59b1d70">

**Comment by bianshuyang** [comment]
I think a lot has this error, let me see what I can do to merge these issues together.

**Comment by bianshuyang** [comment]
https://github.com/NLP-Suite/NLP-Suite/issues/1160

**Comment by bianshuyang** [comment]
This is marked "closed" but is still in working to organize the threads. Please visit the one I linked (#1160) to get further updates if I make some. If I don't make any comments it means it is still under fix.

**Comment by SahithiGangaram434** [comment]
Now I am also getting KeyError: 'myv' as others are when trying to run Stanza. This is what happens when I run, after changing NLP package (parsers & annotators) to Stanza. With the NLP Package for basic functions still being Stanza.
<img width="1120" alt="image" src="https://github.com/NLP-Suite/NLP-Suite/assets/78706301/4309ecfe-5a80-4b34-b0c2-3117ee4707f8">

**Comment by bianshuyang** [comment]
Hi the main thread is updated, You may be interested in taking a look. https://github.com/NLP-Suite/NLP-Suite/issues/1160
