### ISSUE TITLE
[BUG]: Using a Parser with the Novel Corpus 

### ISSUE THREAD

**Issue by angelinacchen** [NLP-Suite/NLP-Suite#1163]
<img width="1348" alt="Screen Shot 2023-09-18 at 1 16 32 PM" src="https://github.com/NLP-Suite/NLP-Suite/assets/107923984/3c029066-2ea4-413f-8dcb-ec2f7e3c831a">
<img width="567" alt="Screen Shot 2023-09-18 at 1 17 08 PM" src="https://github.com/NLP-Suite/NLP-Suite/assets/107923984/28a3de3a-9b25-4793-b53d-a63365b4e5b6">

When I am trying to run spaCy or Stanford Core NLP, using my Novel Corpus for Group 5, the processor runs for many hours stuck on the first document. Even running over night produces no results, it is still stuck on 1/5.

**To Reproduce**
1. Go to GUI for NLP Parsers and Annotators
2. Click on spaCy in Setup
3. Press Run

 - OS: OS 10.15.7
 - Release Version 3.9.8

The only way to stop running is to force close the terminal.

**Comment by bianshuyang** [comment]
Can you send a copy of this txt file? If it is **very large**, you have to split it.

**Comment by angelinacchen** [comment]
I will email the corpus to you.
