### ISSUE TITLE
[BUG]: NGrams Viewer Walks through directory?

### ISSUE THREAD

**Issue by RafaelPiloto10** [NLP-Suite/NLP-Suite#117]
**Describe the bug**
The NGrams Viewer walks through the specified input directory including nested files and creates an error if files are not in the correct "date" format.

**To Reproduce**
1. Set your input directory to include `txt` files and a subfolder with `txt` files in a different format
2. Run the NGrams Viewer

**Expected behavior**
The NGrams viewer should only use the files specified in the input directory. It should not visit nested folders with other txt files.
The culprit appears to be:
https://github.com/NLP-Suite/NLP-Suite/blob/cc136fbf6ea10ef7817114dfac2843996d9724a1/src/NGrams_CoOccurrences_Viewer_main.py#L86

it should be:
```python3
for filename in os.listdir(inputDir):
```

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by Emory-NLP** [comment]
Algortihms rewritten in Python
