### ISSUE TITLE
Specialized visuals

### ISSUE THREAD

**Issue by Emory-NLP** [NLP-Suite/NLP-Suite#1174]
We should introduce visuals of this kind
 
![image](https://github.com/NLP-Suite/NLP-Suite/assets/79026295/6b743279-539b-4fe6-90af-4f4a069f0cd6)
or GIS maps based on Python packages

![image](https://github.com/NLP-Suite/NLP-Suite/assets/79026295/89f3bb8e-5443-4f50-9b24-116523754d8e)

**Comment by bianshuyang** [comment]
Initial attempt is complete for the front figure. The latter figure is still in developmental stage. This is a very tiny command-line based tool to generate an output. Full integration with GUI is needed.
[code.zip](https://github.com/NLP-Suite/NLP-Suite/files/12734155/code.zip)
Post unzip, make sure to have a CoNLL table available and invoke the python using `python3 colormetric.py`. For speed testing and batch testing, try `python3 colormetric.py <command.in >out.out` for suppressing verbose output. The figure would be successfully stored. Note that command.in must be altered to have the correct output depending on where you store the CoNLL table on the machine.
