### ISSUE TITLE
Attempting to run visualize categorical data for the sun burst option results in a blank gephi html being produced

### ISSUE THREAD

**Issue by kaavyamuthuganesan** [NLP-Suite/NLP-Suite#1180]
![sunburst](https://github.com/NLP-Suite/NLP-Suite/assets/142953438/c485cc72-da06-45c6-8d92-0d1001acef6b)
after running, it opens a blank html file
![output](https://github.com/NLP-Suite/NLP-Suite/assets/142953438/ed91b3e4-351e-46ce-8f69-6df3259c1d0a)
![terminal when running sunburst](https://github.com/NLP-Suite/NLP-Suite/assets/142953438/2f15a975-9c11-4ab5-bd92-73452f4518e4)

**Comment by kaavyamuthuganesan** [comment]
I get the same error when using treemap as well
![treemap](https://github.com/NLP-Suite/NLP-Suite/assets/142953438/c3214bbf-b91c-4850-878c-2f00c0f8c183)

**Comment by bianshuyang** [comment]
If you open the html's console using Ctrl+Shfit+I (Windows) or Command Option I (Mac), what you see from "Console" Tab? The treemap and sunburst has a very strict input file requirement as far as I am concerned....

**Comment by kaavyamuthuganesan** [comment]
The following is what I see:
![html console](https://github.com/NLP-Suite/NLP-Suite/assets/142953438/9b88edb8-53ca-4484-8911-905fef91c272)

**Comment by Emory-NLP** [comment]
You are entering the wrong labels in the Filename label/part widget. These are case sensitive and must be contained in the files under the Document field. The new release traps these errors.
