### ISSUE TITLE
Error running GIS Maps

### ISSUE THREAD

**Issue by ghost** [NLP-Suite/NLP-Suite#1194]
**Add a screenshot of the GUI you are running with the widget selections**
<img width="565" alt="Screenshot 2023-09-30 at 5 26 00 PM" src="https://github.com/NLP-Suite/NLP-Suite/assets/143128568/ff5117fb-92a3-4f81-a3a8-da1def5a0e68">

**Describe the bug**
When I input my CoNll table in the GIS GUI, I get the error after geocoding locations.

**To Reproduce**
1. Go to 'GIS GUI'
2. Click on '.Input CSV file' and input CoNll table
3. Run program
4. See error on Terminal

**Screenshots**

**Desktop (please complete the following information):**
 - Mac
 - Newest version of NLP

**Comment by Emory-NLP** [comment]
PLEASE, follow the instructions and attach a screenshot of the GUI you are running with all the options you have selected.

**Comment by ghost** [comment]
My apologies. 

Screenshot of GIS GUI:
<img width="1343" alt="Screenshot 2023-09-30 at 5 52 26 PM" src="https://github.com/NLP-Suite/NLP-Suite/assets/143128568/82e6f4f8-bafa-4632-9df9-0c85af63a850">

**Comment by Emory-NLP** [comment]
Can you please also copy the entire Terminal results? And could you send me by email the CoNLL table you are sing?
You should change the background of your Mac. Horrible! There was an Issue that advised on what to do, now Closed.
