### ISSUE TITLE
[BUG]: Error opening Google Maps GIS html

### ISSUE THREAD

**Issue by evacap1** [NLP-Suite/NLP-Suite#1195]
<img width="1334" alt="Screen Shot 2023-09-30 at 11 28 42 PM" src="https://github.com/NLP-Suite/NLP-Suite/assets/109560962/fc3a48c8-cc84-4d2e-b830-0f787c84e832">

When I run the GIS Text to Map GUI on my corpus (using the sample Professor Dumbass.txt corpus), the Google Earth Pro map works, but the Google Maps gives me an error when I try to open the html file for it.

1. Select "Geographic maps: From texts to maps via Google Earth Pro and Google Maps" under "Visualization Tools"
2. Click on 'RUN' on the bottom right corner of the GIS Pipeline from Text to Map GUI
3. Open "NLP_GIS_CoreNLP_NER_LOCATIONS_Professor Dumbass_Nominatim_Location.html" file found in NLP output folder

<img width="1191" alt="Screen Shot 2023-09-30 at 11 20 06 PM" src="https://github.com/NLP-Suite/NLP-Suite/assets/109560962/8c694d81-e956-4458-a906-6c0ff74da6a4">

 - Mac OS
 - Release Version 4.1.0

**Comment by evacap1** [comment]
Update: even after updating to 4.1.2, I still receive this same error

**Comment by Emory-NLP** [comment]
That is not an error. You simply need a Google Maps key as as a config file under the config subdir (as clearly specified in the required TIPS readings...)

![image](https://github.com/NLP-Suite/NLP-Suite/assets/79026295/795ff1c0-5c1f-4d6d-aa62-16414718852c)

**Comment by evacap1** [comment]
Interesting, I did upload my API key, so I’m not sure what the error stems from?
________________________________
From: Roberto ***@***.***>
Sent: Sunday, October 1, 2023 5:06:26 PM
To: NLP-Suite/NLP-Suite ***@***.***>
Cc: Capelson, Eva ***@***.***>; Author ***@***.***>
Subject: [External] Re: [NLP-Suite/NLP-Suite] [BUG]: Error opening Google Maps GIS html (Issue #1195)


That is not an error. You simply need a Google Maps key as as a config file under the config subdir (as clearly specified in the required TIPS readings...)

[image]<https://user-images.githubusercontent.com/79026295/271853521-795ff1c0-5c1f-4d6d-aa62-16414718852c.png>

**Comment by Emory-NLP** [comment]
Can you share a screenshot of the config file, like I showed you? And if you have the config file, can you open it and see whether you do have a value there? Do NOT share that key... just make sure you have it.

**Comment by Emory-NLP** [comment]
In any case, the NLP Suite would have given you a reminder that the config file is missing or has an empty key.

**Comment by evacap1** [comment]
I opened the config file you mentioned -- it contains my API key there. It's odd -- I did get the error on NLP Suite before I inputted my API key. I don't get that error anymore, which I guess makes sense since the API config file contains my API key.
___________

Eva Capelson

Quantitative Sciences major | History minor
***@***.*** | linkedin.com<https://www.linkedin.com/in/eva-capelson-6744b9221/> | 858-776-3632

________________________________
From: Roberto ***@***.***>
Sent: Sunday, October 1, 2023 2:45 PM
To: NLP-Suite/NLP-Suite ***@***.***>
Cc: Capelson, Eva ***@***.***>; Author ***@***.***>
Subject: [External] Re: [NLP-Suite/NLP-Suite] [BUG]: Error opening Google Maps GIS html (Issue #1195)


In any case, the NLP Suite would have given you a reminder that the config file is missing or has an empty key.

**Comment by Emory-NLP** [comment]
Well, mystery solved.

**Comment by evacap1** [comment]
I meant to say that despite my API key being in my Google Maps API config file, my Google Maps still give me that error.
___________

Eva Capelson

Quantitative Sciences major | History minor
***@***.*** | linkedin.com<https://www.linkedin.com/in/eva-capelson-6744b9221/> | 858-776-3632

________________________________
From: Roberto ***@***.***>
Sent: Sunday, October 1, 2023 3:48 PM
To: NLP-Suite/NLP-Suite ***@***.***>
Cc: Capelson, Eva ***@***.***>; Author ***@***.***>
Subject: [External] Re: [NLP-Suite/NLP-Suite] [BUG]: Error opening Google Maps GIS html (Issue #1195)


Closed #1195<https://github.com/NLP-Suite/NLP-Suite/issues/1195> as completed.

**Comment by Emory-NLP** [comment]
As the messsge says then… did you enter the credit card information?

Cheers, Roberto
________________________________
From: evacap1 ***@***.***>
Sent: Sunday, October 1, 2023 6:57:07 PM
To: NLP-Suite/NLP-Suite ***@***.***>
Cc: Franzosi, Roberto ***@***.***>; State change ***@***.***>
Subject: [External] Re: [NLP-Suite/NLP-Suite] [BUG]: Error opening Google Maps GIS html (Issue #1195)


I meant to say that despite my API key being in my Google Maps API config file, my Google Maps still give me that error.
___________

Eva Capelson

Quantitative Sciences major | History minor
***@***.*** | linkedin.com<https://www.linkedin.com/in/eva-capelson-6744b9221/> | 858-776-3632

________________________________
From: Roberto ***@***.***>
Sent: Sunday, October 1, 2023 3:48 PM
To: NLP-Suite/NLP-Suite ***@***.***>
Cc: Capelson, Eva ***@***.***>; Author ***@***.***>
Subject: [External] Re: [NLP-Suite/NLP-Suite] [BUG]: Error opening Google Maps GIS html (Issue #1195)


Closed #1195<https://github.com/NLP-Suite/NLP-Suite/issues/1195> as completed.

**Comment by evacap1** [comment]
Yes, I had to do that via Google to access my API key
-Eva
___________

Eva Capelson

Quantitative Sciences major | History minor
***@***.*** | linkedin.com<https://www.linkedin.com/in/eva-capelson-6744b9221/> | 858-776-3632

________________________________
From: Roberto ***@***.***>
Sent: Sunday, October 1, 2023 4:08 PM
To: NLP-Suite/NLP-Suite ***@***.***>
Cc: Capelson, Eva ***@***.***>; Author ***@***.***>
Subject: [External] Re: [NLP-Suite/NLP-Suite] [BUG]: Error opening Google Maps GIS html (Issue #1195)


As the messsge says then… did you enter the credit card information?

Cheers, Roberto
________________________________
From: evacap1 ***@***.***>
Sent: Sunday, October 1, 2023 6:57:07 PM
To: NLP-Suite/NLP-Suite ***@***.***>
Cc: Franzosi, Roberto ***@***.***>; State change ***@***.***>
Subject: [External] Re: [NLP-Suite/NLP-Suite] [BUG]: Error opening Google Maps GIS html (Issue #1195)


I meant to say that despite my API key being in my Google Maps API config file, my Google Maps still give me that error.
___________

Eva Capelson

Quantitative Sciences major | History minor
***@***.*** | linkedin.com<https://www.linkedin.com/in/eva-capelson-6744b9221/> | 858-776-3632

________________________________
From: Roberto ***@***.***>
Sent: Sunday, October 1, 2023 3:48 PM
To: NLP-Suite/NLP-Suite ***@***.***>
Cc: Capelson, Eva ***@***.***>; Author ***@***.***>
Subject: [External] Re: [NLP-Suite/NLP-Suite] [BUG]: Error opening Google Maps GIS html (Issue #1195)


Closed #1195<https://github.com/NLP-Suite/NLP-Suite/issues/1195> as completed.

**Comment by Emory-NLP** [comment]
Google requires different API keys for different things. Are you sure you selected the Google maps API? Did you follow closely the tips on getting API keys?

Cheers, Roberto
________________________________
From: evacap1 ***@***.***>
Sent: Sunday, October 1, 2023 7:10:46 PM
To: NLP-Suite/NLP-Suite ***@***.***>
Cc: Franzosi, Roberto ***@***.***>; State change ***@***.***>
Subject: [External] Re: [NLP-Suite/NLP-Suite] [BUG]: Error opening Google Maps GIS html (Issue #1195)


Yes, I had to do that via Google to access my API key
-Eva
___________

Eva Capelson

Quantitative Sciences major | History minor
***@***.*** | linkedin.com<https://www.linkedin.com/in/eva-capelson-6744b9221/> | 858-776-3632

________________________________
From: Roberto ***@***.***>
Sent: Sunday, October 1, 2023 4:08 PM
To: NLP-Suite/NLP-Suite ***@***.***>
Cc: Capelson, Eva ***@***.***>; Author ***@***.***>
Subject: [External] Re: [NLP-Suite/NLP-Suite] [BUG]: Error opening Google Maps GIS html (Issue #1195)


As the messsge says then… did you enter the credit card information?

Cheers, Roberto
________________________________
From: evacap1 ***@***.***>
Sent: Sunday, October 1, 2023 6:57:07 PM
To: NLP-Suite/NLP-Suite ***@***.***>
Cc: Franzosi, Roberto ***@***.***>; State change ***@***.***>
Subject: [External] Re: [NLP-Suite/NLP-Suite] [BUG]: Error opening Google Maps GIS html (Issue #1195)


I meant to say that despite my API key being in my Google Maps API config file, my Google Maps still give me that error.
___________

Eva Capelson

Quantitative Sciences major | History minor
***@***.*** | linkedin.com<https://www.linkedin.com/in/eva-capelson-6744b9221/> | 858-776-3632

________________________________
From: Roberto ***@***.***>
Sent: Sunday, October 1, 2023 3:48 PM
To: NLP-Suite/NLP-Suite ***@***.***>
Cc: Capelson, Eva ***@***.***>; Author ***@***.***>
Subject: [External] Re: [NLP-Suite/NLP-Suite] [BUG]: Error opening Google Maps GIS html (Issue #1195)


Closed #1195<https://github.com/NLP-Suite/NLP-Suite/issues/1195> as completed.

**Comment by evacap1** [comment]
It works now -- thanks for your help!
___________

Eva Capelson

Quantitative Sciences major | History minor
***@***.*** | linkedin.com<https://www.linkedin.com/in/eva-capelson-6744b9221/> | 858-776-3632

________________________________
From: Roberto ***@***.***>
Sent: Sunday, October 1, 2023 4:12 PM
To: NLP-Suite/NLP-Suite ***@***.***>
Cc: Capelson, Eva ***@***.***>; Author ***@***.***>
Subject: [External] Re: [NLP-Suite/NLP-Suite] [BUG]: Error opening Google Maps GIS html (Issue #1195)


Google requires different API keys for different things. Are you sure you selected the Google maps API? Did you follow closely the tips on getting API keys?

Cheers, Roberto
________________________________
From: evacap1 ***@***.***>
Sent: Sunday, October 1, 2023 7:10:46 PM
To: NLP-Suite/NLP-Suite ***@***.***>
Cc: Franzosi, Roberto ***@***.***>; State change ***@***.***>
Subject: [External] Re: [NLP-Suite/NLP-Suite] [BUG]: Error opening Google Maps GIS html (Issue #1195)


Yes, I had to do that via Google to access my API key
-Eva
___________

Eva Capelson

Quantitative Sciences major | History minor
***@***.*** | linkedin.com<https://www.linkedin.com/in/eva-capelson-6744b9221/> | 858-776-3632

________________________________
From: Roberto ***@***.***>
Sent: Sunday, October 1, 2023 4:08 PM
To: NLP-Suite/NLP-Suite ***@***.***>
Cc: Capelson, Eva ***@***.***>; Author ***@***.***>
Subject: [External] Re: [NLP-Suite/NLP-Suite] [BUG]: Error opening Google Maps GIS html (Issue #1195)


As the messsge says then… did you enter the credit card information?

Cheers, Roberto
________________________________
From: evacap1 ***@***.***>
Sent: Sunday, October 1, 2023 6:57:07 PM
To: NLP-Suite/NLP-Suite ***@***.***>
Cc: Franzosi, Roberto ***@***.***>; State change ***@***.***>
Subject: [External] Re: [NLP-Suite/NLP-Suite] [BUG]: Error opening Google Maps GIS html (Issue #1195)


I meant to say that despite my API key being in my Google Maps API config file, my Google Maps still give me that error.
___________

Eva Capelson

Quantitative Sciences major | History minor
***@***.*** | linkedin.com<https://www.linkedin.com/in/eva-capelson-6744b9221/> | 858-776-3632

________________________________
From: Roberto ***@***.***>
Sent: Sunday, October 1, 2023 3:48 PM
To: NLP-Suite/NLP-Suite ***@***.***>
Cc: Capelson, Eva ***@***.***>; Author ***@***.***>
Subject: [External] Re: [NLP-Suite/NLP-Suite] [BUG]: Error opening Google Maps GIS html (Issue #1195)


Closed #1195<https://github.com/NLP-Suite/NLP-Suite/issues/1195> as completed.
