### ISSUE TITLE
[BUG]: Missing UI for Visualization Tools on Mac

### ISSUE THREAD

**Issue by aamaya5** [NLP-Suite/NLP-Suite#1201]
**Add a screenshot of the GUI you are running with the widget selections**
<img width="1351" alt="Screenshot 2023-10-02 at 5 28 06 PM" src="https://github.com/NLP-Suite/NLP-Suite/assets/144411465/7c5d6997-c138-4781-a4cf-04d94deaa26e">

**Describe the bug**
Missing the input box top the right of the csv file field that takes nodes for network graphs

**To Reproduce**
On Macbook, go into visualization tools GUI.

**Desktop (please complete the following information):**
 -OS: MacBook Air M2 Chip

**Comment by Emory-NLP** [comment]
Please, DO click on the ?HELP button of this line.
![image](https://github.com/NLP-Suite/NLP-Suite/assets/79026295/06a86f1d-a450-4d50-9cdc-80f9664e7ec0)
