### ISSUE TITLE
[BUG]: Genism tool cannot find the English language spacy library, but installation of spacy does not work.

### ISSUE THREAD

**Issue by yxyang05** [NLP-Suite/NLP-Suite#1202]
When I try to run the Analysis Tool "What's in your corpus/document(s)? A Sweeping View", I get a popup that says I must run a command to get the spacy package. I have tried running the code stated in the popup and pip install stacy, but the error messages continues to pop up.
<img width="1359" alt="Screenshot 2023-10-02 at 6 52 15 PM" src="https://github.com/NLP-Suite/NLP-Suite/assets/121314139/91db7545-11fd-40fa-9600-a6408f557219">

**Comment by bianshuyang** [comment]
Did you make sure you install and run in the NLP environment?
