### ISSUE TITLE
[BUG]: GUI fails to open

### ISSUE THREAD

**Issue by khuang18** [NLP-Suite/NLP-Suite#1206]
**Add a screenshot of the GUI you are running with the widget selections**
<img width="1346" alt="Screenshot 2023-10-03 at 2 38 38 PM" src="https://github.com/NLP-Suite/NLP-Suite/assets/90067390/24904e8f-0deb-4f62-8aa6-3525ba329127">

**Describe the bug**
Multiple or all GUIs dont open when selected: tested for document statistics, GIS, SVO. Believe it is a problem beginning outside of the individual GUIs themselves. 

**To Reproduce**
1. Open NLP Suite, Enter 
2. Attempt to open a GUI from CORPUS/DOCUMENT Analysis tools 
4. See error in terminal.
<img width="585" alt="Screenshot 2023-10-03 at 2 40 30 PM" src="https://github.com/NLP-Suite/NLP-Suite/assets/90067390/9baff733-a45f-4aa4-9303-d897ee6767f3">
<img width="577" alt="Screenshot 2023-10-03 at 2 40 46 PM" src="https://github.com/NLP-Suite/NLP-Suite/assets/90067390/73563a97-c866-46e2-ad03-2f0afc3a8afe">

**Expected behavior**
Expect GUI selections to open

**Desktop (please complete the following information):**
 - OS: [OS X/Windows]

**Additional context**

**Comment by bianshuyang** [comment]
Is it M1 or Intel chip? It looks like numpy is not right. 
on my computer as well:

`import numpy`
`numpy.__version__`
`Out[6]: '1.24.1'`

**Comment by khuang18** [comment]
Hi Simon,

I'm on Intel chip

Best,
Kevin Huang
Emory University
www.linkedin.com/in/kevin-huang-9696c<http://www.linkedin.com/in/kevin-huang-9696c>
Goizueta Business School | BBA Class of 2024
***@***.*** | 808.675.8695
________________________________
From: Shuyang Bian ***@***.***>
Sent: Tuesday, October 3, 2023 3:16 PM
To: NLP-Suite/NLP-Suite ***@***.***>
Cc: Huang, Kevin ***@***.***>; Author ***@***.***>
Subject: [External] Re: [NLP-Suite/NLP-Suite] [BUG]: GUI fails to open (Issue #1206)


Is it M1 or Intel chip? It looks like numpy is not right.
on my computer as well:

import numpy
numpy.__version__
Out[6]: '1.24.1'

**Comment by bianshuyang** [comment]
`protobuf==3.19.6` is what is on my end. What about yours? I don't have an Intel mac though...  Make sure both packages are the same versions...

**Comment by khuang18** [comment]
Hi Simon,

Mine was 9.23. I just downgraded it to 3.19.6 but still getting the same numpy error even after restarting NLP Suite.


pip show numpy

Name: numpy

Version: 1.24.1


pip show protobuf

Name: protobuf

Version: 3.19.6

These are the versions I am now at.

Best,
Kevin Huang
Emory University
www.linkedin.com/in/kevin-huang-9696c<http://www.linkedin.com/in/kevin-huang-9696c>
Goizueta Business School | BBA Class of 2024
***@***.*** | 808.675.8695
________________________________
From: Shuyang Bian ***@***.***>
Sent: Tuesday, October 3, 2023 3:29 PM
To: NLP-Suite/NLP-Suite ***@***.***>
Cc: Huang, Kevin ***@***.***>; Author ***@***.***>
Subject: [External] Re: [NLP-Suite/NLP-Suite] [BUG]: GUI fails to open (Issue #1206)


protobuf==3.19.6 is what is on my end. What about yours? I don't have an Intel mac though... Make sure both packages are the same versions...

**Comment by khuang18** [comment]
3.23 not 9.23 sorry

Best,
Kevin Huang
Emory University
www.linkedin.com/in/kevin-huang-9696c<http://www.linkedin.com/in/kevin-huang-9696c>
Goizueta Business School | BBA Class of 2024
***@***.*** | 808.675.8695
________________________________
From: Shuyang Bian ***@***.***>
Sent: Tuesday, October 3, 2023 3:29 PM
To: NLP-Suite/NLP-Suite ***@***.***>
Cc: Huang, Kevin ***@***.***>; Author ***@***.***>
Subject: [External] Re: [NLP-Suite/NLP-Suite] [BUG]: GUI fails to open (Issue #1206)


protobuf==3.19.6 is what is on my end. What about yours? I don't have an Intel mac though... Make sure both packages are the same versions...

**Comment by bianshuyang** [comment]
Hi Kevin,
Do you make sure it is in the correct conda? If so we can zoom a bit, hopefully at a time around 9.

**Comment by bianshuyang** [comment]
I am going to run the SVO for you in fact. You might want to use some placeholder to place the result. I am using batch processing to speed it up, but it might not be until 3 hours that some files can be produced...

**Comment by khuang18** [comment]
Yeah, I think I may have messed up that part. I can meet at 9 also, hopefully it wont be a huge issue. If it takes too much time to fix that's alright as I have enough to write on until tomorrow's class. Dont worry too much about SVO.

Best,
Kevin Huang
Emory University
www.linkedin.com/in/kevin-huang-9696c<http://www.linkedin.com/in/kevin-huang-9696c>
Goizueta Business School | BBA Class of 2024
***@***.*** | 808.675.8695
________________________________
From: Shuyang Bian ***@***.***>
Sent: Tuesday, October 3, 2023 6:35 PM
To: NLP-Suite/NLP-Suite ***@***.***>
Cc: Huang, Kevin ***@***.***>; Author ***@***.***>
Subject: [External] Re: [NLP-Suite/NLP-Suite] [BUG]: GUI fails to open (Issue #1206)


I am going to run the SVO for you in fact. You might want to use some placeholder to place the result. I am using batch processing to speed it up, but it might not be until 3 hours that some files can be produced...

**Comment by bianshuyang** [comment]
See you then. I am doing SOTU. In the meantime,
[batch.py.zip](https://github.com/NLP-Suite/NLP-Suite/files/12797424/batch.py.zip)
I attach a script that uses multi thread processing on SVO for my personal backup. 
Zoom link https://emory.zoom.us/my/simonbian

**Comment by khuang18** [comment]
Hey Simon,

Sounds good. Can I ask, for the CoNLL table "heat" maps like the images I attached, what is the distinction between each page? What I mean is that there are 45 pages of these charts, and I am unsure as to what the difference is in each page (different NER tag? frequency?). I can see there are different lemmas on each y axis but don't see any difference on the labels of the graphs.

I will analyze them, but what would be an example of how one might use this type of chart to make an observation about a corpus in general?

Best,
Kevin Huang
Emory University
www.linkedin.com/in/kevin-huang-9696c<http://www.linkedin.com/in/kevin-huang-9696c>
Goizueta Business School | BBA Class of 2024
***@***.*** | 808.675.8695
________________________________
From: Shuyang Bian ***@***.***>
Sent: Tuesday, October 3, 2023 6:44 PM
To: NLP-Suite/NLP-Suite ***@***.***>
Cc: Huang, Kevin ***@***.***>; Author ***@***.***>
Subject: [External] Re: [NLP-Suite/NLP-Suite] [BUG]: GUI fails to open (Issue #1206)


See you then. I am doing SOTU. In the meantime,
batch.py.zip<https://github.com/NLP-Suite/NLP-Suite/files/12797424/batch.py.zip>
I attach a script that uses multi thread processing on SVO for my personal backup.

**Comment by bianshuyang** [comment]
Close as we move on to email instead of using this thread.

**Comment by bianshuyang** [comment]
openpyxl.__version__
Out[3]: '3.0.10'
It turns out openpyxl was_too_ low in version, resulting in incompatibility. Closed the issues and marking some conversations in the process.
