### ISSUE TITLE
[BUG]: Parsers Fail to Load Due to Stanza

### ISSUE THREAD

**Issue by angelinacchen** [NLP-Suite/NLP-Suite#1209]
**Add a screenshot of the GUI you are running with the widget selections**
<img width="1340" alt="Screen Shot 2023-10-04 at 5 14 03 PM" src="https://github.com/NLP-Suite/NLP-Suite/assets/107923984/44c5efa1-44c8-438c-859c-74b57e5a96b6">
<img width="566" alt="Screen Shot 2023-10-04 at 5 15 34 PM" src="https://github.com/NLP-Suite/NLP-Suite/assets/107923984/c369920b-9844-408f-a1ea-9197e2865951">
^ The second screenshot shows me following the directions in the popup

**Describe the bug**
When I try to run Stanford Core NLP, I am unable to run the GUI at all. It tells me I don't have Stanza, however after following the instruction in the popup, the error is still there. I recently replaced the charts_util file in scr to a new one sent by Dr. Franzosi. I'm not sure if that is the reason why I am getting the error but it was the most recent change I made. This issue was not here a few weeks ago. 

**To Reproduce**
1. Go to CORPUS/DOCUMENT Analysis Tools
2. Click on Parsers and Annotators
3. See error

**Desktop (please complete the following information):**
 - OS: Version 10.15.7
 - Release Version 4.1.3

**Comment by bianshuyang** [comment]
Then, remain in the same environment. Type "python". After python is activated, type:
`import stanza`
`stanza.download('en')`

**Comment by bianshuyang** [comment]
It might be a documentation write-up problem.

**Comment by angelinacchen** [comment]
Stanford Core NLP is working for me now, thank you!
