### ISSUE TITLE
[BUG]: Issue with Gephi Output

### ISSUE THREAD

**Issue by lydianneking** [NLP-Suite/NLP-Suite#1217]
**Screenshot of the GUI with the widget selections**
![image](https://github.com/NLP-Suite/NLP-Suite/assets/143012998/5226cc31-274c-4531-88db-e493f01825fb)

**Description of the bug**
I have been trying to use the Gephi tool to visualize the form, POS, and deprel columns of the CoNLL table (of the HIV in Africa Corpus). However, every time I run it, nothing actually opens in Gephi. 

**To Reproduce**
1. Upload CoNLL table
2. Go to the GUI for visualization tools
3. Click on visualize relations and choose Gephi
4. Under csv file field, add Form, POS, and Deprel
5. Click run and allow the output file to open in Gephi
7. See error

**Screenshots**
Empty Gephi: 
![image](https://github.com/NLP-Suite/NLP-Suite/assets/143012998/6368cf99-15a7-4071-ba10-52c726e57215)

**Desktop (please complete the following information):**
 - MacOS Big Sur 11.7.6
 - NLP Version 4.1.5

**Comment by bianshuyang** [comment]
Your input file should be _SVO ideally.... However, you provide a _CoNLL
 It is likely that there is no edge between the option you have selected at all...
Did you see a console log like this?
<img width="794" alt="image" src="https://github.com/NLP-Suite/NLP-Suite/assets/52821055/1dc50aed-bf15-4bd4-ba83-3c4aafaa87e6">

You input ideally would look like:
<img width="1146" alt="image" src="https://github.com/NLP-Suite/NLP-Suite/assets/52821055/df1b2a31-da6f-4187-ba63-3ca16244456b">
Pay very closely to the style of the input file name.

**Comment by bianshuyang** [comment]
[NLP_CoreNLP_1793-03-04-george washington-ina_nn_CoNLL.gexf.zip](https://github.com/NLP-Suite/NLP-Suite/files/12834685/NLP_CoreNLP_1793-03-04-george.washington-ina_nn_CoNLL.gexf.zip)
As a test, please try to open one of a guaranteed-to-be working gexf file using Gephi on your computer. It should be outputting something colorful, with a default example:
<img width="1261" alt="image" src="https://github.com/NLP-Suite/NLP-Suite/assets/52821055/0553180d-8ceb-4a08-bd8b-b8f0eb59a56d">
If you opened the file but had an error message, that means it's not NLP suite problem, it is your Gephi problem. You may want to reinstall, etc.

**Comment by Emory-NLP** [comment]
POS is the edge in Lydia's case. The algorithm needs 3 elements, wherever they come from and not just an SVO csv file.
