### ISSUE TITLE
[BUG]: Running GIS on directory of txt files 

### ISSUE THREAD

**Issue by khuang18** [NLP-Suite/NLP-Suite#1221]
**Add a screenshot of the GUI you are running with the widget selections**
<img width="962" alt="Screenshot 2023-10-07 at 6 10 15 PM" src="https://github.com/NLP-Suite/NLP-Suite/assets/90067390/6a806978-4262-465b-af26-83fe55f2ca96">

- note I am running the SOTU folder instead of professor dumbass (dont have screenshot because I'm currently running another tool which is working but taking some time) 
- Input/Output configurations: I have entered that the filename embeds multiple items, and sorting by the date (sort order = 1), and noting that the filename embeds date as well (date number = 1)

**Describe the bug**
When running the tool with a folder of txt files, the GUI runs for a while but exits with an error within 10 minutes. Screenshots below. Note that when trying to run GUI with one txt file**, professor dumbass,** I successfully generated GIS maps and all expected outputs. 

**To Reproduce**
1. Open GIS GUI
2. Enter SOTU corpus as the input
3. Change sort order to time (1)
4. Change date position to 1 (we want time series)
5. select geocode locations and map locations
6. Run GUI

**Expected behavior**
generate GIS maps and excel charts 

**Screenshots**
<img width="571" alt="Screenshot 2023-10-07 at 5 44 21 PM" src="https://github.com/NLP-Suite/NLP-Suite/assets/90067390/3ae744cd-19e9-4a52-af25-1dab918008b4">
<img width="569" alt="Screenshot 2023-10-07 at 5 45 09 PM" src="https://github.com/NLP-Suite/NLP-Suite/assets/90067390/37169f77-c65e-4285-a495-669074d68ba3">
<img width="568" alt="Screenshot 2023-10-07 at 5 45 52 PM" src="https://github.com/NLP-Suite/NLP-Suite/assets/90067390/26d7b346-0ed2-43d6-8cff-04434cb62248">
<img width="570" alt="Screenshot 2023-10-07 at 5 46 24 PM" src="https://github.com/NLP-Suite/NLP-Suite/assets/90067390/b9d266b6-efad-41ed-97e5-0d7d585d67aa">

**Desktop (please complete the following information):**
 - OS: [OS X/Windows]
 - mac has intel chip

**Additional context**

**Comment by Emory-NLP** [comment]
I would need to see the GUI of the NLP_setup_IO_main GUI with the options selected for the filenames (the value of 1 that you mention, for instance, is NOT a correct option for the date position; and which date option have you selected?). Please, upload an image of the GUI. Finally, which POTUS files are you using? ina_adams_3-04-1797.txt or ina_john adams_3-04-1797.txt (the latter should be used). Please, copy one of the filenames.

**Comment by khuang18** [comment]
Hi Prof. Franzosi,

I understand, I should have taken all the screenshots earlier. I am currently running doc statistics since yesterday and I will upload the GIS GUI screenshots immediately after it comes to a close.

Best,
Kevin Huang
Emory University
www.linkedin.com/in/kevin-huang-9696c<http://www.linkedin.com/in/kevin-huang-9696c>
Goizueta Business School | BBA Class of 2024
***@***.*** | 808.675.8695
________________________________
From: Roberto ***@***.***>
Sent: Sunday, October 8, 2023 9:13 AM
To: NLP-Suite/NLP-Suite ***@***.***>
Cc: Huang, Kevin ***@***.***>; Author ***@***.***>
Subject: [External] Re: [NLP-Suite/NLP-Suite] [BUG]: Running GIS on directory of txt files (Issue #1221)


I would need to see the GUI of the NLP_setup_IO_main GUI with the options selected for the filenames (the value of 1 that you mention, for instance, is NOT a correct option for the date position; and which date option have you selected?). Please, upload an image of the GUI. Finally, which POTUS files are you using? ina_adams_3-04-1797.txt or ina_john adams_3-04-1797.txt (the latter should be used). Please, copy one of the filenames.

**Comment by khuang18** [comment]
<img width="1351" alt="Screenshot 2023-10-08 at 7 16 56 PM" src="https://github.com/NLP-Suite/NLP-Suite/assets/90067390/6c887ec4-2053-4097-b80b-9d3bda7b0536">
<img width="998" alt="Screenshot 2023-10-08 at 7 17 37 PM" src="https://github.com/NLP-Suite/NLP-Suite/assets/90067390/9f46ac8d-35ec-4bcb-a636-d89bc045e865">

Attached are the input output selections I made, along with another screenshot of the file names in the SOTU corpus folder. An example is "1790-01-08_george washington_sotu.txt"

<img width="1352" alt="Screenshot 2023-10-08 at 7 18 49 PM" src="https://github.com/NLP-Suite/NLP-Suite/assets/90067390/328eac29-d0f6-4f35-910b-12d74696e256">

Third, a screenshot of the current GUI settings I am attempting to run. 

<img width="739" alt="Screenshot 2023-10-08 at 7 21 13 PM" src="https://github.com/NLP-Suite/NLP-Suite/assets/90067390/a025d793-41e2-4f3c-842f-6952cab06bf9">
<img width="727" alt="Screenshot 2023-10-08 at 7 21 29 PM" src="https://github.com/NLP-Suite/NLP-Suite/assets/90067390/6e3546d7-a69c-4848-b2ef-8d8a9bc5f3d6">

Fourth and fifth, a screenshot of the error I received. It appears that some of the speeches are indeed processed but at some point, it breaks; I can see text from presidents running for a while until the error pops up. 

Please let me know if there is anything else I can provide to clear up this process.

**Comment by bianshuyang** [comment]
Can another parser run? If not I will run it

**Comment by khuang18** [comment]
I don't think it works, or for me to figure out would be pretty slow, if you could run SOTU would be helpful. I already have Inaugural GIS from last semester when I had it working. I'm continuing to write in the meantime and might start with the subcorpora tests that we havent run yet/looking at the results you got for sentiment analysis. Thanks
