### ISSUE TITLE
Annotator won't run

### ISSUE THREAD

**Issue by abhinavvittal** [NLP-Suite/NLP-Suite#1224]
1. Selected NLP Parsers from the main menu of the GUI
<img width="1344" alt="Screenshot 2023-10-08 at 2 37 24 PM" src="https://github.com/NLP-Suite/NLP-Suite/assets/78614674/862aecb0-33ab-4ca0-881f-5fb678b50dc2">

2. Then selected annotators and sentence splitting 
<img width="1333" alt="Screenshot 2023-10-08 at 2 40 10 PM" src="https://github.com/NLP-Suite/NLP-Suite/assets/78614674/7c421bec-a346-4dca-b253-12610f0eac5a">

3. When I click "Run" nothing happens and my terminal has this error
<img width="561" alt="Screenshot 2023-10-08 at 2 42 05 PM" src="https://github.com/NLP-Suite/NLP-Suite/assets/78614674/aa0dd312-1fc0-4e0f-8f8e-8c7614adc813">

**Comment by bianshuyang** [comment]
You are on 3.9.7, a version too low

**Comment by bianshuyang** [comment]
Current edition: 4.1.7 If you fail to auto upgrade, you must redownload the files under /src and replace all of them to auto update. It is likely that some git configurations is not correctly made

**Comment by abhinavvittal** [comment]
Replaced the entire /src folder but it didn't update.

Please let me know how to proceed. I can Zoom if need be.
________________________________
From: Shuyang Bian ***@***.***>
Sent: Sunday, October 8, 2023 3:01 PM
To: NLP-Suite/NLP-Suite ***@***.***>
Cc: Vittal, Abhinav ***@***.***>; Author ***@***.***>
Subject: [External] Re: [NLP-Suite/NLP-Suite] Annotator won't run (Issue #1224)


Current edition: 4.1.7 If you fail to auto upgrade, you must redownload the files under /src and replace all of them to auto update. It is likely that some git configurations is not correctly made

**Comment by bianshuyang** [comment]
https://emory.zoom.us/s/4237099039

**Comment by bianshuyang** [comment]
Use of CLOSE button to upgrade and way to run was informed

**Comment by abhinavvittal** [comment]
Hi Simon,

The NLP suite crashed when I tried running annotators instead of parsers. I reopened it using the method you told me (open terminal, python3 + drag the NLP file) and it didn't work. I also tried opening terminal in src , typed in conda activate NLP, and then typed in python3 NLP_menu_main.py.

None of these worked. I have attached a video at the bottom of the email of me trying it out.

Thanks,
Nav

[https://res-geo.cdn.office.net/assets/mail/file-icon/png/video_16x16.png]Screen Recording 2023-10-08 at 4.39.36 PM.mov<https://emory-my.sharepoint.com/:v:/g/personal/avittal_emory_edu/EQugggH2H3BNsVhrAhxEL-4BDTBCJAFsrbgYMHa6eYaquw>
________________________________
From: Shuyang Bian ***@***.***>
Sent: Sunday, October 8, 2023 4:13 PM
To: NLP-Suite/NLP-Suite ***@***.***>
Cc: Vittal, Abhinav ***@***.***>; Author ***@***.***>
Subject: [External] Re: [NLP-Suite/NLP-Suite] Annotator won't run (Issue #1224)


Closed #1224<https://github.com/NLP-Suite/NLP-Suite/issues/1224> as completed.

**Comment by bianshuyang** [comment]
Drag to github to reply. Do not respond by email because attachments are encrypted by emory.

**Comment by bianshuyang** [comment]
You should not activate NLP in your particular environment because all packages are installed under the (base) environment...There is also no reason to type a plus between python and a .command as the latter is self executable.
To exit, type `conda deactivate` and go to the **base** environment on your computer...

**Comment by abhinavvittal** [comment]
<img width="566" alt="Screenshot 2023-10-08 at 5 15 02 PM" src="https://github.com/NLP-Suite/NLP-Suite/assets/78614674/895ae7d6-e3f2-4648-b1d3-bd54136fcdb7">

I'm in base now and didn't put the plus. Still giving an error. So, so sorry I'm making you help me with all of this.

**Comment by bianshuyang** [comment]
You must not run any .command with a python. Self executable means that they are able to run on their own without being called upon by an external software. 
In your case , the only correct way is to type in terminal these commands `python3 /Users/abhinavvittal/Downloads/NLP-Suite-current-stable/src/NLP_menu_main.py` (Do check carefully for typos)
