### ISSUE TITLE
read_csv Error

### ISSUE THREAD

**Issue by coralynnkc** [NLP-Suite/NLP-Suite#1225]
0. SCREENSHOTS. 
![image](https://github.com/NLP-Suite/NLP-Suite/assets/142829954/d1bd7327-6eb1-41b5-9b1e-39d62cf84b7c)
1. DESCRIPTION. 
Attempting to launchthe NLP Suite resulted in a pop-up error, specifically: read_csv() got an unexpected keyword argument 'on_bad_lines'.
2. STEPS.
- Launch NLP Suite.
3. INFORMATION. 
Windows OS
NLP Suite Release 4.1.8

**Comment by bianshuyang** [comment]
What's your pandas version? In CONSOLE, use:
`python` or `python3`
`import pandas`
`print(pandas.__version__)`
and see the version. A working version is 1.5.2
If not, you may switch to the correct environment. 
This is a duplicated issue.
https://github.com/NLP-Suite/NLP-Suite/issues/1138
https://github.com/NLP-Suite/NLP-Suite/issues/1137
