### ISSUE TITLE
Error running word clouds GUI

### ISSUE THREAD

**Issue by kaavyamuthuganesan** [NLP-Suite/NLP-Suite#1226]
![word cloud gui](https://github.com/NLP-Suite/NLP-Suite/assets/142953438/1bf3421b-b284-4eb0-9e57-3b1ed3d768a3)
![word cloud error](https://github.com/NLP-Suite/NLP-Suite/assets/142953438/f8e277b4-9905-4e7b-a04c-9c595b6193f3)

**Comment by bianshuyang** [comment]
Have you checked other parsers, including Stanford CoreNLP and spaCy?

**Comment by kaavyamuthuganesan** [comment]
it didnt work for stanford core nlp but it worked for stanza
