### ISSUE TITLE
WordNet Extractor Error

### ISSUE THREAD

**Issue by coralynnkc** [NLP-Suite/NLP-Suite#1227]
0. SCREENSHOTS.
![image](https://github.com/NLP-Suite/NLP-Suite/assets/142829954/4a5139ed-fa0f-4f11-a5e6-7c83a4d69e0f)
![image](https://github.com/NLP-Suite/NLP-Suite/assets/142829954/27089259-0430-43c3-a2e1-82552b0ad28b)
![error](https://github.com/NLP-Suite/NLP-Suite/assets/142829954/f4f4a760-98b1-4192-8e17-fc7a15700079)

1. DESCRIPTION.
Utilizing the WordNet 'extract proper nouns' function results in an error. 

2. STEPS. 
- NLP Suite -> WordNet
- WordNet GUI -> Extract PROPER nouns

3. INFORMATION. 
Windows OS
NLP Suite Release 4.1.8

**Comment by bianshuyang** [comment]
What is the parsers? Show Setup -> Setup NLP package and corpus language

**Comment by bianshuyang** [comment]
See a resolution for a similar widget and see if it can help. https://github.com/NLP-Suite/NLP-Suite/issues/1229

**Comment by coralynnkc** [comment]
![image](https://github.com/NLP-Suite/NLP-Suite/assets/142829954/558e6f40-96a0-4cd7-abc4-1b7eb9bc1767)

**Comment by Emory-NLP** [comment]
Cora, could you send me to my email the csv file that you have in input?
![image](https://github.com/NLP-Suite/NLP-Suite/assets/79026295/f98fa8e1-7a74-4b18-a450-7e9beebfa16e)

**Comment by Emory-NLP** [comment]
Never mind. I can reproduce the error. Thank you.
