### ISSUE TITLE
n-grams

### ISSUE THREAD

**Issue by Emory-NLP** [NLP-Suite/NLP-Suite#1231]
The n-grams algorithm is VERY inefficient. For every gram (1, 2, 3...) it reads all the documents in a corpus. All n-grams (1-gram, 2-gram, 3-gram,...) should be computed at the same time for the same document.

**Comment by bianshuyang** [comment]
[ngrams.zip](https://github.com/NLP-Suite/NLP-Suite/files/12908645/ngrams.zip)
This shortens the original 5 hours solution to 507 seconds (8 minutes)

**Comment by bianshuyang** [comment]
If we opted for no-stanza parser, this could speed up even more

**Comment by Atroxgod** [comment]
how can i get stanza package?

**Comment by bianshuyang** [comment]
Hi, you would need to download by pip.

**Comment by bianshuyang** [comment]
Note that this is a "beta testing" version with no GUI. Note also that no filtering, including stopwords, punctuation, etc. is included. Expect the time to vary based on documents. See last part for timing estimation.
