### ISSUE TITLE
CoOccurence x axis issue

### ISSUE THREAD

**Issue by ghost** [NLP-Suite/NLP-Suite#1232]
I tried running Cooccurrence viewer on NLP Suite
<img width="1200" alt="Screenshot 2023-10-11 at 11 41 12 AM" src="https://github.com/NLP-Suite/NLP-Suite/assets/145512814/dccdfd68-7f25-4401-a6d2-8f84089cb749">
The input was directory of txt files.
<img width="566" alt="Screenshot 2023-10-11 at 11 42 04 AM" src="https://github.com/NLP-Suite/NLP-Suite/assets/145512814/af2097e4-2c03-4633-9a6b-d1b074939642">
I get this value error that says "x not in the list", thus the frequency value are not shown as bars.
<img width="427" alt="image" src="https://github.com/NLP-Suite/NLP-Suite/assets/145512814/e31bb2c8-4612-4e81-b528-79000e5f6321">

**Comment by Emory-NLP** [comment]
Could you send me by email a zipped file of your input documents? The bug occurs when opening the files. It does not affect the bar chart; different issue.
