### ISSUE TITLE
SpaCy Dependency Parser

### ISSUE THREAD

**Issue by coralynnkc** [NLP-Suite/NLP-Suite#1237]
0. SCREENSHOTS.
![Screenshot 2023-10-13 143034](https://github.com/NLP-Suite/NLP-Suite/assets/142829954/3ca0c9da-d370-4f9c-8ce1-841659844600)
![Screenshot 2023-10-13 143117](https://github.com/NLP-Suite/NLP-Suite/assets/142829954/d1db57bc-71ba-46d8-a697-7b572e27f2ef)
![Screenshot 2023-10-13 143138](https://github.com/NLP-Suite/NLP-Suite/assets/142829954/9fc3bed0-1a2b-4e5f-aed1-41b7d35d9a6a)
![Screenshot 2023-10-13 143201](https://github.com/NLP-Suite/NLP-Suite/assets/142829954/18d2f0eb-9160-482c-8f49-bccd1c29cc4d)
1. DESCRIPTION. 
Attempting to run the SpaCy Dependency Parser results in a series of errors in the terminal, suggested by the NLP suite to be a result of not being able to use 'English'. I'm uncertain about how to install that package, if that is the error.
2. STEPS.
NLP Suite Main Menu -> Parsers & Annotators
Parsers & Annotators (SpaCy, Dependency Parser) -> Run
3. INFORMATION.
Windows OS.
Release 4.2.2.

**Comment by bianshuyang** [comment]
I wonder if you can screenshot a bit more as I do see a "RuntimeError" on the first row, but I want to see the complete log history if possible. It looks like it's not a Spacy problem by itself.

**Comment by coralynnkc** [comment]
![image](https://github.com/NLP-Suite/NLP-Suite/assets/142829954/2fdc7807-74c8-4d52-97fb-d34caf9aa08c)
