### ISSUE TITLE
Issue with running Stanza Parser

### ISSUE THREAD

**Issue by yxyang05** [NLP-Suite/NLP-Suite#1241]
I am having the same issue as #1240 on Mac as well. The Stanford CoreNLP and spaCy parsers worked fine. But when I try to run the Stanza parser, I get an error that the 'DataFrame' object has no attribute 'append'
<img width="1344" alt="Screenshot 2023-10-16 at 12 00 34 AM" src="https://github.com/NLP-Suite/NLP-Suite/assets/121314139/5fd06109-9adc-4196-b552-a793577c65dc">
<img width="584" alt="Screenshot 2023-10-15 at 8 53 16 PM" src="https://github.com/NLP-Suite/NLP-Suite/assets/121314139/8a0941f8-a36b-4f54-8157-9243b25c332e">

**Comment by bianshuyang** [comment]
See https://github.com/NLP-Suite/NLP-Suite/issues/1142
