### ISSUE TITLE
Problem Running WordNet

### ISSUE THREAD

**Issue by yxyang05** [NLP-Suite/NLP-Suite#1244]
I'm trying to run the WordNet to extract the proper and improper nouns from my locations NER csv file. However, I am encountering an error whenever I try to run NLP.
<img width="1341" alt="Screenshot 2023-10-18 at 3 46 09 AM" src="https://github.com/NLP-Suite/NLP-Suite/assets/121314139/33d4f0aa-b7ca-4c5c-a007-1f9c40d20a9c">
<img width="569" alt="Screenshot 2023-10-18 at 3 46 28 AM" src="https://github.com/NLP-Suite/NLP-Suite/assets/121314139/c2009caa-56ae-46f6-8f2f-4245687f70b9">

**Comment by Emory-NLP** [comment]
Did you bother reading the ?HELP for the option you are trying to run? Which type of csv file does it require? Any csv file? The option now traps the error but you should read carefully your ?HELP messages.
