### ISSUE TITLE
Previous/next K words

### ISSUE THREAD

**Issue by Emory-NLP** [NLP-Suite/NLP-Suite#1248]
In the search_byWord_main and CoNLL_table_analyzer GUIs below the widgets to allow users to extract 1, 2, 3,... words before and after a given search word were added. We need the code to implement the options.

![image](https://github.com/NLP-Suite/NLP-Suite/assets/79026295/2ef4bed5-3e07-4c88-9ac7-c706aa599fb7)

![image](https://github.com/NLP-Suite/NLP-Suite/assets/79026295/6cf2aa77-80bb-49fd-b83f-4d5c0322bf28)

**Comment by bianshuyang** [comment]
file_search_byWord_util.py.zip
NGrams_CoOccurrences_util.py.zip
Both files done and pushed.
