### ISSUE TITLE
Sunburst and treemap chart generalization

### ISSUE THREAD

**Issue by Emory-NLP** [NLP-Suite/NLP-Suite#1251]
The Sunburst and treemap visualizations 

![image](https://github.com/NLP-Suite/NLP-Suite/assets/79026295/78a2c269-30b5-498e-a6b2-5487795f7f6d)

expect a field named Document. But there is no need to restrict this option to Document. 

![image](https://github.com/NLP-Suite/NLP-Suite/assets/79026295/354bd287-2a05-4034-a2f4-5407d8293671)

We should allow the values of any selected field (e.g., NER) to be used.

**Comment by bianshuyang** [comment]
[Archive.zip](https://github.com/NLP-Suite/NLP-Suite/files/13184205/Archive.zip)
Attached here to mark completion of the issue. Finished an SQL-like format on Oct 25 evening.
