### ISSUE TITLE
SVO_main.py is missing

### ISSUE THREAD

**Issue by kaavyamuthuganesan** [NLP-Suite/NLP-Suite#1252]
when I try to open the SVO gui a popup appears telling me that the file is missing.
![svo main missing](https://github.com/NLP-Suite/NLP-Suite/assets/142953438/c62bc220-7aaf-4a1a-8227-476e75a96b8a)

**Comment by lydianneking** [comment]
This is also happening to me.

**Comment by SahithiGangaram434** [comment]
This is also happening to our group

**Comment by kaavyamuthuganesan** [comment]
for now, my temporary fix was using an older version of the file from when i first downloaded the suite for the set up

**Comment by evacap1** [comment]
Same issue I'm facing!

**Comment by evacap1** [comment]
and it's still there on version 4.3.0

**Comment by Emory-NLP** [comment]
Corrected. Sorry!
