### ISSUE TITLE
Style Analysis GUI complexity/readability GUI

### ISSUE THREAD

**Issue by angelinacchen** [NLP-Suite/NLP-Suite#1264]
<img width="1341" alt="Screen Shot 2023-10-25 at 1 33 06 PM" src="https://github.com/NLP-Suite/NLP-Suite/assets/107923984/867dfa8f-264f-48b3-bcf6-995eaee7386e">
Above is the GUI I am trying to run.

Below is what I see in terminal.

<img width="1345" alt="Screen Shot 2023-10-25 at 1 24 51 PM" src="https://github.com/NLP-Suite/NLP-Suite/assets/107923984/e6b7abac-3186-4897-9384-7904f85d1fa1">

The GUI is stuck on the photo above ^. 

To Reproduce

Go to Style Analysis GUI
Click Complexity/readability GUI
Scroll down to the bottom of the terminal
See error
Desktop (please complete the following information):

OS: macOS Catalina 10.15.7
Release Version 4.3.4

Additional Information:
[Sand_Antonia.txt](https://github.com/NLP-Suite/NLP-Suite/files/13169009/Sand_Antonia.txt)
[Steinbeck_Grapes of wrath.txt](https://github.com/NLP-Suite/NLP-Suite/files/13169010/Steinbeck_Grapes.of.wrath.txt)
[Wharton_The House of Mirth.txt](https://github.com/NLP-Suite/NLP-Suite/files/13169011/Wharton_The.House.of.Mirth.txt)
[Woolf_Mrs Dalloway in Bond Street.txt](https://github.com/NLP-Suite/NLP-Suite/files/13169012/Woolf_Mrs.Dalloway.in.Bond.Street.txt)
[Woolf_To the Lighthouse.txt](https://github.com/NLP-Suite/NLP-Suite/files/13169013/Woolf_To.the.Lighthouse.txt)

I am running it on a novel corpus. I will try to attached it above.

**Comment by bianshuyang** [comment]
[first_file_test.zip](https://github.com/NLP-Suite/NLP-Suite/files/13196436/first_file_test.zip)
Try running the first part of the first file, does it work now? Based on my calculation, it should take 50 seconds for one split file to pass through.

**Comment by angelinacchen** [comment]
I am getting the same issue.
<img width="911" alt="Screen Shot 2023-10-28 at 6 24 10 PM" src="https://github.com/NLP-Suite/NLP-Suite/assets/107923984/06125cc5-5e8f-4e2f-9ebc-66614b6d5ad8">

**Comment by bianshuyang** [comment]
Perhaps upgrade to 4.3.9? You are currently on 4.3.4
Then, try only Sand_Antonia.txt.part01.txt? Not the others?
Finally, check your output folder? Perhaps it did it asynchronously?
If none helps, I might go to class to see.
