### ISSUE TITLE
Sunburst and Treemap

### ISSUE THREAD

**Issue by Emory-NLP** [NLP-Suite/NLP-Suite#1279]
With too many values to display, the sunburst and treemap charts become quite unreadable. We should limit the number of records processed by a user-entered value. Basically, in the function Sunburst_Treemap we should filter the counts field.
    df_grouped = df.groupby(select_and_count).size().reset_index(name='counts')

![image](https://github.com/NLP-Suite/NLP-Suite/assets/79026295/05293d25-f4db-426b-83c7-644c7aec35df)

![image](https://github.com/NLP-Suite/NLP-Suite/assets/79026295/264bbc0b-9f5e-44c1-a806-5e4fbfbfba9c)

Furthermore, in data_visualization1_main , there is a test to remind the user if they forgot to click the + button. but this gives a partial match with different values in it (csv field and value). Should just have an exact match for the csv field.
            if csv_field_categorical_var.get()!='' and not csv_field_categorical_var.get() in str(csv_file_categorical_field_list):

**Comment by bianshuyang** [comment]
[1279.zip](https://github.com/NLP-Suite/NLP-Suite/files/13262259/1279.zip)
Some code snippet appropriate for this issue

**Comment by bianshuyang** [comment]
```
def transform(df,prt,nms):
    nms = int(nms)
    top_X_items = list(df[prt].value_counts()[0:nms].keys())
    df = df[df[prt].isin(top_X_items)]
    return df

for col in df.columns:
    if col!='counts':
        df = transform(df, col, 50) # fixed parameter, Parameter_ only, option 1
```

```
# Method two
import pandas as pd
df = pd.read_csv("Example input.csv")
def transform(df,prt,nms):
    nms = int(nms)
    top_X_items = list(df[prt].value_counts()[0:nms].keys())
    df = df[df[prt].isin(top_X_items)]
    return df

rt = 3 # rate of change, Parameters _ 1, option 2
base = 40 # base_rate, Paramters _ 2, option 2

for col in df.columns:
    if col!='counts':
        df = transform(df, col, base)
        base = base * rt
```

Option 1: Fixed Parameter Filtering 50-100 (default 50)
Option 2: Rate-Propagating Parameter Filtering: 2 values Rate filtering 3 value Base filtering value def = 40
Option 3: No filter at all

**Comment by bianshuyang** [comment]
Charts util, 1962

**Comment by bianshuyang** [comment]
[Archive.zip](https://github.com/NLP-Suite/NLP-Suite/files/13302597/Archive.zip)
