### ISSUE TITLE
N-grams & Co-Occurrences GUI

### ISSUE THREAD

**Issue by Emory-NLP** [NLP-Suite/NLP-Suite#1283]
The n-grams search produces wordclouds that include the search work, contrary to the file_search_byWord_util that excludes the search word from the wordcloud. Should be uniformed?

![image](https://github.com/NLP-Suite/NLP-Suite/assets/79026295/a629eede-683c-40df-b1f2-9bb67b2baa23)

**Comment by bianshuyang** [comment]
Line 506 - 512:
```
                with open(NgramsSearchFileName_txt,'r',encoding='utf-8',errors='ignore') as f:
                    q = f.read()
                for word in search_keywords_list:
                    q = q.replace(word,'')
                    print(q,word)
                with open(NgramsSearchFileName_txt,'w',encoding='utf-8') as f:
                    f.write(q)
```
We will use this as a hot fix for now.

**Comment by bianshuyang** [comment]
Filename: ```NGrams_CoOccurrences_util.py```
