### ISSUE TITLE
Mallet won't run

### ISSUE THREAD

**Issue by abhinavvittal** [NLP-Suite/NLP-Suite#1291]
Hi --

I have MALLET installed on my computer and the file paths have no spaces. Below is an image of how GUI for this week's homework looks.
<img width="1341" alt="Screenshot 2023-11-04 at 11 11 48 AM" src="https://github.com/NLP-Suite/NLP-Suite/assets/78614674/d4587745-6231-48b5-8b7b-94588764809a">

When I click "Run," this is what shows up on my terminal.
<img width="573" alt="Screenshot 2023-11-04 at 11 12 26 AM" src="https://github.com/NLP-Suite/NLP-Suite/assets/78614674/a4ab0f4e-99f2-4c91-8112-0cac5859cc3d">

Please let me know what to do.

**Comment by bianshuyang** [comment]
If you don't click MALLET, how would it run? (Third line option was shown to be empty)

**Comment by bianshuyang** [comment]
You must select either Mallet or Gensim to make it work. The computer cannot guess what you want from null

**Comment by abhinavvittal** [comment]
It worked! Simon and magic, every week! Thank you, so much.
________________________________
From: Shuyang Bian ***@***.***>
Sent: Saturday, November 4, 2023 3:41:14 PM
To: NLP-Suite/NLP-Suite ***@***.***>
Cc: Vittal, Abhinav ***@***.***>; Author ***@***.***>
Subject: [External] Re: [NLP-Suite/NLP-Suite] Mallet won't run (Issue #1291)


You must select either Mallet or Gensim to make it work. The computer cannot guess what you want from null
