### ISSUE TITLE
Sentiment analysis output with plotly and pie charts

### ISSUE THREAD

**Issue by Emory-NLP** [NLP-Suite/NLP-Suite#1292]
When running sentiment analysis with these options
![image](https://github.com/NLP-Suite/NLP-Suite/assets/79026295/c5c12d75-2bde-47c9-b498-bc035858bd1d)

The algorithm produces this set of documents
![image](https://github.com/NLP-Suite/NLP-Suite/assets/79026295/bfef7d82-9cc7-4ccb-97e5-920a3eedee52)

But ...

1. Sentiment Label Statistics by Document.html is not produced. The very likely cause is the following error

![image](https://github.com/NLP-Suite/NLP-Suite/assets/79026295/3d7c2314-d720-46e5-9e95-ae90efed937f)

2. Furthermore, the chart document Frequency Distribution of Sentiment Labels.html is empty.
![image](https://github.com/NLP-Suite/NLP-Suite/assets/79026295/0930ec34-4acd-4a59-a848-5bb2c8f0893f)

**Comment by bianshuyang** [comment]
I was unable to replicate this error. Attached are the results and logs.
[sentiment_CoreNLP_The Three Little Pigs.zip](https://github.com/NLP-Suite/NLP-Suite/files/13269598/sentiment_CoreNLP_The.Three.Little.Pigs.zip)
<img width="1346" alt="image" src="https://github.com/NLP-Suite/NLP-Suite/assets/52821055/5b3e7670-a38a-4cf2-9472-2c478d958551">

Perhaps it's an unclosed, finished issue?

**Comment by bianshuyang** [comment]
[log.txt](https://github.com/NLP-Suite/NLP-Suite/files/13269615/log.txt)

**Comment by Emory-NLP** [comment]
OK. Yours is correct. Bizarre. We will look at it on my my Windows machine.

**Comment by bianshuyang** [comment]
Line 165: charts_plotly_util.py:    changed to: ``` if height == '' or height =='Sentiment label':```
Will suppress the problem for now. It is unclear why we don't add a count for every height.
