### ISSUE TITLE
Data_visualization_2_main GUI with plotly charts

### ISSUE THREAD

**Issue by Emory-NLP** [NLP-Suite/NLP-Suite#1293]
When running the data_visualization_2_main GUI with these options, to obtain a simple plotly pie chart

![image](https://github.com/NLP-Suite/NLP-Suite/assets/79026295/e4b47aad-5838-4fe6-8e69-68479fececbe)

using the sentiment analysis results as the input csv file

![image](https://github.com/NLP-Suite/NLP-Suite/assets/79026295/d058f6cd-91af-430a-9af2-c6cc26ef3a18)

the plot produces an empty chart document. See Issue 1292 for a similar problem using the same input file.

![image](https://github.com/NLP-Suite/NLP-Suite/assets/79026295/3922fa96-8e28-4275-b24d-3d430203b2d9)

**Comment by bianshuyang** [comment]
[charts_plotly_util.py.zip](https://github.com/NLP-Suite/NLP-Suite/files/13320935/charts_plotly_util.py.zip)

**Comment by Emory-NLP** [comment]
Still empty even with the new _util.

![image](https://github.com/NLP-Suite/NLP-Suite/assets/79026295/8035b42a-c4ba-4d8b-b5d1-0f31bc298bde)
