### ISSUE TITLE
Problem setting up parsers and annotators package  

### ISSUE THREAD

**Issue by esteficarbo** [NLP-Suite/NLP-Suite#1300]
<img width="1470" alt="Screenshot 2023-11-05 at 8 57 02 PM" src="https://github.com/NLP-Suite/NLP-Suite/assets/146776706/c7ed24de-a89f-45c5-9e45-1cc591c58b73">

Whenever I try to setup the default NLP parsers & annotators package and default corpus language I get a "Fatal Error". The terminal says "No module named 'seaborn'" and if I try to type in "pip install seaboard" nothing happens. 

To replicate: 
1. Open newly updated NLP suite
2. click on "SETUP default NLP parsers & annotators package and default corpus language

**Comment by Emory-NLP** [comment]
You need to add a screenshot of how/where you pip install seaborn.
