### ISSUE TITLE
file search by single word or collocations did not sort the words correctly

### ISSUE THREAD

**Issue by esteficarbo** [NLP-Suite/NLP-Suite#1302]
When looking at the NLP_Search in class, I noticed that the file search by single word or collocations did not sort the words correctly. 

To replicate go into Graphical User Interface for File Search by Single Word of Collocations, select "Search corpus by word(s)" and type a word and choose "-K 2 and +K 2" . Select Open output files and create chart(s). Run and see words not exactly well organized as seen below. 
![IMG_8799](https://github.com/NLP-Suite/NLP-Suite/assets/146776706/2d31b941-6e81-4ef8-8ae4-97f2954eb0e8)
![IMG_8800](https://github.com/NLP-Suite/NLP-Suite/assets/146776706/c3db6c54-dda9-43f9-ba82-676b79fe7ae6)
![IMG_8801](https://github.com/NLP-Suite/NLP-Suite/assets/146776706/3961140d-7122-4174-87e7-8c3a0f4d8049)

**Comment by bianshuyang** [comment]
Could you bring the definition of "organized" and "corect"? They are meant to be a collection of the words, regardless of the order of the documents?

**Comment by Emory-NLP** [comment]
Oh dear! When you run the file_search_byWord GUI searching for home -3 + 3, some words are bunched together, w/o leaving a space in between and then, of course, the worldcloud is wrong

![image](https://github.com/NLP-Suite/NLP-Suite/assets/79026295/d9a3e37b-4934-4b1f-b3ee-0c08b4f8c529)

![image](https://github.com/NLP-Suite/NLP-Suite/assets/79026295/2b4f3381-f86f-4a1a-8e55-35d5b8913100)

**Comment by bianshuyang** [comment]
Line 158: file_search_byWord_util.py
```f.write(' '.join(a)+"\n") ```
