### ISSUE TITLE
Search corpus by word(s) (Extract sentences)

### ISSUE THREAD

**Issue by Emory-NLP** [NLP-Suite/NLP-Suite#1303]
The function in file_search_byWord extract all sentences containing a search word as a set of txt files and then visualizes results in wordclouds.

![image](https://github.com/NLP-Suite/NLP-Suite/assets/79026295/9598ad1c-c84a-45cc-9405-ff049d20d831)

![image](https://github.com/NLP-Suite/NLP-Suite/assets/79026295/640ec456-a5db-4806-98bd-de511cb3cfd7)

We should also export a csv file in the main output directory as we do in the the search for word option.

![image](https://github.com/NLP-Suite/NLP-Suite/assets/79026295/0246af8c-a5ff-45d8-bc11-dbbf908abda5)

The csv file should contain the search word, the position of the sentence in the document and its relative position, Sentence ID, Sentence, and, MOST importantly the Document ID and Document (as done in the search for word; see output image). This would allow a quick view of sentence content and their documents.

![image](https://github.com/NLP-Suite/NLP-Suite/assets/79026295/e21fae4c-cfa5-4f5b-9458-7b0494998002)

**Comment by bianshuyang** [comment]
Pasting these lines only instead of replacement with a whole file will make sure nothing might be unexpectedly changed. 
Line 512, add:
```
outputFilenameCSV = IO_files_util.generate_output_file_name(inputFilename, inputDir, outputDir, '.csv',
                                                                        'SEARCH_STATISTICS')
            with open(outputFilenameCSV, 'w', encoding='utf-8', errors='ignore') as f:
                f.write('Search Word, Sentence, Sentence ID of the occurrence, Relative position in document, Document ID, Document\n')
            
````

Line 544, because of the addition:
``` 
                        if word_match:
                            sentence = re.findall(r'\b\w+\b', sentence)
                            sentencecopy = sentence
                        else:
                            sentencecopy = sentence
                        if keyword in sentence:
                            with open(outputFilenameCSV,'a',encoding='utf-8',errors='ignore') as f:
                                f.write(keyword+","+csv_escape(''.join(sentencecopy))+','+
                                        str(sentences.index(sentencecopy))+','+
                                        str(sentences.index(sentencecopy)/len(sentences))+','+
                                        str(inputDocs.index(doc))+','+
                                        IO_csv_util.dressFilenameForCSVHyperlink(doc)+
                                        '\n')

```

<img width="933" alt="image" src="https://github.com/NLP-Suite/NLP-Suite/assets/52821055/84dbef0b-6854-43d1-9ec0-fdbb1dc24558">
For verification of the finalized code, see for comparison:
[file_search_byWord_util.py.zip](https://github.com/NLP-Suite/NLP-Suite/files/13298092/file_search_byWord_util.py.zip)
