### ISSUE TITLE
Co-Occurrence VIEWER (co-occurrence in sentence besides document)

### ISSUE THREAD

**Issue by Emory-NLP** [NLP-Suite/NLP-Suite#1305]
There is no way in the NLP Suite to search for words that Co_Occur in the same sentence. The Co-Occurrence VIEWER uses the document as the unit of analysis. May be we can make it a parameter choice? Document or sentence?

![image](https://github.com/NLP-Suite/NLP-Suite/assets/79026295/699473c7-ce3b-433f-ac78-97be3f58665b)

**Comment by bianshuyang** [comment]
Core function is written. Waiting for packaging into a GUI format.

```
def sent_tokenize_stanza(doc, return_text=True):
    if return_text is False:
        return [sentence for sentence in doc.sentences]
    else:
        return [sentence.text for sentence in doc.sentences]
import stanza
stanzaPipeLine = stanza.Pipeline(lang='en', processors= 'tokenize, lemma')

def word_tokenize_stanza(doc):
    lst = []
    for sentence in doc.sentences:
        [lst.append(token.text) for token in sentence.tokens]
    return lst

def is_subset(A, B):
    return all(element in B for element in A)

fullText = 'Three pigs go and come. I come and She here. You donot come. She come. You go. I come and leave. She come and Me and Tom.'
sentences = sent_tokenize_stanza(stanzaPipeLine(fullText))
targets = ['come', 'and']
for sent in sentences:
    if is_subset(targets,word_tokenize_stanza(stanzaPipeLine(sent))):
        print(sent,sentences.index(sent))

```

**Comment by bianshuyang** [comment]
[Within_Sentence_Update.zip](https://github.com/NLP-Suite/NLP-Suite/files/13322878/Within_Sentence_Update.zip)
Upon clicking the required button, user can now generate the within-sentence csv file (no charts regardless of selection, no differentiation between n-grams and co-occurrence) 

Example output
<img width="1191" alt="image" src="https://github.com/NLP-Suite/NLP-Suite/assets/52821055/7448b72a-d9fc-44a6-a2e3-bbbf42e61966">
