### ISSUE TITLE
error running word 2 vec bert

### ISSUE THREAD

**Issue by kaavyamuthuganesan** [NLP-Suite/NLP-Suite#1309]
![word 2 vec gui](https://github.com/NLP-Suite/NLP-Suite/assets/142953438/a9f3f797-8208-4f97-81b2-b6e123a55cfd)
when i try to run word 2 vec for bert i get the following error
![missing module error](https://github.com/NLP-Suite/NLP-Suite/assets/142953438/b4ec46c5-fe3b-4246-8a5d-8231bdf3ee26)
however, i have installed sacremoses in the NLP environment yet I still get the error
![sacremoses present](https://github.com/NLP-Suite/NLP-Suite/assets/142953438/64b97a8e-1834-4236-be86-8275067d2f95)

**Comment by kaavyamuthuganesan** [comment]
I also tried updating paramiko but am still getting this error

**Comment by bianshuyang** [comment]
It appears that NLP environment is not required for your script. Have you tried installing in another environment?

**Comment by bianshuyang** [comment]
To go to the base you may wish to never apply the command of ```conda activate NLP```

**Comment by kaavyamuthuganesan** [comment]
thanks that resolved the issue
