### ISSUE TITLE
CoNLL Table Analyzer for verb analysis

### ISSUE THREAD

**Issue by khuang18** [NLP-Suite/NLP-Suite#1319]
CoNLL table analyzer GUI returns error when trying to run verb analysis of CoNLL input. 
<img width="1349" alt="Screenshot 2023-11-14 at 9 15 43 PM" src="https://github.com/NLP-Suite/NLP-Suite/assets/90067390/17e20a15-8f34-4e0b-beac-ad4d736cefb1">

Screenshot of error in terminal: 
<img width="931" alt="Screenshot 2023-11-14 at 9 15 10 PM" src="https://github.com/NLP-Suite/NLP-Suite/assets/90067390/880fcae7-8aa1-4d95-8738-1c838e4aa9b7">

Here is a screenshot of the CoNLL table in input: 
<img width="1095" alt="Screenshot 2023-11-14 at 9 18 04 PM" src="https://github.com/NLP-Suite/NLP-Suite/assets/90067390/04df3dde-6d83-450d-8e69-863756267262">

**Comment by Emory-NLP** [comment]
Could you please send me via email the zipped CoNLL table you are using? I cannot reproduce the error.

**Comment by khuang18** [comment]
Hi,

Here is the file. Maybe it is a problem local to my computer. Thanks

Best,
Kevin Huang
Emory University
www.linkedin.com/in/kevin-huang-9696c<http://www.linkedin.com/in/kevin-huang-9696c>
Goizueta Business School | BBA Class of 2024
***@***.*** | 808.675.8695
________________________________
From: Roberto ***@***.***>
Sent: Wednesday, November 15, 2023 11:53 AM
To: NLP-Suite/NLP-Suite ***@***.***>
Cc: Huang, Kevin ***@***.***>; Author ***@***.***>
Subject: [External] Re: [NLP-Suite/NLP-Suite] CoNLL Table Analyzer for verb analysis (Issue #1319)


Could you please send me via email the zipped CoNLL table you are using? I cannot reproduce the error.
