### ISSUE TITLE
file_seach_byWord error

### ISSUE THREAD

**Issue by Emory-NLP** [NLP-Suite/NLP-Suite#1332]
When running the file_seach_byWord on the CGWR with the word government

![image](https://github.com/NLP-Suite/NLP-Suite/assets/79026295/25edac92-6c93-4952-a282-809c66f02d4a)

the code breaks 

![image](https://github.com/NLP-Suite/NLP-Suite/assets/79026295/9efe3087-db7e-44d1-be17-64c1db6f12e5)

**Comment by bianshuyang** [comment]
I cannot replicate this on a Mac

**Comment by bianshuyang** [comment]
Logs:
<img width="1194" alt="image" src="https://github.com/NLP-Suite/NLP-Suite/assets/52821055/f905f7b1-71d8-4f9a-96e5-71108882d00f">
Options entered:
<img width="1392" alt="image" src="https://github.com/NLP-Suite/NLP-Suite/assets/52821055/ae0b5a9a-8dfe-4a18-968c-a4d198ac263d">
Perhaps delete files with the word "Cache" and retry? It is likely some cache names may be conflicting

**Comment by Emory-NLP** [comment]
Even after deleting all cache I get the same error. Make sure to search... (EXTRACT)
