### ISSUE TITLE
CoNLL table analyzer for nouns 

### ISSUE THREAD

**Issue by Emory-NLP** [NLP-Suite/NLP-Suite#1338]
The CoNLL table analyzer option for nouns

![image](https://github.com/NLP-Suite/NLP-Suite/assets/79026295/0b1edbe5-02ce-4745-8018-b3b9157de054)

processes only a handful of NER & DepRel tags. Should process all tags (see the lines in CoNLL_noun_analysis_util).

    list_nouns_ner = data_preperation(data, ['COUNTRY','CITY','LOCATION','PERSON','ORGANIZATION','STATE_OR_PROVINCE'],
    ['COUNTRY','CITY','LOCATION','PERSON','ORGANIZATION','STATE_OR_PROVINCE'],4)
    noun_ner_stats = [['Noun NERs', 'Frequencies'],
        ['COUNTRY', ner_counter['COUNTRY']],
        ['CITY', ner_counter['CITY']],
        ['LOCATION', ner_counter['LOCATION']],
        ['PERSON', ner_counter['PERSON']],
        ['ORGANIZATION', ner_counter['ORGANIZATION']],
        ['STATE_OR_PROVINCE', ner_counter['STATE_OR_PROVINCE']]]

    noun_deprel_stats = [['Noun DEPREL Tags', 'Frequencies'],
                         ['Object (obj)', deprel_counter['obj']],
                         ['Indirect object (iobj)', deprel_counter['iobj']],
                         ['Nominal subject (nsubj)', deprel_counter['nsubj']],
                         ['Nominal passive subject (nsubj:pass)', deprel_counter['nsubj:pass']],
                         ['Clausal subject (csubj)', deprel_counter['csubj']],
                         ['Clausal passive subject (csubj:pass)', deprel_counter['csubj:pass']]]

**Comment by bianshuyang** [comment]
[CoNLL_noun_analysis_util.py.zip](https://github.com/NLP-Suite/NLP-Suite/files/13451911/CoNLL_noun_analysis_util.py.zip)
