### ISSUE TITLE
Visualization GUI Error -- (Already resolved via email) 

### ISSUE THREAD

**Issue by jqian45** [NLP-Suite/NLP-Suite#1345]
![image](https://github.com/NLP-Suite/NLP-Suite/assets/144945114/8471696b-bdfb-42b0-a5a9-b29c5877a3fc)
![image](https://github.com/NLP-Suite/NLP-Suite/assets/144945114/5c9a54d2-a27b-4273-8f44-cb639ef54411)

I was trying to run the boxplot visualization GUI, but for some reason when I hit "run," I was unable to produce anything. I have successfully created a boxplot as an .html in the past. 
To replicate:
1. Select "Boxplots" (or any other visualization GUI from the drop down menu in the home GUI
2. Input all necessary information and hit "Run" to see...nothing!

**Comment by jqian45** [comment]
This issue was resolved via email -- Simon's suggestion: Please change data_visualization_2_main.py, line 477 to:

points_menu = tk.OptionMenu(window, points_var, 'all', 'None', 'outliers') Using any powerful text editor."

**Comment by bianshuyang** [comment]
Fixed.
