### ISSUE TITLE
Stanza Does Not Seem To Be Installed 

### ISSUE THREAD

**Issue by sengaungsein** [NLP-Suite/NLP-Suite#1360]
When trying to set up the NLP package and corpus language, the following pop up. 

**Stanza does not seem to be installed in your machine. The file-path

/Users/senga/stanza_resources/resources.json

could not be found.

Please, open  terminal, type conda activate NLP (Enter) and then type pip install stanza (Enter) and try again.**

" it is installed and still showing me this error.

**Comment by jacksonfang0205** [comment]
same issue

**Comment by sengaungsein** [comment]
I got the answer from Simon. 

python 
import stanza
stanza.download('en')

**Comment by jacksonfang0205** [comment]
Thank you so much!
