### ISSUE TITLE
Incorrectly identifies that there is no internet connection despite having one. 

### ISSUE THREAD

**Issue by jhyang21** [NLP-Suite/NLP-Suite#1361]
Upon opening the nlp suite, the following message pops up, even though I have internet connection:
![image](https://github.com/NLP-Suite/NLP-Suite/assets/24422126/dd11a878-7f82-4cb0-a99d-a2033d5bc744)

It seems like the bug has to do with "IO_internet_util.check_internet_availability_warning()" in "get_GitHub_release_version(silent = False)".

I have temporarily changed how "get_GitHub_release_version(silent = False)" check for internet connection on my end. Instead of using "IO_internet_util.check_internet_availability_warning()", I checked Internet connection to Google directly. This update fixed the bug on my end.
```
def get_GitHub_release_version(silent = False):
    # Temporarily bypass the internet check utility and directly test internet connectivity
    try:
        requests.get("http://www.google.com")
    except requests.ConnectionError:
        print("No internet connection available.")
        return '0.0.0'
    release_url = 'https://raw.githubusercontent.com/NLP-Suite/NLP-Suite/current-stable/lib/release_version.txt'
    try:
        GitHub_newest_release = requests.get(release_url).text
        GitHub_release_version_var.set(GitHub_newest_release)
    except Exception as e:
        if not silent:
            mb.showwarning(title='Internet connection error', 
                           message="The attempt to connect to GitHub failed with error: {}\n\nIt is not possible to check the latest release of the NLP Suite at this time. You can continue to run your current release and try again later.".format(e))
        GitHub_newest_release = '0.0.0'
    return GitHub_newest_release
 ```
    
    
    - Andrew Yang (SOC 446 student)

**Comment by JesNi523** [comment]
I have the same internet issue and could not use any function on NLP suite as a result. Andrew, would you please specify how or where I should apply your code?

**Comment by jhyang21** [comment]
> I have the same internet issue and could not use any function on NLP suite as a result. Andrew, would you please specify how or where I should apply your code?

You can edit the function in "GUI_util.py" in src folder.

**Comment by Emory-NLP** [comment]
How about simply changing from bing to google the internet_on function? If that works, without changing the get_GitHub_release_version function, I can push this change.
 
![image](https://github.com/NLP-Suite/NLP-Suite/assets/79026295/294d8957-ae48-41f9-b4a9-5ee0a6e0b3a6)

**Comment by jhyang21** [comment]
You are right, I didn't see IO_internet_util.py. That should fix the problem.

**Comment by Emory-NLP** [comment]
Would you mind trying? If that works, the problem was bing... and I will push the changes.

**Comment by jhyang21** [comment]
I've tried on my end, and it works for me.
