### ISSUE TITLE
AttributeError: 'ImageDraw' object has no attribute 'textsize', when running Python WordCloud on Mac

### ISSUE THREAD

**Issue by MatthewB2024** [NLP-Suite/NLP-Suite#1374]
When running Python WordCloud on my M1 Mac, I am getting an attribute error. I am not sure how to fix this. When I use a WordCloud service website such as Wordclouds or Wordle, I get the desired results. Please see the attached screenshots for further investigation. 

<img width="1418" alt="Screenshot 2024-01-27 at 7 38 24 PM" src="https://github.com/NLP-Suite/NLP-Suite/assets/157931067/28abc2c4-dd90-47f4-8d51-be65f69df81b">
![Screenshot 2024-01-27 at 7 38 39 PM](https://github.com/NLP-Suite/NLP-Suite/assets/157931067/862c129b-fdf7-4534-b784-34e279f2d827)
![Screenshot 2024-01-27 at 7 38 55 PM](https://github.com/NLP-Suite/NLP-Suite/assets/157931067/a93dd21f-f40f-49f9-8ea5-48e56b5d4885)

**Comment by bianshuyang** [comment]
https://github.com/NLP-Suite/NLP-Suite/issues/1372

**Comment by gabrielischwartz** [comment]
I am having the same issue.
