### ISSUE TITLE
NLP suite converting files erros (pdf to txt) 

### ISSUE THREAD

**Issue by sengaungsein** [NLP-Suite/NLP-Suite#1375]
Type Error

**Comment by sengaungsein** [comment]
![Uploading Screenshot 2024-01-28 at 9.09.17 PM.png…]()

**Comment by sengaungsein** [comment]
<img width="1440" alt="Screenshot 2024-01-28 at 9 09 17 PM" src="https://github.com/NLP-Suite/NLP-Suite/assets/145607641/22bdc36d-4cb4-45c6-93cd-88769ad1cf80">

**Comment by Emory-NLP** [comment]
Bug fixed in release 4.6.3
