### ISSUE TITLE
CORPUS/DOCUMENT Statistics Runtime Error

### ISSUE THREAD

**Issue by LouisLu00** [NLP-Suite/NLP-Suite#1376]
The NLP suite constantly gives me this run time error. 

![Screenshot 2024-01-28 at 9 11 43 PM](https://github.com/NLP-Suite/NLP-Suite/assets/87416327/a68a7983-b47f-4201-bf7e-488f5f97e933)

**Comment by bianshuyang** [comment]
What's the GUI interface when you run it?
