### ISSUE TITLE
Problem with step 2 

### ISSUE THREAD

**Issue by cpei22** [NLP-Suite/NLP-Suite#1382]
I've successfully passed the tests of running python and conda in step one and also installed git. Proceeded to step two and ran into this error message.  
![Screenshot 2024-01-29 141347](https://github.com/NLP-Suite/NLP-Suite/assets/112918264/818c84b1-ce63-4129-bee9-655045699cde)

However, the bottom message of step 2 still says installation completed

**Comment by bianshuyang** [comment]
You will do it manually. PS now doesn't work anymore. 
1.In terminal check if you have NLP by typing `conda env list`
2.1 If not you will need to open STEP2 by txt and type:
`conda create -n NLP python=3.8 -y`
`call conda activate NLP`
2.2  If you have NLP,  you need `conda install pytorch torchvision cudatoolkit -c pytorch`
3. Then manually click on the `src` folder in your NLP Suite current stable folder downloaded from `GitHub`. Make sure your terminal is in that folder, and type `pip install -r requirements.txt`. 
4. Then go back to the `setup_Windows` and copy past from the following. Press enter when needed.
`git init ..`
`git remote add -m current-stable -f origin https://github.com/NLP-Suite/NLP-Suite.git`
`git checkout -f current-stable`
`git add -A .`
`git stash`
`git pull -f origin current-stable`
5. Then run the run bat and it should be set.

**Comment by bianshuyang** [comment]
If not then make appointment: https://calendly.com/simonbian/nlpinstall

**Comment by bianshuyang** [comment]
I have helped Christopher in today's Zoom session.
