### ISSUE TITLE
having issue merging files

### ISSUE THREAD

**Issue by JesNi523** [NLP-Suite/NLP-Suite#1384]
Per the requirement for using wordcloud on the web, we can only upload one file to be analyzed. As Professor Franzosi suggested, I would have to use the file merger under the pre-processing tool to do this. 
However when I try to run this tool, it does not execute. The error message says:

![image](https://github.com/NLP-Suite/NLP-Suite/assets/122462035/d9ad3080-7d70-4495-85b1-22e313c1a78b)

**Comment by bianshuyang** [comment]
Do you wish to merge multiple txts into one? Here's a command that can be helpful.
`cat *.txt >> total.txt` (that would direct all .txt to a single file called total.txt)
It could be ">" or ">>" depending on the type of windows.

**Comment by Emory-NLP** [comment]
Fixed bug in release 4.6.4.

**Comment by JesNi523** [comment]
> Do you wish to merge multiple txts into one? Here's a command that can be helpful. `cat *.txt >> total.txt` (that would direct all .txt to a single file called total.txt) It could be ">" or ">>" depending on the type of windows.

Thank you Simon! That worked. 

One minor change: the cat command would work for Linux and macOS. For window users like myself, we would use 'type' command to carry out this action.

**Comment by JesNi523** [comment]
> Fixed bug in release 4.6.4.

When I tried to get the latest release by closing the NLP and hoped for automatic update, NLP decided to tell me this:

![image](https://github.com/NLP-Suite/NLP-Suite/assets/122462035/4373f4e3-c26b-4051-af67-c8353a4170a6)

What might be the issue here?

**Comment by bianshuyang** [comment]
[git_ensure.bat.zip](https://github.com/NLP-Suite/NLP-Suite/files/14125396/git_ensure.bat.zip)
Hi, could you try unzip the attached, place it in Setup_Windows, and run only the git_ensure.bat?
![image](https://github.com/NLP-Suite/NLP-Suite/assets/52821055/4241fa1f-26a8-4ab7-b048-36e0b7d8b4ba)

Thanks!
