### ISSUE TITLE
Topic Modeling GUI: Gensim tool says it needs Spacy 

### ISSUE THREAD

**Issue by sgluong** [NLP-Suite/NLP-Suite#1395]
On the Topic Modeling GUI, I keep getting this message when I hit run. I have tried to install Spacy, and I have entered the command python -m spacy download en_core_web_sm. As you can see in the screenshot, it says that download was successful and I can now load the package, but I am still unable to run the Topic Modeling. Any help would be much appreciated! 

<img width="1346" alt="Screenshot 2024-02-05 at 9 15 51 PM" src="https://github.com/NLP-Suite/NLP-Suite/assets/156851450/a245daba-dcd9-49eb-84e0-a72c403d19f3">
<img width="1166" alt="Screenshot 2024-02-05 at 9 16 04 PM" src="https://github.com/NLP-Suite/NLP-Suite/assets/156851450/4c396613-da33-4807-95bb-e3705d8e99d6">
<img width="517" alt="Screenshot 2024-02-05 at 9 16 47 PM" src="https://github.com/NLP-Suite/NLP-Suite/assets/156851450/f17b8585-25a6-4aac-871b-1a4186cdbcc2">

**Comment by bianshuyang** [comment]
I see you are doing at base not NLP here.
Did you conda activate NLP?

**Comment by sgluong** [comment]
Got it now! Thank you!
