### ISSUE TITLE
File search by words

### ISSUE THREAD

**Issue by Emory-NLP** [NLP-Suite/NLP-Suite#1397]
The file search by words

![image](https://github.com/NLP-Suite/NLP-Suite/assets/79026295/4a6122f8-6141-426d-96dc-6b166e5a7ec8)
with the NYT book reviews fails to find at least 2 instances of "white house" when searching for the word "house" and -K=1.
Furthermore, in output, some document hyperlinks are set incorrectly.
 
![image](https://github.com/NLP-Suite/NLP-Suite/assets/79026295/da305e01-61be-4eed-9406-322712081c85)

**Comment by bianshuyang** [comment]
1. The case sensitive is not included previously. Attached is a version.
 [file_search_byWord_util.py.zip](https://github.com/NLP-Suite/NLP-Suite/files/14187078/file_search_byWord_util.py.zip)
