### ISSUE TITLE
Failure to create properly formatted CSV file from File Search by Single Word or Collocations

### ISSUE THREAD

**Issue by MatthewB2024** [NLP-Suite/NLP-Suite#1401]
The CSV file contains an improperly formatted table as the second row contains titles instead of observations and there are also empty/incorrectly labeled columns. Since this table is formatted incorrectly, this CSV file yields empty visuals when used as the input for various visualization tools.

<img width="1333" alt="Screenshot 2024-02-07 at 7 43 30 PM" src="https://github.com/NLP-Suite/NLP-Suite/assets/157931067/4c89b898-54ef-4bd3-b0e3-f6ced964b8ee">
<img width="1341" alt="Screenshot 2024-02-07 at 7 42 32 PM" src="https://github.com/NLP-Suite/NLP-Suite/assets/157931067/966be6eb-f167-452f-8bfe-a8e7c0016265">
<img width="1123" alt="Screenshot 2024-02-07 at 7 43 09 PM" src="https://github.com/NLP-Suite/NLP-Suite/assets/157931067/2ba10d21-a39b-4fc9-b773-1feac082e31c">
<img width="695" alt="Screenshot 2024-02-07 at 7 42 13 PM" src="https://github.com/NLP-Suite/NLP-Suite/assets/157931067/8887dbc1-56fc-4622-ba9f-84a55d7c317a">

**Comment by bianshuyang** [comment]
In file_search_by_Word_util.py:
Add the below 2 lines into the original code.
original:

```
    if (not (minus_K_words_var and plus_K_words_var)):
        with open(outputFilename, "a", newline="", encoding='utf-8', errors='ignore') as csvFile:
            # something something below...
```

New

```
    if (not (minus_K_words_var and plus_K_words_var)):
        with open(outputFilename, 'w') as f:
            f.write("") # flushing
        with open(outputFilename, "a", newline="", encoding='utf-8', errors='ignore') as csvFile:
            # something something below...
```

**Comment by Emory-NLP** [comment]
That unfortunately does not solve the problem

![image](https://github.com/NLP-Suite/NLP-Suite/assets/79026295/e87f0b59-8b81-43ed-a3e6-980e0d491618)
