### ISSUE TITLE
Issue of Word embedding via Bert 

### ISSUE THREAD

**Issue by whyooooo** [NLP-Suite/NLP-Suite#1406]
<img width="564" alt="Screenshot 2024-02-14 at 12 07 22 PM" src="https://github.com/NLP-Suite/NLP-Suite/assets/144286074/761633a3-b473-4994-b03f-33c8433ac3e4">
When I try to compute the word distance with specific words, the terminal turns out with this error and couldn't complete the work.

**Comment by Emory-NLP** [comment]
Please, add the image of the GUI with all the options you are running.

**Comment by whyooooo** [comment]
> Please, add the image of the GUI with all the options you are running.
<img width="1159" alt="Screenshot 2024-02-14 at 1 00 42 PM" src="https://github.com/NLP-Suite/NLP-Suite/assets/144286074/4a290cb7-c5c5-4b03-8343-6549f8c985bb">
