### ISSUE TITLE
Issue of Bert Word Embedding Model

### ISSUE THREAD

**Issue by LouisLu00** [NLP-Suite/NLP-Suite#1407]
![Screenshot 2024-02-18 at 1 39 17 PM](https://github.com/NLP-Suite/NLP-Suite/assets/87416327/aa00ef0b-edbf-47a3-bf7a-46e3085e3ff1)

When i tried to run the Bert Modelling in the word-embedding model GUI, it asks me to install the tensorflow package. However, I cannot open the GUI after installing it.

**Comment by henryxu21** [comment]
![8031708281741_ pic](https://github.com/NLP-Suite/NLP-Suite/assets/156882767/f1891abd-f568-4b5e-a65c-3dbbbbe3b73d)

**Comment by Emory-NLP** [comment]
As the instructions say, please, upload the image of the GUI you are using so that we know what machine you are using

**Comment by henryxu21** [comment]
<img width="1351" alt="Screenshot 2024-02-18 at 2 02 25 PM" src="https://github.com/NLP-Suite/NLP-Suite/assets/156882767/8e17e804-8731-4ba3-91eb-7785071c8bfe">

**Comment by henryxu21** [comment]
i am using Mac, and 4.6.7/4.6.9 release

**Comment by Emory-NLP** [comment]
Are you free to Zoom? https://emory.zoom.us/my/franzosi
