### ISSUE TITLE
ConLL table analyzer I/O configuration error

### ISSUE THREAD

**Issue by gabrielischwartz** [NLP-Suite/NLP-Suite#1419]
<img width="258" alt="Screen Shot 2024-03-01 at 2 34 09 PM" src="https://github.com/NLP-Suite/NLP-Suite/assets/156736610/30ee328d-988b-4d42-adc2-032e5e2578d7"> Error Message

<img width="1357" alt="Screen Shot 2024-03-01 at 5 59 09 PM" src="https://github.com/NLP-Suite/NLP-Suite/assets/156736610/e56964a2-1bd8-433d-867b-be12765b3cf3"> Main menu selection that took me there

<img width="1354" alt="Screen Shot 2024-03-01 at 6 00 14 PM" src="https://github.com/NLP-Suite/NLP-Suite/assets/156736610/39bae424-debb-4e48-92aa-8ede0569f7d8"> GUI where the I/O selection isn't working

<img width="462" alt="Screen Shot 2024-03-01 at 6 03 37 PM" src="https://github.com/NLP-Suite/NLP-Suite/assets/156736610/ec430614-7f26-4e23-92cb-9923fa04e05b"> conll_table_analyzer_config.csv

The ConLL table analyzer gives me this error message every time I try to change the Input/Output configuration setting. I need to put the ConLL table into the input to perform analysis on it, but after I clear this error the Input/Output menu does not appear.

**Comment by Emory-NLP** [comment]
Could you add all the screenshots for all he GUIs you are sing?
Can you also add the screenshot of the CoNLL_table_analyzer_config.cvs?

**Comment by gabrielischwartz** [comment]
Just added the images. Please let me know if theres anything else I should add.

**Comment by Emory-NLP** [comment]
"after I clear this error the Input/Output menu does not appear." I need to see the screenshot where this menu does not appear. Also, can you widen the headers of the conll_table_analyzer_config.csv?

**Comment by gabrielischwartz** [comment]
<img width="1416" alt="Screen Shot 2024-03-02 at 10 08 03 AM" src="https://github.com/NLP-Suite/NLP-Suite/assets/156736610/5481b627-4f7b-4cc6-be7d-c39a1eedcfd9">

**Comment by gabrielischwartz** [comment]
> "after I clear this error the Input/Output menu does not appear." I need to see the screenshot where this menu does not appear. Also, can you widen the headers of the conll_table_analyzer_config.csv?

The error message I showed above is what appears and then the I/O menu does not appear. I don't know how I should screenshot the menu not appearing.

**Comment by whyooooo** [comment]
I encountered the same error message as the screenshots. How should I fixed it?

**Comment by Emory-NLP** [comment]
I would need to Zoom to see your error. I cannot reproduce the error.

**Comment by gabrielischwartz** [comment]
The new NLP Suite Update fixed this issue.
