### ISSUE TITLE
Clause analysis on CoNLL Table

### ISSUE THREAD

**Issue by gabrielischwartz** [NLP-Suite/NLP-Suite#1427]
When running a clause analysis on a CoNLL table the NLP Suite Instantly runs and there is no output.

https://github.com/NLP-Suite/NLP-Suite/assets/156736610/0e5187ab-2922-471d-a467-34d197059ac2

**Comment by Emory-NLP** [comment]
What do reminders, TIPS, ?HELP say about Clause Analysis and neural network models?
