### ISSUE TITLE
BERT Word2Vec model

### ISSUE THREAD

**Issue by sengaungsein** [NLP-Suite/NLP-Suite#1435]
Started running BERT Word2Vec model on 298090 words at Thu Mar 14 23:34:50 2024

Finished running BERT Word2Vec model exporting 17378 non-distinct words at Thu Mar 14 23:41:56 2024

Started preparing charts via t-SNE for 17378 non-distinct words at Thu Mar 14 23:41:56 2024
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

**Comment by sengaungsein** [comment]
The program does not execute after this command prompt error. I have to forced close the program.

**Comment by sengaungsein** [comment]
{'text/html': '        <script type="text/javascript">\n        window.PlotlyConfig = {MathJaxConfig: \'local\'};\n        if (window.MathJax && window.MathJax.Hub && window.MathJax.Hub.Config) {window.MathJax.Hub.Config({SVG: {font: "STIX-Web"}});}\n        if (typeof require !== \'undefined\') {\n        require.undef("plotly");\n        requirejs.config({\n            paths: {\n                \'plotly\': [\'https://cdn.plot.ly/plotly-2.16.1.min\']\n            }\n        });\n        require([\'plotly\'], function(Plotly) {\n            window._Plotly = Plotly;\n        });\n        }\n        </script>\n        '}
Exception in Tkinter callback
Traceback (most recent call last):
  File "/Users/senga/anaconda/envs/NLP/lib/python3.8/tkinter/__init__.py", line 1892, in __call__
    return self.func(*args)
  File "word2vec_main.py", line 101, in <lambda>
    run_script_command=lambda: run(GUI_util.inputFilename.get(),
  File "word2vec_main.py", line 90, in run
    filesToOpen = word2vec_Gensim_util.run_Gensim_word2vec(inputFilename, inputDir, Word2Vec_Dir, config_filename, openOutputFiles, chartPackage, dataTransformation,
TypeError: run_Gensim_word2vec() got an unexpected keyword argument 'diachronic'

**Comment by sengaungsein** [comment]
Gensim also dose not works.

**Comment by Emory-NLP** [comment]
In all of the Issues raised there is screenshot of the GUI used so do not know which released you are using.

**Comment by sengaungsein** [comment]
I used 4.7.3
