### ISSUE TITLE
NLP Geocoding Tip File Missing 

### ISSUE THREAD

**Issue by sengaungsein** [NLP-Suite/NLP-Suite#1441]
<img width="372" alt="Screenshot 2024-03-22 at 4 18 38 PM" src="https://github.com/NLP-Suite/NLP-Suite/assets/145607641/2bae54ba-48e4-4610-9c91-31f0698e4195">

**Comment by sengaungsein** [comment]
It is only missing when you go to CSV - Map , not in the GUI of text to map.

**Comment by Emory-NLP** [comment]
PLEASE! Seng, ALWAYS upload a screenshot of the GUI you are using.
