### ISSUE TITLE
Issue with Sentence Complexity Analyzer

### ISSUE THREAD

**Issue by sgluong** [NLP-Suite/NLP-Suite#1458]
When trying to run the Sentence Complexity analysis, I get this error. 

<img width="1247" alt="Screenshot 2024-04-12 at 2 42 26 PM" src="https://github.com/NLP-Suite/NLP-Suite/assets/156851450/6801c8c8-7770-4fba-acf1-8ea0398b505b">
<img width="651" alt="Screenshot 2024-04-12 at 2 42 37 PM" src="https://github.com/NLP-Suite/NLP-Suite/assets/156851450/97b8edfa-ad4d-466d-9912-c03a402da3af">

**Comment by whyooooo** [comment]
<img width="466" alt="Screenshot 2024-04-12 at 9 00 56 PM" src="https://github.com/NLP-Suite/NLP-Suite/assets/144286074/2b85309f-ce3b-4b9e-82bc-47bae9cfccf7">
I have the same issue

**Comment by gabrielischwartz** [comment]
I am having the same issue
