### ISSUE TITLE
Issue with Nominalization

### ISSUE THREAD

**Issue by whyooooo** [NLP-Suite/NLP-Suite#1459]
<img width="506" alt="Screenshot 2024-04-12 at 9 01 29 PM" src="https://github.com/NLP-Suite/NLP-Suite/assets/144286074/db617e32-d80d-4e5b-85a5-8cda99d1302a">
When run the Nominalization function, the above issue occurred.

**Comment by sgluong** [comment]
I got the same issue with nominalization.

**Comment by tdavisshelton** [comment]
Howdy Sarah and NPL Suite Team. I was trying to run this tool and have run into the same issue.

**Comment by tdavisshelton** [comment]
![NLPSuite_Nominalization_04 13 2024](https://github.com/NLP-Suite/NLP-Suite/assets/104233326/0cef98af-9232-44ab-89b8-db050b9a392a)
![NLPSuite_Nominalization_04 13 2024_2](https://github.com/NLP-Suite/NLP-Suite/assets/104233326/c016d338-a7e8-4c8b-ad16-1218bb40ccc4)
![NLPSuite_Nominalization_04 13 2024_3](https://github.com/NLP-Suite/NLP-Suite/assets/104233326/480b47d0-477b-40f4-a3bb-1b62f57ff02e)

**Comment by gabrielischwartz** [comment]
I am having the same issue with nominalization

**Comment by shawnchen03** [comment]
The exact Issue here from Jessie & Shawn's group. Can't run it still.

**Comment by averyrosen** [comment]
We also had the same issue.
<img width="632" alt="Screenshot 2024-04-14 at 8 35 07 PM" src="https://github.com/NLP-Suite/NLP-Suite/assets/103871341/b4db54f3-43a0-41d2-8fca-0eff170534d4">
