### ISSUE TITLE
Sentence complexity error 

### ISSUE THREAD

**Issue by henryxu21** [NLP-Suite/NLP-Suite#1465]
<img width="1071" alt="Screenshot 2024-04-15 at 1 52 33 PM" src="https://github.com/NLP-Suite/NLP-Suite/assets/156882767/dbc1e194-fb04-469f-9a2e-9cbc9a4c0984">

Readability works, however, sentence complexity does not work.

**Comment by Emory-NLP** [comment]
You are using a VERY old release, 4.7.5, when we are currently at 4.8.2, as shown here
![image](https://github.com/NLP-Suite/NLP-Suite/assets/79026295/2f343da8-df09-4eec-86b9-2c3a45add8d5)
The problem has been solved.
