### ISSUE TITLE
spaCy not available

### ISSUE THREAD

**Issue by whyooooo** [NLP-Suite/NLP-Suite#1473]
Regarding the rubric for HW6, the function of using spaCy for CoNLL table analyzer is still not working with spaCy. As the screenshots shows, it is only working with Stanza. 
<img width="1208" alt="Screenshot 2024-04-17 at 9 44 18 PM" src="https://github.com/NLP-Suite/NLP-Suite/assets/144286074/89e0dbf4-3514-4ae9-80fe-a1aaac3c4d8b">
<img width="1230" alt="Screenshot 2024-04-17 at 9 44 30 PM" src="https://github.com/NLP-Suite/NLP-Suite/assets/144286074/94a0397d-8d39-4118-bf46-393727fc999e">

**Comment by Emory-NLP** [comment]
This is not an error. Only Stanza is available in the NLP Suite for basic functions, notably tokenization and lemmatization.  For more complex functions, NER, parsers, sentiment, all packages are available.
