### ISSUE TITLE
Issue running parser to generate conll table

### ISSUE THREAD

**Issue by khuang18** [NLP-Suite/NLP-Suite#1493]
Here is the GUI I am working in: 
<img width="1349" alt="Screenshot 2024-07-09 at 6 14 44 PM" src="https://github.com/NLP-Suite/NLP-Suite/assets/90067390/3b4a7f9d-a531-4626-9dd5-85aef7acfe0b">

Here is the error message after the gui appears to run for a while, before breaking: 
<img width="818" alt="Screenshot 2024-07-09 at 6 14 15 PM" src="https://github.com/NLP-Suite/NLP-Suite/assets/90067390/f3c0d013-a4d7-4406-80a5-589666e90e9b">
<img width="815" alt="Screenshot 2024-07-09 at 6 14 32 PM" src="https://github.com/NLP-Suite/NLP-Suite/assets/90067390/43f60d0a-a709-4dbc-8dfe-b2d5bbc616c9">

Tried multiple times and got consistent error after a while; I don't think this can be resolved by re-running GUI. 

Here is the INPUT/OUTPUT settings: 
<img width="1351" alt="Screenshot 2024-07-09 at 6 15 00 PM" src="https://github.com/NLP-Suite/NLP-Suite/assets/90067390/b914d156-660e-4c7d-970f-44e3eff440ba">
<img width="852" alt="Screenshot 2024-07-09 at 6 15 16 PM" src="https://github.com/NLP-Suite/NLP-Suite/assets/90067390/91041175-8733-4274-af1f-be0e1a629015">

**Comment by Emory-NLP** [comment]
Kevin, the very first error says that there is a connection problem with the Stanford CoreNLP server. Try again tomorrow. It happens sometimes. Roberto

![image](https://github.com/NLP-Suite/NLP-Suite/assets/79026295/4f435e1f-0f88-4079-81d7-86c62b8f4175)
