### ISSUE TITLE
Merge files using different field names

### ISSUE THREAD

**Issue by DDVD233** [NLP-Suite/NLP-Suite#203]
We will need to check that

1. the same number of fields is selected for each selected merged file
2. the data types are correspondingly the same (and should probably be numeric)
the field names, I suppose, do not necessarily have to be exactly the same (Document ID, Document ID); could be Document ID, Doc_ID, as long as they correspond

**Comment by Emory-NLP** [comment]
1. the data types should be numeric
2. the field names do not necessarily have to be the same as long as they correspond
