### ISSUE TITLE
[BUG]: about not able to run anything "[main] INFO CoreNLP - StanfordCoreNLPServer listening at /[0:0:0:0:0:0:0:0]:9000"

### ISSUE THREAD

**Issue by chenyingying0402** [NLP-Suite/NLP-Suite#214]
**Describe the bug**
This bug makes me not able to run any of the tools in the nlpsuite. The terminal just remains in this stage.

**To Reproduce**
For any tools, click run and then I will get this error message. For example, this time I chose to run sentiment analysis with the default setting. It couldn't work at all.

**Screenshots**
<img width="729" alt="截屏2021-04-04 下午12 57 23" src="https://user-images.githubusercontent.com/37049722/113499090-c8424380-9545-11eb-8d55-808b604c86e5.png">

**Desktop (please complete the following information):**
 - MAC
 - latest released version at the github

**Additional context**
Professor said the bug was fixed but I don't know why it appears in my computer. Now I couldn't use the nlpsuite to do my homework.

**Comment by RafaelPiloto10** [comment]
Duplicate to #219. Closing for now
