### ISSUE TITLE
[BUG]: No Such File or Directory

### ISSUE THREAD

**Issue by knroebuck** [NLP-Suite/NLP-Suite#215]
**Describe the bug**
I am using the AJS corpus and attempting to run SVO. It appears that when running Stanford_CoreNLP_annotator_util.py for the COREF annotator, it gives a 'no such file or directory' error when calling the first file of my corpus.

**To Reproduce**
1. Open NLP Suite
2. Click Enter NLP Suite
3. Click Run CORPUS/DOCUMENT Analysis Tools
4. Scroll down to SVO extractor and visualization
5. Run
6. Unclick utf-8 encoding check (complete GUI with all inputs screenshot below)
7. Run 

**Screenshots**
Inputs:
![Screenshot (476)](https://user-images.githubusercontent.com/63971557/113502729-277b6600-94fc-11eb-8e42-0f86b70552ff.png)

Error:
![Screenshot (477)](https://user-images.githubusercontent.com/63971557/113502737-3a8e3600-94fc-11eb-8baa-49a6a967f54c.png)

**Desktop (please complete the following information):**
 - Windows 10
 - Release Version (type `NLP --version` e.g. 22) - I typed NLP --version and it just keep re-opening the NLP anaconda prompt but didn't give a number.

**Additional context**

**Comment by Emory-NLP** [comment]
Are you using the most recent version of the NLP Suite? This issue was solved a few days prior to your post. Please, try again.
