### ISSUE TITLE
[BUG]: the algorithm could not find the wordnet

### ISSUE THREAD

**Issue by KaheiH1104** [NLP-Suite/NLP-Suite#218]
**Describe the bug**
I have downloaded Wordnet on my machine and put it in the NLP folder. When I tried to run sentiment analysis, the program fails to find WordNet. After the program ends, only CoreNLP analysis is shown in the output directory. To locate WordNet as prompted, I have tried "import nltk, nltk.download('wordnet')" in my terminal(src folder, under NLP environment), but it seems like I type it in the wrong manner and the machine cannot identify the command. 

**Screenshots**
<img width="849" alt="Screen Shot 2021-04-05 at 01 45 01 AM" src="https://user-images.githubusercontent.com/63899121/113517860-1b071400-95b5-11eb-8b56-cb2d082810f6.png">
<img width="710" alt="Screen Shot 2021-04-05 at 01 43 05 AM" src="https://user-images.githubusercontent.com/63899121/113517865-24907c00-95b5-11eb-9cdf-d2b461dd0a9c.png">
<img width="852" alt="Screen Shot 2021-04-05 at 01 39 50 AM" src="https://user-images.githubusercontent.com/63899121/113517869-28240300-95b5-11eb-888f-6779ede48a27.png">
<img width="591" alt="Screen Shot 2021-04-05 at 02 29 53 AM" src="https://user-images.githubusercontent.com/63899121/113518136-ebf1a200-95b6-11eb-8444-f209c6bd8ac0.png">

**Desktop (please complete the following information):**
 - Mac
 - newest version on Github

**Additional context**

**Comment by RafaelPiloto10** [comment]
The commands you tried should be run under the python interpreter. Try the following:

- Open a new terminal
- If you have the NLP Shortcut installed, type `nlp` to activate your environment. Otherwise type, `conda activate NLP`
- Next, type `python3`
- Next type the following commands one by one:
```python
import nltk
nltk.download("wordnet")
exit()
```

Then try again.

**Comment by Emory-NLP** [comment]
The WordNet you download from Princeton is separate from the NLTK WordNet download. 
1. If the NLTK data download fails, in command line type: python -m nltk.downloader all
2. In any case, do NOT put WordNet inside the NLP folder or it will be erased when you upgrade the NLP Suite from GitHub. All external software should be placed outside the NLP folder.

**Comment by KaheiH1104** [comment]
it works thanks
