### ISSUE TITLE
[BUG]: Sentiment Analysis - Stanford Core NLP (the first one) does not work

### ISSUE THREAD

**Issue by chenyingying0402** [NLP-Suite/NLP-Suite#219]
**Describe the bug**
A clear and concise description of what the bug is. Please indicate what corpus you are using.

**To Reproduce**
1. Go to 'Sentiment Analysis'
2. Click on 'Algorithms' - the first one - stanford core nlp
3. See error message in the terminal

**Screenshots**
![WechatIMG444](https://user-images.githubusercontent.com/37049722/113519724-9e7a3280-95c0-11eb-958b-7dd981bf5d6b.jpeg)

**Desktop (please complete the following information):**
 - MAC
 - latest version on the Github 

**Additional context**
Thanks

**Comment by RafaelPiloto10** [comment]
Hi, could you confirm the following information:

- Are you in China?
- Are you using a VPN?
- Paste the contents found in your `software_config.csv` file. It can be found in NLP Folder -> config -> software_config.csv

**Comment by chenyingying0402** [comment]
Software | Path | Download_link
-- | -- | --
Stanford CoreNLP | /Users/yingyingchen/Desktop/NLP-Suite-current-stable/stanford-corenlp-4.2.0 | https://nlp.stanford.edu/software/stanford-corenlp-latest.zip
Mallet | /Users/yingyingchen/Desktop/NLP-Suite-current-stable/mallet-2.0.8 | http://mallet.cs.umass.edu/download.php
SENNA | /Users/yingyingchen/Desktop/NLP-Suite-current-stable/senna | https://ronan.collobert.com/senna/download.html
WordNet | /Users/yingyingchen/Desktop/NLP-Suite-current-stable/WordNet-3.0 | https://wordnet.princeton.edu/download/current-version

**Comment by RafaelPiloto10** [comment]
Thank you for that information. Please make sure to answer the other remaining questions if this issue has not been resolved yet. Also, it is highly recommended that you do **NOT** place external software within the NLP Suite folder. It **is recommended** that you place your external software in a separate folder outside of NLP.

**Comment by chenyingying0402** [comment]
I am in China and use the VPN. Thanks for your information.

**Comment by chenyingying0402** [comment]
Ok I will try to move to a separate folder outside of NLP.
