### ISSUE TITLE
[BUG]: Sentiment Analysis Error: Cannot handle Incoming Annotation

### ISSUE THREAD

**Issue by CeliaHu1220** [NLP-Suite/NLP-Suite#227]
**Describe the bug**
I was running sentiment analysis with Stanford CoreNLP, but got an error message saying "could not handle incoming annotation". My corpus is a short and small txt file (only 20kb), in utf-8 format.

**To Reproduce**
1. Go to 'Sentiment Analysis'
2. Click on 'Select Sentiment Analysis algorithm : Stanford CoreNLP'
3. Hit run

**Screenshots**
Add screenshots to help explain your problem and indicate the error.
![image](https://user-images.githubusercontent.com/60986118/113762449-961c1780-96e6-11eb-9459-06f3136d26e1.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Release Version: latest version

**Additional context**
I was able to run Sentiment Analysis (Stanford CoreNLP) for certain corpus, but when I tried it with a different text file, I got the error message.

**Comment by DDVD233** [comment]
Can you send me the text file which gives the issue? If it works for other corpora but not this one then there may be an issue with this corpus.
