### ISSUE TITLE
[BUG]: Error of generating graphs in the shape of the story

### ISSUE THREAD

**Issue by chenyingying0402** [NLP-Suite/NLP-Suite#230]
**Describe the bug**
After running for 7 hours to process all the files, corenlp failed to generate the shape of stories. Before generating, it asked me to choose the appropriate number like 5 and 10 (sorry I forgot what the numbers were for).
This is what I got for right now. 

<img width="382" alt="截屏2021-04-09 上午12 24 02" src="https://user-images.githubusercontent.com/37049722/114062830-8826ec00-98ca-11eb-97fa-5ed90795a8ef.png">

**To Reproduce**
1. Go to 'Sentiment Analysis' - 'Shape of stories visualization' - 'stanford corenlp algorithm'
<img width="1100" alt="截屏2021-04-09 上午12 23 51" src="https://user-images.githubusercontent.com/37049722/114062726-6af21d80-98ca-11eb-82e6-399b29dd51e3.png">

**Screenshots**
<img width="762" alt="截屏2021-04-09 上午12 23 41" src="https://user-images.githubusercontent.com/37049722/114062780-7cd3c080-98ca-11eb-9333-c279aeac508e.png">

**Desktop (please complete the following information):**
 - MAC
 - latest version 

**Additional context**
Thanks

**Comment by Flora-Chen6** [comment]
Same error message without ticking "compute and visualize statistics" and "best topic estimation", selected the recommended 5 and 10. But I got only speed assessment as output.

**Comment by kguan2** [comment]
I met the same error as well

**Comment by CeliaHu1220** [comment]
Same error. And I made sure that I had the most updated version of the suite

**Comment by Emory-NLP** [comment]
The latest release should have solved the problems. Please, also always report the release number you are using.
