### ISSUE TITLE
[BUG]: Index 0 is out of bounds for axis 0 with size 0

### ISSUE THREAD

**Issue by StarLiu1** [NLP-Suite/NLP-Suite#234]
Corpus: State of the Union Address

To reproduce: run suite, input text file directory, check all the boxes for shape of story

<img width="478" alt="Screen Shot 2021-04-10 at 5 17 24 PM" src="https://user-images.githubusercontent.com/44296551/114284822-9f77ed80-9a20-11eb-9c4f-fe49d3ca5c8d.png">

Macbook pro: 10.15.4

**Comment by Emory-NLP** [comment]
The newest release should check for empty sentiment analysis scores.
