### ISSUE TITLE
[BUG]: Nominalization Error: pywsd

### ISSUE THREAD

**Issue by jsw031** [NLP-Suite/NLP-Suite#240]
**Describe the bug**
Corpus: Inaugural Addresses
The NLP suite required me to install pywsd before running the Nominalization. After I used pip install pywsd on my terminal and successfully install it, the NLP suite still shows missing that module. 

**Screenshots**
<img width="553" alt="Screen Shot 2021-04-15 at 00 41 19" src="https://user-images.githubusercontent.com/81481325/114750452-940d2500-9d86-11eb-9c2b-3941f2cab628.png">
<img width="568" alt="Screen Shot 2021-04-15 at 01 08 23" src="https://user-images.githubusercontent.com/81481325/114750958-24e40080-9d87-11eb-83aa-c118259fef44.png">

**Desktop (please complete the following information):**
 - OS: [OS X]
 - Release Version (the newest release)

**Comment by zoneli13** [comment]
I am having this same problem when I tried just now.
![Screen Shot 2021-04-15 at 10 34 04 AM](https://user-images.githubusercontent.com/44302000/114887090-1cff7d00-9dd6-11eb-9747-55c8a873cb8a.png)
That is the error that shows up for me.
OS: macOS Catalina

**Comment by Emory-NLP** [comment]
According to web error reporting, try the command (to upgrade wn)
pip install -U pywsd

**Comment by zoneli13** [comment]
This did not work for me. I already have pywsd installed as well. The same error as above appeared.

**Comment by jsw031** [comment]
I tried this command : pip install -U pywsd
It is still not working.

**Comment by RafaelPiloto10** [comment]
Error has already been resolved in a duplicate post: https://github.com/NLP-Suite/NLP-Suite/issues/247

Closing this issue
