### ISSUE TITLE
[BUG]: Can't open Normalization due to the lack of "pywsd"

### ISSUE THREAD

**Issue by chenyingying0402** [NLP-Suite/NLP-Suite#247]
**Describe the bug**
I could not open "normalization" in the NLP suite. Even after I have already installed pywsd package in the terminal, the error message still showed up.

**To Reproduce**
Just open the GUI and click "normalization", the error message will pop out.

**Screenshots**
<img width="971" alt="截屏2021-04-17 上午8 43 42" src="https://user-images.githubusercontent.com/37049722/115097930-a8584a00-9f5f-11eb-9ad0-44bfdc2c2b81.png">
![9471618620446_ pic_hd](https://user-images.githubusercontent.com/37049722/115097938-b3ab7580-9f5f-11eb-97d5-7bbc5078d3dc.jpg)

**Desktop (please complete the following information):**
 - MAC
 - latest version

**Additional context**
thanks

**Comment by chenyingying0402** [comment]
sorry typo, it should be "nominalization" instead of "normalization"

**Comment by Emory-NLP** [comment]
According to web error reporting, try the command (to upgrade wn)
pip install -U pywsd

**Comment by chenyingying0402** [comment]
Hi, I still got the same result. It said I already satisfied the requirement. I am still not able to open nominalization.

**Comment by kai-ovo** [comment]
Our group has the same error (after trying the suggested action).

**Comment by CeliaHu1220** [comment]
Same issue (made sure that we've installed the required package)

**Comment by rbeauvi** [comment]
I'm having the same issue (after trying suggestions)

**Comment by jinahyejin** [comment]
Hi! I fixed my error by specifying the package version by saying pip install pywsd==1.0.4 and the NLP seemed to work.

**Comment by chenyingying0402** [comment]
> Hi! I fixed my error by specifying the package version by saying pip install pywsd==1.0.4 and the NLP seemed to work.

Thx! worked for me

**Comment by chenyingying0402** [comment]
> > Hi! I fixed my error by specifying the package version by saying pip install pywsd==1.0.4 and the NLP seemed to work.
> 
> Thx! worked for me

But then I encountered a new error in nominalization

**Comment by RafaelPiloto10** [comment]
pywsd has a [dependency conflict](https://github.com/alvations/pywsd/pull/63) that is currently[ in the process of being patched](https://github.com/alvations/pywsd/pull/63/commits/591d388f5e30817701e9eea9371a37db35f1f361). For now, the `pywsd` issue can be fixed manually by downgrading your **wn** version:

`pip install wn==0.0.23`

**Leaving this issue open for now so that other students can see this solution**
