### ISSUE TITLE
[BUG]: TypeError error in Normalization

### ISSUE THREAD

**Issue by CeliaHu1220** [NLP-Suite/NLP-Suite#248]
**Describe the bug**
I got a "TypeError" when running my files in the normalization function.
**The complete error message:**
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\10316\anaconda3\lib\tkinter\__init__.py", line 1883, in __call__
    return self.func(*args)
  File "nominalization_main.py", line 352, in <lambda>
    run_script_command=lambda: run(GUI_util.inputFilename.get(),
  File "nominalization_main.py", line 334, in run
    Excel_outputFilename=Excel_util.create_excel_chart(GUI_util.window, [counter_nominalized_list], output_filename_dir_nominalized_frequencies,outputDir,'NOM_verb'
TypeError: create_excel_chart() missing 1 required positional argument: 'chart_type_list'

**To Reproduce**
1. Go to Corpus/Document Analysis Tools
2. Select Normalization
3. Input the file directory and hit run

**Screenshots**
![image](https://user-images.githubusercontent.com/60986118/115163546-b4cfc600-a077-11eb-95e9-56c261b4db11.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Release Version: Latest version: 1.3.7
![image](https://user-images.githubusercontent.com/60986118/115163552-c1ecb500-a077-11eb-868b-10fd8d5f5aa3.png)

**Additional context**
It seems like I'm the only one getting this error message.

**Comment by chenyingying0402** [comment]
I got the same bug!!

**Comment by RafaelPiloto10** [comment]
> I got the same bug!!

You mentioned in[ another issue](https://github.com/NLP-Suite/NLP-Suite/issues/247#issuecomment-822062497) that you got this error after downgrading your pywsd version. Though that resolved your initial issue, it is possible that the current NLP Software does not support an older version of pywsd. Can you uninstall pywsd (`pip uninstall pywsd && pip install pywsd && pip install wn==0.0.23`) and confirm if you get the same error?

**Comment by KaheiH1104** [comment]
I also get the same bug.

**Comment by RafaelPiloto10** [comment]
@Emory-NLP
The error can be found on this line: https://github.com/NLP-Suite/NLP-Suite/blob/ea5358093a846f5a0ad0682dcc040e7355184903/src/nominalization_main.py#L334

There is a missing comma after `'NOM_verb' `, which is causing the bug. Leaving issue open until the latest patch includes this bug fix.
