### ISSUE TITLE
[BUG]: Error about N-gram in the style analysis

### ISSUE THREAD

**Issue by chenyingying0402** [NLP-Suite/NLP-Suite#268]
**Describe the bug**
After finishing processing the files, the NLP suite reported errors in generating the output files.

**To Reproduce**
<img width="1156" alt="截屏2021-04-22 下午9 41 56" src="https://user-images.githubusercontent.com/37049722/115724555-a1906380-a3b3-11eb-90a2-e2cee779df64.png">
<img width="1097" alt="截屏2021-04-22 下午9 42 17" src="https://user-images.githubusercontent.com/37049722/115724570-a48b5400-a3b3-11eb-989f-6eaddfbef7e9.png">

**Screenshots**
<img width="960" alt="截屏2021-04-22 下午9 39 28" src="https://user-images.githubusercontent.com/37049722/115724669-be2c9b80-a3b3-11eb-8185-3ac155cabe10.png">

**Desktop (please complete the following information):**
 - MAC
 - latest

**Additional context**
thanks

**Comment by Emory-NLP** [comment]
I tried a couple of times (taking all day) to test the script. I get the same error. Not sure why. It may be that the system simply runs out of resources. For now, I would simply untick the checkbox to compute Excel charts
![image](https://user-images.githubusercontent.com/79026295/115864838-7898be80-a405-11eb-84d5-c7eec1e369a3.png)
You can always produce the charts using the csv file that the algorithm creates using either R or Excel itself.

**Comment by chenyingying0402** [comment]
> I tried a couple of times (taking all day) to test the script. I get the same error. Not sure why. It may be that the system simply runs out of resources. For now, I would simply untick the checkbox to compute Excel charts
> ![image](https://user-images.githubusercontent.com/79026295/115864838-7898be80-a405-11eb-84d5-c7eec1e369a3.png)
> You can always produce the charts using the csv file that the algorithm creates using either R or Excel itself.

Thanks for your work. Here are just some of the files I got from so far. I am not sure how many files I should get as the results. How many I still need to get?
<img width="578" alt="截屏2021-04-23 下午11 51 17" src="https://user-images.githubusercontent.com/37049722/115897262-d02f3c80-a48e-11eb-9fa0-7c67eead39ce.png">

**Comment by Emory-NLP** [comment]
1048576 is simply 2 to the 20th power, and thus this number is the largest that can be represented in twenty bits. The algorithm you run has reached that maximum number of rows. The Excel chart util now traps the error.
