### ISSUE TITLE
[BUG]: Error in coNLL table's searching functions

### ISSUE THREAD

**Issue by chenyingying0402** [NLP-Suite/NLP-Suite#269]
**Describe the bug**
I am not sure if this is an issue with my own corpus of conll table analyzer.

**To Reproduce**
- CoNLL Table Analyzer
- searched "he" or "him" as the tokens (I have successfully done searching "she" and "her" and generated results)
- see the error

**Screenshots**
<img width="1251" alt="截屏2021-04-22 下午5 15 41" src="https://user-images.githubusercontent.com/37049722/115725252-4448e200-a3b4-11eb-9c54-59118b527d1e.png">

**Desktop (please complete the following information):**
 - MAC
 - latest

**Additional context**
thanks, if you need my corpus I can provide it with you

**Comment by Emory-NLP** [comment]
Depending upon when you ran the parser that created the CoNLL table, the Record ID may start from 1 with every new document. There was a bug in the CoNLL_annotator. That would result in a problem with the CoNLL table analyzer which relies on a strict sequence of Record ID, as I mentioned in class today. You need to rerun the parser and all will be OK.
