### ISSUE TITLE
[BUG]: error in "Sentence complexity" again

### ISSUE THREAD

**Issue by chenyingying0402** [NLP-Suite/NLP-Suite#274]
**Describe the bug**
Hi after I ran the entire corpus, error message showed up.

**To Reproduce**
Style analysis - complexity/readability analysis(left) - sentence complexity (right)
https://github.com/NLP-Suite/NLP-Suite/issues/257 (the same)

<img width="669" alt="截屏2021-04-23 上午5 22 03" src="https://user-images.githubusercontent.com/37049722/115786942-0f5c7f80-a3f4-11eb-84ac-92cd72705efc.png">

**Desktop (please complete the following information):**
 - MAC
 - latest

**Additional context**
Thanks I really have a huge corpus for project

**Comment by Emory-NLP** [comment]
Unfortunately, it takes hours to test the error. While I get the same error using your same corpus, the error does not occur with any other corpus and no clue why Pandas breaks. So, I simply trap the error with this warning 
"An error was encountered in merging individual files of sentence complexity. Please, use R to merge the csv files containing the sentence complexity scores for each sentence of each input txt file saved in the output directory " ...

**Comment by Emory-NLP** [comment]
Sentence complexity rewritten in Python
