### ISSUE TITLE
[BUG]: Error Sentence Analysis  

### ISSUE THREAD

**Issue by jsw031** [NLP-Suite/NLP-Suite#278]
**Describe the bug**
Encounter an error: pandas.errors.EmptyDataError: No columns to parse from file

**To Reproduce**

**Screenshots**
<img width="1102" alt="Screen Shot 2021-04-25 at 14 29 35" src="https://user-images.githubusercontent.com/81481325/115983279-d8909000-a5d2-11eb-934a-f670521440f0.png">

**Desktop (please complete the following information):**
 - OS: [MAC OS X]
 - Release Version ( the latest version) 

**Additional context**
My corpus is Inaugural Addresses

**Comment by Emory-NLP** [comment]
What is your input Jessica? It is hidden behind the error screenshot...

**Comment by jsw031** [comment]
The whole Inaugural Addresses

**Comment by Emory-NLP** [comment]
OK, that type of error is now captured and the user warned. It seems tat Pandas is running out of resources.  It will give you the warning displayed below. All individual csv files will have been saved. Will upload new release shortly. 

mb.showwarning("Fatal error", "An error was encountered in merging the " + str(Ndocs) + " individual csv files of sentence complexity. Please, use R to merge the csv files containing the sentence complexity scores for each sentence of each input txt file saved in the output directory " + outputDir)

**Comment by ssong88emory** [comment]
I am having this same problem on mac
