### ISSUE TITLE
[BUG]: Required Sentence_Complexity.Jar not found

### ISSUE THREAD

**Issue by jinahyejin** [NLP-Suite/NLP-Suite#279]
When attempting to run the sentence complexity analysis, it states it requires the sentence_complexity.jar in the subdirectory src but is missing. 
I have checked my src and found it doesn't exist and I've also downloaded and checked the separate link with java files and they do not seem to have it. 

**To Reproduce**
1. Go to Style analysis GUI
2. Click on Complexity/Readability Analysis
3. Scroll down to Sentence Complexity and click RUN

![image](https://user-images.githubusercontent.com/59975110/116009169-0f23d600-a5e6-11eb-9039-b90ae8c622ce.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Release Version 1.3.8

**Comment by CeliaHu1220** [comment]
Download the jar file from https://drive.google.com/file/d/1ZlpjVo4GK98lrvTXEoXqRUpcOuIwzh3_/view?usp=sharing. Thanks to  Yingying for creating this public link for us to download!!!

**Comment by Emory-NLP** [comment]
If you all just paid attention to what goes on in class! The jar file was placed in Canvas under Files!!!
