### ISSUE TITLE
[BUG]: UnicodeDecodeError when trying to run SVO extractor

### ISSUE THREAD

**Issue by jinahyejin** [NLP-Suite/NLP-Suite#291]
**Describe the bug**
I tried to run the SVO extractor again and I have been getting an UnicodeDecodeError and will not let me run the SVO extractor. 

**To Reproduce**
1. Go to SVO extractor and visualization
2. Click on RUN without any changes to the GUI
3. See error

![image](https://user-images.githubusercontent.com/59975110/116245085-91231480-a736-11eb-9e63-d8b43f36899e.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Release Version: 1.3.8

**Comment by Emory-NLP** [comment]
You should run the utf-8 compliance algorithm. It looks like you have characters in the documents that break the code. Will assign error to Claude, just in case. If you send me the file that gives the error I can test with the specific file, but run utf-8 first.

**Comment by jinahyejin** [comment]
Hello, I ran the files through the utf-8 compliance and it states there were utf-8 compliant. 
![image](https://user-images.githubusercontent.com/59975110/116248369-d09f3000-a739-11eb-8887-6f1da096250a.png)
So I wasn't exactly sure what the error was talking about.

**Comment by Emory-NLP** [comment]
Jina, I looked more closely at the error. Sorry. Nothing to do with input files. It breaks when testing for Java installation. Will look into it further.

**Comment by RafaelPiloto10** [comment]
Hi @jinahyejin, could you please open a new command prompt and type the following: `java -version`. Please screen shot the output. Next, type `java --version` (this one has two dashes) and screen shot this output too. Please attach both of these screen shots in your reply. Thank you!

**Comment by jinahyejin** [comment]
Hello, this is what I get as ouput:
![image](https://user-images.githubusercontent.com/59975110/116645709-5bec1180-a944-11eb-82f5-062be9ec43f0.png)

**Comment by RafaelPiloto10** [comment]
@jinahyejin, thank you for that. It looks like you don't have Java correctly installed or the java configurations were messed with. Can you try removing java from your system and installing the [Java 8 JDK](https://www.oracle.com/java/technologies/javase/javase-jdk8-downloads.html)

**Comment by jinahyejin** [comment]
Hi I have uninstalled and reinstalled Java and updated my NLP code but this was an error when I tried opening SVO extractor.

![image](https://user-images.githubusercontent.com/59975110/117224225-63486a80-addd-11eb-8afb-415ee4ae2859.png)

**Comment by RafaelPiloto10** [comment]
This appears to be an unrelated issue. I am going to close this issue since it seems like the issue relating to Java has been resolved. Please make a new issue relating to the new bug you have encountered with the SVO extractor.
