### ISSUE TITLE
[BUG]: name 'nSAscoreFiles' is not defined running shape of stories

### ISSUE THREAD

**Issue by jinahyejin** [NLP-Suite/NLP-Suite#292]
**Describe the bug**
When trying to run shape of stories with the three different sentiment analysis csv files, I have gotten the NameError for all three. 

**To Reproduce**
1. Go to shape of stories GUI
2. Insert any VADER, Sentiwordnet, or Hedonometer csv file as input.
3. Select RUN without changing other settings

**Screenshots**
![image](https://user-images.githubusercontent.com/59975110/116247984-64243100-a739-11eb-9ec3-7da60b4c623c.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Release Version 1.3.8

**Comment by Emory-NLP** [comment]
Please, use the latest release. That bug was already fixed in 1.3.9
