### ISSUE TITLE
[BUG]: Import error when attempting to run SVO extractor & visualization 

### ISSUE THREAD

**Issue by yuribrunner2000** [NLP-Suite/NLP-Suite#298]
**Describe the bug**
Unable to run SVO extraction & visualization using latest version of the NLP suite. 

**To Reproduce**
1. Go to SVO extractor & visualization 
2. Click on run
3. See error

**Screenshots**
<img width="1153" alt="Screen Shot 2021-05-09 at 11 50 35 AM" src="https://user-images.githubusercontent.com/83916268/117578649-4c479800-b0bd-11eb-8b73-b5822a00d41b.png">

**Desktop (please complete the following information):**
 - OS: macOS High Sierra 10.13.5
 - Release Version 1.4.1

**Comment by Emory-NLP** [comment]
Glad that reinstalling the NLP-Suite solved the problems.
