### ISSUE TITLE
[BUG]: Java Viewer Script Did Not Produce an N-grams Output File 

### ISSUE THREAD

**Issue by yuribrunner2000** [NLP-Suite/NLP-Suite#299]
**Describe the bug**
Attempting to run N-Gram viewer using latest version of the NLP suite. Using ASR corpus with date adjusted files. 

**To Reproduce**
1. Go to N-Gram and Word Co-Occurrence Viewer.
2. Follow Setup as shown in screenshot. 
3. Click Run 

**Screenshots**
<img width="1100" alt="Screen Shot 2021-05-09 at 11 56 50 AM" src="https://user-images.githubusercontent.com/83916268/117578860-72216c80-b0be-11eb-8660-79a0423be0c1.png">
<img width="989" alt="Screen Shot 2021-05-09 at 11 57 41 AM" src="https://user-images.githubusercontent.com/83916268/117578862-73eb3000-b0be-11eb-8f7c-d95a7403e761.png">

**Desktop (please complete the following information):**
 - OS: macOS High Sierra 10.13.5
 - Release Version 1.4.1

**Comment by Emory-NLP** [comment]
Unfortunately the Java N-grams Viewer on some machines does not work. We are working on a Python N-grams Viewer; so, we are not trying to solve the glitches with the Java version.
