### ISSUE TITLE
Auto Update Script

### ISSUE THREAD

**Issue by DDavid233** [NLP-Suite/NLP-Suite#3]
Progress

- Mac 

- [x] Script
- [x] Testing

- Windows

- [x] Script
- [x] Testing
- [ ] 32bit support

**Comment by RafaelPiloto10** [comment]
Nice! Are the paths relative to the script or the NLP folder? I think it might be a good idea to isolate install scripts to an installation folder for their respective OS's. What do you think?

Also, [Windows_STEP1-install_anaconda.bat](https://github.com/NLP-Suite/NLP-Suite/blob/main/Windows_STEP1-install_anaconda.bat) is specific to x64 OS. We should be careful about x32. Do you think it would be worth having a python script to generate/run the commands we currently have, but dynamically depending on OS & location? This may help reduce the number of scripts we have and better clarify the installation steps to the user.

**Comment by zjdavid** [comment]
> Nice! Are the paths relative to the script or the NLP folder? I think it might be a good idea to isolate install scripts to an installation folder for their respective OS's. What do you think?

The paths are relative to the script. I think it would be a good idea to isolate scripts. I will add that to my todo list.

> Also, [Windows_STEP1-install_anaconda.bat](https://github.com/NLP-Suite/NLP-Suite/blob/main/Windows_STEP1-install_anaconda.bat) is specific to x64 OS. We should be careful about x32. Do you think it would be worth having a python script to generate/run the commands we currently have, but dynamically depending on OS & location? This may help reduce the number of scripts we have and better clarify the installation steps to the user.

Yes, but I am not sure if any of our users are still using 32bit Windows. If we include a 32bit version of Anaconda, that would be another 400MB adding to the bundle size. 32bit Windows only supports 4GB of RAM, which is not quite very usable in 2021, I guess...

**Comment by RafaelPiloto10** [comment]
> Yes, but I am not sure if any of our users are still using 32bit Windows. If we include a 32bit version of Anaconda, that would be another 400MB adding to the bundle size. 32bit Windows only supports 4GB of RAM, which is not quite very usable in 2021, I guess...

Good point, Anaconda still offers a 32 bit download, so I think that it would be worth our while to offer support for 32 bit machines even though it is unlikely for someone to still have a 32 bit machine at this point in time. In the installation script for 32 bit machines, we can state that the NLP Suite is not optimized for their machine. However, I think it is still important to consider future users who may be running 32 bit machines. What do you think?

**Comment by zjdavid** [comment]
Sure, I will add that to my todo list
