### ISSUE TITLE
[BUG]: Could not find conda environment: nlp

### ISSUE THREAD

**Issue by tigersun1999** [NLP-Suite/NLP-Suite#317]
I downloaded everything and followed the instructions. Everything went ok, but when I try running the program, it says Could not find conda environment: nlp. When I type conda info --envs, I can see a conda environment discovered. What should I do next?
![bug](https://user-images.githubusercontent.com/62780915/131208725-5206f16a-7e67-4d6e-9dd0-7add60ad97ee.png)

**Comment by RafaelPiloto10** [comment]
Thanks for filing the bug report!

Please use "[verify installation](https://github.com/NLP-Suite/NLP-Suite/wiki/Troubleshooting#verifying-installation)" to see where your installation has gone awry. 

I can say that it is obvious STEP 2 did not successfully work -- STEP 2 creates the NLP environment, which is missing from your `conda info --envs`. Try to run STEP 2 again and read the entire command prompt output for any errors.

Please attach the full output here after running STEP 2 if you still encounter any errors

**Comment by tigersun1999** [comment]
I did realize that my step 2 did not successfully work. However, when I went through it again, there was some new troubleshoot, yet it still said successfully installed. Also, when I run the program, my cmd was still in the back and this window popped out. I wonder if it was indeed installed properly.
![dd1eb198dda6863a508a51974ec6d40](https://user-images.githubusercontent.com/62780915/131241428-3bc96604-b02f-482f-9e7d-5ffe7d77c0c2.png)
![7b5f699bbb360d5cdef22c7993d5e78](https://user-images.githubusercontent.com/62780915/131241429-c8948215-02ce-4bfe-b5f1-aed2574365cb.png)

**Comment by RafaelPiloto10** [comment]
Take a look at https://github.com/NLP-Suite/NLP-Suite/wiki/Troubleshooting#microsoft-visual-c-plus-plus-required. This is the first Windows error we have seen, so thank you for reaching out!

Once you have installed the Build Tools and have installed C++ V14.0 or greater, run STEP2 again to complete the installation

**Comment by RafaelPiloto10** [comment]
@tigersun1999, please confirm you were able to successfully install C++ tools when you get the chance! Thanks!

**Comment by Emory-NLP** [comment]
Notice that environments are case sensitive NLP and not nlp. As such, conda activate nlp, is not recognized.
