### ISSUE TITLE
[BUG]: The NLP software won't show up after Mac_run.command

### ISSUE THREAD

**Issue by kathyyyding** [NLP-Suite/NLP-Suite#331]
**Describe the bug**
I don't know why the NLP software won't show up after I click the Mac_run.command. It used to work. I tried click update.command and step2-install. It's still not working. it shows in the terminal that the process is completed.

**Screenshots**
<img width="571" alt="Screen Shot 2021-09-02 at 12 27 56 PM" src="https://user-images.githubusercontent.com/89586841/131881822-e4468361-ff1e-478b-977b-5f9340ff47b0.png">

**Desktop (please complete the following information):**
 - Macbook
 - Release Version (type `NLP --version` e.g. 22) 

**Additional context**

**Comment by RafaelPiloto10** [comment]
@kathyyyding, "Process Completed" does not mean that the process exited without any issues. Please scroll up on your terminal after running the Mac_run.command and attach any other screenshots showing the error causing NLP Suite to crash.

**Comment by kathyyyding** [comment]
> @kathyyyding, "Process Completed" does not mean that the process exited without any issues. Please scroll up on your terminal after running the Mac_run.command and attach any other screenshots showing the error causing NLP Suite to crash.

<img width="985" alt="Screen Shot 2021-09-03 at 3 54 19 PM" src="https://user-images.githubusercontent.com/89586841/132059296-56ccdb21-accb-4580-a3ec-9074fcd330c8.png">
Here is the whole screenshot of the terminal.

**Comment by DDVD233** [comment]
It looks like both issues are related to pandas. Please follow this [instruction](https://github.com/NLP-Suite/NLP-Suite/issues/333#issuecomment-912715234) and see if it solves the problem. 

Also, it would be great if you could post a screenshot of your step2 output.

**Comment by kathyyyding** [comment]
> It looks like both issues are related to pandas. Please follow this [instruction](https://github.com/NLP-Suite/NLP-Suite/issues/333#issuecomment-912715234) and see if it solves the problem.
> 
> Also, it would be great if you could post a screenshot of your step2 output.

I think the problem is in step2. It shows proceed all the time. I waited for the terminal to end for 2 hours, but it didn't finish. I'll paste the output of step2 below. 

Last login: Sun Sep  5 14:05:51 on ttys002
/Users/katharineding/Desktop/QTM446W/NLP-Suite-current-stable/setup_Mac/STEP2-install_components.command ; exit;
(base) katharineding@MacBook-Pro-3 ~ % /Users/katharineding/Desktop/QTM446W/NLP-Suite-current-stable/setup_Mac/STEP2-install_components.command ; exit;
Collecting package metadata (current_repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.10.1
  latest version: 4.10.3

Please update conda by running

    $ conda update -n base -c defaults conda



## Package Plan ##

  environment location: /Users/katharineding/anaconda/envs/NLP

  added / updated specs:
    - python=3.9


The following NEW packages will be INSTALLED:

  ca-certificates    pkgs/main/osx-64::ca-certificates-2021.7.5-hecd8cb5_1
  certifi            pkgs/main/osx-64::certifi-2021.5.30-py39hecd8cb5_0
  libcxx             pkgs/main/osx-64::libcxx-10.0.0-1
  libffi             pkgs/main/osx-64::libffi-3.3-hb1e8313_2
  ncurses            pkgs/main/osx-64::ncurses-6.2-h0a44026_1
  openssl            pkgs/main/osx-64::openssl-1.1.1l-h9ed2024_0
  pip                pkgs/main/osx-64::pip-21.2.4-py37hecd8cb5_0
  python             pkgs/main/osx-64::python-3.9.6-h88f2d9e_1
  readline           pkgs/main/osx-64::readline-8.1-h9ed2024_0
  setuptools         pkgs/main/osx-64::setuptools-52.0.0-py39hecd8cb5_0
  sqlite             pkgs/main/osx-64::sqlite-3.36.0-hce871da_0
  tk                 pkgs/main/osx-64::tk-8.6.10-hb0a8c7a_0
  tzdata             pkgs/main/noarch::tzdata-2021a-h5d7bf9c_0
  wheel              pkgs/main/noarch::wheel-0.37.0-pyhd3eb1b0_0
  xz                 pkgs/main/osx-64::xz-5.2.5-h1de35cc_0
  zlib               pkgs/main/osx-64::zlib-1.2.11-h1de35cc_3


Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate NLP
#
# To deactivate an active environment, use
#
#     $ conda deactivate

Collecting package metadata (current_repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.10.1
  latest version: 4.10.3

Please update conda by running

    $ conda update -n base -c defaults conda



## Package Plan ##

  environment location: /Users/katharineding/anaconda/envs/NLP

  added / updated specs:
    - cudatoolkit
    - pytorch
    - torchvision


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    cudatoolkit-9.0            |       h41a26b3_0       188.5 MB
    ffmpeg-4.3                 |       h0a44026_0        10.1 MB  pytorch
    gnutls-3.6.15              |       hed9c0bf_0         974 KB
    lame-3.100                 |       h1de35cc_0         316 KB
    libidn2-2.3.2              |       h9ed2024_0          85 KB
    libtasn1-4.16.0            |       h9ed2024_0          53 KB
    libunistring-0.9.10        |       h9ed2024_0         519 KB
    libxml2-2.9.12             |       hcdb78fc_0         1.1 MB
    lz4-c-1.9.3                |       h23ab428_1         140 KB
    nettle-3.7.3               |       h230ac6f_1         380 KB
    ninja-1.10.2               |       hf7b0b51_1         106 KB
    openh264-2.1.0             |       hd9629dc_0         635 KB
    openjpeg-2.4.0             |       h66ea3da_0         301 KB
    pillow-8.3.1               |   py39ha4cf6ea_0         602 KB
    pytorch-1.9.0              |          py3.9_0        79.0 MB  pytorch
    torchvision-0.10.0         |         py39_cpu         6.8 MB  pytorch
    typing_extensions-3.10.0.0 |     pyh06a4308_0          27 KB
    zstd-1.4.9                 |       h322a384_0         476 KB
    ------------------------------------------------------------
                                           Total:       290.0 MB

The following NEW packages will be INSTALLED:

  blas               pkgs/main/osx-64::blas-1.0-mkl
  bzip2              pkgs/main/osx-64::bzip2-1.0.8-h1de35cc_0
  cudatoolkit        pkgs/main/osx-64::cudatoolkit-9.0-h41a26b3_0
  ffmpeg             pytorch/osx-64::ffmpeg-4.3-h0a44026_0
  freetype           pkgs/main/osx-64::freetype-2.10.4-ha233b18_0
  gettext            pkgs/main/osx-64::gettext-0.21.0-h7535e17_0
  gmp                pkgs/main/osx-64::gmp-6.2.1-h23ab428_2
  gnutls             pkgs/main/osx-64::gnutls-3.6.15-hed9c0bf_0
  icu                pkgs/main/osx-64::icu-58.2-h0a44026_3
  intel-openmp       pkgs/main/osx-64::intel-openmp-2021.3.0-hecd8cb5_3375
  jpeg               pkgs/main/osx-64::jpeg-9b-he5867d9_2
  lame               pkgs/main/osx-64::lame-3.100-h1de35cc_0
  lcms2              pkgs/main/osx-64::lcms2-2.12-hf1fd2bf_0
  libiconv           pkgs/main/osx-64::libiconv-1.16-h1de35cc_0
  libidn2            pkgs/main/osx-64::libidn2-2.3.2-h9ed2024_0
  libpng             pkgs/main/osx-64::libpng-1.6.37-ha441bb4_0
  libtasn1           pkgs/main/osx-64::libtasn1-4.16.0-h9ed2024_0
  libtiff            pkgs/main/osx-64::libtiff-4.2.0-h87d7836_0
  libunistring       pkgs/main/osx-64::libunistring-0.9.10-h9ed2024_0
  libuv              pkgs/main/osx-64::libuv-1.40.0-haf1e3a3_0
  libwebp-base       pkgs/main/osx-64::libwebp-base-1.2.0-h9ed2024_0
  libxml2            pkgs/main/osx-64::libxml2-2.9.12-hcdb78fc_0
  llvm-openmp        pkgs/main/osx-64::llvm-openmp-10.0.0-h28b9765_0
  lz4-c              pkgs/main/osx-64::lz4-c-1.9.3-h23ab428_1
  mkl                pkgs/main/osx-64::mkl-2021.3.0-hecd8cb5_517
  nettle             pkgs/main/osx-64::nettle-3.7.3-h230ac6f_1
  ninja              pkgs/main/osx-64::ninja-1.10.2-hf7b0b51_1
  olefile            pkgs/main/noarch::olefile-0.46-py_0
  openh264           pkgs/main/osx-64::openh264-2.1.0-hd9629dc_0
  openjpeg           pkgs/main/osx-64::openjpeg-2.4.0-h66ea3da_0
  pillow             pkgs/main/osx-64::pillow-8.3.1-py39ha4cf6ea_0
  pytorch            pytorch/osx-64::pytorch-1.9.0-py3.9_0
  torchvision        pytorch/osx-64::torchvision-0.10.0-py39_cpu
  typing_extensions  pkgs/main/noarch::typing_extensions-3.10.0.0-pyh06a4308_0
  zstd               pkgs/main/osx-64::zstd-1.4.9-h322a384_0


Proceed ([y]/n)?

**Comment by RafaelPiloto10** [comment]
Resolved -- Solution: Student did not type "y" to proceed when running STEP 2. STEP 2 would hang waiting for input to continue installation.

After typing "y", STEP2 completed and the student was able to open the NLP Suite.
