### ISSUE TITLE
[BUG]: NLP Suite No Longer Opens

### ISSUE THREAD

**Issue by BillyMartin8** [NLP-Suite/NLP-Suite#333]
**Describe the bug**
After closing the Suite, the Mac_run.command no longer opens the Suite.  Upon executing the command, the terminal runs the program and then says "Process Completed."  After doing this, the Suite opens and immediately closes.  I tried uninstalling and reinstalling, but this did not resolve the issue.

**To Reproduce**
I closed the Suite, then ran the Mac_run.command.

**Screenshots**
<img width="570" alt="Screen Shot 2021-09-02 at 5 15 23 PM" src="https://user-images.githubusercontent.com/89608553/131917204-a8bb998e-2932-4de0-a8a5-68abf83125ef.png">

**Desktop (please complete the following information):**
 - MacOS Big Sur (11.5.2)
 - NLP release 15.3

**Comment by RafaelPiloto10** [comment]
Going to jump in here to get you going. @BillyMartin8, it looks like part of the error was cut off (towards the top of your screenshot). To have a better idea of the error you are getting, we will need to see the full error. In any case, it is clear that you are missing a package "pandas," which means there may have been an error with STEP2. 

Please take a look at [installing missing modules/packages](https://github.com/NLP-Suite/NLP-Suite/wiki/Troubleshooting#missing-python-module-or-package) to install pandas. If future problems persist, it may be helpful to try running STEP 2 again and paying close attention for any "errors".

**Comment by DDVD233** [comment]
Yes, I agree with Rafael that this is an issue with Pandas. We also found that the requirements.txt is corrupted on September 2nd. If you download NLP-Suite on/after that date, please redownload it after we fix the issue later today.

**Comment by RafaelPiloto10** [comment]
@BillyMartin8, another student had an identical error as you. Please refer to the [solution](https://github.com/NLP-Suite/NLP-Suite/issues/331#issuecomment-914306490) to that issue.

Please confirm if your issue persists or is resolved

**Comment by BillyMartin8** [comment]
That issue is resolved. Thank you!


On Sep 7, 2021, at 9:30 AM, Rafael Piloto ***@***.***> wrote:

﻿

@BillyMartin8<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FBillyMartin8&data=04%7C01%7Cbilly.martin%40emory.edu%7C32a76c6a15bc46c719de08d97203b0ad%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637666182448999855%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=%2BRDCbZYRCtZsRN1OgyPUE27XCJ79lVRdkW0BJ%2BwBM0o%3D&reserved=0>, another student had an identical error as you. Please refer to the solution<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FNLP-Suite%2FNLP-Suite%2Fissues%2F331%23issuecomment-914306490&data=04%7C01%7Cbilly.martin%40emory.edu%7C32a76c6a15bc46c719de08d97203b0ad%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637666182449009849%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=0r2hQuP57u3aE6A8off%2BiqAiaXbpPBY4udBnArVzzYo%3D&reserved=0> to that issue.

Please confirm if your issue persists or is resolved

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FNLP-Suite%2FNLP-Suite%2Fissues%2F333%23issuecomment-914308568&data=04%7C01%7Cbilly.martin%40emory.edu%7C32a76c6a15bc46c719de08d97203b0ad%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637666182449019844%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=bS4S3ANYlv89ewURDv%2BWXyeQZNWzjrW4QVmOmUORT4k%3D&reserved=0>, or unsubscribe<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAVLVC2PN7OIZQKOKYFS5QYTUAYHYDANCNFSM5DKAPDBQ&data=04%7C01%7Cbilly.martin%40emory.edu%7C32a76c6a15bc46c719de08d97203b0ad%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637666182449019844%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=fujyTli7S4WvhuA7NoqTVv%2BQCI8iJLrhxg6ywvQ9MG4%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cbilly.martin%40emory.edu%7C32a76c6a15bc46c719de08d97203b0ad%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637666182449029840%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=yZ0ZXlEplYMrj8pmWwgGAOft2%2FVf2GA24pWQqhJsLRs%3D&reserved=0> or Android<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cbilly.martin%40emory.edu%7C32a76c6a15bc46c719de08d97203b0ad%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637666182449039833%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=E0YTVQ80u4OIrfSo0pAYPWhfYyH7gUkIgqy3YTm%2FTUM%3D&reserved=0>.
