### ISSUE TITLE
no module named pyLDAvis.gensim

### ISSUE THREAD

**Issue by BillyMartin8** [NLP-Suite/NLP-Suite#337]
**Describe the bug**
When attempting to open the "WHAT'S IN YOUR CORPUS" analysis tool on NLP Suite version 1.5.4, the "run" tool does not open.  In the terminal, an error message saying "no module named 'pyLDAvis.gensim' appears, but I am unsure of how to get the module.

**To Reproduce**
Select Stanford CoreNLP as the external software.
Select WHAT'S IN YOUR CORPUS
Click "run"

**Screenshots**
<img width="942" alt="Screen Shot 2021-09-04 at 1 17 54 PM" src="https://user-images.githubusercontent.com/89608553/132103105-5cae48cc-83db-4133-bc51-d50dd740a61a.png">

**Desktop (please complete the following information):**
NLP Suite 1.5.4
MacOS 11.5.2 

**Additional context**
When initially attempting to click run, there were numerous missing files, which I had to manually install through the terminal.  This problem only arose after I downloaded the additional files.

**Comment by Emory-NLP** [comment]
You need to make sure that if you pip install the package you are in the right NLP environment.
