### ISSUE TITLE
[BUG]: Step 2 Installation Failure

### ISSUE THREAD

**Issue by FF15enc** [NLP-Suite/NLP-Suite#345]
**Describe the bug**
 Running step two gives the error: /Users/chrisfeng/anaconda/bin/activate: No such file or directory

**Screenshots**
<img width="566" alt="Screen Shot 2021-09-07 at 10 13 40 PM" src="https://user-images.githubusercontent.com/78893139/132435267-0efa9ce7-a0fe-4c10-9d40-b6c5b1749f44.png">

**Desktop (please complete the following information):**
 - OS X
 - NLP 1.51
 
**Additional context**
I suspect that it's because my anaconda file is /Users/chrisfeng/anaconda3

**Comment by Emory-NLP** [comment]
I will let Rafael or Wei address this issue. Not sure what is happening.

**Comment by Emory-NLP** [comment]
We have now added a check for Anaconda3.
