### ISSUE TITLE
[BUG]: Word Cloud Issue

### ISSUE THREAD

**Issue by BillyMartin8** [NLP-Suite/NLP-Suite#346]
**Describe the bug**
On NLP Suite Version 1.5.5, the word cloud feature only works for locally generated word clouds (such as Python).  When attempting to use the other word cloud tools, the text is incorrectly imported or the user is directed to the main page of the word cloud generator, without a way to import the text.

**To Reproduce**
1. Choose the 'Word Cloud' tool under the 'CORPUS/DOCUMENT Analysis Tools'
2. Select the desired CORPUS and output location
3. Choose any of the non-locally stored generators (for the purpose of this issue, I chose WordClouds.com

**Screenshots**
<img width="1470" alt="Screen Shot 2021-09-07 at 11 32 03 PM" src="https://user-images.githubusercontent.com/89608553/132442197-46ace83f-6e92-4431-8638-16230d5778bd.png">

**Desktop (please complete the following information):**
 - OS: MacOS 11.5.2
 - Release Version: NLP Suite Version 1.5.5

**Comment by Emory-NLP** [comment]
I am not sure where the problem is. You would need to give the screenshot of the error that Python wordclouds gives you. Please, add image. As for wordcloud web services, you will need either to copy and paste the text or upload a file. I have now added a reminder to tat effect.
