### ISSUE TITLE
[BUG]: No Access Privileges to NLP Suite

### ISSUE THREAD

**Issue by BillyMartin8** [NLP-Suite/NLP-Suite#354]
**Describe the bug**
When attempting to run commands on the 'setup_Mac' folder, I am denied access.  A message saying that I do not have appropriate access privileges appears.  The 'STEP1' command is the only one that does not face this issue.

**To Reproduce**
1. Open the NLP-Suite-current-stable folder
2. Click on setup_Mac
3. Click any file (other than 'STEP1').

**Screenshots**
<img width="1098" alt="Screen Shot 2021-09-09 at 4 15 49 PM" src="https://user-images.githubusercontent.com/89608553/132756340-3a082b67-efe4-4e11-a26c-5f838cbbdbeb.png">

**Desktop (please complete the following information):**
 - MacOS 11.5.2
 - Release 1.5.6

**Comment by DDVD233** [comment]
Please follow the following steps and see if it solves the issue:
1. Open a terminal window
2. Type `sudo chmod -R 770 ` (Notice there is a space after 777)
3. Drag & Drop the entire NLP-Suite to the terminal window, press enter
![tg_image_563561205](https://user-images.githubusercontent.com/16710181/132762439-10e49f09-681d-4388-bd5f-96247e8eb0ac.jpeg)
4. Type your password and click enter. As you are typing, your password will not be shown.
5. Try running STEP2 again and see if it solves the problem. 

What the command does is it gives you the access privilege. If you are interested, you can find more information about `chmod` command [here](https://en.wikipedia.org/wiki/Chmod).

**Comment by FF15enc** [comment]
> Please follow the following steps and see if it solves the issue:
> 
> 1. Open a terminal window
> 2. Type `sudo chmod -R 770 ` (Notice there is a space after 777)
> 3. Drag & Drop the entire NLP-Suite to the terminal window, press enter
>    ![tg_image_563561205](https://user-images.githubusercontent.com/16710181/132762439-10e49f09-681d-4388-bd5f-96247e8eb0ac.jpeg)
> 4. Type your password and click enter. As you are typing, your password will not be shown.
> 5. Try running STEP2 again and see if it solves the problem.
> 
> What the command does is it gives you the access privilege. If you are interested, you can find more information about `chmod` command [here](https://en.wikipedia.org/wiki/Chmod).

Not OP but this did not solve my issue. The same issue still persists when I try to open Step 2.

**Comment by DDVD233** [comment]
> > Please follow the following steps and see if it solves the issue:
> > 
> > 1. Open a terminal window
> > 2. Type `sudo chmod -R 770 ` (Notice there is a space after 777)
> > 3. Drag & Drop the entire NLP-Suite to the terminal window, press enter
> >    ![tg_image_563561205](https://user-images.githubusercontent.com/16710181/132762439-10e49f09-681d-4388-bd5f-96247e8eb0ac.jpeg)
> > 4. Type your password and click enter. As you are typing, your password will not be shown.
> > 5. Try running STEP2 again and see if it solves the problem.
> > 
> > What the command does is it gives you the access privilege. If you are interested, you can find more information about `chmod` command [here](https://en.wikipedia.org/wiki/Chmod).
> 
> Not OP but this did not solve my issue. The same issue still persists when I try to open Step 2.

Could you try updating to the latest release? This issue has been fixed in release 1.5.8.

**Comment by BillyMartin8** [comment]
It appears that uninstalling the NLP Suite and downloading the latest release from GitHub fixed the issue, as per @DDavid233's recommendation.  I believe this issue can now be resolved.  Thank you!
