### ISSUE TITLE
[BUG]: Step 2 error : The following untracked working tree files would be overwritten by checkout

### ISSUE THREAD

**Issue by FentonSun** [NLP-Suite/NLP-Suite#357]
**Describe the bug**
 Error: The following untracked working tree files would be overwritten by checkout:
I couldn't install the packages named "pyLDAvis.gensim", so I tried to re-install the anaconda to solve it, however, I faced a new problem in step 2.

**Screenshots**
<img width="567" alt="Screen Shot 2021-09-11 at 11 07 30 PM" src="https://user-images.githubusercontent.com/89586744/132970557-9ee9c9af-8edb-42ae-b58b-a0c4c2f5c0b7.png">
<img width="553" alt="Screen Shot 2021-09-11 at 11 07 44 PM" src="https://user-images.githubusercontent.com/89586744/132970560-c281a7ce-fa97-42b2-ac1a-92edef81a24c.png">
<img width="560" alt="Screen Shot 2021-09-11 at 11 08 02 PM" src="https://user-images.githubusercontent.com/89586744/132970561-adeba104-9fde-46f4-b495-6e737ad5e1bb.png">
<img width="565" alt="Screen Shot 2021-09-11 at 11 08 12 PM" src="https://user-images.githubusercontent.com/89586744/132970563-6fd79593-48ef-48a1-b20e-ab7c0f6f0bae.png">
<img width="570" alt="Screen Shot 2021-09-11 at 11 09 31 PM" src="https://user-images.githubusercontent.com/89586744/132970573-6e76ef75-01e3-4875-b158-a869376cdd3e.png">

**Desktop (please complete the following information):**
 - OS: MacOS Mojave
 - Release Version: NLP 1.5.8

**Comment by RafaelPiloto10** [comment]
@FentonSun, you can ignore this error - it is trying to setup GitHub but it is already setup so it is complaining. Are you getting any errors opening NLP Suite?

**Comment by FentonSun** [comment]
There is no other errors when opening the NLP Suite, thanks a lot!
