### ISSUE TITLE
[BUG]: Not having Appropriate Privileges 

### ISSUE THREAD

**Issue by LeoYoo2002** [NLP-Suite/NLP-Suite#360]
When I try to run the NLP suite, it says "The file “run_NLP-Suite.command” could not be executed because you do not have appropriate access privileges." 
<img width="1440" alt="Screen Shot 2021-09-12 at 8 17 13 PM" src="https://user-images.githubusercontent.com/90583470/133008774-a01dfeb1-de13-46fa-a932-5963346100d3.png">

**Comment by Emory-NLP** [comment]
That bug was solved. Take a look at the Closed issue on permission error for a solution.
