### ISSUE TITLE
[BUG]: NLP Suite Not Opening 

### ISSUE THREAD

**Issue by iloveviola** [NLP-Suite/NLP-Suite#390]
Upon installation of the NLP Suite and clicking on the icon, only the cmd screen pulls up. I am only able to run the program by typing "python NLP_menu_main.py" into the command line.

Previously, the program would pull up directly after clicking the icon.

![image](https://user-images.githubusercontent.com/89374783/134603064-80df587c-a1cf-4223-9bb8-ac4862e01756.png)

My PC runs Windows 10.

**Comment by DDVD233** [comment]
Hi,
Could you follow these steps and see what happens:

1. Right-click the Windows icon on the lower-left corner, select "Run Powershell"
2. Open the NLP Suite folder, enter the setup_windows folder. Drag & drop the "run_NLP-Suite.bat" file onto the Powershell window. 
3. Press enter.
4. Send me a screenshot of the output in the PowerShell window.

Thanks.

**Comment by scifinina** [comment]
![Screenshot (82)](https://user-images.githubusercontent.com/90849892/134976838-0c87de82-9255-4c4f-8c35-17e34e4e6933.png)

(for version 1.6.6)
