### ISSUE TITLE
[BUG]: WordNet File Opening

### ISSUE THREAD

**Issue by danielJi030** [NLP-Suite/NLP-Suite#394]
![1632580283(1)](https://user-images.githubusercontent.com/90074893/134775076-1771b0a5-2637-4c08-bd8c-530d8f1544f9.png)

According to the instruction, an CSV file should be opened. However, it only allows txt files to be opened.

![1632580192(1)](https://user-images.githubusercontent.com/90074893/134775029-a1170ef0-62be-4ac2-a075-de6779c88481.png)

**Comment by Emory-NLP** [comment]
Which script are you running Daniel? That image you attached does not help. Provide the image of the entire GUI...

**Comment by danielJi030** [comment]
![1632586059(1)](https://user-images.githubusercontent.com/90074893/134778068-0165cf7c-31be-44dc-ade1-e2bdb2fd88fe.png)

 It is the wordnet script

**Comment by Emory-NLP** [comment]
Which options are you running to require a csv file? You are probably running tis option
![image](https://user-images.githubusercontent.com/79026295/134778652-34f68028-62d1-4512-abab-36869a159535.png)
You need to click on the Select dictionary file button. I have now changed both the button label to Select dictionary csv file and in any case open automatically the file selection. Will push later.

**Comment by danielJi030** [comment]
This option actually requires me to open a CSV file using the IO widget at the top......

**Comment by Emory-NLP** [comment]
Could we zoom?

**Comment by Emory-NLP** [comment]
OK, I see the problem. You are using this option.
![image](https://user-images.githubusercontent.com/79026295/134790449-8e7a0ab8-9014-40dd-a58a-bbe505222273.png)
Daniel, next time, if it takes several emails and my tests to find out where/what the problem is I will not respond to/take care of the issue. Sorry!

**Comment by danielJi030** [comment]
Dr. Franzosi, I think I didn't express it properly. All of the functions require a CSV file to be loaded through the IO Widget no matter what option below. However, the IO Widget ONLY allows TXT files.

**Comment by allisonreinhardt** [comment]
I'm having the same problem as Daniel. I uploaded the CoNLL table as the dictionary csv file, but it is still giving me an error message saying that the input file at the top needs to be in csv format even though it is only taking txt files.
![Image 9-26-21 at 3 31 PM](https://user-images.githubusercontent.com/78457469/134821645-47fb7ee0-9c74-403b-a678-0b96bfcfa6f4.jpg)
![UNADJUSTEDNONRAW_mini_71](https://user-images.githubusercontent.com/78457469/134821652-4f90efb0-ff1d-43cd-869c-b8fdf3e09fec.jpg)

**Comment by allisonreinhardt** [comment]
Daniel, I started running this option instead, and it seems to be working since it uses the regular input directory.
![UNADJUSTEDNONRAW_mini_72](https://user-images.githubusercontent.com/78457469/134821780-e5f78b2c-f2fd-47e4-97ef-95fd0f8b91db.jpg)
