### ISSUE TITLE
[BUG]: "Wordnet_Search_UP.jar" was not found in the src

### ISSUE THREAD

**Issue by danielJi030** [NLP-Suite/NLP-Suite#399]
I am running the option in the graph and accordingly, the Wordnet_Search_UP.jar cannot be found in the NLP src directory.

![1632763820(1)](https://user-images.githubusercontent.com/90074893/134957114-1ce127be-f6f1-47f9-b579-982555d5a11d.png)

It seems this file does not exist either in the original NLPSuite directory or the WordNet file since I've checked both.

**Comment by Emory-NLP** [comment]
Let me assign the issue to Wei and Rafael. These jar files are downloaded trough Wei's bat files but... are not pushed with new releases (way too big). And... they are not in the GitHub src folder. Thabnks!

**Comment by DDVD233** [comment]
Please rerun STEP2 and see if that fixes the problem.
Alternatively, you can directly download all jars through this link: [https://drive.google.com/file/d/1rXpt4o7o_vnRONJCjBvCVU8Sn5MewzCO/view?usp=sharing](https://drive.google.com/file/d/1rXpt4o7o_vnRONJCjBvCVU8Sn5MewzCO/view?usp=sharing)

If you choose to download directly, please put it under the src folder within NLP main folder.
