### ISSUE TITLE
[BUG]: Gender CoreNLP Annotator not working

### ISSUE THREAD

**Issue by meganxyang** [NLP-Suite/NLP-Suite#403]
**Describe the bug**
I was trying to run the gender annotator without nouns/pronouns only first names and personal pronouns. It didn't go through. 

**Screenshots**
![Uploading Screen Shot 2021-09-28 at 5.57.02 PM.png…]()

**Desktop (please complete the following information):**
 - OS: OS X 11.5.2 Big Sur
 - Release Version (type `NLP --version` e.g. 22): I tried this command and it says the command doesn't exist. I have used the update command after Professor Franzosi said he fixed the wordnet issues!

**Additional context**
Ran it on the INA corpus which only has 62 documents, compared to SOTU's 234.

**Comment by Emory-NLP** [comment]
I am not sure what you are running. Please, attach screenshots with all the IO configurations and GUI options you are using.

**Comment by meganxyang** [comment]
Hi Dr. Franzosi, Here is my screenshot. I think it didn’t load when I initially uploaded on the website.  My I/O configuration was the defaultINPUT: potusspeeches/inaOUTPUT: 446w output (my general output folder) GUI: Checked fields – Annotate first names by gender (using Census dictionary), Process personal pronounse Hope this gives more context. Best,Megan Yang From: Roberto ***@***.***>Date: Tuesday, September 28, 2021 at 8:43 PMTo: NLP-Suite/NLP-Suite ***@***.***>Cc: meganxyang ***@***.***>, Author ***@***.***>Subject: Re: [NLP-Suite/NLP-Suite] [BUG]: Gender CoreNLP Annotator not working (#403)I am not sure what you are running. Please, attach screenshots with all the IO configurations and GUI options you are using.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Emory-NLP** [comment]
Bug fixed in release 1.7.7
