### ISSUE TITLE
[BUG]: Google Map not working

### ISSUE THREAD

**Issue by mru20** [NLP-Suite/NLP-Suite#408]
**Describe the bug**
Me and my partner are both getting the following error when running Google Map:
<img width="572" alt="Screen Shot 2021-10-03 at 11 20 29 AM" src="https://user-images.githubusercontent.com/91796548/135738241-832325df-2506-4a3b-bc0e-50b42412d2a5.png">
<img width="1270" alt="Screen Shot 2021-10-03 at 11 17 49 AM" src="https://user-images.githubusercontent.com/91796548/135738281-0525c9de-df5e-43fb-a28c-a9cdbe5f6e72.png">
The API key was correctly set up and filled in when the error occured. 

**Desktop (please complete the following information):**
 - macOS Big Sur 11.5.2

**Comment by Emory-NLP** [comment]
Spelling error NER_oututFilename fixed in 1.7.3
