### ISSUE TITLE
Traceback when running Google map

### ISSUE THREAD

**Issue by celinefeng99** [NLP-Suite/NLP-Suite#409]
Hi, Dr. Franzosi! When I started running the NLP map through Google Earth Pro, the terminal shows a series of tracebacks as shown in the image. Then there is no results shown. Can you tell me what I can do with it? Thank you!
<img width="1031" alt="Screen Shot 2021-10-02 at 11 45 48 PM" src="https://user-images.githubusercontent.com/71453334/135738950-7f55b60f-92ed-44aa-bf7b-a84f600ddbe5.png">

**Comment by Emory-NLP** [comment]
Next time, please post the screenshot of the GUI you are running. But... There is an error with Stanford CoreNLP at the very top causing a cascade of errors. You may not have installed CoreNLP properly (although the NLP Suite checks for that)? To test that CoreNLP works on your machine, open the Stanford CoreNLP GUI and run a basic annotator like POS. It should not work...
![image](https://user-images.githubusercontent.com/79026295/135748982-f67495b6-0f97-49a2-b453-9c00651694e0.png)
