### ISSUE TITLE
TypeError: can only concatenate str (not "float") to str

### ISSUE THREAD

**Issue by saayamorton** [NLP-Suite/NLP-Suite#412]
<img width="682" alt="Screen Shot 2021-10-03 at 12 27 58 PM" src="https://user-images.githubusercontent.com/89603448/135762933-386a0136-fe75-4bbb-93d0-821164ee5624.png"
<img width="1412" alt="Screen Shot 2021-10-03 at 12 28 06 PM" src="https://user-images.githubusercontent.com/89603448/135762939-38dfcc39-37fa-4f50-b747-b41efbc7690a.png">
>
Hi Dr. Franzosi! When I was running the GIS Pipeline, it kept stopping due to the error "TypeError: can only concatenate str (not "float") to str." I wasn't sure how to fix this or if it was an issue within the CoNLL table that me and my partner were using. Thank you!

**Comment by Emory-NLP** [comment]
I would need the screenshot of all the errors you get so I can see the exact line of the error.

**Comment by saayamorton** [comment]
Oh no! It looks like the screenshot of the error did not attach
<img width="682" alt="Screen Shot 2021-10-03 at 1 15 13 PM" src="https://user-images.githubusercontent.com/89603448/135764528-76effeb6-c1cd-4fbb-9f7e-872381f15b08.png">
.

**Comment by Emory-NLP** [comment]
The bug should be fixed. Give it a try.
