### ISSUE TITLE
City names and how they are grouped

### ISSUE THREAD

**Issue by saayamorton** [NLP-Suite/NLP-Suite#415]
I have noticed in the past few weeks working with the location NER tags that sometimes cities that have multiple words get separated. For example, cities like Buenos Aires are split into "Buenos" and "Aires" even though this should be one city. This has affected the analysis that I have done because when I look at the prevalence of these cities they take up more space then they should on graphs. With cities like New York City or Rio de Janeiro, it would then create a new datapoint for the third word in the 3-gram. 

<img width="803" alt="Screen Shot 2021-10-03 at 2 58 42 PM" src="https://user-images.githubusercontent.com/89603448/135767708-780b2788-0900-4299-a260-d85de7389b57.png">

In this case, the city of Los Angeles is seen to be counted as "LA" and as "Los" and "Angeles"

<img width="803" alt="Screen Shot 2021-10-03 at 2 58 29 PM" src="https://user-images.githubusercontent.com/89603448/135767718-37f388f0-7e1f-4d46-b55a-9f7f66bdb47a.png">

I guess I am hoping that there is a way that the NLP Suite can run the Stanford Core NLP and take into account cities that are more than just a 1-gram. But, this might also mess up how New York City is counted and the word "new" is counted.

**Comment by Emory-NLP** [comment]
You cannot rely on the CoNLL table for that. You need to run the Stanford CoreNLP_NER annotator locations for that.
