### ISSUE TITLE
[BUG]: ValueError when geocoding

### ISSUE THREAD

**Issue by emmaej13** [NLP-Suite/NLP-Suite#417]
I am getting this error during geocoding after the locations have been extracted from the .csv file

**Screenshots**
<img width="672" alt="nlp error" src="https://user-images.githubusercontent.com/78837632/135772690-8969c435-f3cb-444b-b29c-28b5fa069ca9.png">

Here is the GUI. Does it matter what is used as the input txt file, since the locations are being extracted from the .csv file?
![image](https://user-images.githubusercontent.com/78837632/135772840-5f763045-a382-4391-a668-73954062a710.png)

**Comment by Emory-NLP** [comment]
Could you send me the csv file you are using  to my emory email?
