### ISSUE TITLE
[Release Google Drive Bug]: setup_auto_update script not referencing correct branch to update from

### ISSUE THREAD

**Issue by RafaelPiloto10** [NLP-Suite/NLP-Suite#43]
**Describe the bug**
The setup_auto_update script is not referencing the correct branch in the Google Drive release link.

**To Reproduce**
1. Download the recent release from the Google Drive
2. Run the setup_auto_update.bat file

**Expected behavior**
Should set `current-stable` as the branch to track.

**Desktop (please complete the following information):**
 - OS: Windows

**Comment by DDVD233** [comment]
OK I will update that.

**Comment by DDVD233** [comment]
I've made a PR. Will make a new release when I get back home.

**Comment by RafaelPiloto10** [comment]
@DDavid233, make sure to update the google drive to reflect the changes you made in STEP-2 for windows. Close this issue once we have updated the Drive

**Comment by DDVD233** [comment]
Solved by the latest release.
