### ISSUE TITLE
[BUG]: Python Crashes when Attempting to Open SVO GUI or run Python WordClouds

### ISSUE THREAD

**Issue by BillyMartin8** [NLP-Suite/NLP-Suite#457]
**Describe the bug**
When attempting to open the SVO GUI and run the Python WordClouds, Python crashes.

**To Reproduce**
1. Download the latest patch (1.8.4).
2. Select the SVO Extractor
3. Click 'run,' see error
4. Open WordClouds
5.  Select 'python wordclouds'
6.  Click 'run,' see error

**Screenshots**
<img width="1177" alt="Screen Shot 2021-10-19 at 5 07 43 PM" src="https://user-images.githubusercontent.com/89608553/137991773-32d9dbc0-4920-46d6-9f4d-dfb81ef382f7.png">
<img width="1185" alt="Screen Shot 2021-10-19 at 5 07 53 PM" src="https://user-images.githubusercontent.com/89608553/137991786-807d780a-51f4-470c-b6c4-3610a2dd2baf.png">
<img width="1184" alt="Screen Shot 2021-10-19 at 5 08 06 PM" src="https://user-images.githubusercontent.com/89608553/137991794-ba0a7b44-bacb-448b-a48c-500403f13fb4.png">
<img width="1183" alt="Screen Shot 2021-10-19 at 5 08 17 PM" src="https://user-images.githubusercontent.com/89608553/137991818-c1d9904b-0970-4899-8107-30b4a8f283e4.png">
<img width="1189" alt="Screen Shot 2021-10-19 at 5 08 27 PM" src="https://user-images.githubusercontent.com/89608553/137991914-f7fdef9a-7ee0-4f2a-9d16-63bf80052d02.png">
<img width="1185" alt="Screen Shot 2021-10-19 at 5 08 39 PM" src="https://user-images.githubusercontent.com/89608553/137991924-4fd06d77-e615-40e2-996e-8f2956854d33.png">
<img width="1188" alt="Screen Shot 2021-10-19 at 5 08 50 PM" src="https://user-images.githubusercontent.com/89608553/137991930-25557ef1-62a0-4c27-98e9-d3fd65058917.png">
<img width="1185" alt="Screen Shot 2021-10-19 at 5 08 59 PM" src="https://user-images.githubusercontent.com/89608553/137991934-991ab503-7034-4ee6-82cd-f5b5113f3e3d.png">
<img width="1187" alt="Screen Shot 2021-10-19 at 5 09 09 PM" src="https://user-imag
<img width="1185" alt="Screen Shot 2021-10-19 at 5 08 59 PM" src="https://user-images.githubusercontent.com/89608553/137992012-265c4736-c27a-413f-888b-6fa0af210338.png">
<img width="1187" alt="Screen Shot 2021-10-19 at 5 09 09 PM" src="https://user-images.githubusercontent.com/89608553/137992021-a83d7574-cdaf-4735-92a1-cc75d54ba38c.png">
<img width="1195" alt="Screen Shot 2021-10-19 at 5 09 20 PM" src="https://user-images.githubusercontent.com/89608553/137992042-e2669d5c-5c86-49e1-8243-62796a060395.png">
<img width="1188" alt="Screen Shot 2021-10-19 at 5 09 30 PM" src="https://user-images.githubusercontent.com/89608553/137992051-ffc28231-b025-4c73-a4e3-59ad8759042d.png">
<img width="1200" alt="Screen Shot 2021-10-19 at 5 09 39 PM" src="https://user-images.githubusercontent.com/89608553/137992056-fd49306a-b2b5-4e64-8850-69e436dbe341.png">
<img width="1195" alt="Screen Shot 2021-10-19 at 5 09 57 PM" src="https://user-images.githubusercontent.com/89608553/137992070-941c2d61-e3c6-45d9-80e1-a5cd921b1b00.png">
<img width="1191" alt="Screen Shot 2021-10-19 at 5 10 05 PM" src="https://user-images.githubusercontent.com/89608553/137992080-cc39fc18-e76b-4ee2-9639-c5268c8cd234.png">
<img width="1183" alt="Screen Shot 2021-10-19 at 5 10 14 PM" src="https://user-images.githubusercontent.com/89608553/137992089-3ab31dda-039d-43c8-ab60-b4c07220fb40.png">
<img width="1183" alt="Screen Shot 2021-10-19 at 5 10 24 PM" src="https://user-images.githubusercontent.com/89608553/137992094-d9f2c826-c233-4989-99d8-ab491cc9b613.png">
<img width="1190" alt="Screen Shot 2021-10-19 at 5 10 36 PM" src="https://user-images.githubusercontent.com/89608553/137992103-16945cc5-3d89-482a-82bf-0eb8039b3c9c.png">
<img width="1183" alt="Screen Shot 2021-10-19 at 5 10 45 PM" src="https://user-images.githubusercontent.com/89608553/137992114-73b2fa53-cdfc-4c7b-8435-844080d8e9cc.png">
<img width="1188" alt="Screen Shot 2021-10-19 at 5 11 06 PM" src="https://user-images.githubusercontent.com/89608553/137992127-e5ec352c-855b-491f-9a27-fba2cdb740d2.png">
<img width="1182" alt="Screen Shot 2021-10-19 at 5 11 17 PM" src="https://user-images.githubusercontent.com/89608553/137992130-43318799-b343-41d3-a931-d4c39b12d2ff.png">
<img width="1185" alt="Screen Shot 2021-10-19 at 5 11 26 PM" src="https://user-images.githubusercontent.com/89608553/137992140-84129905-cf98-4310-862e-b81bdade66ed.png">
<img width="1185" alt="Screen Shot 2021-10-19 at 5 11 34 PM" src="https://user-images.githubusercontent.com/89608553/137992144-6de5f45b-58e8-4a69-af14-7fd4a4711504.png">
<img width="1192" alt="Screen Shot 2021-10-19 at 5 11 41 PM" src="https://user-images.githubusercontent.com/89608553/137992151-a6dd4b12-e129-40ca-a191-f790931acdd9.png">
<img width="1181" alt="Screen Shot 2021-10-19 at 5 07 32 PM" src="https://user-images.githubusercontent.com/89608553/137992157-e392254e-725e-4ea0-9af8-61e29f2d5355.png">

**Desktop (please complete the following information):**
 - OS: MacOS 11.6
 - Release Version: NLP Suite 1.8.4

**Comment by DDVD233** [comment]
Hello Bill,
I think I need the information below to better understand the issue. 
- The log shows you are running an Intel Mac with 16GB of memory. Is that correct? 
- Please run `nlp` to activate nlp environment, then tun `pip freeze` to print your package versions. Please attach a screenshot of the result.
Thanks!

**Comment by BillyMartin8** [comment]
That is correct.  I will also attach an image of my MacBook Overview below.  I will also attach the results of the 'pip freeze' command.
<img width="252" alt="Screen Shot 2021-10-20 at 4 03 07 PM" src="https://user-images.githubusercontent.com/89608553/138163739-2209e14b-9f6b-4352-b0c7-5d0505f50aa0.png">
<img width="1792" alt="Screen Shot 2021-10-20 at 4 03 19 PM" src="https://user-images.githubusercontent.com/89608553/138163757-c8bcb199-a264-4d49-8d76-b6fb16d2e6f8.png">
<img width="1792" alt="Screen Shot 2021-10-20 at 4 03 34 PM" src="https://user-images.githubusercontent.com/89608553/138163761-e8fe7e24-dd86-467b-936a-d8539fc6c44e.png">

**Comment by DDVD233** [comment]
The package list looks fine. Could you try replacing your wordclouds_util.py under NLP Suite/src/ with the one I'm sending you?

Remember to unzip the file before replacing. 
[wordclouds_util.py.zip](https://github.com/NLP-Suite/NLP-Suite/files/7397312/wordclouds_util.py.zip)

**Comment by BillyMartin8** [comment]
I unzipped and replaced the wordclouds_util.py with the one you linked above, to no avail.  I am still getting the same error message as before.

**Comment by DDVD233** [comment]
The next thing I would suggest is to reinstall Python. The error signals a memory overflow, which implies a very low-level issue.

**Comment by BillyMartin8** [comment]
I attempted to reinstall python by running 'step 1' (the 'readme' document stated that running 'step 1' installs anaconda and python), but the issue continues to be present.  Is there another way for me to manually uninstall and reinstall python?  If I were to do it manually, what version of python would I install?

**Comment by Emory-NLP** [comment]
Everything OK after uninstalling and reinstalling Python.
