### ISSUE TITLE
[BUG]: Unable to update NLP Suite

### ISSUE THREAD

**Issue by iloveviola** [NLP-Suite/NLP-Suite#460]
After clicking on the update_NLP-Suite.bat, my NLP Suite version does not update to the newest available version on GitHub.

1. Close NLP Suite if running.
2. Go to setup_Windows.
3. Click on update_NLP-Suite.bat.
4. Type "y" in command line when prompted.
5. Press Enter key to exit command line.
6. Reopen NLP Suite.
7. Old version reappears.

**Expected behavior**
For newest version to appear after reopening NLP Suite.

**Screenshots**
![image](https://user-images.githubusercontent.com/89374783/138345841-fe43e2c3-ff86-4395-99f6-8bc7f28c7169.png)

**Desktop (please complete the following information):**
 - OS: Windows

**Comment by DDVD233** [comment]
Could you try running update_NLP Suite_auto.bat and try again?

**Comment by iloveviola** [comment]
Same results as previous. Does not update NLP Suite to newer version.

**Comment by DDVD233** [comment]
After you press y, is there any other output?

If you cannot see any output (because it exits too fast), try the following:

- Right-click the Windows button on the lower-left corner of your screen
- Select "Open Powershell" (or something similar to that)
- Drag and drop the update_NLP-Suite.bat to the Powershell window
- Press enter to run it
- Send me a screenshot of the output

**Comment by iloveviola** [comment]
![image](https://user-images.githubusercontent.com/89374783/139324405-9bdc2d59-28f4-478f-a099-d7b6d47ccfd8.png)

**Comment by iloveviola** [comment]
It still does not update to the newest version. Is there possibly an issue with the installation of Git?

**Comment by DDVD233** [comment]
Hi @iloveviola, the one you should run is `update_NLP Suite_auto.bat` not  `update_NLP Suite.bat`. Please try again and send me a screenshot.

It could be a problem with Git installation. You can try going through the setup instructions in [this guide](https://git-scm.com/book/en/v2/Getting-Started-Installing-Git).

**Comment by iloveviola** [comment]
![image](https://user-images.githubusercontent.com/89374783/139949735-19c0509c-ea2e-4a3c-903c-312defebd0c1.png)
![image](https://user-images.githubusercontent.com/89374783/139949774-b0aad1f6-9099-4083-962c-7b0c8763af51.png)
