### ISSUE TITLE
 SVO annotator: CoreNLP_annotator: Efficiency issue

### ISSUE THREAD

**Issue by Emory-NLP** [NLP-Suite/NLP-Suite#478]
The CoreNLP_annotator takes approximately 50 minutes to run SVO on some 200 long chapters of the seven Harry Potter books. It takes 1 hor and 30 minutes to run 1900 short NYT book reviews. Is there an issue of efficiency in the way the CoreNLP_annotator handles files?

**Comment by ClaudeHu** [comment]
I think the efficiency has been maximized. The majority of time cost of SVO was spent on running Stanford CoreNLP, and the times of calling the command "nlp.annotate(text, properties=params_NN)" has been minimized.
