### ISSUE TITLE
[BUG]: Missing License File in recent current-stable

### ISSUE THREAD

**Issue by RafaelPiloto10** [NLP-Suite/NLP-Suite#49]
**Describe the bug**
After this push: https://github.com/NLP-Suite/NLP-Suite/commit/d82a9d96f74da6793ebc2828c3cbf5c73207ecc3
The License file that the script checks for on start up went missing - appears to be deleted rather than renamed.

**To Reproduce**
1. pull the most recent version of current-stable and try to run `python NLP_menu_main.py`

**Expected behavior**
Should open NLP Suite without any errors

**Screenshots**
![image](https://user-images.githubusercontent.com/31188361/109109947-381e0c80-7704-11eb-8ec0-2b947985169e.png)

**Desktop (please complete the following information):**
 - OS: Any

**Comment by RafaelPiloto10** [comment]
@Emory-NLP, this issue appears to still be present.
These appear to be the lines that is causing the code to break:
https://github.com/NLP-Suite/NLP-Suite/blob/19f99e517b7075fdc993b1f2e5d55abe24544dc1/src/GUI_util.py#L364-L371

We could also, just add the license again to `lib`. Was this issue resolved? I pulled the recent changes and I didn't see a fix - still have the issue. Reopening issue for now.

**Comment by Emory-NLP** [comment]
Ehm. The newest release checks for the old filename first, renames it and checks. Tested extensively so we would have to ask them to change the filename

**Comment by RafaelPiloto10** [comment]
So what you are saying is that the user must change the LICENSE file to the appropriate name and move it to the `lib` folder?
The file `LICENSE-NLP-1.0.txt` does not exist either, which is why it is causing the fatal error.

**Comment by Emory-NLP** [comment]
Oh I see. Then that is problem with the push, pull, roll over, etc. That file with either name should ALWAYS be there :-(

**Comment by RafaelPiloto10** [comment]
Fixed in #59
