### ISSUE TITLE
[BUG]: File size slider prevents DBpedia from running continuously

### ISSUE THREAD

**Issue by allisonreinhardt** [NLP-Suite/NLP-Suite#490]
I'm running DBpedia on the Harry Potter corpus, and between every file, the file size slider GUI keeps coming up and will not continue processing until I click "OK." It's okay when I'm on my computer, but it will not make any progress overnight since I need to keep clicking the slider after every file.
<img width="879" alt="Screen Shot 2021-10-29 at 5 24 22 PM" src="https://user-images.githubusercontent.com/78457469/139503600-ee57f95a-adf4-4954-9c03-0815b26602f4.png">

**Comment by Emory-NLP** [comment]
You are right. Let me modify the code and re-upload. Thanks

**Comment by danielJi030** [comment]
I've encountered the same problem and would like to know if an updated version of NLP Suite has been published or not.

**Comment by Emory-NLP** [comment]
Please, check the Canvas announcement.
