### ISSUE TITLE
[BUG]: YAGO error

### ISSUE THREAD

**Issue by allisonreinhardt** [NLP-Suite/NLP-Suite#491]
I keep getting this error when I try to run YAGO.
<img width="565" alt="Screen Shot 2021-10-31 at 1 29 27 AM" src="https://user-images.githubusercontent.com/78457469/139569386-da6ec764-be61-4634-bd9b-3d659a7b9853.png">

**Comment by Emory-NLP** [comment]
Unfortunately, your screenshot does not include the first YAGO_util line that started the error. Can you upload that? But ... From the look of it, the YAGO server timed out.

**Comment by allisonreinhardt** [comment]
I ran it overnight, and it stopped at document 4.
<img width="1440" alt="Screen Shot 2021-10-31 at 9 46 55 AM" src="https://user-images.githubusercontent.com/78457469/139586710-45b06ec1-8c19-4ce0-afd0-a013ad1538c3.png">

**Comment by allisonreinhardt** [comment]
<img width="1440" alt="Screen Shot 2021-10-31 at 9 49 58 AM" src="https://user-images.githubusercontent.com/78457469/139586908-26c26540-61b5-4108-994f-fa30bb340d91.png">

**Comment by Emory-NLP** [comment]
Indeed, a timeout error from the server. I am getting similar errors as I test DBpedia and the error happens on different files every time, depending upon internet traffic (Halloween!!!). If you try to run YAGO on document 4 by itself it will run, but... that s not a solution for a large corpus. The only solution is to try at another time.
