### ISSUE TITLE
[BUG]: DBPedia INPUT bug for MAC

### ISSUE THREAD

**Issue by FentonSun** [NLP-Suite/NLP-Suite#494]
**Describe the bug**
When I select the INPUT to be files directory (192files for Harry Potter). NLP Suite actually analyzes the same txt file over and over again for 192 times.

**Screenshots**
<img width="1286" alt="屏幕快照 2021-10-31 下午1 52 28" src="https://user-images.githubusercontent.com/89586744/139595862-2bd728f8-d8b6-4f11-b7e1-60984c60bd75.png">

<img width="1362" alt="屏幕快照 2021-10-31 下午1 49 45" src="https://user-images.githubusercontent.com/89586744/139595857-a912f241-dc63-4d64-9f38-251cc96d66f6.png">

**Desktop (please complete the following information):**
 - OS: macOS Mojave
 - NLP_Suite 1.9.1

**Comment by Emory-NLP** [comment]
Try the new release. Trapping errors of all sorts has been a nightmare. Let me know if 1.9.2 works.

**Comment by FentonSun** [comment]
It's now working correctly. Thanks professor!
