### ISSUE TITLE
Potential Bug: call to python instead of python3

### ISSUE THREAD

**Issue by RafaelPiloto10** [NLP-Suite/NLP-Suite#5]
https://github.com/NLP-Suite/NLP-Suite/blob/afdef5dfd34f5c127ee336495736e5ac88846da3/src/NLP_welcome_main.py#L62

OS call using `python` instead of specifying `python3` can raise a potential bug for users who are not in the NLP environment or have anaconda installed. I am testing NLP Suite on my linux machine, and I am having issues installing anaconda with a zsh shell. Instead, I tried to run the script using my default installation of python3 with dependencies installed. 

This call:
https://github.com/NLP-Suite/NLP-Suite/blob/afdef5dfd34f5c127ee336495736e5ac88846da3/src/NLP_welcome_main.py#L62
breaks on my machine because `python` does not exist, and if it did, it would have referenced python2. This is a rare case given that most users should have anaconda installed and are expected to be in the environment, but still a bug nonetheless. Safer call may be:
`call("python3 NLP_menu_main.py", shell=True) `

**Comment by zjdavid** [comment]
If the user is not in the NLP environment, it would be an issue. All packages should be installed in the Anaconda virtual environment. If the program is called outside the NLP environment, there would be a lot of missing packages. 
With that said, you can install all the packages without using the virtual environment (although it's not recommended). So it is a good idea to switch to `python3` to enforce python3 environment. By the way, is python3 always in the system environment when you have python3 installed?

**Comment by RafaelPiloto10** [comment]
Of course. Again, this would be a very rare situation. The user must know what they're doing to take this approach. Regardless, it would be safer to call `python3` everywhere instead of using `python`. If you have python3 installed, `python3` will always be in the system environment. Anaconda will use the python version installed in the environment when using `python`, but it can also be referenced using `pythonV` where `V` is the version.

**Comment by zjdavid** [comment]
Then I think it's safe to change that. Could you make a fix?

**Comment by RafaelPiloto10** [comment]
[Windows does not have `python3`](https://stackoverflow.com/a/40931434).... Whoops! Closing this issue - We will keep the usage of `python` and hope the user is in the right environment.
