### ISSUE TITLE
[BUG]: DBPedia ontology class selection produces the same result

### ISSUE THREAD

**Issue by danielJi030** [NLP-Suite/NLP-Suite#500]
![image](https://user-images.githubusercontent.com/90074893/139605705-905b2020-3537-48ba-a858-396127ae32bf.png)

This is the screenshot of the HTML file I generated when selecting "Event" as the ontology class. Clearly, many of the words shouldn't be annotated...

This result is the same as the one I generated by selecting "Activity" as the ontology class. The ontology class selection feature is not working properly.

**Comment by scifinina** [comment]
I have the same problem, here are screenshots of my results and also the ontological categories I chose when running once (I also ran with "thing" selected and "relationship" both with the same results, so a total of three separate runs with same results)
![image](https://user-images.githubusercontent.com/90849892/139613188-35cc8597-3c35-473d-9780-1775041c4d68.png)
![Screenshot (109)](https://user-images.githubusercontent.com/90849892/139613206-f6f00380-f24d-42d6-9253-73d7c102d242.png)

**Comment by Emory-NLP** [comment]
Yes. as I mentioned in the CANVAS announcement... "The current version tags everything in the DBpedia ontology list. It also does not implement color. Will continue..." Very unclear message, I realize now. What I should have said is that regardless of ontology class and subclass selected, the NLP Suite script in its current release will ALWAYS tag everything in its ontology.
