### ISSUE TITLE
[BUG]: YAGO error prevent results from being created

### ISSUE THREAD

**Issue by ryan-anil** [NLP-Suite/NLP-Suite#501]
I get this same error every time I have tried to run a YAGO annotation. The error reports say it is a server problem but I was also confused by there being a server response present, even though I have no output html file created.
![Screenshot (32)](https://user-images.githubusercontent.com/89484984/139607086-effa4152-9dcb-437f-a067-9588b8dda45c.png)
![Screenshot (33)](https://user-images.githubusercontent.com/89484984/139607088-3393eca3-b63c-4908-bd13-2a2467d57282.png)

**Comment by Emory-NLP** [comment]
Yesterday the YAGO server must have been down. It was giving a server error all afternoon and evening. It is running again today.
