### ISSUE TITLE
[BUG]: running YAGO, anaconda SSL: CERTIFICATE_VERIFY_FAILED error

### ISSUE THREAD

**Issue by scifinina** [NLP-Suite/NLP-Suite#502]
As I was trying to run the yago program, an error that says [SSL: CERTIFICATE_VERIFY_FAILED] pops up and stops the program from completing. The preceding messages have the Anaconda file directory in them, so could this be related to anaconda?
(doesn't matter what options I choose, tried with many diff ones, Windows machine, latest NLP version)
![Screenshot (108)](https://user-images.githubusercontent.com/90849892/139614487-ee196f8d-6d96-4797-af15-959e461b74f2.png)

**Comment by Emory-NLP** [comment]
Python requires an SSL security certificate now to access web files. Both DBpedia and YAGO now temporarily setup the certificate.   When I push the new release it will avoid the warning, but this should be enabled with Python.
