### ISSUE TITLE
[BUG]: CoreNLP results in csv output file do not follow the order of files in a folder

### ISSUE THREAD

**Issue by BillyMartin8** [NLP-Suite/NLP-Suite#505]
I am running the Stanford CoreNLP parser using the Harry Potter book chapters in a folder. The files are sorted by book and chapter.

<img width="812" alt="Screen Shot 2021-11-01 at 3 03 17 PM" src="https://user-images.githubusercontent.com/89608553/139726777-c2779e26-b790-41df-a062-5b5808d54e52.png">

But when I run the algorithm, it starts processing from book7-11.

![image](https://user-images.githubusercontent.com/79026295/139730146-cacdc591-9d1d-40f3-ac4d-5b3e6299ce99.png)

As a results, he CNLL table is out of sequence, which makes it difficult to analyze the data in the proper order.

<img width="1545" alt="Screen Shot 2021-11-01 at 3 03 02 PM" src="https://user-images.githubusercontent.com/89608553/139726775-66033135-4723-4f7a-b780-69988a85ec21.png">

**PROBLEM IN THE FUNCTION def getFileList in IO_files_util?**
All algorithms rely on the function def getFileList in IO_files_util to obtain the list of files to be processed. The function works well on Windows but seems to return the files in a different order than in the folder.

**Comment by Emory-NLP** [comment]
We should use such algorithms as suggested here
https://stackoverflow.com/questions/5967500/how-to-correctly-sort-a-string-with-a-number-inside/5967539#5967539
https://stackoverflow.com/questions/21289201/read-files-sequentially-in-order
Especially here
https://nedbatchelder.com/blog/200712/human_sorting.html
