### ISSUE TITLE
[BUG]: YAGO [WinError 10060]-- program fails but then output file received later?

### ISSUE THREAD

**Issue by scifinina** [NLP-Suite/NLP-Suite#508]
**The bug**
I was running YAGO again on 1.9.5 to see if it worked, and at first it was fine. But then it fails after processing about 5 files with the WinError 10060 seen in the screenshots. I tried running YAGO immediately after with just one file, in case I just overloaded the system somehow- it finishes, the browser results pulls up the file fine, but the excel sheet is strange: it seems to be using a few of the files that were processed in the first failed YAGO run? and not the file I had just put in, which also showed the correct single text in the browser highlight file. 
After, I run the same 1-file again, and get the 10060 error. 
When the 10060 error comes up, no result files are opened/produced.
![yago error 1](https://user-images.githubusercontent.com/90849892/140001795-ab64aa0e-b7eb-44a6-a67e-8e670be12f7e.png)
![yago error 2](https://user-images.githubusercontent.com/90849892/140001801-bcd78c5a-d574-4ee4-b87f-e9ae9f6118bc.png)
![yago error 3](https://user-images.githubusercontent.com/90849892/140001806-350a561c-12a5-4b6c-9163-f225480c0e12.png)
![weird yago output](https://user-images.githubusercontent.com/90849892/140001819-b7a827f3-66f3-4f54-a175-6ec10750a535.png)

**Comment by Emory-NLP** [comment]
I am not sure what is happening with ALL severs. My nominatim no longer works, with servers errors. I fixed the issue of opening an old file... I hope.
