### ISSUE TITLE
GIS script csv LOCATIONS output file: wrong sentence with quotes in a sentence

### ISSUE THREAD

**Issue by Emory-NLP** [NLP-Suite/NLP-Suite#513]
When running the GIS script
![image](https://user-images.githubusercontent.com/79026295/140647840-03f8e728-4776-48ed-8045-60c2b996607a.png)
The extraction of sentences in the output csv file is misleading in the presence of quotes in a sentence. For instance, the following sentence in the original Indian folktale story Indian_stories_LOVING LAILI.txt 
"Who killed him?" asked Majnun.
is processed like this " asked Majnun."
![image](https://user-images.githubusercontent.com/79026295/140647805-01f655ab-07b9-4280-8e09-6beb21867408.png)

**Comment by ClaudeHu** [comment]
Stanford CoreNLP split this sentence into two.
![Screen Shot 2022-01-12 at 10 58 11 AM](https://user-images.githubusercontent.com/33562602/149175521-07d1fbda-74ce-4425-adf9-cb1254b7abea.png)
