### ISSUE TITLE
Stanford CoreNLP quote annotator bug

### ISSUE THREAD

**Issue by Emory-NLP** [NLP-Suite/NLP-Suite#515]
The CoreNLP quote annotator using the 1001 Nights_Burton folktales (e.g., King Sindibad and his Falcon.txt) produces in output the wrong identification of the speaker. For instance, his, her are not even in the sentence exported for King Sindibad and his Falcon.txt.  

![image](https://user-images.githubusercontent.com/79026295/140795620-d792bb8e-f84b-4362-9e48-35f71f33e6af.png)

**Comment by ClaudeHu** [comment]
That is a problem which comes from Stanford CoreNLP
![Screen Shot 2022-01-09 at 6 22 51 PM](https://user-images.githubusercontent.com/33562602/148705396-991bbe91-e135-419e-81a6-a7cca7004f32.png)

**Comment by Emory-NLP** [comment]
Yes, these are very weird sentences anyway...

From: ClaudeHu ***@***.***>
Sent: Monday, January 10, 2022 12:24 AM
To: NLP-Suite/NLP-Suite ***@***.***>
Cc: Franzosi, Roberto ***@***.***>; Author ***@***.***>
Subject: [External] Re: [NLP-Suite/NLP-Suite] Stanford CoreNLP quote annotator bug (Issue #515)


That is a problem which comes from Stanford CoreNLP
[Screen Shot 2022-01-09 at 6 22 51 PM]<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F33562602%2F148705396-991bbe91-e135-419e-81a6-a7cca7004f32.png&data=04%7C01%7Crfranzo%40emory.edu%7C1eaebaa815b2404ecb1608d9d3c7152d%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637773674294794193%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=dJBfrkFjmomE3uY3pXdJpQrcuol%2BTHp1uuBDLYELkUo%3D&reserved=0>

-
Reply to this email directly, view it on GitHub<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FNLP-Suite%2FNLP-Suite%2Fissues%2F515%23issuecomment-1008445445&data=04%7C01%7Crfranzo%40emory.edu%7C1eaebaa815b2404ecb1608d9d3c7152d%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637773674294794193%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=YWehmE3mVx9u%2FqXLPipcSiXtp7sFBoHi8Mw%2FgQY0IfY%3D&reserved=0>, or unsubscribe<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAS25Q57JWQAYEOE5GEKXL3TUVIKIBANCNFSM5HTKJ7PA&data=04%7C01%7Crfranzo%40emory.edu%7C1eaebaa815b2404ecb1608d9d3c7152d%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637773674294794193%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=OieTtDa3bexu%2FBDFp64PsxR8vHYdFYECzLPA0%2BHOYmA%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Crfranzo%40emory.edu%7C1eaebaa815b2404ecb1608d9d3c7152d%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637773674294794193%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=ARp1Ge%2BSWHrJwepFPUGLSaWixcc1PBBYDSqYscrHusI%3D&reserved=0> or Android<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Crfranzo%40emory.edu%7C1eaebaa815b2404ecb1608d9d3c7152d%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637773674294794193%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=udTEITjezGLIZnDvhH1dWVbt%2BFpwk9Dr7Ro3v9cWaSs%3D&reserved=0>.
