### ISSUE TITLE
[BUG]: TIPS files for this week are unavailable

### ISSUE THREAD

**Issue by allisonreinhardt** [NLP-Suite/NLP-Suite#518]
I ran the shape of stories algorithm, but when I tried to open the TIPS files so that I could analyze it (data reduction algorithms, hierarchical clustering, singular value decomposition, NMF), it said that they could not be found. 
<img width="257" alt="Screen Shot 2021-11-14 at 11 33 21 AM" src="https://user-images.githubusercontent.com/78457469/141689766-06888630-db64-4d9d-af01-f84b496a255a.png">

**Comment by Emory-NLP** [comment]
As I mentioned in class several times, there are NO TIPS files for the shape of stories...
