### ISSUE TITLE
[BUG]: Local variable error in Shape of Stories .py file

### ISSUE THREAD

**Issue by ryan-anil** [NLP-Suite/NLP-Suite#520]
When I try to run the shape of stories algorithm for any of the three types (HC, SVD, NMF), I get the same error in shape_of_stories_main.py, I checked the file and the variable 'answer' is never initialized from what I can tell.
![Screenshot (45)](https://user-images.githubusercontent.com/89484984/141697636-3c99c830-afac-4b9d-a849-c5fd00eb84b1.png)
![Screenshot (44)](https://user-images.githubusercontent.com/89484984/141697640-7ed21783-53ba-45cc-85a2-959dc815398c.png)

**Comment by Emory-NLP** [comment]
Should be fixed now. Indentation problem. With PyCharm you have to watch copying/pasting like a hawk since it re-indents lines...

**Comment by ryan-anil** [comment]
I am getting a pop-up error from the NLP Suite now when I try to press run. It says that my input directory has no txt files which is incorrect. I am trying to run the whole Indian section of the folktales but it is saying that the directory has no files in it.

**Comment by ryan-anil** [comment]
I just realized that is slightly incorrect. I need to input a csv file for the HC, SVD, or NMF processes, but when I clicked and tried to run sentiment analysis from this GUI it said that there were no txt files which was incorrect.
