### ISSUE TITLE
The Open file operation failed ERROR WITH INPUT OUTPUT CONFIGURATION

### ISSUE THREAD

**Issue by avarnaswaika** [NLP-Suite/NLP-Suite#526]
**Describe the bug**
When I try to change the input/output configuration, an error pops up.

**Screenshots**
Add screenshots to help explain your problem and indicate the error.

<img width="1440" alt="Screenshot 2021-11-16 at 4 27 35 PM" src="https://user-images.githubusercontent.com/89501720/142070413-39442cb4-0308-4b29-a2aa-bd56fd14b798.png">

**Desktop (please complete the following information):**
 - OS:

**Comment by DDVD233** [comment]
What is your OS version?

Also, I would suggest against putting any of your NLP files under iCloud drive. It will lead to a series of problems. Could you put them in a folder outside of the cloud drive?

**Comment by avarnaswaika** [comment]
version 12.0.1
it is not there in my iCloud drive

**Comment by DDVD233** [comment]
Hi @avarnaswaika,

This is a known issue on macOS 12. See [here](https://bugs.python.org/issue44828). The issue is on Apple's side. 

I would suggest you rerun step1 and step2 and see if that fixes the issue.

**Comment by avarnaswaika** [comment]
I ran step 1 and 2 again but the issue is still not fixed.
