### ISSUE TITLE
DOUBLE WINDOW OPENING ON MAC

### ISSUE THREAD

**Issue by avarnaswaika** [NLP-Suite/NLP-Suite#530]
**Describe the bug**
As soon as we press enter on the first page of the NLP suite, a warning message pops up along with an extra window.

**To Reproduce**
1. Go to open NLP suite Mac run command 
2. Click on enter 

**Screenshots**
![imp](https://user-images.githubusercontent.com/89501720/142459172-c0e34fe2-0749-480a-8e9a-9c2ea5c17b5b.jpg)

**Desktop (please complete the following information):**
 - OS
 - Release Version 2.0.4

**Comment by Jerrybibo** [comment]
This issue has been patched in the latest update.

**Comment by Jerrybibo** [comment]
This issue is largely cosmetic; will be looked at as low priority.

**Comment by Emory-NLP** [comment]
Correct. I re-opened it because you had closed but... it had not been solved. Too many other serious things to worry about.
