### ISSUE TITLE
[BUG]: Error with importing CONLL table

### ISSUE THREAD

**Issue by allisonreinhardt** [NLP-Suite/NLP-Suite#534]
I'm trying to import a CONLL table for the CONLL table analyzer, but for some reason it says that the table doesn't have the correct amount of columns.
<img width="251" alt="Screen Shot 2021-11-20 at 2 53 17 PM" src="https://user-images.githubusercontent.com/78457469/142739302-a6c1804a-f89d-4233-bb05-6d5182ee298e.png">

**Comment by FentonSun** [comment]
Same problem. My CoNLL table also has 12 columns.
