### ISSUE TITLE
[BUG]: CoNLL table analyzer stuck

### ISSUE THREAD

**Issue by FF15enc** [NLP-Suite/NLP-Suite#536]
**Describe the bug**
CoNLL Table Analyzer stuck on the first analysis tool. I left it overnight last night and it was still stuck after 12 hours of run time. Tried again after 2.0.7 to no luck. 

**To Reproduce**
Run CoNLL table analyzer with any variation of analysis selected. 

**Screenshots**

![23221637528931_ pic](https://user-images.githubusercontent.com/78893139/142779088-4592b517-b2fe-483a-994b-d8bb66ff1c1a.jpg)

**Desktop (please complete the following information):**
 - OS: OSX 
 - Release Version 2.0.7

**Comment by Emory-NLP** [comment]
Can you post a screenshot of your CoNLL table such as this?
<img width="915" alt="image" src="https://user-images.githubusercontent.com/79026295/142782411-33003af9-a161-4a95-8e3b-37d0dc12539a.png">

**Comment by FF15enc** [comment]
<img width="912" alt="Screen Shot 2021-11-21 at 6 08 04 PM" src="https://user-images.githubusercontent.com/78893139/142782551-6d4c2e0d-cbca-44a4-84df-3fcf5bab9875.png">
)

**Comment by Emory-NLP** [comment]
OK, You do have the correct CoNLL. Could you send me the zipped file by email?

**Comment by BillyMartin8** [comment]
I am also encountering this issue.  I have attached a screenshot of my terminal and input CoNLL table below.
<img width="567" alt="Screen Shot 2021-11-21 at 5 29 52 PM" src="https://user-images.githubusercontent.com/89608553/142935643-c08615b6-1bd6-4c51-acb5-a548d3635071.png">
<img width="1286" alt="Screen Shot 2021-11-22 at 4 11 50 PM" src="https://user-images.githubusercontent.com/89608553/142935914-c5b7d1c4-a901-44bf-91a4-276aa73acd92.png">
