### ISSUE TITLE
[BUG]: NLP Suite External Software

### ISSUE THREAD

**Issue by jsmontg** [NLP-Suite/NLP-Suite#583]
I am stuck on setting up Mallet, Wordnet, or Google Earth Pro. I have them installed on my Mac, but when it asks me to select the location of the folder for each software, it says:

 
The selected software directory

/Users/username/Downloads/mallet-2.0.8/src/cc/mallet'

is NOT the expected Mallet directory. The directory should contain, among other things, the directories 'bin' and 'class'. DO MAKE SURE THAT WHEN YOU UNZIP THE MALLET ARCHIVE YOU DO NOT END UP WITH A MALLET DIRECTORY INSIDE A MALLET DIRECTORY.

and

The selected software directory

/Users/username/nltk_data/corpora/wordnet'

is NOT the expected WordNet directory. The directory should contain, among other things, the directories 'dict' and 'src'. DO MAKE SURE THAT WHEN YOU UNZIP THE WORDNET ARCHIVE YOU DO NOT END UP WITH A WORDNET DIRECTORY INSIDE A WORDENET DIRECTORY.

and for Google Earth Pro, I cannot locate the folder for it on my Mac.

**Comment by Jerrybibo** [comment]
For your three issues:

1. For Mallet, make sure your directory is set to `mallet-2.0.8/`, and not the `mallet` inside `mallet-2.0.8/src/cc/`.
i.e., your directory should be `/Users/username/Downloads/mallet-2.0.8`.
2. For WordNet, I'm not sure where you obtained your software, but be sure to download it from [https://wordnet.princeton.edu/download/current-version](https://wordnet.princeton.edu/download/current-version). (Look for WordNet-3.0.tar.gz.)
If the link does not work, try right-clicking and copying the link, then pasting it into a new browser tab.
Once the file has finished downloading, extract the files and point the software directory to that folder.
If properly set up, your directory for WordNet should be `/Users/username/Downloads/WordNet-3.0`, assuming you extracted it to your Downloads folder.
3. For Google Earth Pro, the installation directory should be `/Applications/Google Earth Pro.app` under default installation settings.

For all of the above, you can also manually modify where NLP-Suite goes to look for software by clicking the button to the right of "Setup External Software" on the main operating screen.

Let me know at github@jerry.games if there are further issues.
