### ISSUE TITLE
Stanford CoreNLP error when running * (gender, quote, NER normalized date)

### ISSUE THREAD

**Issue by Emory-NLP** [NLP-Suite/NLP-Suite#591]
Running Stanford_CoreNLP_main with the Murphy file in input and * for CoreNLP annoators
<img width="954" alt="image" src="https://user-images.githubusercontent.com/79026295/151618010-f9f2ad82-a0e3-44c8-863f-e7c1d508f678.png">

leads to the following error:

<img width="688" alt="image" src="https://user-images.githubusercontent.com/79026295/151618240-b1790f31-a209-496b-b32b-cec248e72b9e.png">

**Comment by cynthiadwq** [comment]
Found the bug that causes this error. Will send fix soon.

**Comment by Emory-NLP** [comment]
Th fix did eliminate the bug itself but, two problems persist.
1. It produces this warning
<img width="308" alt="image" src="https://user-images.githubusercontent.com/79026295/151648160-a842aacd-eaf5-4a71-89de-c7766cc5a921.png">
2. The dictionary-annotated html file has no gender tags. Neither problem occurs wen running the gender annotator by itself rather than as *
<img width="942" alt="image" src="https://user-images.githubusercontent.com/79026295/151648207-717e48d7-8045-45ec-a489-f0947cce7b87.png">
