### ISSUE TITLE
[BUG]: Python WordClouds not fixed in 2.3.9

### ISSUE THREAD

**Issue by Kyle-Lou** [NLP-Suite/NLP-Suite#598]
**Describe the bug**
The previous bug of Python Wordscloud is fixed but there is a new error which stops me from producing the result 

**To Reproduce**
just run the Python wordclouds, click any box and run

**Screenshots**
![239](https://user-images.githubusercontent.com/77580846/152086898-56367eea-628d-477c-ac0f-999ad16708ba.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Release Version: NLP 2.3.9

**Additional context**

**Comment by Emory-NLP** [comment]
It looks like a file in your corpus has utf-8 encoding problems. Run the utf-8 compliance test.
