### ISSUE TITLE
MALLET Topic Modeling Bar Chart Hangs on Access

### ISSUE THREAD

**Issue by Jerrybibo** [NLP-Suite/NLP-Suite#608]
The Excel workbook generated by the MALLET Topic Modeling routine (under Corpus Analysis Tools) hangs while attempting to load the bar chart.

For my specific instance, I attempted to perform MALLET topic modeling on the `ina` directory of the POTUS speeches with 20 topics, on Windows. The NLP-Suite version is 2.4.8.

Bug Reproduction:
1. Enter GUI by running "Topic modeling (via MALLET)" under "CORPUS Analysis Tools"
2. Ensure that the corpus is properly selected and the output directory correct.
3. Locate the bar chart Excel workbook after the program completes analysis (named `NLP_Mallet_TM_NLP-Mallet_Output_Keys_bar_chart`) and load all sheets.
4. Select sheet 2 ("Chart").

**Comment by Jerrybibo** [comment]
Please leave a comment if you are able to view the bar chart, and the specs used to generate such chart.

**Comment by Emory-NLP** [comment]
Please, always add a screenshot of the GUI involved so that we can see which release you are running.

**Comment by Jerrybibo** [comment]
Issue persists with 2.4.9 on my device.

**Comment by Emory-NLP** [comment]
Please, add screenshots of the MALLET GUI and of the Excel csv file.

**Comment by Jerrybibo** [comment]
It would be the most efficient if you could perform the bug reproduction steps as detailed above, but here are the screenshots:

MALLET UI
![image](https://user-images.githubusercontent.com/59254806/152705317-86fe9dbd-61bf-4546-b0a5-c8791721e64b.png)

Executes without error, taking 6 seconds on local machine.

Excel CSV file in question: 
Sheet 1 (Excel Data):
![image](https://user-images.githubusercontent.com/59254806/152705365-180f8cb1-ec11-47a1-951e-c5d81659463a.png)

Sheet 3 (Labels):
![image](https://user-images.githubusercontent.com/59254806/152705379-8766bdac-9d3a-497b-abad-bf4250f112de.png)

Sheet 2 (Chart):
![image](https://user-images.githubusercontent.com/59254806/152705392-c79a8072-b66a-45c2-a7f5-572e1165bf39.png)

It is clear that the computer is performing some form of computation according to Task Manager:
![image](https://user-images.githubusercontent.com/59254806/152705415-64e94c2e-fdfd-47f1-8777-8815e5439e64.png)

but the workbook is stuck as "Not responding."

**Comment by Emory-NLP** [comment]
The file barchartsample.xlsm somehow got corrupted. Restored and problem solved.
