### ISSUE TITLE
Issue with running StanfordCoreNLP parser with specific Java versions

### ISSUE THREAD

**Issue by Kyle-Lou** [NLP-Suite/NLP-Suite#612]
**Describe the bug**
When I run the corenlp parser, it pops up errors as shown in the picture below.

**To Reproduce**
1. Go the StanfordCoreNLP
2. Run the parser with a random file

**Screen
![1644359005(1)](https://user-images.githubusercontent.com/77580846/153086329-b63919aa-e272-4106-98ac-8e948428e7e2.png)
shots**

![1644359070(1)](https://user-images.githubusercontent.com/77580846/153086338-c88e70f2-370f-42fc-a6cb-0f5b163fd45b.png)

**Desktop (please complete the following information):**
 - OS: Windows X64
 - Release Version: 2.5.1

**Additional context**

**Comment by Jerrybibo** [comment]
I can reproduce this error on my machine. I am taking a look into it.

**Comment by Emory-NLP** [comment]
-d64 is passed to the Stanford server to use 64 bits JAVA, normally set to 32 as default. Which Java version have you installed?

**Comment by Kyle-Lou** [comment]
17.0.1 64-bit

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Emory-NLP** [comment]
Is it Java JDK?

From: Yizhou Lou ***@***.***>
Sent: Wednesday, February 9, 2022 10:19 PM
To: NLP-Suite/NLP-Suite ***@***.***>
Cc: Franzosi, Roberto ***@***.***>; Comment ***@***.***>
Subject: [External] Re: [NLP-Suite/NLP-Suite] [BUG]: Issue with running StanfordCoreNLP parser on windows machine in version 2.5.1 (Issue #612)

17.0.1 64-bit

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Kyle-Lou** [comment]
how to check the jdk

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Jerrybibo** [comment]
@YizhouLou, to check the JDK version, the fastest way is to:
1. Open up Command Prompt (type cmd.exe into the search bar);
2. Type `java -version` and hit enter;
3. Report the number you find there.

I am aware that the script is written for Java 8 and most people nowadays should have 14+. I personally have 16 (16.0.1). I am actively trying to figure out a workaround for this problem.

**Comment by Kyle-Lou** [comment]
yeah, I think my version is java17

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Jerrybibo** [comment]
I have just walked it through with @YizhouLou, but I thought I'd leave a record here just in case:

There is a way of solving this problem while maintaining multiple Java versions, by fiddling with the `PATH` variable.
Of course, as a developer I believe that there needs to be a better fix than the one below.

It's kind of long, but read carefully as to not miss any steps.

## Checking/Installing Java 8
Let's first check whether you have a valid Java 8 installation. This can be done by typing "Configure Java" in Windows Search. If no app pops up, then just download Java 8 from the link below and set it up.

Open that "Configure Java" app and go to tab 3 ("Java"), then hit the "View..." button.
You should see a table, with one or more rows populated. One row must start with 1.8; it there is not, install Java 8 as below.
If there is, **take note of the 4th field ("Path")**. Copy it down to an empty Notepad file for reference.

In any case, if you don't have a 64-bit Java 8 installed (or you're not sure), [here is Java 8's download link](https://www.java.com/en/download/). Be sure that the website says Java 8 before downloading, and complete the installation, removing any outdated Java 8 installations along the way.

**Note the Java update version as you download.** It is the 3-digit number after `jre-8u` and before `-windows-x64`. At the time of writing, the Java update version is 321.

## Configuring PATH
1. Open System Properties > Advanced. You can access this through typing "PATH" in Windows Search. The window should be as follows:
![image](https://user-images.githubusercontent.com/59254806/153334000-90ecf570-5183-4e38-a43c-a5a0554aafc2.png)
2. Click on Environment Variables.
3. Find "Path" under the "System variables" table, then double click on it.
4. Click "New" on the right side, then enter `C:\Program Files\Java\jre1.8.0_XXX\bin` into the newly created field, and replace the `XXX` with the 3-digit update version you found above.
    * Alternatively, paste the "Path" you found from Configure Java into the field, removing the trailing `\javaw.exe`.
5. Select that field you just created, then click "Move Up" until it is at the top.
Your window should look like this (Don't worry about row 2+):
![image](https://user-images.githubusercontent.com/59254806/153345145-3ea11911-e175-4067-ac2d-5aab25802306.png)
 
Now close down everything (by hitting OK) and restart NLP-Suite; Stanford CoreNLP should run fine.

**Comment by Jerrybibo** [comment]
Reopened as a feature enhancement request, and for record-keeping for other students who may be encountering the same issue.

**Comment by Emory-NLP** [comment]
From what I see the Java implementation you display is JRE. According to Stanford CoreNLP that should not work. You need JDK. This is what my environment variables look like.
<img width="365" alt="image" src="https://user-images.githubusercontent.com/79026295/153408685-3653b81f-0315-452e-a31c-82d3386cfc4b.png">

**Comment by Emory-NLP** [comment]
Perhaps we need to further improve the function
def check_java_installation(script):
in IO_libraries_util
In that function we simply check if Java is installed ad which version via java -version which only lists the version number. To find out whether java is jre or jdk we need to search in Path in Environment variables (as shown in image here)
https://www.techiedelight.com/check-environment-variables-python/ 
I implemented the os.environ test. Should work better now.

**Comment by Jerrybibo** [comment]
> From what I see the Java implementation you display is JRE. According to Stanford CoreNLP that should not work. You need JDK. This is what my environment variables look like. <img alt="image" width="365" src="https://user-images.githubusercontent.com/79026295/153408685-3653b81f-0315-452e-a31c-82d3386cfc4b.png">

To my knowledge this is incorrect.
There is no mention of a JDK requirement (only Java) on the indexed Stanford CoreNLP page: https://www.google.com/search?q=site%3Astanfordnlp.github.io+JDK
Neither is there a logical need for it, as we are not re-compiling raw Java code: https://www.java.com/en/download/help/techinfo.html

I have helped multiple people by installing the Runtime and it has worked fine. I respectfully disagree with this.

**Comment by Emory-NLP** [comment]
You may be right. It may well be an old requirement. Keep in mind that the Stanford website does not always tell you exactly what you need. Several websites on CoreNLP recommend JDK. See a couple here.
https://cloudacademy.com/blog/natural-language-processing-stanford-corenlp/
http://www.linguisticsweb.org/doku.php?id=linguisticsweb:tutorials:automaticannotation:stanford_core_nlp:stanford_core_nlp_3.9.2

**Comment by Emory-NLP** [comment]
In reality, we do not know why Kyle's code failed (and for other rare Windows users ). Two reasons:
1. Java 17
2. Java JRE, rather than JDK
Ideally, we should re-install Java JDK 17 on Kyle's machine and see whether that would work.
