### ISSUE TITLE
NLP Suite Version 2.4.6 update error

### ISSUE THREAD

**Issue by adrianevalencia** [NLP-Suite/NLP-Suite#613]
When closing NLP Suite in order to initiate the update, the command console throws this error: 
```
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "NLP_menu_main.py", line 30, in exit_handler
    update_self(window,GUI_util.GitHub_release_version_var.get())
  File "C:\Users\Adrian Valencia\Desktop\Documents\QTM 190\NLP-Suite-current-stable\src\update_util.py", line 24, in update_self
    if Repository('.').head.shorthand == 'current-stable':
_pygit2.GitError: reference 'refs/heads/master' not found
```

 - OS: Windows 10
 - Release Version (2.4.6)

**Comment by DDVD233** [comment]
Could you try the following:
- Download the latest version directly from Github through [this link](https://github.com/NLP-Suite/NLP-Suite/archive/refs/heads/current-stable.zip)
- extract the setup_Windows folder, **overwrite** your old setup_Windows folder with the new ones
- Run step2 again
Thanks
