### ISSUE TITLE
update error

### ISSUE THREAD

**Issue by Emory-NLP** [NLP-Suite/NLP-Suite#620]
The automatic update script gives this error... Could we actually trap Git's response to have a better idea f what is happening?

<img width="684" alt="image" src="https://user-images.githubusercontent.com/79026295/153971864-f3e41adb-b731-4348-b7cc-5eedfdadbe3a.png">

**Comment by DDVD233** [comment]
Instead of 
```
except:
    mb.warning('ERROR!')
```
We can do this
```
except Exception as e:
   mb.warning(e);  # or print(e)
```
This will print the error.

**Comment by Emory-NLP** [comment]
Good point. Thank you.

Roberto
Sent from my iPhone

On Feb 15, 2022, at 17:28, DDavid ***@***.***> wrote:

﻿

Instead of

except:
    mb.warning('ERROR!')


We can do this

except Exception as e:
   mb.warning(e);  # or print(e)


This will print the error.

—
Reply to this email directly, view it on GitHub<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FNLP-Suite%2FNLP-Suite%2Fissues%2F620%23issuecomment-1040861500&data=04%7C01%7Crfranzo%40emory.edu%7C0ad962b9efa54c74132f08d9f0d28a78%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637805609328549499%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=X%2Ftv5kJN0WSBjrQRHs8LhzWKbp06CJ7RiK7Zthfixuk%3D&reserved=0>, or unsubscribe<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAS25Q534V4K4JAO6LDHHYKTU3LHSDANCNFSM5ONAXBSA&data=04%7C01%7Crfranzo%40emory.edu%7C0ad962b9efa54c74132f08d9f0d28a78%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637805609328549499%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=z9brmHPyPy4tiwrTcY5nQpZeg0QvZn6DQaLnA2sq81o%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Crfranzo%40emory.edu%7C0ad962b9efa54c74132f08d9f0d28a78%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637805609328549499%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=tuQcKVi2krGLKXMy5bVTeY1hiE%2Fr2dH7FTZh6LtaKas%3D&reserved=0> or Android<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Crfranzo%40emory.edu%7C0ad962b9efa54c74132f08d9f0d28a78%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637805609328549499%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=LrtrNU49%2Bm%2BEhsuzZCf4XrrhIyGGhMCSIpftPZ47cIg%3D&reserved=0>.

**Comment by Emory-NLP** [comment]
Done!

From: DDavid ***@***.***>
Sent: Tuesday, February 15, 2022 5:29 PM
To: NLP-Suite/NLP-Suite ***@***.***>
Cc: Franzosi, Roberto ***@***.***>; Author ***@***.***>
Subject: [External] Re: [NLP-Suite/NLP-Suite] update error (Issue #620)


Instead of

except:

    mb.warning('ERROR!')

We can do this

except Exception as e:

   mb.warning(e);  # or print(e)

This will print the error.

-
Reply to this email directly, view it on GitHub<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FNLP-Suite%2FNLP-Suite%2Fissues%2F620%23issuecomment-1040861500&data=04%7C01%7Crfranzo%40emory.edu%7C0ad962b9efa54c74132f08d9f0d28a78%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637805609328549499%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=X%2Ftv5kJN0WSBjrQRHs8LhzWKbp06CJ7RiK7Zthfixuk%3D&reserved=0>, or unsubscribe<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAS25Q534V4K4JAO6LDHHYKTU3LHSDANCNFSM5ONAXBSA&data=04%7C01%7Crfranzo%40emory.edu%7C0ad962b9efa54c74132f08d9f0d28a78%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637805609328549499%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=z9brmHPyPy4tiwrTcY5nQpZeg0QvZn6DQaLnA2sq81o%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Crfranzo%40emory.edu%7C0ad962b9efa54c74132f08d9f0d28a78%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637805609328549499%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=tuQcKVi2krGLKXMy5bVTeY1hiE%2Fr2dH7FTZh6LtaKas%3D&reserved=0> or Android<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Crfranzo%40emory.edu%7C0ad962b9efa54c74132f08d9f0d28a78%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637805609328549499%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=LrtrNU49%2Bm%2BEhsuzZCf4XrrhIyGGhMCSIpftPZ47cIg%3D&reserved=0>.
