### ISSUE TITLE
[BUG]: GIS pipeline error

### ISSUE THREAD

**Issue by nams1012** [NLP-Suite/NLP-Suite#629]
**Describe the bug**
We are using the NYT Book Reviews corpus. I ran the text to map tool on the corpus. When it ran the GIS pipeline, it stopped at 9984/12288, producing a socket.timeout error. I have attached a screenshot of the error.

**Screenshots**
<img width="1440" alt="Screenshot 2022-02-18 at 8 51 13 PM" src="https://user-images.githubusercontent.com/100006272/154781652-72c404d9-3323-40a6-ac07-58df5335f244.png">

**Desktop (please complete the following information):**
 - OS: Mac OS X
 - Release Version : NLP Suite version 2.6.0

**Additional context**

**Comment by Emory-NLP** [comment]
Are you using Nominatim or Google for geocoding? You may need to split the corpus in two parts.

**Comment by nams1012** [comment]
> Are you using Nominatim or Google for geocoding? You may need to split the corpus in two parts.

We used Nominatim

**Comment by nams1012** [comment]
I split the corpus into two parts but got the same error when I reached the same location as the last time.
