### ISSUE TITLE
[BUG]: Connection error while trying to run SVO Extractor

### ISSUE THREAD

**Issue by nams1012** [NLP-Suite/NLP-Suite#647]
When I try to run the SVO Extractor, I instantly get a connection error and have no idea how to fix it.

<img width="1440" alt="Screenshot 2022-02-26 at 5 34 10 PM" src="https://user-images.githubusercontent.com/100006272/155861215-70379d46-7e1d-4bad-94ef-550a7b733415.png">

 - OS: OS X
 - Release Version : 2.7.1

**Comment by cynthiadwq** [comment]
Could you provide more context on this issue? Were you on VPN when running the script? Did you try restart terminal/laptop and rerun the script?

**Comment by nams1012** [comment]
I was not on VPN and I did try restarting the terminal, but still got the same error.

**Comment by Emory-NLP** [comment]
Could you also add a screenshot of the entire GUI so we know which options you are using?

**Comment by nams1012** [comment]
Yes, here is a screenshot of the GUI.
<img width="1397" alt="Screenshot 2022-02-26 at 10 19 22 PM" src="https://user-images.githubusercontent.com/100006272/155866793-92f33ddc-b515-4ae2-b9ed-a26bf57f5107.png">

**Comment by nams1012** [comment]
Although I believe I got the same error when I was running the same thing without S&O gender and S&O speaker. I also had the same error when I tried to run it without coreference.
