### ISSUE TITLE
[BUG]: SENNA SVO extractor failed to generate output file

### ISSUE THREAD

**Issue by ChenQi0320** [NLP-Suite/NLP-Suite#649]
**Describe the bug**
When i run the SENNA SVO extractor, it say finish running but can not produce output files.

**To Reproduce**
Just run the SENNA SVO extractor on the whole corpus.

**Desktop (please complete the following information):**
 - OS: 
<img width="704" alt="Screen Shot 2022-02-26 at 11 38 04 PM" src="https://user-images.githubusercontent.com/98725367/155889645-3508cab4-103f-468f-be07-654e480b6288.png">
OS X

**Additional context**

**Comment by Emory-NLP** [comment]
Have you checked the output directory hat the Senna files are there?

**Comment by ChenQi0320** [comment]
> 

Yes, i did. And i have seen that a new folder is created but that folder is empty
<img width="1184" alt="Screen Shot 2022-02-27 at 11 18 44 AM" src="https://user-images.githubusercontent.com/98725367/155890382-49ab7b63-0d9c-4e37-bd25-f09013891ece.png">
.

**Comment by Emory-NLP** [comment]
Can you please upload a screenshot of the GUI with all the options you are using to run SENNA? Also, can you specify where the SVO_Dir_All folder is?

**Comment by ChenQi0320** [comment]
> Can you please upload a screenshot of the GUI with all the options you are using to run SENNA? Also, can you specify where the SVO_Dir_All folder is?

Yes. Here is the screenshot for the options i chose.
![WechatIMG945](https://user-images.githubusercontent.com/98725367/155890614-cafb1267-1b02-461a-b399-1068441a71ae.jpeg)

And when i run it i assign the output directory as
"/Users/chenqi/Desktop/emory/2022Spring/QTM446w/OUTPUT/SVO_SENNA" The SVO_Dir_All folder is created within it.
