### ISSUE TITLE
Manual coref Find/search - 2 bugs

### ISSUE THREAD

**Issue by Emory-NLP** [NLP-Suite/NLP-Suite#662]
The Find/search function only searches the right-hand panel. Should search either both panel or whichever panel you click on to select?

<img width="612" alt="image" src="https://user-images.githubusercontent.com/79026295/157672407-90476e35-8200-4e00-8861-954f7a903664.png">

There is also no way to close the Find bar.

**Comment by DDVD233** [comment]
The first part is fixed by branch FIX/find_bar_issue. You can pull that branch directly from Roberto, and I think it is unlikely it will cause a conflict.

For the second part, why do we want to close the find bar?

**Comment by Emory-NLP** [comment]
It is good. Could we set the focus on the search bar when hitting Ctrl+F?
