### ISSUE TITLE
[BUG]: Index Out of Range for Indain Folktale Sentiment Analysis

### ISSUE THREAD

**Issue by tonychengu** [NLP-Suite/NLP-Suite#674]
![Screenshot (470)](https://user-images.githubusercontent.com/45869998/161397800-ba954943-f76f-49cb-a068-913f8d4adc96.png)
Only exist with Indian folktale. Have run it twice and reported the same issue.

**Comment by xxlin-haa** [comment]
I ran into same issue on Chinese folktales

**Comment by Emory-NLP** [comment]
I ran the algorithms on the entire collection of cross-country folktales. It worked just fine. It looks to me like this is a memory error. You can try to run it separately on the Indian (or Chinese) corpus and perhaps try to trap the error.
