### ISSUE TITLE
[BUG]: Sentence Complexity analysis cannot be excuted due to "Assertion Error"

### ISSUE THREAD

**Issue by Kyle-Lou** [NLP-Suite/NLP-Suite#687]
**Describe the bug**
I cannot run the sentence complexity analysis on my NLP Suite 2.9.0

**To Reproduce**
1. Go to Sentence Analysis
2. Click on Sentence Complexity
3. Hit run

**Screenshots**
![1650500979(1)](https://user-images.githubusercontent.com/77580846/164346237-05dff338-d107-4a6f-ab2a-a7e3979d7d7d.png)
![1650500990(1)](https://user-images.githubusercontent.com/77580846/164346293-54b18d39-2f1a-4796-a258-47a10cb2cfd5.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Release Version NLP 2.9.0

**Additional context**

**Comment by Emory-NLP** [comment]
Hopefully, Mino, who wrote the function will solve the problem.

**Comment by ckalsdh** [comment]
@YizhouLou at which file do you get an error? Does the error occur from the beginning?

**Comment by Kyle-Lou** [comment]
i used the ina file in POTUS, i think the error doesn't appear until the later part (after all the files are processed).

**Comment by ckalsdh** [comment]
<img width="1368" alt="image" src="https://user-images.githubusercontent.com/31490043/164357230-3e71778a-f79d-47ad-b8be-b28e2133c5b1.png">
I just tried POTUS ina and get an output. The issue might be the different version of stanza. Can you try this command inside NLP environment?
`pip install –force-reinstall git+https://github.com/stanfordnlp/stanza.git@dev`

**Comment by Kyle-Lou** [comment]
I have a memory error this time...
FYI, my computer has a 16G RAM
![1650509051(1)](https://user-images.githubusercontent.com/77580846/164361291-756e8378-1412-4e7f-9288-dec7dc89edb3.png)

**Comment by ckalsdh** [comment]
Okay this error seems familiar. Can you try these two commands again?
pip install –force-reinstall spacy
pip install –force-reinstall git+https://github.com/stanfordnlp/stanza.git@dev

**Comment by Kyle-Lou** [comment]
don't seem to work
![1650510628(1)](https://user-images.githubusercontent.com/77580846/164364124-9ca49c74-0ea5-427c-838e-f933a0438e8f.png)
