### ISSUE TITLE
[BUG]: Cannot execute Nominalization GUI

### ISSUE THREAD

**Issue by Kyle-Lou** [NLP-Suite/NLP-Suite#688]
**Describe the bug**
When I try to run the Nominalization GUI, this error shows up

**To Reproduce**
1. Go to Style Analysis
2. Click on Nominalization GUI
4. See error in command line

**Screenshots**
![1650510723(1)](https://user-images.githubusercontent.com/77580846/164364385-288b2daf-c1d1-4df4-b978-f555405f5bc3.png)
![1650510772(1)](https://user-images.githubusercontent.com/77580846/164364407-c2bfbf7e-e3b9-4340-8d46-766a58b5cbf6.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Release Version 2.9.0

**Additional context**
I ran the "ina" file in POTUS

**Comment by Emory-NLP** [comment]
For Nominalization, take a look at Issue #533 Nominalization with pywsd (python word sense disambiguation) for a possible solution.

**Comment by YizhouLou** [comment]
yes, I have followed the instruction in the tips file to pip install pywsd. Actually, I even tried to reinstall the pywsd. But they didn't work for me.

**Comment by Kyle-Lou** [comment]
Thank you professor, it worked for me after reinstalling the wordnet. Also, I suggest that this help windows can be updated to include the instruction to reinstall wordnet, as reinstalling pywsd alone doesn't solve the problem.
