### ISSUE TITLE
"Fatal Error" with nominalization

### ISSUE THREAD

**Issue by oliturner21** [NLP-Suite/NLP-Suite#689]
Throws fatal error even though the python requirements are already satisfied.
<img width="567" alt="Screen Shot 2022-04-21 at 1 00 21 PM" src="https://user-images.githubusercontent.com/66083697/164512893-596c36e4-3456-4ab7-9d01-e49ef1577684.png">
<img width="1397" alt="Screen Shot 2022-04-21 at 1 00 01 PM" src="https://user-images.githubusercontent.com/66083697/164512896-a75826bd-9757-4de3-9c70-331a7df38217.png">

**Comment by Allytaih** [comment]
Installing the following two in the NLP environment fixed it for me:
pip install pywsd~=1.2.4
pip install wn==0.0.23
