### ISSUE TITLE
[BUG]: Incomplete Headers For WordNEt csv Output in the whats_in_your_corpus

### ISSUE THREAD

**Issue by tonychengu** [NLP-Suite/NLP-Suite#719]
With the sample data, the output for the "what else in your corpus" produces csv with incomplete headers that make it hard for pandas to parse it.
<img width="537" alt="image" src="https://user-images.githubusercontent.com/45869998/171732445-243f61a1-a6e9-4b4a-8849-6f5b676e5f3f.png">

**Comment by Emory-NLP** [comment]
The Java script WordNet_Search_UP.jar needs to be edited to loop through the max number of intermediate synsets to create all the appropriate headers as Intermediate Synset 1, Intermediate Synset 2, Intermediate Synset 3, ...
Unfortunately, the number of Intermediate Synsets varies with top synset but... we should add the appropriate headers in the csv output file editing appropriately the Java script.
