### ISSUE TITLE
Python Plotly Miss Packages: Homework 1

### ISSUE THREAD

**Issue by bianshuyang** [NLP-Suite/NLP-Suite#739]
**Describe the bug**
As shown in the image below:
<img width="1331" alt="image" src="https://user-images.githubusercontent.com/52821055/187001713-4cae8101-c1fd-4da6-8c38-7ad515c4f221.png">
Error Message from back-end:
Traceback (most recent call last):
  File "/Users/simonbian/anaconda/envs/NLP/lib/python3.7/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "charts_Excel_main.py", line 88, in <lambda>
    column_hover_list)
  File "charts_Excel_main.py", line 51, in run
    data_to_be_plotted = charts_Excel_util.prepare_data_to_be_plotted_inExcel(inputFilename_name, selected_series, chart_type, 0)
NameError: name 'charts_Excel_util' is not defined

**To Reproduce**
1. Go to "Graphical User Interface (GUI) for Excel Charts" under "Excel Chart" under "Visualization tools"
2. Click on Run when inputting an outputed csv file selecting the x axis column as document id and y axis as count from file such as NLP_corpus_stats_XYZXYZXYZ_sent_group_stats.csv:
3. 
<img width="1148" alt="image" src="https://user-images.githubusercontent.com/52821055/187001960-95fa09fa-c60e-47dd-ad96-b03b3ad74324.png">

5. Scroll down to Select Excel chart type as bar, and automatically compute chart select any of the three option
6. See error

**Screenshots**
As above

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Release Version 3.1 / 3.0.1

**Additional context**
This is for a prompt in Homework 1, says "Visualize the results in Excel and plotLy. "
This is why the issue is raised.

**Comment by Emory-NLP** [comment]
I expect there to be several bugs of this type due to filename or variable name changes. Fixed in 3.0.2. Keep in mind that most algorithms will produce automatically either Excel or plotLy charts. The Excel chart GUI is one of the first developed in the NLP Suite and we have not kept up with testing/development.
