### ISSUE TITLE
Cannot install stanza / stanza reported to be missing

### ISSUE THREAD

**Issue by bianshuyang** [NLP-Suite/NLP-Suite#741]
**Describe the bug**
(https://stanfordnlp.github.io/stanza/download_models.html)
The page is supposed to be link to download, no button / hyperlink was found.
Github package was downloaded, but was unable to be recognized by NLP suite as below.
It appears Stanza can be used without any specification?
<img width="1096" alt="image" src="https://user-images.githubusercontent.com/52821055/187041979-19f828ca-5129-429e-baf1-0419718edb65.png">

**To Reproduce**
<img width="864" alt="image" src="https://user-images.githubusercontent.com/52821055/187042353-48200e43-f650-4610-8410-ca47331330cf.png">
The above is what I selected.
<img width="326" alt="image" src="https://user-images.githubusercontent.com/52821055/187042361-0e0d4f50-0f2b-47d2-b7c4-19c6e2cd48de.png">
The error message above.
I am confused, what is the link to which I can download a stanza? Or, have I been doing it correctly in that Stanza require no installation? I found stanza in the site packages under the Anaconda environment though, and even selecting that doesn't work.

**Desktop (please complete the following information):**
 - OS: [e.g. OS X]
 - Release Version (type 3.0.2)

**Comment by Emory-NLP** [comment]
Correct. Stanza is installed automatically as a Python package. Problem corrected in 3.0.3 along with other unnecessary installation warnings.
