### ISSUE TITLE
unable to open NLP Suite

### ISSUE THREAD

**Issue by chelfen** [NLP-Suite/NLP-Suite#743]
I was able to open the NLP Suite yesterday and this afternoon. I closed it a couple hours ago and when I tried to enter again just now (by clicking the "Enter NLP Suite" button), I receive this error message:

<img width="564" alt="Screen Shot 2022-08-27 at 6 14 03 PM" src="https://user-images.githubusercontent.com/97575241/187049820-c92a3af9-17bc-4d00-8c48-7aef0e9216ba.png">

An icon for Python pops up at the bottom of my screen, bounces a couple times and then disappears, leaving me stuck at the opening screen.

<img width="60" alt="Screen Shot 2022-08-27 at 6 16 42 PM" src="https://user-images.githubusercontent.com/97575241/187049830-77e5ac70-e6ac-4ffa-a1a7-87f8bdac6f02.png">

**Comment by ckalsdh** [comment]
<img width="162" alt="image" src="https://user-images.githubusercontent.com/31490043/187050748-d0ad21f1-2feb-4516-82c4-e03d4f703633.png">
What is your version on the top left corner of first window?

**Comment by chelfen** [comment]
My version is what is pictured in your comment above!
