### ISSUE TITLE
Not able to choose stanza directory

### ISSUE THREAD

**Issue by sundari02** [NLP-Suite/NLP-Suite#744]
When I try to choose where stanza is installed, the tab closes automatically and shows this error: 
![image](https://user-images.githubusercontent.com/76914587/187050880-d38a5aad-2609-49e7-a755-515ea078df3d.png)

**Comment by Emory-NLP** [comment]
You are using a previous release. Problem has been fixed. Look at release notes

Roberto
Sent from my iPhone

On Aug 27, 2022, at 19:02, sundari02 ***@***.***> wrote:

﻿

When I try to choose where stanza is installed, the tab closes automatically and shows this error:
[image]<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F76914587%2F187050880-d38a5aad-2609-49e7-a755-515ea078df3d.png&data=05%7C01%7Crfranzo%40emory.edu%7Ca08f50c2e62e4339ff5e08da88802c88%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637972381331322268%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=5MnxlnmZN579BQyEWmTMRbdG%2FD%2BXHoe5dtstV%2FlYDLE%3D&reserved=0>

**Comment by sundari02** [comment]
![image](https://user-images.githubusercontent.com/76914587/187051683-06bdccaf-c499-4e0e-ae3b-72ced6b128b2.png)
Is this not the latest version?

**Comment by sundari02** [comment]
3.0.3

**Comment by Emory-NLP** [comment]
That is indeed the correct release. Most likely, your NLP_setup_external_software_config.csv file (in the config subdirectory) contains a record for Stanza, from previous bug. Please, delete that record and you should be fine.
