### ISSUE TITLE
unable to download stanza

### ISSUE THREAD

**Issue by chelfen** [NLP-Suite/NLP-Suite#748]
using a mac, whenever i try to download stanza using the "import stanza" command i get the following error: 
<img width="414" alt="Screen Shot 2022-08-31 at 12 22 28 PM" src="https://user-images.githubusercontent.com/97575241/187729341-1ffd0536-01eb-446a-ba70-e0e744acb236.png">

stanza.download() doesn't do anything in the terminal either... i don't know if i'm misunderstanding the directions or not but i can't seem to figure it out

**Comment by ckalsdh** [comment]
Hello,

"import stanza" is a Python language, and you are in the linux command shell (even though you are inside a conda NLP env), which is why the shell is responding "command not found." stanza should be already installed in your env when you ran STEP2-install_NLP-Suite.command.
