### ISSUE TITLE
[BUG]: No available module NGrams_CoOccurrences_Viewer_main.py

### ISSUE THREAD

**Issue by bianshuyang** [NLP-Suite/NLP-Suite#749]
**Describe the bug**
Cannot go to N Grams Co Occurences Viewer for homework?

**To Reproduce**
GUI for style analysis; *
N grams / Co-occurences viewer ; *
Click on it, and message in console is:
* FileNotFoundError: [Errno 2] No such file or directory: 'NGrams_CoOccurrences_Viewer_main.py': 'NGrams_CoOccurrences_Viewer_main.py'

**Screenshots**
<img width="1229" alt="image" src="https://user-images.githubusercontent.com/52821055/187950327-73784c9a-e84d-49d9-b45c-222df5b5d2bf.png">

**Desktop (please complete the following information):**
 - OS: [OS X/]
 - Release Version (3.0.4)

**Additional context**
From homework 2,  " Why can you only run the co-occurrence VIEWER and not the N-grams".... We cannot use the **co-occurence VIEWER** here....

**Comment by Emory-NLP** [comment]
Fixed in release 3.0.5

**Comment by bianshuyang** [comment]
"..... in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'python NGrams_CoOccurrences_Viewer_main.py': 'python NGrams_CoOccurrences_Viewer_main.py'
"
Bug was raised again...

Need to consider that some user's default command is:
python3 .xxxx.py
instead of python
Will fix by myself but just leave it here for anyone with potential bugs again.
