### ISSUE TITLE
NLP suite not running

### ISSUE THREAD

**Issue by SophiaZhangEmory** [NLP-Suite/NLP-Suite#752]
I'm running the NLP suite trying to open the style analysis script. 
<img width="1368" alt="Screen Shot 2022-09-01 at 3 00 30 PM" src="https://user-images.githubusercontent.com/112049859/187992428-bbd553bb-5e05-47fa-917c-7602319607b2.png">
I then get this error:
<img width="1359" alt="Screen Shot 2022-09-01 at 3 00 40 PM" src="https://user-images.githubusercontent.com/112049859/187992478-31b2d2bf-6ed9-426a-a89b-ffcc67423c46.png">

**Comment by ckalsdh** [comment]
ran STEP3 command, re-installed python 3.8 inside NLP env and requirements.txt

**Comment by natashaemory** [comment]
I am having the same issues and followed these steps. I am still getting the same error message.
