### ISSUE TITLE
OutOfMemoryError Java heap space

### ISSUE THREAD

**Issue by Emory-NLP** [NLP-Suite/NLP-Suite#77]
Users with Java version greater than 8 may experience this Java error with heap memory size.

**Comment by RafaelPiloto10** [comment]
Mixed reviews here. From my research, the "-d64" flag is only meant for Linux/Unix based systems. It should not work for Windows. However, the "-d64" flag was primarily present during Java 8. After JDK 9, the flag was marked deprecated and then no longer supported in future versions (https://superuser.com/questions/1370522/unrecognized-option-d64-occurs-with-ibm-informix-installation).

**Comment by noeyjix** [comment]
After updating to the current release, I can no longer produce a CoNLL table using Stanford CoreNLP, receiving the -d64 error as well: 

![image](https://user-images.githubusercontent.com/79263241/109719815-34acda00-7b77-11eb-82f6-6040bcb40ed2.png)

**Comment by RafaelPiloto10** [comment]
Can you confirm your Java JDK version? You can check this by typing `java --version` in your command prompt. From what we researched, the -d64 option is only available in java version <=9. If you have a Java version greater than Java 9, I would recommend that you uninstall your current Java version and **[download jdk 8](https://www.oracle.com/java/technologies/javase-downloads.html)**

**Comment by noeyjix** [comment]
Yes, it was 15. I took your advice and switched to jdk 8, and everything ran smoothly (except for the "illegal hex character" error leading to ~5% of files not being analyzed...). Thank you!

**Comment by RafaelPiloto10** [comment]
Perfect, I think we can close this issue for now. Note: Porting to Java 8 can cause an `illegal hex character` error. Reference: #76

**Comment by Emory-NLP** [comment]
Some of the GUIs now automatically replace non-ASCII characters and % to percent to avoid problems. If you send me the csv error file and tell me which script you are running, we can trap the error and run the file cleaning automatically and let the user know.
