### ISSUE TITLE
[BUG]: unable to run conll table 

### ISSUE THREAD

**Issue by chelfen** [NLP-Suite/NLP-Suite#772]
i'm trying to run the conll table for analysis on the harry potter corpus on my mac. i'm using NLP version 3.1.1.

first i go to the home page and select the "NLP parsers and annotators" option 

<img width="1315" alt="Screen Shot 2022-09-10 at 12 30 52 AM" src="https://user-images.githubusercontent.com/97575241/189468742-305b50ba-1f3b-45d3-bd11-12e7fec65383.png">

i am then directed to this GUI and set it up as follows before pressing run:

<img width="1391" alt="Screen Shot 2022-09-10 at 12 28 59 AM" src="https://user-images.githubusercontent.com/97575241/189468758-f8e34adf-cf32-460c-a5fc-99873b52b5a2.png">

the program starts to run but shuts down within seconds and i receive the following error:

<img width="1221" alt="Screen Shot 2022-09-10 at 12 28 51 AM" src="https://user-images.githubusercontent.com/97575241/189468769-69600243-41f3-449e-8de9-21306ee5c28b.png">

i saw someone else had a similar issue previously because they were running the wrong version of java (i.e. 16 instead of 1.8). i uninstalled and re-installed my java and made sure i am currently running the 1.8 version. i am still getting the error and am not sure what else to do.

**Comment by Emory-NLP** [comment]
Could you post any lines listed by the error handler before [errno 61] Connection refused? What it is saying is that it cannot connect to the Stanford CoreNLP server. You do need the Java JDK version. Could you try, as you did, 1.6? Maybe we can Zoom?

**Comment by chelfen** [comment]
<img width="1295" alt="Screen Shot 2022-09-10 at 10 08 41 AM" src="https://user-images.githubusercontent.com/97575241/189487140-3655cb37-567c-4a60-810c-50c45803680e.png">

<img width="1292" alt="Screen Shot 2022-09-10 at 10 08 55 AM" src="https://user-images.githubusercontent.com/97575241/189487143-51288297-5b8c-4d41-b955-f9dbb0fd6456.png">

<img width="1294" alt="Screen Shot 2022-09-10 at 10 09 09 AM" src="https://user-images.githubusercontent.com/97575241/189487148-b50b170c-ca00-4747-8ebc-1b13b793638e.png">

i also noticed that the syllabus has the "probabilistic context free grammar" option chosen, but i have the "neural network" option chosen. i tried to choose the PCFG option and but the suite wouldn't let me (i would click on the option from the dropdown menu and it would still read "neural network"), so the errors i have been encountering and are included in the above pictures are with the neural network option.

i'm not available to zoom until around 5 tonight, which i'd be happy to do but i know isn't ideal.

**Comment by Emory-NLP** [comment]
Yes, I am aware of the fact that you can only do neural network. Have not had a moment to look into the issue. Maybe today. 5pm exactly would be fine. at 5:45 will have to leave

**Comment by Emory-NLP** [comment]
Fixed the dropdown menu issue. Will push now new release to GitHub.

**Comment by chelfen** [comment]
is there a zoom link i can use for 5?

**Comment by Emory-NLP** [comment]
Personal zoom in syllabus for office hours

Roberto
Sent from my iPhone

On Sep 10, 2022, at 2:12 PM, chelfen ***@***.***> wrote:

﻿

is there a zoom link i can use for 5?
