### ISSUE TITLE
Unable to update 3.1.2 version

### ISSUE THREAD

**Issue by LinZhou89** [NLP-Suite/NLP-Suite#774]
Normally the NLP suite will be automatically updated to the newest version if I click "close" button after the announcement of new release popup. However nothing happened. My version is 3.1.1
![Screenshot 2022-09-10 223531](https://user-images.githubusercontent.com/113271885/189509692-b0c2f408-e179-45b0-84bc-34cfbf720c74.jpg)
![Screenshot 2022-09-10 223555](https://user-images.githubusercontent.com/113271885/189509711-2161b459-a6dd-4f59-8bd0-772ca7cf2437.jpg)

**Comment by DDVD233** [comment]
Please wait for Dr. Franzosi for an update, and after the update is pushed, please add 

`import sys`

to the first line of NLP_setup_update_util.py. This should fix the problem.
