### ISSUE TITLE
[BUG]: Freezing when running Normalize N-gram

### ISSUE THREAD

**Issue by Joshman7177** [NLP-Suite/NLP-Suite#779]
When I ran the Normalize N-gram option in the N-gram GUI it kept freeing in the terminal after parsing through all of the documents. I restarted the Suite multiple times and kept running into the same issue. There's no error message, it just freezes and doesn't generate an output.

**Comment by Joshman7177** [comment]
Bug

**Comment by Emory-NLP** [comment]
Please, always post a screenshot of the GUI so that I know which release you are using and what options.
