### ISSUE TITLE
[BUG]: Cannot open GUIs

### ISSUE THREAD

**Issue by cfcalvi** [NLP-Suite/NLP-Suite#790]
When I enter the sweet and attempt to open a GUI to run something (I was trying to run co-occurence in the n-grams viewer) it opens an error message saying nothing has been selected.

Screenshot to replicate:
<img width="1391" alt="Screen Shot 2022-09-14 at 6 48 32 PM" src="https://user-images.githubusercontent.com/105314519/190276855-9cd21a34-161e-4348-aa01-bd76179239b4.png">

Expected result:
The n-grams viewer would open and I could run it with my corpus. 

**Desktop (please complete the following information):**
 - OS: OS X

**Comment by Emory-NLP** [comment]
I do not get that err or unfortunately on my Dell which makes it harder to test. The only issue I see is that you are selecting two different things, one for corpus and one for document; they open the same GUI.  I have now changed it to open different GUIs, as they should, in the hope this may solve the problem.

**Comment by cfcalvi** [comment]
Here is another screenshot. In this one you can see that I only selected one and the error still occurs. ☹


From: Roberto ***@***.***>
Date: Wednesday, September 14, 2022 at 7:24 PM
To: NLP-Suite/NLP-Suite ***@***.***>
Cc: Calvino, Camila ***@***.***>, Author ***@***.***>
Subject: [External] Re: [NLP-Suite/NLP-Suite] [BUG]: Cannot open GUIs (Issue #790)

I do not get that err or unfortunately on my Dell which makes it harder to test. The only issue I see is that you are selecting two different things, one for corpus and one for document; they open the same GUI. I have now changed it to open different GUIs, as they should, in the hope this may solve the problem.

**Comment by cfcalvi** [comment]
Update!

After the last update I was able to run and open the GUI! Thanks!

From: Calvino, Camila ***@***.***>
Date: Thursday, September 15, 2022 at 9:35 AM
To: NLP-Suite/NLP-Suite ***@***.***>, NLP-Suite/NLP-Suite ***@***.***>
Cc: Author ***@***.***>
Subject: Re: [External] Re: [NLP-Suite/NLP-Suite] [BUG]: Cannot open GUIs (Issue #790)
Here is another screenshot. In this one you can see that I only selected one and the error still occurs. ☹


From: Roberto ***@***.***>
Date: Wednesday, September 14, 2022 at 7:24 PM
To: NLP-Suite/NLP-Suite ***@***.***>
Cc: Calvino, Camila ***@***.***>, Author ***@***.***>
Subject: [External] Re: [NLP-Suite/NLP-Suite] [BUG]: Cannot open GUIs (Issue #790)

I do not get that err or unfortunately on my Dell which makes it harder to test. The only issue I see is that you are selecting two different things, one for corpus and one for document; they open the same GUI. I have now changed it to open different GUIs, as they should, in the hope this may solve the problem.
