### ISSUE TITLE
[BUG]: Issue with shells.

### ISSUE THREAD

**Issue by saspoon1** [NLP-Suite/NLP-Suite#791]
**Describe the bug**
I ran the NLP suite and it told me that there was an update available. I then closed the NLP suite so that it could update, and it told me that I was using the wrong shell. I was running with bash. Then I changed to z-shell and now it gives me a fatal error message about a thing called kaleido. I pip installed it but it still doesn't work.

**To Reproduce**
1. Have a mac
2. open NLP suite old update
3. close it so it updates
4. open it
5. see error

**Screenshots**

<img width="1402" alt="Screen Shot 2022-09-14 at 6 52 18 PM" src="https://user-images.githubusercontent.com/97714402/190276780-6d87cb05-934b-4f7f-a2c8-03e36c84f50d.png">

**Desktop (please complete the following information):**
macOS Montery 12.5.1

**Comment by Emory-NLP** [comment]
kaleido is used by plotLy (static). A simple pip install kaleido should do the trick but... maybe not. For now, do not use the chart option plotLy (static).
https://pypi.org/project/kaleido/
