### ISSUE TITLE
[BUG]: SVO Filter Algorithm not working with spaCy

### ISSUE THREAD

**Issue by HelenBai2002Tong** [NLP-Suite/NLP-Suite#793]
![image](https://user-images.githubusercontent.com/38171691/190312293-e694f7d2-a24c-4714-a981-7dcabf3292ec.png)
Using SpaCy to run SVO extractions will lead to this error. When trying with one small file, I do not get this error. However, using multiple files or a really long file(the whole Arabian folktales) will encounter this issue.

OS: Windows 11

**Comment by Emory-NLP** [comment]
Could you provide a screenshot of the filter and lemmatize options you have selected in the GUI? They are hidden by the error in prompt.

**Comment by HelenBai2002Tong** [comment]
![image](https://user-images.githubusercontent.com/38171691/190472154-4627b216-6a5a-4d95-aaa3-0104dd949ff5.png)
This is the filter and lemmatize option.
