### ISSUE TITLE
[BUG]: Unable To Search Significant combinations of words

### ISSUE THREAD

**Issue by lailanashid** [NLP-Suite/NLP-Suite#797]
**Describe the bug**
Getting this pop-up saying no results were found in the corpus, even though we know the words are included within it. Because of this problem, my team is unable to complete HW4.

**To Reproduce**
1. Go to GUI for CoNLL Table Analyzer
2. Click on 'searched token'
3. search combination of words

**Screenshots**

<img width="260" alt="Screen Shot 2022-09-17 at 2 34 46 PM" src="https://user-images.githubusercontent.com/112135938/190871812-87ddbe98-0ef8-4927-88a0-f7c7a6bf6ca3.png">

**Additional context**
Add any other context about the problem here: Using a Mac

**Comment by Emory-NLP** [comment]
Without the full GUI to se which options  you are searching I cannot debug the problem (IF IT IS A PROBLEM and not a bad/unsupported use of the search)

**Comment by lailanashid** [comment]
> Without the full GUI to se which options you are searching I cannot debug the problem (IF IT IS A PROBLEM and not a bad/unsupported use of the search)

Two screenshots are attached below to illustrate the concern.
<img width="1325" alt="Screen Shot 2022-09-17 at 3 26 31 PM" src="https://user-images.githubusercontent.com/112135938/190873441-c3cf7cb1-57b1-4fa3-a4f3-d4a336bd5fb4.png">
<img width="1341" alt="Screen Shot 2022-09-17 at 3 25 40 PM" src="https://user-images.githubusercontent.com/112135938/190873443-ad3ac1ef-d458-4150-b44b-61091c785287.png">

**Comment by Emory-NLP** [comment]
Ah! You entering a collocation (i.e., a combination of words) but the CoNLL table only has one word per record and the search operates on that one record, for either a FORM or LEMMA specific value. You would need to use the n-gram co-occ VIEWER or the word search function for that. I will trap that error warning the user.
