### ISSUE TITLE
[BUG]: Difficulty Running Clause Analyses

### ISSUE THREAD

**Issue by lailanashid** [NLP-Suite/NLP-Suite#798]
**Describe the bug**
Cannot run clause analyses due to index error

**To Reproduce**
1. Go to 'CoNLL Table Analyzer GUI'
2. Click on 'CLAUSE analyses'
3. See error

**Expected behavior**
To get clause analyses

**Screenshots**

<img width="1440" alt="Screen Shot 2022-09-16 at 10 49 41 AM" src="https://user-images.githubusercontent.com/112135938/190877430-47c1debb-0909-43ae-8429-6ad847dcfb55.png">

**Additional context**
Using a Mac

**Comment by natashaemory** [comment]
We are having the same issue
