### ISSUE TITLE
[BUG]: Trouble running CoNLL Table Analyzer

### ISSUE THREAD

**Issue by saspoon1** [NLP-Suite/NLP-Suite#802]
**Describe the bug**
Get error message saying that my CoNLL table is not ordered so the program cannot run. I have gone and sorted by RecordID (and saved it) but it still does not work.
Using the folktales corpus.
I cannot upload the CoNLL table because it is 156 MB...

**To Reproduce**
1. Go to CoNLL analyzer GUI
2. do the searched token one. I have tried inputting king once and also girl once
3. click that it is a noun and we want all of them *
4. click that we are looking for co-occuring adjectives and we want all of them (*)
5. Run and see error

**Screenshots**
<img width="1440" alt="PNG image" src="https://user-images.githubusercontent.com/97714402/190931590-e3bda8fc-314e-4e64-9c65-e1bb60c8e54b.png">

**Desktop (please complete the following information):**
 - OS: macOS Montery 12.5.1

**Additional Context**
The right side of the analyzer worked fine (noun/verb/function analysis) when I ran it.

**Comment by saspoon1** [comment]
I am still experiencing this issue. I have included a screenshot of my CoNLL table -- maybe there is sth wrong with it? (Also included a screenshot of the error).

<img width="1440" alt="Screen Shot 2022-09-19 at 10 03 33 PM" src="https://user-images.githubusercontent.com/97714402/191151642-d4f1f776-2e86-4676-918b-af03e22f7e0b.png">

<img width="1440" alt="PNG image" src="https://user-images.githubusercontent.com/97714402/191151647-9749573a-8ac2-4ea0-b711-3c33dc2dae40.png">

**Comment by Emory-NLP** [comment]
Indeed it's a bug. Run the script with all * then filter the output file by the tags you want. Until the issue is fixed.
