### ISSUE TITLE
N-gram not running

### ISSUE THREAD

**Issue by SamirKaddoura** [NLP-Suite/NLP-Suite#826]
**Describe the bug**
A clear and concise description of what the bug is. Please indicate what corpus you are using.

**To Reproduce**

**Screenshots**
Add screenshots to help explain your problem and indicate the error.

**Desktop (please complete the following information):**
 - OS: [e.g. OS X/Windows]
 - Release Version (type `NLP --version` e.g. 22) 

**Additional context**

**Comment by Emory-NLP** [comment]
Please, answer the questions as asked by the bug template and rewrite the title as a concise title as "N-gram not running"

**Comment by SamirKaddoura** [comment]
N-gram tool not running: When I choose the N-gram tool on the Suite and click on run, the button resets to its default after a couple of seconds and no new window is opened. The command prompt says there is no module en_core_web_sm so I tried to pip install it but it was unavailable

**To  Reproduce**

1. Enter the Suite
2. Select "N-grams (words and character)
3. Click the run Button
![Screenshot (6)](https://user-images.githubusercontent.com/102534280/194375510-501dc68a-6997-4863-b009-76d6250a64df.png)

**Desktop**
OS: Windows
Release version: 3.3.4

**Comment by Emory-NLP** [comment]
Better in the title but where are the answers to all the questions, the required screenshots so that we know which GUI you are running and with which selected options.

**Comment by Emory-NLP** [comment]
The option works on other machines, including my Windows laptop. You must have missing packages. Please, upload to GitHub screenshots of the beginning and end of any error listed in terminal/command prompt.
