### ISSUE TITLE
Gender annotator error

### ISSUE THREAD

**Issue by bianshuyang** [NLP-Suite/NLP-Suite#827]
Error In:
<img width="1026" alt="image" src="https://user-images.githubusercontent.com/52821055/196013640-14fd9bd8-dd36-448e-b2bb-9991f98a4d9a.png">
====
<img width="1407" alt="image" src="https://user-images.githubusercontent.com/52821055/196013635-55b43e15-4ca0-459c-9416-4aba276c1f83.png">

Error Message:
<img width="578" alt="image" src="https://user-images.githubusercontent.com/52821055/196013626-99e587b7-09e5-48cd-9170-4d72baf4c2a7.png">

OS: Mac
Newest version

**Comment by Emory-NLP** [comment]
Please, change the import annotator_gender_dictionary_util to import html_annotator_gender_dictionary_util
Cannot push the change since I am still testing major changes to the Suite.
