### ISSUE TITLE
Narrative Analysis tool doesn't work and reports Exception in Tkinter callback

### ISSUE THREAD

**Issue by SophiaZhangEmory** [NLP-Suite/NLP-Suite#828]
**Describe the bug**
The Narrative Analysis tool doesn't work after clicking a single or several checkboxes in the GUI. 
Our corpus is a collection of 102 news articles on the coronavirus outbreak. Our input files directory is a folder including 102 txt files. We also tried to input CoNLL tables and csv files, but the same error appeared in the terminal again.

**To Reproduce**
1. Go to 'CORPUS/DOCUMENT Analysis Tools' in the main GUI and choose 'Narrative Analysis (All options GUI)'
2. Click on a random checkbox in the Narrative Analysis GUI
3. The suite doesn't work, and we can see the error in the terminal.

**Screenshots**
<img width="586" alt="Screen Shot 2022-10-16 at 4 12 38 PM" src="https://user-images.githubusercontent.com/112049859/196056269-63aaca3f-9ec4-4a48-bddc-097bbca2349a.png">

**Desktop (please complete the following information):**
 - Mac OS X
 - Release Version: Both NLP version 3.1.2 and 3.3.4, the most recent version.

**Comment by Emory-NLP** [comment]
Could you please always upload the GUI that you are using I assume narrative_analysis_main and show which options you are ticking and running? Thanks

**Comment by SophiaZhangEmory** [comment]
Many thanks! I'm using the narrative_analysis_main GUI, and this error appears in the terminal no matter what options are we ticking. There are three examples of this bug (we tried different options and made screenshots separately):
<img width="1368" alt="Screen Shot 2022-10-16 at 6 35 02 PM" src="https://user-images.githubusercontent.com/112049859/196062128-830e6130-c2e3-4e6a-bdd4-3157c9e61a5f.png">
<img width="1369" alt="Screen Shot 2022-10-16 at 6 35 24 PM" src="https://user-images.githubusercontent.com/112049859/196062131-cc9224fa-5b30-43e9-8de2-334200a114b5.png">
<img width="1377" alt="Screen Shot 2022-10-16 at 6 35 36 PM" src="https://user-images.githubusercontent.com/112049859/196062136-e1555db5-9c5a-4db7-aa7b-31093f911dd8.png">

**Comment by Emory-NLP** [comment]
OK, now I see. Problem solved for missing variable. Cannot push tonight since there have been sweeping changes and do not want to run the risk that things will not work with homework due (but hmk is NOT on narrative analysis). Will push tomorrow morning.
