### ISSUE TITLE
[BUG]: Wrong result on NLP parsers & annotators GUI

### ISSUE THREAD

**Issue by SeongUgKim** [NLP-Suite/NLP-Suite#832]
**Describe the bug**
When clicking pre-processing tools: file checking & cleaning (Open GUI) and Coreference resolution (Open GUI) button, it raises "FileNotFoundError: [Errno 2] No such file or directory: 'python file_checker_converter_cleaner_main.py'" error. 

In addition, after setting the specific annotator such as Gender annotator or Coreference Pronominal resolution, GUI produces wrong outputs: Stanford CoreNLP CONLL table and related data and graphs such as frequency distribution of DEP Rel and frequency distribution of form and lemma value.

**To Reproduce**
1. Go to 'NLP parsers & annotators GUI'
2. Click on 'pre-processing tools: file checking & cleaning (Open GUI) and Coreference resolution (Open GUI) button'
3. See error
OR
1. Go to 'NLP parsers & annotators GUI'
2. Click on Annotators
3. Select Gender annotator or Coreference Pronominal resolution
4. Ouputs wrong result

**Screenshots**
<img width="1392" alt="Screen Shot 2022-10-17 at 8 52 51 PM" src="https://user-images.githubusercontent.com/59695647/196310178-c4c06d6e-69a6-44b0-8b23-72c6af3a91bd.png">
<img width="1369" alt="Screen Shot 2022-10-17 at 8 55 30 PM" src="https://user-images.githubusercontent.com/59695647/196310446-b2eb39c3-f9f5-4945-b3bf-113be3963796.png">
<img width="915" alt="Screen Shot 2022-10-17 at 8 53 01 PM" src="https://user-images.githubusercontent.com/59695647/196310210-ac00a2b1-69ef-4f08-8f06-93eb16a9e7b7.png">

**Desktop (please complete the following information):**
 - OS: OS X
 - Release Version: 'NLP --3.3.5 

**Additional context**
Encounter this problem while making Video/Tips.

**Comment by Emory-NLP** [comment]
Fixed the first bug. Added a comment for the second issue. You are actually running both parser and gender. And nly parser is run. Now you are warned. Will push tomorrow after testing other options.
