### ISSUE TITLE
[BUG]: Sentiment Analysis Not Working

### ISSUE THREAD

**Issue by HelenBai2002Tong** [NLP-Suite/NLP-Suite#842]
**Describe the bug**
When selecting Sentiment Analysis and clicking on "Run", there is an error in the terminal and the Sentiment Analysis will not pop up.

**Screenshots**
<img width="1395" alt="Screen Shot 2022-10-19 at 5 01 23 PM" src="https://user-images.githubusercontent.com/38171691/196803519-21d0f610-ffe2-4d56-b9e6-73f7f48c9333.png">

The error in the terminal
<img width="562" alt="Screen Shot 2022-10-19 at 5 03 17 PM" src="https://user-images.githubusercontent.com/38171691/196803690-190be022-ec65-418a-b9b9-e87e5e4d4894.png">

**Desktop:**
 - OS: MacOS
 - Release Version:3.3.9

**Comment by Emory-NLP** [comment]
This error does not happen on Windows. Please, upload the image of the entire list you get in terminal. There may be a problem with installing some of the many packages used by sentiment analysis algorithms.

**Comment by HelenBai2002Tong** [comment]
This is the entire list in the terminal.
<img width="1507" alt="Screen Shot 2022-10-19 at 5 12 01 PM" src="https://user-images.githubusercontent.com/38171691/196805290-a0db7f19-51b0-48ae-a0d1-15bc99c8daaf.png">

**Comment by Emory-NLP** [comment]
Ehm. Let me assign the issue to Naman. Not sure if it is a Mac problem or a problem with missing packages on your Mac.

**Comment by HelenBai2002Tong** [comment]
I think Cole and I have the same issue:(

**Comment by nams1012** [comment]
I had the same issue as well, changing my python version to one <3.8 seemed to get rid of the issue. I am on Python 3.7.13 and I don't get the error anymore. Of course I am still looking into it and will update if I get a solution.

**Comment by HelenBai2002Tong** [comment]
Ok, thanks for the update.

**Comment by HelenBai2002Tong** [comment]
Hi Naman,

I am wondering have you encountered the same issue in the terminal after
you change to Python 3.7.13.

Error #15: Initializing libiomp5.dylib, but found libomp.dylib already
initialized.
