### ISSUE TITLE
no gephi or word cloud files

### ISSUE THREAD

**Issue by chelfen** [NLP-Suite/NLP-Suite#859]
this error occurred when running the SVO extraction through openIE and stanford coreNLP on macs. below is the GUI for which it occurred:

<img width="1346" alt="Screen Shot 2022-10-22 at 12 15 42 PM" src="https://user-images.githubusercontent.com/97575241/197349851-cd2833a1-a74c-4f7c-a066-332aadd495f5.png">

running the SVO extraction returns no gephi files for the network graphs and no word clouds. my partner and i are unable to run stanford coreNLP and therefore got the files from two other groups, so i don't have any further details on the terminal output. i double-checked with both groups that they didn't forget to send us the files and they both said they couldn't find them either.

**Comment by Emory-NLP** [comment]
Unfortunately, this is not an error with CoreNLP but depends only on which files were sent to you :-(

**Comment by Emory-NLP** [comment]
And BTW, from the GUI, you are simply running Stanford CoreNLP rather than OpenIE...
