### ISSUE TITLE
[BUG]: Unresponsive pages

### ISSUE THREAD

**Issue by saspoon1** [NLP-Suite/NLP-Suite#861]
**Describe the bug**
I noticed that my terminal was stuck on the same place for a few hours and I was getting a spinning wheel when I hovered over it. I went to force quit and my computer says that the python pages and terminal are both unresponsive.

**To Reproduce**
1. Run the Stanford CoreNLP SVO extractor

**Expected behavior**
It will look like it is running fine until hours later you realize that the terminal has the same exact words on the bottom line that it did hours ago and that your mouse is a spinning wheel when you hover over it.

**Screenshots**

<img width="1440" alt="Screen Shot 2022-10-22 at 6 03 58 PM" src="https://user-images.githubusercontent.com/97714402/197364200-353ec410-a33d-4ee5-904e-2e51ddfa21fc.png">

**Desktop (please complete the following information):**
 - OS: macOS Monterey Version 12.5.1

**Comment by saspoon1** [comment]
<img width="1440" alt="Screen Shot 2022-10-22 at 6 07 27 PM" src="https://user-images.githubusercontent.com/97714402/197364223-1ad60342-469c-4a9f-89f3-aa16a4ebf96c.png">

Here is another screenshot (with the nlp suite version information available).

**Comment by Emory-NLP** [comment]
It seems like you are running bash? The NLP Suite has been optimized for zsh. I am surprised you did not get an error about this. You should switch to zsh.

**Comment by saspoon1** [comment]
Thank you! I am currently running SENNA SVO Extractor without any issues (and spaCy ran fine). It's been running for about three hours now and is on document 72/511. Do you think that I should terminate the program and switch to zsh or wait till it finished running? And does optimized for zsh mean that it will be faster when I switch over?

**Comment by Emory-NLP** [comment]
SENNA is very slow indeed...
