### ISSUE TITLE
[BUG]: Senna SVO

### ISSUE THREAD

**Issue by Joshman7177** [NLP-Suite/NLP-Suite#863]
Senna SVO wont run, continuously generates popup that wont go away after pressing cancel

Error achieved by selecting Senna package for SVO annotator

<img width="256" alt="Screen Shot 2022-10-23 at 10 29 34 AM" src="https://user-images.githubusercontent.com/78614695/197397903-a189670d-7825-4ec3-8174-3d5e71e44b65.png">

 - OS:  OS X]
 - Release Version (type `NLP --version 3.4.3)

**Comment by Emory-NLP** [comment]
It looks like you have a Mac and need to put SENNA under applications. I do not know how Mac works, unfortunately.

**Comment by Joshman7177** [comment]
The SENNA folder is in the same folder as all of the other downloads, and this popup keeps popping up after hitting ok. I tried restarting my computer but the popup keeps appearing and preventing me from using the NLP Suite at all.

**Comment by Joshman7177** [comment]
And this is the error I get when I try to open senna-osx

<img width="256" alt="Screen Shot 2022-10-23 at 10 56 12 AM" src="https://user-images.githubusercontent.com/78614695/197399234-c72e1c2f-52a9-4ffc-9fbb-7bd2551999d4.png">

**Comment by Emory-NLP** [comment]
Ah. You may need to instruct Mac to allow SENNA. You should ask other students with a Mac. But SENNA will take hours to run...
