### ISSUE TITLE
[BUG]: Stanza SVO error

### ISSUE THREAD

**Issue by natashaemory** [NLP-Suite/NLP-Suite#864]
When running Stanza SVO, an error occurs 

**To Reproduce**
1. Go to SVO GUI
2. Click on Stanza
3. Run it

**Screenshots**
<img width="700" alt="Screen Shot 2022-10-23 at 10 32 28 AM" src="https://user-images.githubusercontent.com/112787725/197400941-67e4f257-9873-411f-9560-76fca671f7f3.png">

**Desktop (please complete the following information):**
 - macOS Version 12.5.1
 - Release Version 3.4.3

**Comment by Emory-NLP** [comment]
Upload the screenshot of the SVO GUI with the options you se for running Stanza.

**Comment by Emory-NLP** [comment]
Never mind. I get the same error.
