### ISSUE TITLE
[BUG]: Issue Running Sentiment Analysis GUI

### ISSUE THREAD

**Issue by lailanashid** [NLP-Suite/NLP-Suite#871]
**Describe the bug**

I cannot run the sentiment analysis (neural network/tensor options) GUI due to a pop-up that occurs. I attempted to run step 2 according to the TIPS file, but that did not resolve the issue. (My group is using the presidential speeches corpus)

**To Reproduce**
1. Go to 'enter NLP suite'
2. Click on 'sentiment analysis (neutral network/tensor options) GUI
3. See error

**Screenshots**
Add screenshots to help explain your problem and indicate the error.

<img width="260" alt="Screen Shot 2022-10-27 at 6 37 35 PM" src="https://user-images.githubusercontent.com/112135938/198411592-93811e57-a925-4e28-9b38-23c6eb866caf.png">
<img width="560" alt="Screen Shot 2022-10-27 at 6 37 47 PM" src="https://user-images.githubusercontent.com/112135938/198411597-3bb115d1-177b-440f-b597-7edc9beb2039.png">

**Desktop (please complete the following information):**
 - OS: OS (macbook air)
 - Release Version: NLP Release 3.4.7

**Comment by Emory-NLP** [comment]
First, please, always add the screenshots of the GUI you are running with the selected options...
1. you are running bash instead of zsh; you to convert to zsh
2. you need to pip install transformers and pip install pygit2

**Comment by lailanashid** [comment]
Unfortunately, I am unable to add a screenshot of the GUI that I am running because I am unable to get the GUI to run. The pop-up messages occurs as soon as I enter the NLP Suite, so no GUI is running yet. In addition, I have taken the steps to convert to zsh, and I am unsure of what you are referring to in your second tip. I do not have a coding or computer science background, so I would appreciate more clarification. Thank you!

**Comment by Emory-NLP** [comment]
I see. We will need to Zoom. Free now? Or tomorrow.

**Comment by lailanashid** [comment]
I am available to meet via zoom at 10:00 AM.

**Comment by Emory-NLP** [comment]
OK
