### ISSUE TITLE
unable to adjust memory with NLP suite

### ISSUE THREAD

**Issue by chelfen** [NLP-Suite/NLP-Suite#876]
working on the harry potter corpus on a mac. i am working within the sentiment analysis GUI and am having memory issues when running stanford coreNLP. i'm trying to increase the memory, but am unable to save the changes i try to make. here is the GUI i am in to start:

<img width="1344" alt="Screen Shot 2022-10-28 at 1 08 38 PM" src="https://user-images.githubusercontent.com/97575241/198693580-fb4e2fbd-827c-488f-8a79-c2a439b8937a.png">

here is what the changes look like before i submit:

<img width="1235" alt="Screen Shot 2022-10-28 at 1 07 16 PM" src="https://user-images.githubusercontent.com/97575241/198694122-faed837c-851c-4c6e-b0bf-f15752e34981.png">

when i adjust the memory from 4 -> 11 and hit the save button, nothing happens. i closed that GUI and reopened it to see if my changes were saved, and they weren't.

**Comment by Emory-NLP** [comment]
Thhe way to see if the value was changed is by clicking on the Open config button next to the display of the currently available...

**Comment by Emory-NLP** [comment]
But... will change the display when you open the setup_NLP_package_... displaying current values.

**Comment by chelfen** [comment]
just confirming that opening the csv file shows that no changes were made: memory is still at 4.0
