### ISSUE TITLE
[BUG]: Cannot get past pop up 

### ISSUE THREAD

**Issue by ke-ortlund** [NLP-Suite/NLP-Suite#877]
<img width="1298" alt="Screen Shot 2022-10-28 at 1 47 50 PM" src="https://user-images.githubusercontent.com/116300887/198700258-4534ce1d-dfed-42ce-844f-f2e019dcfe85.png">

The message instructs the user to choose a new directory for Stanford CoreNLP however when you press "ok" it just reappears. You can't click out of it.

**Comment by Emory-NLP** [comment]
Do you have time to Zoom at some point to see how you have setup your machine?
