### ISSUE TITLE
unable to open semantic analysis GUI

### ISSUE THREAD

**Issue by chelfen** [NLP-Suite/NLP-Suite#879]
working on the harry potter corpus on a mac. i enter the main GUI of the NLP suite and try to access the semantic analysis option: 
<img width="1298" alt="Screen Shot 2022-10-28 at 8 53 30 PM" src="https://user-images.githubusercontent.com/97575241/198754489-8c970782-a932-4a56-999d-042f75c736ac.png">

i receive the following error message upon hitting run:
<img width="565" alt="Screen Shot 2022-10-28 at 8 53 41 PM" src="https://user-images.githubusercontent.com/97575241/198754498-9d5c3f0b-5818-48eb-a54b-d04671f39f93.png">

the GUI starts to load but abruptly terminates, with the error message appearing about 15 seconds in.

**Comment by Emory-NLP** [comment]
In the NLP environment type
pip install contextualSpellCheck
