### ISSUE TITLE
[BUG]: Terminal Unresponsive

### ISSUE THREAD

**Issue by saspoon1** [NLP-Suite/NLP-Suite#880]
**Add a screenshot of the GUI you are running with the widget selections**
<img width="1440" alt="Screen Shot 2022-10-29 at 11 03 12 AM" src="https://user-images.githubusercontent.com/97714402/198839120-5fdb4fe7-d4e3-400e-a533-e6c1958534de.png">
 
**Describe the bug**
Terminal became unresponsive approximately seven hours after the coreference SVO extractor started running. This is the second time that CoreNLP has done this. I had to terminate the program and lost progress. I am running terminal through z-shell instead of born-again-shell this time.

**To Reproduce**
1. Run the CoreNLP SVO extractor with coreference on the folktales corpus
2. Maybe get the error

**Desktop (please complete the following information):**
 - OS: Mac OS Monterey 12.5.1
 - NLP --3.5.0 

**Additional context**
I had previously raised an issue about this that has since been closed.

**Comment by Emory-NLP** [comment]
It is unlikely that the computer is unresponsive. But coreference is the SLOWEST annotator in CoreNLP. Depending upon how much memory your laptop has this will slow things down. You may just want to run SVO w/o coref and run coref on just a subset of files.
