### ISSUE TITLE
[BUG]: Stanza Sentiment Analysis Issue

### ISSUE THREAD

**Issue by natashaemory** [NLP-Suite/NLP-Suite#885]
**Describe the bug**
Error occurs when trying to run sentiment analysis using Stanza.

**To Reproduce**
1. Go to Sentiment Analysis GUI
2. Click on Stanza 
3. Run
4. See error in terminal

**Screenshots**

<img width="1313" alt="Stanza Sentiment Analysis Issue" src="https://user-images.githubusercontent.com/112787725/198857078-250788cf-c925-4f7a-8914-63ceb57aa0cf.png">

**Desktop (please complete the following information):**
 - MacOS Version 12.5.1
 - NLP Version 3.5.0

**Comment by Emory-NLP** [comment]
in terminal/command line and the NLP environment (NOT base),  type 
pip install pandas -upgrade

**Comment by Emory-NLP** [comment]
you may also need to
pip install stanza -upgrade

**Comment by natashaemory** [comment]
<img width="561" alt="Screen Shot 2022-10-30 at 1 41 20 PM" src="https://user-images.githubusercontent.com/112787725/198893041-018d5ba8-fd2f-46e9-b9b4-ed5b58a8a5cf.png">

Getting the same error after pip installations

**Comment by Emory-NLP** [comment]
Oh no! With the mousepad fried after last night crash I made a mistake. there are -- dashes not one
pip install --upgrade stanza
pip install --upgrade pandas

**Comment by bianshuyang** [comment]
Hi all, I used the method, but a new error message ocurred. Is that in your case as well?
<img width="666" alt="image" src="https://user-images.githubusercontent.com/52821055/198923068-084ee8d9-4b6e-402f-8e39-4335000e0699.png">

**Comment by bianshuyang** [comment]
Noticeably when doing such command it is necessary to restart the entire NLP suite to get it work.

**Comment by Emory-NLP** [comment]
That is ALWAYS the case with any Python programs as it works with what it currently has...
