### ISSUE TITLE
[BUG]: Error when trying to open Sentiment Analysis GUI

### ISSUE THREAD

**Issue by saspoon1** [NLP-Suite/NLP-Suite#886]
**Add a screenshot of the GUI you are running with the widget selections**

<img width="1300" alt="Screen Shot 2022-10-29 at 11 29 27 PM" src="https://user-images.githubusercontent.com/97714402/198861231-ac853e09-8a9a-43bd-8ff0-b88c3eb80ff3.png">

<img width="1440" alt="Screen Shot 2022-10-29 at 11 27 01 PM" src="https://user-images.githubusercontent.com/97714402/198861233-d085542b-894b-4b00-92e4-685804b62cd2.png">

<img width="1010" alt="Screen Shot 2022-10-29 at 11 29 18 PM" src="https://user-images.githubusercontent.com/97714402/198861267-373530ce-907d-4ea3-a288-6095ce2c4562.png">

**Describe the bug**
I tried to open the Sentiment Analysis GUI through both the main page and the ALL options for emotion/sentiment analysis GUI. I got the same error in terminal for both: 

"Traceback (most recent call last):
  File "sentiment_analysis_main.py", line 24, in <module>
    import BERT_util
  File "/Users/spoonerfamily/Desktop/NLP-Suite-current-stable/src/BERT_util.py", line 26, in <module>
    import contextualSpellCheck
ModuleNotFoundError: No module named 'contextualSpellCheck'"

**To Reproduce**
1. Enter NLP Suite
2. Click on CORPUS/DOCUMENT Analysis Tools dropdown
3. Select Sentiments analysis (neural netwrok/tensor options: BERT, spaCy, Stanford CoreNLP, Stanza)
4. See error in terminal and the GUI never opens.

**Desktop (please complete the following information):**
 - OS: MacOS Monterey 12.5.1
 - NLP 3.5.0

**Additional context**
I originally got the following message and followed the directions on the pop-up. (I typed 'NLP' into the terminal and then pip installed sentencepiece, sentence_transformers, and tensor flow.)

![68876783481__E2A4B71F-D01B-40E1-8FF6-83A3349932CC](https://user-images.githubusercontent.com/97714402/198861419-54f702b7-632b-4854-98fb-329fbdb89284.png)

**Comment by Emory-NLP** [comment]
In terminal/command line type
pip install contextualSpellCheck
and of course also install those packages that the reminder tells you to install
