### ISSUE TITLE
still no visuals for stanza

### ISSUE THREAD

**Issue by chelfen** [NLP-Suite/NLP-Suite#891]
running sentiment analysis with stanza on the harry potter corpus on a mac. only a csv file is returned. i am running the latest version of the nlp suite (3.5.2), here is the final output in my terminal when stanza finishes running:
<img width="1236" alt="Screen Shot 2022-10-30 at 9 14 25 PM" src="https://user-images.githubusercontent.com/97575241/198912615-08e1d012-695e-495a-bf73-fc31b1ab981e.png">

**Comment by Emory-NLP** [comment]
Can you PLEASE read what is displayed in terminal? :-)
