### ISSUE TITLE
[BUG]: Issue Running Stanford CoreNLP Sentiment Analysis GUI

### ISSUE THREAD

**Issue by lailanashid** [NLP-Suite/NLP-Suite#892]
**Describe the bug**
This bug may be specific to the presidential speeches corpus, but there is a file that cannot be processed via the Sentiment Analysis GUI when Stanford CoreNLP is selected. The terminal states that an error has occurred and that it will continue processing the next file, but that does not happen and Stanford CoreNLP ends up freezing for 24+ hours.

**To Reproduce**
1. Go to GUI for Sentiment Analysis
2. Click on Stanford CoreNLP for sentiment analysis algorithm. 

**Screenshots**
<img width="1249" alt="Screen Shot 2022-10-31 at 10 56 05 AM" src="https://user-images.githubusercontent.com/112135938/199039245-9b58d4ac-3af1-4cbf-b49e-7d69ecb126b7.png">

<img width="564" alt="Screen Shot 2022-10-31 at 10 55 53 AM" src="https://user-images.githubusercontent.com/112135938/199039262-44fc6608-43e5-4122-8da5-85c64972c576.png">

**Desktop (please complete the following information):**
 - OS: OS (macbook air)
 - Release Version: NLP Release 3.5.1

**Comment by Emory-NLP** [comment]
![image](https://user-images.githubusercontent.com/79026295/199061104-483e41d2-72e3-4012-a1a7-be50ce70156f.png)
You simply ran out of memory. Do you have only 8GB of memory? Also... did the algorithm continue to the next file?

**Comment by lailanashid** [comment]
The algorithm didn't continue to run. I ran into this problem twice: once the file was 56/296 and this time it's 40/296, and both times no file has been processed afterwards. I have 8GB of memory; however, I have only used 6.45GB! Therefore, I'm not sure if this is a memory-related issue.

**Comment by Emory-NLP** [comment]
You could try to move the memory bar to 7 and see whether it would make things better. You should reboot the machine as well before trying this.

![image](https://user-images.githubusercontent.com/79026295/199072949-73b70e6d-95f7-45f8-a828-90ab4725047b.png)
