### ISSUE TITLE
SentiWordNet Sentiment Analysis need to prompt user to download nltk in advance

### ISSUE THREAD

**Issue by bianshuyang** [NLP-Suite/NLP-Suite#893]
<img width="396" alt="image" src="https://user-images.githubusercontent.com/52821055/199086521-f28e34d4-48ec-4c2c-bf9b-d68ef7fa49b0.png">
I tried this module for 3 times, each time I have to go back to the logger and found out the package I missed for Sentiwordnet in nltk under sentiment analysis. 
It need to pop up a window to inform user of the 3 required packages: wordnet omw-1.4  and sentiwordnet

**Comment by Emory-NLP** [comment]
Darn. You are right. We have taken out NLTK nearly everywhere but forgot it here? For now, do not run sentiWordnet unless you find an easy way to get nltk.download('sentiwordnet). Check the function
def import_nltk_resource(window, resource_path, resource):
in IO_libraries_util.
