### ISSUE TITLE
[BUG]: Error When Running Stanza Sentiment Algorithm

### ISSUE THREAD

**Issue by selmahassan** [NLP-Suite/NLP-Suite#894]
**Add a screenshot of the GUI you are running with the widget selections**

**Describe the bug**
Stanza Algorithm

**To Reproduce**

**Screenshots**
Add screenshots to help explain your problem and indicate the error.
<img width="1440" alt="Screen Shot 2022-10-31 at 5 56 54 PM" src="https://user-images.githubusercontent.com/78364187/199118332-d7e32f86-83a3-4217-bf91-4cca3e40c662.png">

**Desktop (please complete the following information):**
 - OS: [e.g. OS X/Windows]
 - Mac

**Additional context**

**Comment by Emory-NLP** [comment]
Please, always include in full the output in terminal/command line
