### ISSUE TITLE
[BUG]: Option '-d64' breaks the Stanford CoreNLP

### ISSUE THREAD

**Issue by DDVD233** [NLP-Suite/NLP-Suite#90]
**Describe the bug**
The option -d64 is not recognized. It breaks CoreNLP main.

**To Reproduce**
1. Open Stanford CoreNLP main.
2. Run with arbitrary files. 

**Output**

> You can follow CoreNLP in command line.
> 
> Unrecognized option: -d64
> Error: Could not create the Java Virtual Machine.
> Error: A fatal exception has occurred. Program will exit.
![image](https://user-images.githubusercontent.com/16710181/109621667-3c1fb380-7b76-11eb-9401-b97375b9bd4e.png)

**Desktop (please complete the following information):**
 - OS: macOS

**Additional context**
It is likely to be an macOS-only issue. Deleting the option '-d64' solves the issue.

**Comment by RafaelPiloto10** [comment]
Mixed reviews here. From my research, the "-d64" flag is only meant for Linux/Unix based systems. It should not work for Windows. However, the "-d64" flag was primarily present during Java 8. After JDK 9, the flag was marked deprecated and then no longer supported in future versions (https://superuser.com/questions/1370522/unrecognized-option-d64-occurs-with-ibm-informix-installation).

**Comment by RafaelPiloto10** [comment]
Related to #77
