### ISSUE TITLE
[BUG]: Stanford CoreNLP Sentiment analysis not working

### ISSUE THREAD

**Issue by SamirKaddoura** [NLP-Suite/NLP-Suite#904]
**Add a screenshot of the GUI you are running with the widget selections**

**Describe the bug**
When trying to run Stanford CoreNLP sentiment analysis on the folktales corpus, Stanford CoreNLP crashes on the following document and just stops:Caused by: class java.lang.OutOfMemoryError: Java heap space
[Warning] Stanford CoreNLP is not JSON. Trying to convert output to JSON...
[Error] Could not convert output to JSON! Error: Expecting value: line 1 column 1 (char 0)
Stanford CoreNLP failed to process your document Arabian 1001 Nights_Burton_stories_The Eldest Lady's Tale.txt Processing will continue with the next file.
Processing file 17/511 Arabian 1001 Nights_Burton_stories_The End of the Tailor's Tale.txt

**To Reproduce**
1. Run Sentiment Analysis GUI 
2. Choose Stanford CoreNLP as sentiment analysis parser
3. Error on terminal at Arabian 1001 Nights_Burton_stories_The Eldest Lady's Tale.txt

**Screenshots**
![Screenshot (14)](https://user-images.githubusercontent.com/102534280/199641189-7219b595-df43-4b7c-a5bb-f7be3a6ef423.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Release Version 3.5.7

**Additional context**

**Comment by Emory-NLP** [comment]
If you read carefully the message in terminal/command line, CoreNLP states that you have run out of memory heap space. You just don't have enough resources on your machine. When that happens, you should reboot your laptop to make sure you have a clean slate and give it another try.
