### ISSUE TITLE
Sentiment Analysis freedom choice

### ISSUE THREAD

**Issue by SamirKaddoura** [NLP-Suite/NLP-Suite#906]
**Is your feature request related to a problem? Please describe.**
When choosing the parsers for sentiment analysis, we can either choose all parsers, all neural network parsers, all dictionary parsers, or any parser individually. This isn't too big of a deal but sometimes it may simplify things to run through any parser of our choice

**Describe the solution you'd like**
Would there be a way to completely customize the choice of Parsers we'd like? For example, I could choose to run Stanford CoreNLP, Bert and ANEW without any of the others

**Comment by Emory-NLP** [comment]
Yes. It is precisely designed that way. Not sure what you mean
