### ISSUE TITLE
Cannot open any GUI

### ISSUE THREAD

**Issue by selmahassan** [NLP-Suite/NLP-Suite#915]
**Add a screenshot of the GUI you are running with the widget selections**

**Describe the bug**
Any GUI I try to open, I receive the same error message.

**To Reproduce**

**Screenshots**
<img width="1440" alt="Screen Shot 2022-11-07 at 9 08 57 AM" src="https://user-images.githubusercontent.com/78364187/200331428-aa046992-76fc-4498-a4f4-a592bcc27c7a.png">

**Desktop (please complete the following information):**
 - OS: [e.g. OS X/Windows]: OS 11.1
 - Release Version (type `NLP --version` e.g. 22): NLP 3.6.1

**Additional context**

**Comment by Emory-NLP** [comment]
All of a sudden it seems that something is missing for spaCy to run. At terminal, in the NLP environment, type: 
sudo python -m spacy download en_core_web_sm

**Comment by isaacha12** [comment]
Try this command inside NLP environment:
       python -m spacy download en_core_web_sm
