### ISSUE TITLE
[BUG]: Cannot Open any GUIs

### ISSUE THREAD

**Issue by jeongrok** [NLP-Suite/NLP-Suite#918]
**Add a screenshot of the GUI you are running with the widget selections**
<img width="1349" alt="Screen Shot 2022-11-08 at 16 43 21" src="https://user-images.githubusercontent.com/97694079/200682267-43a0548f-8330-44ef-b077-8c5a4207c6c6.png">

**Describe the bug**
When I try to run Shape of Stories, Sentiment Analysis, SVO, or any other GUIs within NLP, it does not open and constantly gives me errors.

**To Reproduce**
1. Go to 'Main Menu of NLP'
2. Click on 'Sentiment Analysis'
3.. See error related to 'leaked semaphore objects' or 'DeprecationWarning: Antialias is deprecated' 

**Screenshots**
<img width="877" alt="Screen Shot 2022-11-08 at 16 43 42" src="https://user-images.githubusercontent.com/97694079/200682605-6798688c-b458-4b52-abb2-13107434abed.png">

**Desktop (please complete the following information):**
 - OS: [macOS Monterey 12.3]
 - Release Version: 3.6.1

**Comment by Emory-NLP** [comment]
The semaphore problem is raised by the Apple M1/M2 chip. On the Stackoverflow, you also find suggestions to use python 3.9, instead of 3.8 but... all of that may have been prior to the M1 chip and Tensorflow.
