### ISSUE TITLE
Shape of stories import error

### ISSUE THREAD

**Issue by ameerhusary** [NLP-Suite/NLP-Suite#925]
**Add a screenshot of the GUI you are running with the widget selections**
<img width="570" alt="image" src="https://user-images.githubusercontent.com/88027416/201429338-35f19142-9aff-48ae-a9ac-751ecd1abdd3.png">

**Describe the bug**
A clear and concise description of what the bug is. Please indicate what corpus you are using.
folktales corpus tried to just enter the GUI but it said there is an import error. 
**To Reproduce**
1. Go to '...' main page select shape of stories
2. Click on '....' run
3. See error

**Screenshots**
Add screenshots to help explain your problem and indicate the error.
<img width="570" alt="image" src="https://user-images.githubusercontent.com/88027416/201429440-476ffeb9-4a7d-4ca5-a80b-2e09fdf1e47b.png">

**Desktop (please complete the following information):**
 - OS: [e.g. OS X/Windows] mac
 - Release Version (type `NLP --version` e.g. 22) most recent

**Additional context**

**Comment by Emory-NLP** [comment]
try 
pip install bert-extractive-summarizer
although this does not work for me. Naman is looking into it
