### ISSUE TITLE
[BUG]: Topic Modeling via Gensim GUI cannot be opened on MacBook 

### ISSUE THREAD

**Issue by ling-xiao-chen** [NLP-Suite/NLP-Suite#927]
**Describe the bug**
After pip installing the required packages, the MALLET GUI works, but I am unable to open the Topic Modelling Gensim GUI. The GUI exits after loading for a few seconds. I'm using news reports during the COVID-19 pandemic. 
<img width="1241" alt="Screen Shot 2022-11-12 at 2 39 18 PM" src="https://user-images.githubusercontent.com/92634719/201491757-7c23c45f-636c-4302-843d-9f2011622906.png">

 - OS: MacOS Monterey version 12.5 M2 
 - NLP -- version 3.6.4.

**Comment by Emory-NLP** [comment]
Do you get any feedback in terminal?

**Comment by ling-xiao-chen** [comment]
<img width="561" alt="Screen Shot 2022-11-12 at 8 56 19 PM" src="https://user-images.githubusercontent.com/92634719/201501841-2bd54d0a-7070-4001-b570-afd3d88b2cc5.png">

../src/NLP_welcome_main.py:103: DeprecationWarning: ANTIALIAS is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.LANCZOS instead.
  image_obj = Image.open(image).resize((int(image_width), int(image_height)), Image.ANTIALIAS)
Traceback (most recent call last):
  File "topic_modeling_gensim_main.py", line 40, in <module>
    import topic_modeling_gensim_util
  File "/Users/lingxiao/Desktop/446WBigData/NLP-Suite-current-stable/src/topic_modeling_gensim_util.py", line 36, in <module>
    import pyLDAvis.gensim
ModuleNotFoundError: No module named 'pyLDAvis.gensim'

Thank you for your help!

**Comment by Emory-NLP** [comment]
ehm. I do not see an error for import pyLDAvis. Try this in the NLP environment.
pip install pyLDAvis.gensim

**Comment by ling-xiao-chen** [comment]
Terminal feedback: 
(NLP) lingxiao@Lingxiaos-MacBook-Air ~ % pip install pyLDAvis.gensim
ERROR: Could not find a version that satisfies the requirement pyLDAvis.gensim (from versions: none)
ERROR: No matching distribution found for pyLDAvis.gensim

Thank you!

**Comment by Emory-NLP** [comment]
I was afraid of that. Can you try this?
pip install pyLDAvis --upgrade

**Comment by ling-xiao-chen** [comment]
(NLP) lingxiao@Lingxiaos-MacBook-Air ~ % pip install pyLDAvis --upgrade
Requirement already satisfied: pyLDAvis in ./miniforge3/envs/NLP/lib/python3.8/site-packages (3.3.1)
Requirement already satisfied: numexpr in ./miniforge3/envs/NLP/lib/python3.8/site-packages (from pyLDAvis) (2.8.4)
Requirement already satisfied: numpy>=1.20.0 in ./miniforge3/envs/NLP/lib/python3.8/site-packages (from pyLDAvis) (1.22.3)
Requirement already satisfied: scipy in ./miniforge3/envs/NLP/lib/python3.8/site-packages (from pyLDAvis) (1.9.3)
Requirement already satisfied: gensim in ./miniforge3/envs/NLP/lib/python3.8/site-packages (from pyLDAvis) (4.2.0)
Requirement already satisfied: pandas>=1.2.0 in ./miniforge3/envs/NLP/lib/python3.8/site-packages (from pyLDAvis) (1.5.1)
Requirement already satisfied: scikit-learn in ./miniforge3/envs/NLP/lib/python3.8/site-packages (from pyLDAvis) (1.1.3)
Requirement already satisfied: joblib in ./miniforge3/envs/NLP/lib/python3.8/site-packages (from pyLDAvis) (1.2.0)
Requirement already satisfied: funcy in ./miniforge3/envs/NLP/lib/python3.8/site-packages (from pyLDAvis) (1.17)
Requirement already satisfied: jinja2 in ./miniforge3/envs/NLP/lib/python3.8/site-packages (from pyLDAvis) (3.1.2)
Requirement already satisfied: setuptools in ./miniforge3/envs/NLP/lib/python3.8/site-packages (from pyLDAvis) (65.5.0)
Requirement already satisfied: sklearn in ./miniforge3/envs/NLP/lib/python3.8/site-packages (from pyLDAvis) (0.0)
Requirement already satisfied: future in ./miniforge3/envs/NLP/lib/python3.8/site-packages (from pyLDAvis) (0.18.2)
Requirement already satisfied: pytz>=2020.1 in ./miniforge3/envs/NLP/lib/python3.8/site-packages (from pandas>=1.2.0->pyLDAvis) (2022.6)
Requirement already satisfied: python-dateutil>=2.8.1 in ./miniforge3/envs/NLP/lib/python3.8/site-packages (from pandas>=1.2.0->pyLDAvis) (2.8.2)
Requirement already satisfied: smart-open>=1.8.1 in ./miniforge3/envs/NLP/lib/python3.8/site-packages (from gensim->pyLDAvis) (5.2.1)
Requirement already satisfied: MarkupSafe>=2.0 in ./miniforge3/envs/NLP/lib/python3.8/site-packages (from jinja2->pyLDAvis) (2.1.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in ./miniforge3/envs/NLP/lib/python3.8/site-packages (from scikit-learn->pyLDAvis) (3.1.0)
Requirement already satisfied: six>=1.5 in ./miniforge3/envs/NLP/lib/python3.8/site-packages (from python-dateutil>=2.8.1->pandas>=1.2.0->pyLDAvis) (1.16.0)

After putting that down, the Gensim would still exit unexpectedly.

**Comment by Emory-NLP** [comment]
another try Lingxiao
pip install gensim --upgrade

**Comment by ling-xiao-chen** [comment]
Sorry it still doesn't work 
------
(NLP) lingxiao@Lingxiaos-MacBook-Air ~ % pip install gensim --upgrade
Requirement already satisfied: gensim in ./miniforge3/envs/NLP/lib/python3.8/site-packages (4.2.0)
Requirement already satisfied: smart-open>=1.8.1 in ./miniforge3/envs/NLP/lib/python3.8/site-packages (from gensim) (5.2.1)
Requirement already satisfied: numpy>=1.17.0 in ./miniforge3/envs/NLP/lib/python3.8/site-packages (from gensim) (1.22.3)
Requirement already satisfied: scipy>=0.18.1 in ./miniforge3/envs/NLP/lib/python3.8/site-packages (from gensim) (1.9.3)
(NLP) lingxiao@Lingxiaos-MacBook-Air ~ %

**Comment by Emory-NLP** [comment]
At a loss. Sorry!
