### ISSUE TITLE
[BUG]: Gensim Word2Vec Does Not Open on Mac 

### ISSUE THREAD

**Issue by ke-ortlund** [NLP-Suite/NLP-Suite#933]
<img width="1345" alt="Screen Shot 2022-11-18 at 11 36 56 AM" src="https://user-images.githubusercontent.com/116300887/202755649-dc9d5fc9-6814-4eb0-83bc-5d2c6f557a0e.png">

After clicking "run" on the Word2Vec Gensim GUI it buffers, opens a new tab, then exits. 

Downloading https://raw.githubusercontent.com/stanfordnlp/stanza-resources/main/resources_1.4.0.json: 154kB [00:00, 16.2MB/s]
2022-11-18 11:37:54 INFO: Loading these models for language: en (English):
========================
| Processor | Package  |
------------------------
| tokenize  | combined |
| lemma     | combined |
========================

2022-11-18 11:37:54 INFO: Use device: cpu
2022-11-18 11:37:54 INFO: Loading: tokenize
2022-11-18 11:37:54 INFO: Loading: lemma
2022-11-18 11:37:54 INFO: Done loading processors!
Traceback (most recent call last):
  File "word2vec_main.py", line 16, in <module>
    import BERT_util
  File "/Users/keortlund/Downloads/NLP-Suite-current-stable/src/BERT_util.py", line 31, in <module>
    from summarizer import Summarizer,TransformerSummarizer
ImportError: cannot import name 'TransformerSummarizer' from 'summarizer' (/Users/keortlund/anaconda/envs/NLP/lib/python3.8/site-packages/summarizer/__init__.py)

- I have pip installed all the required packages

**Comment by Emory-NLP** [comment]
summarizer giving a problem on an unnecessary import.
For now, with any text editor open the file BERT_util.py in your src folder, Line 31:
from summarizer import Summarizer,TransformerSummarizer
take out the last package for the line to read like this and save.
from summarizer import Summarizer
