### ISSUE TITLE
BERT word embeddings output too glitchy to use

### ISSUE THREAD

**Issue by chelfen** [NLP-Suite/NLP-Suite#937]
i'm trying to run the BERT word embeddings tools on the harry potter corpus on a mac. the two html files that BERT produces are incredibly slow to respond to any mouse movements, to the point where i can't examine any part of the plot in detail. whenever i try to navigate around it or use the zoom tool, i receive the following error 3-4 minutes after initiating the movement with my cursor:

<img width="1310" alt="Screen Shot 2022-11-21 at 1 16 21 PM" src="https://user-images.githubusercontent.com/97575241/203130155-0fe8ee39-1b94-428a-97bf-c22a9ac3784f.png">

i have tried loading the plots in safari and google chrome and have had no luck with either.

**Comment by nams1012** [comment]
BERT word embeddings will be updated soon (still in progress) and may perform better once it is, so for now, just wait for a bit till its updated

**Comment by Emory-NLP** [comment]
Claire, can you try the new release I just pushed? Naman completed the distance measures.

**Comment by chelfen** [comment]
receiving this error:
<img width="560" alt="Screen Shot 2022-11-21 at 10 12 55 PM" src="https://user-images.githubusercontent.com/97575241/203212283-cbcc7b23-f10c-4853-b205-c2710414e415.png">

**Comment by Emory-NLP** [comment]
OK. That is easy to fix. Thank you Claire for trying so hard.

**Comment by Emory-NLP** [comment]
Fixed, Claire. Will push now.
