### ISSUE TITLE
[BUG]: 'NLP_default_package_language_config.csv' could not be found 

### ISSUE THREAD

**Issue by HridanshS** [NLP-Suite/NLP-Suite#938]
**Describe the bug**
When running file_search_byWord_main.py or any file which uses NLP_default_package_language_config.csv, a pop-up comes saying the following:
"The config file 'NLP_default_package_language_config.csv' could not be found in the sub-directory 'config' of your main NLP Suite folder.

Please, setup next the default NLP package and language options."

**To Reproduce**
1. Go to Terminal on Mac
2. Run python file_search_byWord_main.py
3. Wait for a couple moments
5. See error - the GUI will not come at all

**Expected behavior**
This pop-up should not come at all. The GUI should display

**Solution**
I saved a version of the NLP_default_package_language_config.csv file in the config folder of my current working directory and the entire issue ended. The solution is just to add the NLP_default_package_language_config.csv file into config directory. 
When the NLP Suite is downloaded from the GitHub page, it should automatically have this file included.

**Screenshots**
<img width="1354" alt="image" src="https://user-images.githubusercontent.com/78390395/203183458-056eb084-45be-4315-b04b-725a5fda7f2a.png">

**Operating System:**
 - MacOS

**Comment by Emory-NLP** [comment]
Unfortunately, that problem is linked to the M1 chip issue. Sorry!
