### ISSUE TITLE
[BUG]: Unable to run Word2Vec

### ISSUE THREAD

**Issue by lailanashid** [NLP-Suite/NLP-Suite#942]
<img width="1331" alt="Screen Shot 2022-11-21 at 11 01 54 PM" src="https://user-images.githubusercontent.com/112135938/203218508-ddbf9f1f-c1f6-4763-a689-a8aaf6d7ccb0.png">

**Describe the bug**
When trying to run Word2Vec (both Bert and Gensim), I receive a pop saying that I need to change the shell to zsh. Even though I have followed the steps given in the tips file, I continued to receive the pop up. My group is using the presidential speeches corpus. In the window next to the pop up, I also got the message "No module named 'sacremoses'" which might also be contributing to the problem.

**To Reproduce**
1. Go to Word2Vec
2. Click on run
3. Scroll down to see the pop up and "No module named 'sacremoses'" message

**Desktop (please complete the following information):**
 - OS: macbook
 - Release Version: 3.7.3

**Additional context**

**Comment by selmahassan** [comment]
I have the same issue

**Comment by selmahassan** [comment]
fixed it by typing "pip install sacremoses" in the command line
