### ISSUE TITLE
[BUG]: BERT Outputs Unresponsive 

### ISSUE THREAD

**Issue by ke-ortlund** [NLP-Suite/NLP-Suite#943]
The BERT outputs (two html files: all words in the corpus, clustering) are unresponsive on a mac. Manipulating the html to zoom in or drag the screen results in "page unresponsive". This occurs everytime (have tried several reruns). 

<img width="1410" alt="Screen Shot 2022-11-22 at 5 39 11 PM" src="https://user-images.githubusercontent.com/116300887/203435766-a49a1609-5be0-4b4d-9707-c6587975cd81.png">

**Comment by nams1012** [comment]
Will test on the Harry Potter corpus and get back to you, there may simply be too many words, but will test

**Comment by ke-ortlund** [comment]
Hi Dr. Franzosi, 
 
I hope you enjoyed your Thanksgiving!

Have you had a chance to test BERT yet? We are still unable to work with the data to finish up the HW. 

Thanks,
Kaegan

**Comment by Emory-NLP** [comment]
Hi Kaegan, Naman tried with various approaches, but it looks like with BERT Word2Vec on a large corpus we have reached the limits of what we can do on a laptop. Please, just use it with a subsample of your data. Roberto
