### ISSUE TITLE
[BUG]: Auto_update

### ISSUE THREAD

**Issue by noeyjix** [NLP-Suite/NLP-Suite#97]
**Describe the bug**
I'm not sure if the auto update is working. I followed steps suggested by Rafael (removing .git folder) and rerunning the setup_auto_update script for Windows. 

Now when I exit the NLP Suite, rather than the previous error of "You asked to pull from the remote 'origin', but did not specify a branch. Because this is not the default configured remote for your current branch, you must specify a branch on the command line", I get the error "fatal: not a git repository (or any of the parent directories):  .git" 

**To Reproduce**
I followed instructions to delete all files from my current NLP folder, then replaced them with the current version on github. I added the java files back to the src folder. I ran the setup_audo_update script for Windows. Then, when closing the NLP Suite, I got an error before command closes "You asked to pull from the remote 'origin', but did not specify a branch. Because this is not the default configured remote for your current branch, you must specify a branch on the command line"

Rafael suggested deleting the hidden .git folder, so I did. Then, I ran the setup_auto_update script for Windows again. Now, the error in command is "fatal: not a git repository (or any of the parent directories):  .git" 

**Screenshots**
Add screenshots to help explain your problem and indicate the error.
![image](https://user-images.githubusercontent.com/79263241/109678830-01535680-7b49-11eb-9399-da6c9b1be87b.png)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Release Version NLP-Suite-current-stable (downloaded at 8:16am 3/2/21)

**Comment by RafaelPiloto10** [comment]
Thank you for creating the student bug report. Could you run the `setup_auto_update.bat` script via the command prompt (open the command prompt, drag and drop the bat file into the command prompt, press enter). Could you attach a screenshot of the output that you get?

**Comment by noeyjix** [comment]
Yep, this is what I get:

![image](https://user-images.githubusercontent.com/79263241/109681040-129d6280-7b4b-11eb-91d4-1e74983f20ea.png)

**Comment by RafaelPiloto10** [comment]
Could you try running: `cd 'C:\Program Files (x86)\NLP\' && git init . && git remote add -t * -f origin https://github.com/NLP-Suite/NLP-Suite.git && git checkout -f current-stable && git add -A . && git stash`

**Comment by noeyjix** [comment]
Same message

![image](https://user-images.githubusercontent.com/79263241/109685870-af61ff00-7b4f-11eb-8527-573e4753a4a8.png)

**Comment by RafaelPiloto10** [comment]
Can you confirm the path of where your NLP Suite folder is?

**Comment by noeyjix** [comment]
C:\Program Files (x86)\NLP

**Comment by noeyjix** [comment]
Ok, I ranthis after changing directories:

git init . && git remote add -t * -f origin https://github.com/NLP-Suite/NLP-Suite.git && git checkout -f current-stable && git add -A . && git stash

and it appears to be working? Maybe it was the apostrophes?

**Comment by noeyjix** [comment]
Yes, it is, in fact, working. It pulls upon closing NLP. Thanks for your help!

**Comment by RafaelPiloto10** [comment]
Awesome, thanks!
