### ISSUE TITLE
External software setup

### ISSUE THREAD

**Issue by Emory-NLP** [NLP-Suite/NLP-Suite#978]
There is a problem about Java (JDK) record being inserted several times in the config file NLP_setup_external_software_config.csv. The issue is likely to be in the function def get_external_software_dir(calling_script, package, silent, only_check_missing) in the script IO_libraries_util.py

![image](https://user-images.githubusercontent.com/79026295/212551788-c7347f56-1977-4fd7-90bf-c2cf5952880d.png)

**Comment by vkameswaran** [comment]
The issue relates to the function `get_external_software_dir` in the file `IO_libraries_util.py`. This happens on my machine when this function is called with Stanford Core NLP, Gephi, or Google Earth (those that appear before the Java entry). When the system checks if all dependencies are present, it exits once it finds the corresponding line, before it finds Java. So, it thinks Java is not in the file, and adds it again. There are two solutions:

1. Move Java to the top of the CSV file, to ensure that it is always found if present.
2. Check the whole CSV file for the Java record first, before doing the real pass to locate the desired record.

I think option 2 is a better long-term solution.

I don't have permission to create a branch on this repository, but these are the changes that need to be made:
- In IO_libraries_util.py, line 590, change the initialization to
  ```java_found = any(['Java' in row[0] for row in existing_software_config])```
- We can delete lines 621-623 that check if java is found in the loop over the CSV file

These changes seem to fix the issue for me.

**Comment by Emory-NLP** [comment]
Brilliant!
