### ISSUE TITLE
CoNLL table analyzer Excel charts

### ISSUE THREAD

**Issue by Emory-NLP** [NLP-Suite/NLP-Suite#98]
Some of the Excel charts produced by the CoNLL table analyzer cannot be opened

**Comment by noeyjix** [comment]
When running the CoNLL analyzer, I'm unable to open four of the files produced (the first four listed):
_kw_deprel_stats_pie_chart.xlsx
_kw_postag_stats_pie_chart.xlsx
_co_kw_deprel_stats_pie_chart.xlsx
_co_kw_postag_stats_pie_chart.xlsx
![image](https://user-images.githubusercontent.com/79263241/110172494-3cfd5300-7dcb-11eb-96a2-6a74f520eaf4.png)
![image](https://user-images.githubusercontent.com/79263241/110172588-5b634e80-7dcb-11eb-9ee6-a55eed7e99f9.png)
