### ISSUE TITLE
[BUG]: spaCy parser doesn't run (problem with the "typer" package?)

### ISSUE THREAD

**Issue by tim-cho** [NLP-Suite/NLP-Suite#999]
**Add a screenshot of the GUI you are running with the widget selections**
![spacy_gui](https://user-images.githubusercontent.com/115910874/215303567-97929d38-e489-4396-8b99-8eac85bf9195.png)

**Describe the bug**
A clear and concise description of what the bug is. Please indicate what corpus you are using.
Corpus:: Health Narratives
The spaCy parser won't run due to an error, as shown below:
![spacy_error](https://user-images.githubusercontent.com/115910874/215303720-9aeedb9a-500f-4d6e-b5bb-2f129047a84e.png)

Looking up the error brought me to the following pages:
https://github.com/tiangolo/typer/issues/427
https://github.com/tiangolo/typer/pull/463

**To Reproduce**
1. Open "Parsers & annotators" from the main menu GUI
2. Select the spaCy package from setup at the bottom of the parser GUI
3. Click run

**Desktop (please complete the following information):**
- OS: Windows
- NLP Version 3.4.5

**Comment by Emory-NLP** [comment]
There seems to be rare issue with tiangolo. I would try the suggested solution until they fix it. Just try 
pip install click>=8.0.0,<9.0.0

![image](https://user-images.githubusercontent.com/79026295/215334524-af727443-1cbb-4314-90e2-8eeb27aed7c6.png)
